### ISSUE TITLE
Modeling: Default Conventions

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#10]

**Comment by hahmed** [comment]
Is there in ef7 an equivalent of configurations below?

modelBuilder.Configurations.Add(new BroadcastMappings());

**Comment by rowanmiller** [comment]
Closing as I have added conventions into the modelling docs in https://github.com/aspnet/EntityFramework.Docs/commit/8706c3cd17486fd70020af43994798369d2d5e83

There are some areas of modelling that still need docs, but those are tracked by https://github.com/aspnet/EntityFramework.Docs/issues/9

**Comment by rowanmiller** [comment]
@hahmed not yet, but you can easily split out bits of config by writing a static method that takes a ModelBuilder
