### ISSUE TITLE
many many example

### ISSUE THREAD

**Issue by esargent** [aspnet/EntityFramework.Docs#100]
from http://ef.readthedocs.org/en/latest/modeling/relationships.html#many-to-many

    public class Tag
    {
        public **string** TagId { get; set; }

        public List<PostTag> PostTags { get; set; }
    }

    public class PostTag
    {
        public int PostId { get; set; }
        public Post Post { get; set; }

        public **int** TagId { get; set; }
        public Tag Tag { get; set; }
    }

Shouldn't TagID be the same type in both classes? Not string in one, and int in the other?

**Comment by rowanmiller** [comment]
Thanks for pointing this out. Fixed in https://github.com/aspnet/EntityFramework.Docs/commit/416ae0401a9f76056a7ee4d350f671abfe24155a
