### ISSUE TITLE
What if Ids (BlogId, PostId) setters are private/protected? 

### ISSUE THREAD

**Issue by alecola** [aspnet/EntityFramework.Docs#1002]
if Ids (BlogId, PostId) setters are private/protected (https://github.com/dotnet-architecture/eShopOnContainers/blob/1b7200791931f33c94206822a69644ca820bb0dc/src/Services/Ordering/Ordering.Domain/SeedWork/Entity.cs), I can't use HasData as you showed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@alecola Use anonymous objects, as shown in the second example.
