### ISSUE TITLE
Spatial

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework.Docs#1006]
Coming in EF Core 2.2...

* NTS
  * Use a factory from `GeometryServiceProvider.Instance.CreateGeometryFactory(srid)` to create instances. `new` is possible but discouraged.
  * `M` is hard (needs a different CoordinateSequence/Factory) and doesn't always work (e.g. NetTopologySuite/NetTopologySuite#156)
  * `CircularString`, `CompoundCurve`, and `CurvePolygon` not supported (see NetTopologySuite/NetTopologySuite#247)
  * `SRID` not honored. `Area`, `Distance`, and `Length` will be in degrees
* InMemory (no additional package)
  * Install NTS; add properties; done
* SQLite (package Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite)
  * Needs SpatiaLite
    * Windows: In the box via NuGet
      * No AnyCPU on .NET Framework
      * No UWP
    * MacOS: `brew install libspatialite`
    * Linux: `apt-get install libsqlite3-mod-spatialite` (on Ubuntu anyway)
  * Configure SRID and dimension on properties
* SQL Server (package Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite)
  * Defaults to `geography`, can map to `geometry`
  * The usual `geography` gotchas
    * `X` is `Long`
    * `Y` is `Lat`
    * `Polygon` is weird
      * `ExteriorRing` must be oriented counter-clockwise
      * `InteriorRings` must be oriented clockwise
  * `FullGlobe` isn't supported by NTS
    * Including geography polygons without an exterior ring
  * Need a SQL-Server-specific operation? Let us know on aspnet/EntityFrameworkCore#13421

**Comment by divega** [comment]
Assigning to @bricelam and the 2.2 milestone 

cc @ajcvickers
