### ISSUE TITLE
Foreign keys

### ISSUE THREAD

**Issue by iSeiryu** [aspnet/EntityFramework.Docs#1008]
The article says: "Frequently the foreign key properties are in shadow state". What about not so frequent cases when the key properties are not in shadow state?
More examples would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
The first example shows how to provide seed data without shadow properties.

**Comment by iSeiryu** [comment]
The first example doesn't operate with foreign keys. The article does NOT say "the foreign key properties are ALWAYS in shadow state". It says "Frequently".
What about the rest of the cases that are not considered "frequent"? Or any time there are foreign keys between the entities we HAVE to use shadow properties in order to use HasData() seeding method?

**Comment by ajcvickers** [comment]
@iSeiryu The point is that properties are either in shadow state or not. If they are normal properties...then they are normal properties and they are set just like any other normal property. In other words, there is nothing special here about foreign keys. But one of the reasons you may be using shadow state is for foreign keys.

**Comment by iSeiryu** [comment]
When I set the properties "just like any other normal property" I get errors when adding a new migration (different errors depending on how I setup my entities).
So far this is the only way that worked:
- set up shadow properties for the foreign keys;
- use anonymous class to pass an object to HasData() method.
Basically mock the approach from the article. But the article didn't state it was the only way to deal with the Foreign keys and I'm failing to find any other approach that would work.

I'm trying to avoid using anonymous classes.

**Comment by AndriySvyryd** [comment]
@iSeiryu Can you paste the errors that you get and the corresponding model configuration?
