### ISSUE TITLE
naoenche

### ISSUE THREAD

**Issue by gilsonbispo** [aspnet/EntityFramework.Docs#1009]
....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91606b46-d8a2-8824-a1ae-522f35362ec4
* Version Independent ID: 22a92f99-5e43-96d7-82d1-cd02ccdc5af8
* Content: [Querying Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/)
* Content Source: [entity-framework/core/querying/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
No issue details.
