### ISSUE TITLE
Powershell version on Windows 7

### ISSUE THREAD

**Issue by mehrt** [aspnet/EntityFramework.Docs#101]
If one follows the tutorial [here](http://ef.readthedocs.org/en/latest/getting-started/full-dotnet/new-db.html) and does so on a box running Windows 7, chances are that they'll receive the following error ...

```
The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:14
+ Add-Migration <<<<  MyFirstMigration
    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
... when trying to execute `Add-Migration MyFirstMigration`.

This is due to the fact that Powershell may be Version 2 or 3. It needs to be Version 4 for this to work.
I had this issue on two separate W7 boxes on which I tried playing with EF7, so I think other people may run into this as well. The first time it took me almost a day to figure this out. So a hint towards this in the tutorial may be a good idea.
Installing an update from [here](https://www.microsoft.com/en-us/download/details.aspx?id=40855) fixed it.

**Comment by mehrt** [comment]
Sorry, I didn't notice #99 being actually the same issue ...

**Comment by mehrt** [comment]
The minimum version probably should also be mentioned [here](http://ef.readthedocs.org/en/latest/cli/powershell.html) ...

**Comment by rowanmiller** [comment]
@mehrt good point, change is out for review #109

**Comment by mehrt** [comment]
:+1:
