### ISSUE TITLE
Is there a version of this with SQL Server?

### ISSUE THREAD

**Issue by maacpiash** [aspnet/EntityFramework.Docs#1012]
I would like to do the same things: create a new app with a new SQL database from scratch, where I would like to use SQL Server. There is a tutorial on using SQL Server, but that one shows how to handle a database that already exists. Is there a way to develop an app in the same way as described here, only with SQL Server instead of SQLite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio or https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.1

**Comment by jahbenjah** [comment]
This document will work for SQL Server changing two lines.
1. In **Install Entity Framework Core** change  `dotnet add package Microsoft.EntityFrameworkCore.Sqlite` for this:

`dotnet add package Microsoft.EntityFrameworkCore.SqlServer`
2.  In the OnConfiguring method change ` optionsBuilder.UseSqlite("Data Source=blogging.db");` 
`optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Blogging;Integrated Security=True");`

**Comment by Rick-Anderson** [comment]
@maacpiash 	did that answer your questions?

**Comment by maacpiash** [comment]
Yes it did. Thank you all very much :smile:
