### ISSUE TITLE
Nullable foreign keys

### ISSUE THREAD

**Issue by mattfrear** [aspnet/EntityFramework.Docs#1015]
I am not sure of the accuracy of this block of text:
> You can use the Fluent API to configure whether the relationship is required or optional. Ultimately this controls whether the foreign key property is required or optional. This is most useful when you are using a shadow state foreign key. If you have a foreign key property in your entity class then the requiredness of the relationship is determined based on whether the foreign key property is required or optional (see Required and Optional properties for more information).

I am new to EF Core, and have a one to many relationship defined, where the foreign keys are `int`. EF appears to be creating an optional relationship, i.e. the Foreign keys on my child table are nullable.
I also have one to one relationships defined with foreign keys of int and EF is making them nullable.

I am struggling to make them non-nullable (especially one to one relationship) so some more documentation around doing that would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@mattfrear Sometimes columns can be made nullable in the database for other reasons--such as when they are part of a derived type in a TPH inheritance mapping. If you're not doing this or anything similar and your FK properties are being mapped to columns with different nullability, then please file a new issue on https://github.com/aspnet/EntityFrameworkCore/issues including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by mattfrear** [comment]
I wonder if the example shown here backs up what I was saying about having a nullable int foreign key

```
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Post>()
            .HasOne(p => p.Blog)
            .WithMany(b => b.Posts)
            .IsRequired();
    }
```

**Comment by regisbsb** [comment]
Use `[Required]`
