### ISSUE TITLE
Typo in a method

### ISSUE THREAD

**Issue by Peska** [aspnet/EntityFramework.Docs#1027]
There is a typo in a method:
mockSet.As&lt;IQueryable&lt;Blog&gt;&gt;().Setup(m =&gt; m.GetEnumerator()).Returns(0 =&gt; data.GetEnumerator());
Should be:
mockSet.As&lt;IQueryable&lt;Blog&gt;&gt;().Setup(m =&gt; m.GetEnumerator()).Returns(data.GetEnumerator());

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a04a5e4-3060-2331-f78d-8b45064b8983
* Version Independent ID: 673d9406-3fa1-a9eb-f5cc-a431155e0260
* Content: [Testing with a mocking framework - EF6](https://docs.microsoft.com/en-gb/ef/ef6/fundamentals/testing/mocking#testing-query-scenarios)
* Content Source: [entity-framework/ef6/fundamentals/testing/mocking.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/testing/mocking.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by rschindhelm-haba** [comment]
This is already fixed. You may want to close this issue.

**Comment by asartem** [comment]
The recommended fix is wrong! It's even worser!

Take your attention on such importan thing like GetEnumerator which should called as Func here:
  mockSet.As<IQueryable<Blog>>().Setup(m => m.GetEnumerator()).Returns(  ( )=>  data.GetEnumerator());
instead of your wrong implemenration 
  mockSet.As<IQueryable<Blog>>().Setup(m => m.GetEnumerator()).Returns(data.GetEnumerator());

Because Returns(data.GetEnumerator()); will reach end of collection after first loop and each next request to collection\mocked object will return empty result!

**Comment by Peska** [comment]
It couldn't be worse, because previous example didn't compile at all.

But good catch. I reopened this issue. Thanks.

**Comment by santino-majur** [comment]
hey am new to testing, been following the tutorial but i can't quiet figure out where to create the async query provider. any help will be appreciated. thanks

**Comment by rschindhelm-haba** [comment]
Hey @santino-majur,

welcome. Your question does not relate to this issue, but let try to answer it here anyway.
It happens when you setup the Mock for the `IQueryable<Blog>`, where you use the `TestDbAsyncQueryProvider` instead of the default one:
```
mockSet.As<IQueryable<Blog>>()
       .Setup(m => m.Provider)
       .Returns(new TestDbAsyncQueryProvider<Blog>(data.Provider)); // here
```

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
