### ISSUE TITLE
Example and comments are different for DepartmentID.

### ISSUE THREAD

**Issue by abduldm** [aspnet/EntityFramework.Docs#1030]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

 // Get the course where currently DepartmentID = 1.
    Course course2 = context.Courses.First(c=>c.DepartmentID == 2);

**Comment by ajcvickers** [comment]
@abduldm Can you submit a PR to correct the comment.

**Comment by abduldm** [comment]
@ajcvickers , I have created the PR and its a small change :)

**Comment by ajcvickers** [comment]
Thanks!
