### ISSUE TITLE
ASP.NET CORE: What is the Configuration.GetConnectionString("BloggingDatabase") namespace?

### ISSUE THREAD

**Issue by serhioV** [aspnet/EntityFramework.Docs#1034]
options.UseSqlServer(Configuration.GetConnectionString("BloggingDatabase")));

Does not recognize "Configuration". What is the namespace to use? Not clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by jahbenjah** [comment]
The `Configuration ` property is defined in the `Startup` class and it is initialized thru dependency injection. Here is the sample for a project created with  `dotnet new mvc -au Individual` 
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
```

**Comment by MarkRobles** [comment]
It would be useful more examples of connection strings with other providers :)

**Comment by omar-ebrahim** [comment]
services.AddDbContext<Context>(opt => opt.UseMySQL(Configuration.GetConnectionString(connectionStringName)));

If you use MySQL then you need the `MySql.Data.EntityFrameworkCore` NuGet package
