### ISSUE TITLE
How to compare "Yes" with "1.0"?

### ISSUE THREAD

**Issue by Calvin-Yuhui-Liu** [aspnet/EntityFramework.Docs#1042]
I would suggest to provide version numbers for EF6. It makes more sense to compare "2.0" (in stead of "Yes") with "1.0". Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc2d1a4-a434-69f9-3df3-9818c571c978
* Version Independent ID: a272636c-100d-fb7b-d7a9-713adc0b2b8e
* Content: [EF Core & EF6 Feature by Feature Comparison](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features)
* Content Source: [entity-framework/efcore-and-ef6/features.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/features.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@Calvin-Yuhui-Liu Can you give some more details on how this makes sense?

**Comment by Bluejanis** [comment]
Well it could show 6.0 instead of Yes. For that to work somebody has to look up which feature works since which version. Would that benefit anyone though? I think everybody now would start with the latest version anyways.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
