### ISSUE TITLE
Interface support?

### ISSUE THREAD

**Issue by Bluejanis** [aspnet/EntityFramework.Docs#1047]
Does EF Core support interfaces?
There is no information about this at all, but I am getting migration errors when I am trying to use ef core with interfaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc2d1a4-a434-69f9-3df3-9818c571c978
* Version Independent ID: a272636c-100d-fb7b-d7a9-713adc0b2b8e
* Content: [EF Core & EF6 Feature by Feature Comparison](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features)
* Content Source: [entity-framework/efcore-and-ef6/features.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/features.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
There is no first-class support. See https://github.com/aspnet/EntityFrameworkCore/issues/757 and https://github.com/aspnet/EntityFrameworkCore/issues/13344
