### ISSUE TITLE
Unit testing EF7

### ISSUE THREAD

**Issue by MikeWasson** [aspnet/EntityFramework.Docs#105]
It would be great to have an official doc on unit testing with EF7.

**Comment by MikeWasson** [comment]
Two things that I didn't grok at first:

- Keep DbContext's isolated; don't re-use the same context to seed the database and then query.
- Call `EnsureDeleted` after each test

Another minor gotcha for me: Call `EnsureDeleted` _before_ calling `Assert` (in xUnit), so if the assertion fails, you aren't left with stuff in the DB.

**Comment by ardalis** [comment]
If you're talking about testing that hits the database, then be sure to call it something other than unit testing. But yes, having an article on integration testing between EF and the database would be great!

**Comment by rowanmiller** [comment]
We already have #95 tracking this - EnsureDeleted is actually probably not the best as it will cause issues with multi-threaded testing. #95 has details on how to get a database scoped to each test.

**Comment by MikeWasson** [comment]
@ardalis: I actually meant using the InMemory provider to unit test other code that calls into EF. 

@rowanmiller: Thanks!
