### ISSUE TITLE
Document owned entity collections support in 2.2

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1052]
Update owned entity types documentation to cover it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* GitHub Login: @julielerman
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Fixed by https://github.com/aspnet/EntityFramework.Docs/pull/1097.

**Comment by weitzhandler** [comment]
Very unclear what type of entity is `Distributor` of (is it owned? can it be owned?) and the IDs referred to. Please update the example.

**Comment by weitzhandler** [comment]
I already figured it out, but it didn't just pop out to me, and usually it does when reading the MS docs...
I'd just suggest to elaborate a bit further.

**Comment by weitzhandler** [comment]
[Related](https://github.com/aspnet/EntityFramework.Docs/issues/1199#issuecomment-450283645).
