### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by CobusKruger** [aspnet/EntityFramework.Docs#1054]
The link to Transien services (occurring several times in the document) is broken and shows me a very fetching 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c833c51-54f7-8fcd-bb67-7a1136ded1dc
* Version Independent ID: 16cfe3dc-ce9d-1351-e9f6-80846bc0616b
* Content: [ServiceCollectionMap.TryAddTransient Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.servicecollectionmap.tryaddtransient?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/ServiceCollectionMap.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/ServiceCollectionMap.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by mairaw** [comment]
We changed the design to be like MSDN and no longer have separate entries. I'm wondering if there's CI run missing somewhere to resolve the links properly or a full build. I'll try running a full build for both docsets first.

**Comment by smitpatel** [comment]
@mairaw - Any update on this? Do we need to do something on our end in API docs to avoid this broken link?

**Comment by ajcvickers** [comment]
@mairaw Ping. Any thoughts on this?

**Comment by ajcvickers** [comment]
@smitpatel to transfer issue.

**Comment by smitpatel** [comment]
The link Transient correctly points to the enum rather than broken. Closing as fixed.
