### ISSUE TITLE
Where HasData fails

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/EntityFramework.Docs#1055]
`HasData` relies completely on migrations, so if you already had data in that table before adding `HasData` migration next time you will try to migrate an exception will be thrown. There is no way to check if data already exists in the table you want to seed. I think that seeding using the old way (without `HasData`) inside `using (var serviceScope = webHost.Services.CreateScope())` is more advantageous because you can check if data exists before seeding, not if migration was applied.

So Imagine we have 2 migrations, first migration creates the table, some data was added to that new table in the meantime, after some time we decide we want to seed the table with some default rows but the problem is there are already some rows in the table and we can't protect ourselves against it. Just 1 problem showing that manual seeding like before EF Core 2.1 is superior to `HasData`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by zhaparoff** [comment]
Yeah, faced the same issue today =(
Actually, as for me, old plain SQL seems to remain the most reliable and flexible option to perform data seeding in EF Core.
This 'HasData' look like a workaround, applicable for a initial development, when you always can drop & recreate a development database from the scratch. But not a reliable solution for production DB migrations, unless you are using SQL script generation and further manual SQL script corrections for migrations.

**Comment by AndriySvyryd** [comment]
`HasData` has many drawbacks and limitations compared to the traditional seeding approach, but if your scenario is supported it makes the deployment process simpler by integrating seeding into migrations.

**Comment by Sigvaard** [comment]
@AndriySvyryd thanks for clearing this up. I think because of these drawbacks I just prefer to use custom seeding.
