### ISSUE TITLE
Reader Mode

### ISSUE THREAD

**Issue by aluRamb0** [aspnet/EntityFramework.Docs#1058]
There is no reader mode for this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5e03de-96f5-6589-5ac1-de0b0406076e
* Version Independent ID: 36fd08ad-ba31-42e4-b74b-1b76874fdfe9
* Content: [Provider Support for Spatial Types - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/providers/spatial-support)
* Content Source: [entity-framework/ef6/fundamentals/providers/spatial-support.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/providers/spatial-support.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@divega Do you know what "reader mode" is?

**Comment by divega** [comment]
I suspect the customer was referring to reader mode in his web browser but I am not sure. However for this particular page, I am able to use reader mode in Safari without any problem. 

@mairaw, What do you think? If it is about browser reader model, is there a general goal that our docs should be written in a way that enables that or any known artifacts that may prevent it that need to be avoided?

**Comment by smitpatel** [comment]
Ping @mairaw

**Comment by ajcvickers** [comment]
@mairaw Ping. Any ideas here?

**Comment by ajcvickers** [comment]
@smitpatel to transfer issue.

**Comment by smitpatel** [comment]
I tested out reader mode in Edge beta for the article. It is working correctly. I don't think there is any specific settings in docs build to enable reader mode (if that is what it refers to here). Closing as could not repro.
