### ISSUE TITLE
Clarify differences in database view support

### ISSUE THREAD

**Issue by jawn** [aspnet/EntityFramework.Docs#1060]
The lack of view support when working database-first is an important discinction to know. I suggest adding it to this comparison page.

Source: 
- "Reverse engineering database views into query types: This feature is postponed to EF Core 3.0." https://blogs.msdn.microsoft.com/dotnet/2018/10/17/announcing-entity-framework-core-2-2-preview-3/
- "At the moment we generate code only from tables, not views." from https://github.com/aspnet/EntityFrameworkCore/issues/1679

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0036f8c5-d838-69a5-cc09-dc74df09bc07
* Version Independent ID: 5335749f-e32f-979f-7139-f5f14373e283
* Content: [Compare Entity Framework 6 and Entity Framework Core](https://docs.microsoft.com/en-gb/ef/efcore-and-ef6/)
* Content Source: [entity-framework/efcore-and-ef6/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Consolidated into #990. May no longer be relevant.
