### ISSUE TITLE
ClientSetNull has inconsistant behavior in EF Core 2.1.4

### ISSUE THREAD

**Issue by victarary** [aspnet/EntityFramework.Docs#1061]
I just write an example to verify ClientSetNull in EF Core 2.1.4.
I have two enties - Person and Book which is one to many relationship but without foreign key in database.

Here is the fluent API:

```C#
entity.HasMany(p => p.Book)
                .WithOne(b =>; b.Person)
                .HasPrincipalKey(p => p.PersonCode)
                .HasForeignKey(b =>; b.PersonCode)
                .OnDelete(DeleteBehavior.ClientSetNull);
```

Here is the code invoked from my program:

```C#
using (var dbContext = new TestDBContext())
{
    var james = new Person() { PersonCode = "P001", Name = "James", Age = 30 };

    var chineseBook = new Book() { BookCode = "B001", Isbn = "001", BookName="Chinese" };
    var japaneseBook = new Book() { BookCode = "B002", Isbn = "001", BookName= "Japanese" };
    var englishBook = new Book() { BookCode = "B003", Isbn = "001", BookName = "English" };

    james.Book = new List<Book>() { chineseBook, japaneseBook, englishBook };

    dbContext.Person.Add(james);
    dbContext.SaveChanges();
}

using (var dbContext = new TestDBContext())
{
    var james = dbContext.Person.Include(e => e.Book).First(e => e.Name == "James");

    dbContext.Person.Remove(james);

    dbContext.SaveChanges();
}
```

Finally, I got three book rows in database with Null value on column PersonCode, but the document said it should be the value won't be effected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
This will be covered by #473
