### ISSUE TITLE
Customize 404 page

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#107]
Does RTD support custom 404 pages?

Example: http://docs.efproject.net/en/latest/something_missing

![image](https://cloud.githubusercontent.com/assets/2696087/12248438/3f74bfd8-b86e-11e5-9aa2-470a70d8eb5b.png)

**Comment by rowanmiller** [comment]
Sadly it does not... some discussion on that here https://github.com/rtfd/readthedocs.org/issues/353

**Comment by natemcmaster** [comment]
:cry:
