### ISSUE TITLE
Multiple column mappings

### ISSUE THREAD

**Issue by MCFHTAGENTS** [aspnet/EntityFramework.Docs#1071]
Agree with #793 on the DBContext definition
Also - what is the syntax for mapping multiple columns and are the column attributes in the POCO object honoured?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-gb/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by MCFHTAGENTS** [comment]
I agree - this works but is quite cumbersome to maintain - attribute support anyone!
Thanks
Mark

**Comment by ajcvickers** [comment]
@MCFHTAGENTS Yes, attributes are supported.
