### ISSUE TITLE
Missed add a link for the text "How DbContext Discovers the Model and Database Connection topic"

### ISSUE THREAD

**Issue by fbilo** [aspnet/EntityFramework.Docs#1072]
Locate at the part 4. Reading & Writing Data, the "where is my data" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8be815-df51-dc77-fb5b-ccfa7f742e10
* Version Independent ID: 353c54e3-b7c9-fcdd-ca71-2a11beab19fd
* Content: [Code First to a New Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/new-database.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/workflows/new-database.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by Dave-Lowndes** [comment]
It would be good to have that topic linked in the text :+1:  How hard can it be to add it?

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
