### ISSUE TITLE
what is startup project for?

### ISSUE THREAD

**Issue by touseefbsb** [aspnet/EntityFramework.Docs#1079]
still failing to understand why we are creating a startup console project when we are not even going to use it? the steps described create migration folder in Database project rather than startup project, and we are not adding any code to startup project as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by neven10** [comment]
It's answer is  literally  at the beginning , in bold and marked !Important .
Don't skip while reading.

**Comment by touseefbsb** [comment]
I know on a technical level that startup is supposed to run the commands, I was just confused as there was no code whatsoever in the project, but I guess it doesnt need any code to run migrations like commands. Thanks for the help anyways.
