### ISSUE TITLE
Working with Transactions

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#108]
In particular, how to achieve scenarios that would previously have been done with TransactionScope

**Comment by ElvisHalil** [comment]
Looking for exactly this.  I am using repository pattern with EF 7 and have a method where all my DB updates happen.  I'd like to wrap all of these DB calls (Repository.Add + SaveChanges) into a single transaction so if anything fails everything rolls back for all repositories for that particular set of data. 

With what I've read it's currently not supported.  Any work around at this time?

**Comment by rowanmiller** [comment]
In RC1 you would need to use `context.Database.BeginTransaction()`/`UseTransaction()` to setup using the same transaction for multiple contexts. If all the data is being saved thru a single context instance, then it is already transactional.

**Comment by hikalkan** [comment]
Hi,

We may have also these scenarios:

* Multiple dbcontext type with single connection string (same database, different contexes)
* Multiple dbcontext type with multiple database (each dbcontext targets to a different database, in different server or same server)
* Single dbcontext type with multiple database (for example, a multi-tenant app which has a single dbcontext type but each tenant has it's own database), so there will be multiple instances of same dbcontext type in a unit of work

For such requirements, how can we create a transaction that will be shared by all these contexes :) Will EF Core support that?

**Comment by hikalkan** [comment]
And idea? Thanks.

**Comment by rowanmiller** [comment]
Hey,

First bullet point is covered in https://docs.efproject.net/en/latest/saving/transactions.html#cross-context-transaction-relational-databases-only. The other two would use the same technique, except you would need to use `DbConnection.EnlistTransaction(...)` since you would need two separate connections. The one disclaimer is that I haven't actually tried that, but I see no reason that it shouldn't work.

~Rowan

**Comment by hikalkan** [comment]
Thank you so much for leading me, and sorry for not finding the document before.
Have a nice day.

**Comment by rowanmiller** [comment]
Closing as we have docs now - https://docs.efproject.net/en/latest/saving/transactions.html

**Comment by xyting** [comment]
@rowanmiller 

Have any `Multiple dbcontext type with multiple database (each dbcontext targets to a different database, in same server)` demo code? I have not found any about your say `DbConnection.EnlistTransaction(...)`

hope your help, thanks!

**Comment by xyting** [comment]
@hikalkan 

Have any about `Multiple dbcontext type with multiple database (each dbcontext targets to a different database, in same server)` demo code? or more help links?

hope your help, thanks!

**Comment by hikalkan** [comment]
@xyting I don't have demo code.

**Comment by xyting** [comment]
@hikalkan Have any opinion about @rowanmiller point `DbConnection.EnlistTransaction(...)`?

**Comment by hikalkan** [comment]
Maybe he is saying UseTransaction. He can answer better :)

**Comment by rowanmiller** [comment]
Via the Database APIs you can only share a single transaction if you use the same connection, which won't work if you are targeting different databases. You probably want to spin up two transactions and then call `Commit()` on both once the operations succeed.
