### ISSUE TITLE
How do I insert foreign key related data?

### ISSUE THREAD

**Issue by kudlatiger** [aspnet/EntityFramework.Docs#1081]
when i execute below line, 
 modelBuilder.Entity&lt;DeviceTypeFamily&gt;().HasData(new DeviceTypeFamily {Name = "ABC" });

This line will produce auto generated guid, now this shall be the input for new table. How can we do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
@kudlatiger You need to specify the GUID value explicitly, `HasData` cannot be used with store-generated values
