### ISSUE TITLE
'Scaffold-DbContext' is not recognized -> require EF Tools

### ISSUE THREAD

**Issue by bertstomphorst** [aspnet/EntityFramework.Docs#1084]
"If you receive an error stating The term 'Scaffold-DbContext' is not recognized as the name of a cmdlet, then close and reopen Visual Studio."

Actual solution is to install nuget package Microsoft.EntityFrameworkCore.Tools

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/nl-nl/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by vivainio** [comment]
Yes, especially since this page appears prominently in google search

**Comment by dazinator** [comment]
Just hit by this.

**Comment by barsham** [comment]
thx for sharing.

**Comment by scarber777** [comment]
I ran into this on a console app. Installing Microsoft.EntityFrameworkCore.Tools didn't help, even after a VS restart. I used the EF CLI to scaffold. 

dotnet ef dbcontext scaffold "Server=.\;Database=AdventureWorksLT2012;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -o Model

**Comment by rumesh-smec** [comment]
Refer to this, it will make your life easier 

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell

**Comment by DanKyungu** [comment]
To resolve this issue, you will have to run this command in the package manager console Install-Package Microsoft.EntityFrameworkCore.Tools before to run the Scaffold-DbContext command, hope it help !

**Comment by bennyjonsson** [comment]
I had to start Visual Studio as an administrator to get it to work. Probably due to local policies in on our computers at my work...

**Comment by ajcvickers** [comment]
@bricelam @Rick-Anderson It looks like ASP.NET tutorial gets the package through ASP.NET scaffolding, so it doesn't need to be explicitly installed. Do you think we should change anything here?

**Comment by Rick-Anderson** [comment]
Yes, VS installs all the scaffolding packages and tools. If you select the [VSC tab](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio-code#scaffold-student-pages), it provides full instructions.

The meta-data in this issue points to our repo, why is this issue in the EF repo?

This page gets 22K PV/Month with a 92% CSAT.

Recommend closing.
