### ISSUE TITLE
Falta exemplos claros

### ISSUE THREAD

**Issue by gilsonbispo** [aspnet/EntityFramework.Docs#1098]
Algum dia voces deixaram a abordagem academica para demonstrar algo mais claro???
Isto ai não esclareceu nada!!!!

Translated:
Have you ever left the academic approach to demonstrate something clearer ???
This did not clarify anything !!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0eb2cf-b975-5468-d6c3-8c3526b97e90
* Version Independent ID: a9f2b88f-f586-f93d-7c99-2d605e539bcf
* Content: [EntityTypeBuilder.HasMany Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.hasmany?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@gilsonbispo Please provide more details on where you need clear examples.
