### ISSUE TITLE
Example seems prone to SQL Injection

### ISSUE THREAD

**Issue by jawn** [aspnet/EntityFramework.Docs#1104]
If I understand correctly, the following example in this doc seems prone to SQL injection, if the parameters are deteremined dynamically. If that's the case, this should be replaced with a parameterized version or at least a big warning.
```C#
var city = "London";
var contactTitle = "Sales Representative";

using (var context = CreateContext())
{
    context.Set&lt;Customer&gt;()
        .FromSql($@"
            SELECT *
            FROM ""Customers""
            WHERE ""City"" = {city} AND
                ""ContactTitle"" = {contactTitle}")
            .ToArray();
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ba7f05-993f-4213-9acb-ed02f9e8bb78
* Version Independent ID: eef6ac8f-8bbc-36af-c1cf-410b9bad7dfd
* Content: [What is new in EF Core 2.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0)
* Content Source: [entity-framework/core/what-is-new/ef-core-2.0.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-2.0.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@jawn `{city}` and `{contactTitle}` both indicate parameters and result in parameterization of the query as shown in the generated SQL. Because this doesn't just to string concatenation but instead does correct parameterization it should be safe from SQL injection.

**Comment by jawn** [comment]
I thought the $"" is determined first before being passed to the FromSql, like this:

![image](https://user-images.githubusercontent.com/1705112/48256322-8c0b6700-e40f-11e8-9bbf-4bffbc44f1ba.png)

If that is not the case then it's not an issue indeed.

**Comment by ronniedepriest** [comment]
HEY!!!
Jawn is correct - the $@ is NOT interpolation, it is creating a FormattableString object, this documentation needs fixed!
