### ISSUE TITLE
Safe String Interpoliation example

### ISSUE THREAD

**Issue by NetMage** [aspnet/EntityFramework.Docs#1105]
Does the Safe String Interpolation example have quotes in the proper places for the FromSQL? How could it know the parameter had spaces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ba7f05-993f-4213-9acb-ed02f9e8bb78
* Version Independent ID: eef6ac8f-8bbc-36af-c1cf-410b9bad7dfd
* Content: [What is new in EF Core 2.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0)
* Content Source: [entity-framework/core/what-is-new/ef-core-2.0.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-2.0.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@NetMage Can you explain a bit more what you mean? It looks correct to me, but I don't understand how the parameter having spaces is relevant since these are converted to SQL parameters anyway.

**Comment by NetMage** [comment]
In this code,

$@" SELECT * FROM ""Customers"" WHERE ""City"" = {city} AND ""ContactTitle"" = {contactTitle}"
My understanding is that the compiler (essentially) translates this into a call to String.Format that results in a string with the variables inserted inline.
SELECT * FROM "Customers" WHERE "City" = London AND "ContactTitle" = Sales Representative
How does EF Core modify this translation?
(Also, shouldn't the SQL no longer have doubled quotes?)

**Comment by ajcvickers** [comment]
@NetMage That's not how it works. The compiler makes the format string with placeholders and the parameters available so they can be translated into SQL with parameters.

**Comment by NetMage** [comment]
I'm sorry, I missed the compiler supporting FormattableString as an alternative to interpolation when C# 6 came out, I don't think it had a lot of publicity.

Thanks!

**Comment by ronniedepriest** [comment]
NO NO NO - this NOT interpolation, this is passing in a FormattableString Object!!!! Please fix the language on the page..... the syntax 
$@"", is creating a FormattableString object ---- BAD BAD, do NOT tell Devs to use string interpolation here, it is a SQLi!!!
