### ISSUE TITLE
The relationship fix-up note: previous only?

### ISSUE THREAD

**Issue by NetMage** [aspnet/EntityFramework.Docs#1106]
The relationship fix-up note implies only previously loaded entities in a context will be included, but I saw in other places that future loading of entities could cause fix-up of navigation properties to include those entities as well - is it just previous, or is it any time entities that belong to a navigation property are loaded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@NetMage Whenever an entity is tracked by the context it will be fixed up to all other entities that are tracked by the context.
