### ISSUE TITLE
Primary Keys of type String also get automatically generated Ids

### ISSUE THREAD

**Issue by acolombi** [aspnet/EntityFramework.Docs#1112]
"By convention, non-composite primary keys of type short, int, long, or Guid will be setup to have values generated on add. All other properties will be setup with no value generation."

I think type String will also get a Guid automatically generated on add. I'm looking at StringValueGenerator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Starting with EF Core 3.0, strings no longer get generated values by default.
