### ISSUE TITLE
Circular references in Definition of Terms

### ISSUE THREAD

**Issue by SimpleSamples** [aspnet/EntityFramework.Docs#1125]
In your "Definition of Terms", Dependent entity says "contains the foreign key" and Foreign key says "property(s) in the dependent entity". That is a circular reference, right? Does "foreign key" mean something different from the typical definition for databases in general? If so then its definition should not depend on dependent entities. Even if a foreign key in this context is defined the same as for other databases the term should not be defined in a manner that implies they are specific to this context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@SimpleSamples Can you explain in more detail what you mean by, "the term should not be defined in a manner that implies they are specific to this context?"

**Comment by divega** [comment]
Triage: It is not clear to us what we can do to improve this here and we haven't gotten an answer. If there are ideas to improve these definitions, a good way to go about it is to send a PR with some suggestions.
