### ISSUE TITLE
Can we use an abstract class as a base class of the hierarchy?

### ISSUE THREAD

**Issue by DeveloperLookBook** [aspnet/EntityFramework.Docs#1128]
Can we use an abstract class as a base class of the hierarchy? Please,  add example of the DB settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7106ae9-405f-8857-cd3e-571e966dea10
* Version Independent ID: 62ce23dc-9e20-525a-ea51-0dd76c1b7812
* Content: [Inheritance (Relational Database) - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance)
* Content Source: [entity-framework/core/modeling/relational/inheritance.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/inheritance.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by kentliu2007** [comment]
Yes, I've tried this in one of my recently EF Core project.
For the parent class and child classes, it will AS IS what we doing usually.
For example:
public abstract class Function { ...}
public class Menu : Function {...}

In the DBContext class, we can expose above classes to DBSet, and only need to define the Entity for <Function> :
public class MyDBContext : DbContent
{
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
...
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
...
modelBuilder.Entity<Function>(entity =>
            {.....});
....
}
But if you want to have any other specific requirements such as Ignore Properties of sub class, you can continue declare these, for example:
modelBuilder.Entity<Memu>().Ignore(e => e.MenuProperty1);
