### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by andres-carrilloAdapt2** [aspnet/EntityFramework.Docs#1129]
Hello, Is the OnModelCreating method necessary? or is it optional? how will the database know which columns map to which property without it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1226698-6874-6f8f-f716-1974152243fa
* Version Independent ID: 9e7bdb7a-d3dc-03a2-99f6-78aa46cc8357
* Content: [Porting from EF6 to EF Core - Porting a Code-Based Model](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code)
* Content Source: [entity-framework/efcore-and-ef6/porting/port-code.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/porting/port-code.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@andres-carrilloAdapt2 Both EF Core and EF6 do some amount of model configuration based on conventions and attributes. For example, when you have a `DbSet<TEntity>` property on your derived DbContext, EF (any version that supports code first) will try to infer the basic mappings by using reflection on the given .NET entity type. While reflecting on the type, it will also look for certain attributes from System.ComponentModel.DataAnnotations (and some others in the case of EF Core) like KeyAttribute to infer additional model configuration. EF will also consider a property called `Id` or entity-type-name + `Id` is the key and needs to be auto-generated. 

So in theory you only need to override OnModelCreating and make calls to code first methods if the information from reflection, conventions and attributes is insufficient. In my experience most real-world applications need some amount of explicit model configuration. 

There are also much more advanced ways of using EF in which to create the model separately and then you pass it to the DbContext.
