### ISSUE TITLE
As always, irrelevent links...

### ISSUE THREAD

**Issue by BDTomasz** [aspnet/EntityFramework.Docs#1133]
I got an error in a project I am working on, another dev built it and now I am trying to run it and make some updates but getting an error linking me to http://go.microsoft.com/fwlink/?LinkId=260882... useless as always

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ff9e912-8811-412a-e31d-6f1a3a8a5264
* Version Independent ID: c095d046-e38c-cb8f-c036-93e7de86c774
* Content: [Overview - EF6](https://docs.microsoft.com/en-nz/ef/ef6/index)
* Content Source: [entity-framework/ef6/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/index.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
This link is supposed to point to https://docs.microsoft.com/ef/ef6/fundamentals/configuring/config-file#ef-database-providers-ef6-onwards. 

Apparently the fwlink is pointing to some specific page that wasn't redirected correctly during the documentation migration, although I confirmed that http://msdn.com/data/jj556606 redirects correctly. 

I will try to get the fwlink updated.

**Comment by divega** [comment]
Note to self: http://msdn.microsoft.com/data/jj730568 should redirect to this too.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
