### ISSUE TITLE
YouTube version 

### ISSUE THREAD

**Issue by krchome** [aspnet/EntityFramework.Docs#1136]
YouTube version at :
 https://www.youtube.com/edit?o=U&ar=1&video_id=I-vajE9ZKC4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@krchome that link is invalid. I assume you wanted to post "watch?" URL, not this one.

**Comment by martinoc** [comment]
https://www.youtube.com/watch?v=I-vajE9ZKC4
