### ISSUE TITLE
Add `Console.WriteLine` calls to samples

### ISSUE THREAD

**Issue by blno** [aspnet/EntityFramework.Docs#1139]
Note from @divega: this is a suggestion to introduce some descriptive Console.WriteLine() calls in the sample code in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a14313-c182-e33a-08e5-63b126bbf90e
* Version Independent ID: f800faf2-93f7-8632-772a-0355080f5952
* Content: [Async query and save - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/async)
* Content Source: [entity-framework/ef6/fundamentals/async.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/async.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by blno** [comment]
public static void PerformDatabaseOperations()
            {
                using (var db = new BloggingContext())
                {
                    // Create a new blog and save it
                    db.Blogs.Add(new Blog
                    {
                        Name = "Test Blog #" + (db.Blogs.Count() + 1)
                    });

Console.WriteLine("Calling SaveChanges.");
                    db.SaveChanges();

                    // Query for all blogs ordered by name
Console.WriteLine("Executing query.");
                    var blogs = (from b in db.Blogs
                                orderby b.Name
                                select b).ToList();

                    // Write all blogs out to Console
Console.WriteLine("Query completed with following results:");
                    Console.WriteLine();
                    Console.WriteLine("All blogs:");
                    foreach (var blog in blogs)
                    {
                        Console.WriteLine(" " + blog.Name);
                    }
                }
            }

**Comment by divega** [comment]
@blno when you submit feedback please try to write down some details in the initial post. We also accept contributions to the documentation, and it is quite easy to do by clicking on the edit (:pencil2:) button on the page you want to change.

**Comment by divega** [comment]
Triage: At this point we are not planning to retroactively add more Console.WriteLine calls to existing samples and code snippets. We will consider PRs to specific samples and if they really add clarity to the sample, we will likely incorporate them.
