### ISSUE TITLE
Owned collections moved to 3.0.0?

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework.Docs#1146]
As per this issue: https://github.com/aspnet/EntityFrameworkCore/issues/13295. If I'm interpreting that correctly, you might want to remove it from this 2.2 doc. If I'm misinterpreting, can you clarify? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9091a2-2335-76a4-74a1-366daed70f6c
* Version Independent ID: ab1cba85-048f-d55b-6276-545317f5a624
* Content: [What is new in EF Core 2.2 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.2)
* Content Source: [entity-framework/core/what-is-new/ef-core-2.2.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-2.2.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@julielerman owned collections are supported in EF Core 2.2, but on relational providers you have to configure the keys of the owned entities. Issue aspnet/EntityFrameworkCore#13295 is only about making that additional ceremony unnecessary in the future.

**Comment by julielerman** [comment]
yikes. Thanks for clarifying!! I have unwittingly miscommunicated this in a few conference sessions . :( I'll go try it out !
