### ISSUE TITLE
Possibly compile time error

### ISSUE THREAD

**Issue by benneyman** [aspnet/EntityFramework.Docs#1153]
In the code snippet under Attaching a new entity to the context, the variable ```blog``` is defined twice within a scope. 
```
using (var context = new BloggingContext())
{
    // Add a new User by setting a reference from a tracked Blog
    var blog = context.Blogs.Find(1);
    blog.Owner = new User { UserName = "johndoe1987" };

    // Add a new Post by adding to the collection of a tracked Blog
    var blog = context.Blogs.Find(2);
    blog.Posts.Add(new Post { Name = "How to Add Entities" });

    context.SaveChanges();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130521ba-2943-c640-4190-7e22af37e154
* Version Independent ID: c31908e9-2836-8efd-5df6-e9dc5b5a9a5f
* Content: [Working with entity states - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/change-tracking/entity-state)
* Content Source: [entity-framework/ef6/saving/change-tracking/entity-state.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/change-tracking/entity-state.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Good catch @benneyman!
