### ISSUE TITLE
Sample code and description inconsistent

### ISSUE THREAD

**Issue by victor-david** [aspnet/EntityFramework.Docs#1160]
### Code sample the doc displays
~~~c#
[ComplexType]
public class BlogDetails
{
    // defined as nullable
    public DateTime? DateCreated { get; set; }

    [MaxLength(250)]
    public string Description { get; set; }
}
~~~

### Text that follows the code sample
> Another interesting note is that although the DateCreated property was defined as a **non-nullable** DateTime in the class, the relevant database field is nullable. You must use the Required annotation if you wish to affect the database schema.

The text below the sample is misleading / possibly confusing to the reader. The DateTime object is indeed defined as nullable and the corresponding database field is nullable; this is default behavior.  A non-nullable DateTime is automatically considered required and therefore creates a non-nullable database field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7bd305-ac97-ca3c-f8c0-031d8d9c7599
* Version Independent ID: 2d0b358a-5cfd-60e4-251f-c4e824bba348
* Content: [Code First Data Annotations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations)
* Content Source: [entity-framework/ef6/modeling/code-first/data-annotations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/data-annotations.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
