### ISSUE TITLE
Magic strings?

### ISSUE THREAD

**Issue by Serjster** [aspnet/EntityFramework.Docs#1163]
You saying that the Microsoft recommended way is to use magic strings??? Really?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b143a3f-aecb-49b6-66e1-0c459af0e2de
* Version Independent ID: 1b594bfc-f0a3-4938-a415-50ea34805d8e
* Content: [Data Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types)
* Content Source: [entity-framework/core/modeling/relational/data-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/data-types.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@Serjster By "magic strings" I assume you mean things like "varchar(256)"? If so, these are database-specific types (in this case for SQL Server) and are defined by the database, not by EF. This API is specifically about allowing mapping to any database-specific type, which EF may no nothing about.

**Comment by Serjster** [comment]
These should be an enum or method extension that is T-SQL specific or something that allows you to specify the type without using magic strings. This is well known bad coding practice.

**Comment by acharcourts** [comment]
I encountered the same issue converting from EF6 fluent configuration `DecimalPrecision()` and just coded a trivial extension of my own to remove magic strings from code.

```
public static class EfCoreExtensions
{
        public static PropertyBuilder HasDecimalPrecision(this PropertyBuilder propertyBuilder, byte precision, byte scale)
        {
            return propertyBuilder.HasColumnType($"decimal({precision}, {scale})");
        }
}
```
