### ISSUE TITLE
Misleading statement about owned types

### ISSUE THREAD

**Issue by voroninp** [aspnet/EntityFramework.Docs#1168]
&gt; EF Core allows you to model entity types that can only ever appear on navigation properties of other entity types.

This is wrong. At least `EF Core 2.2` allows me to read/create owned entities separately via `Set&lt;OwnedType&gt;()` method. In other words there is no point in saying
&gt; can only ever appear on navigation properties
 
Proof:

```CSharp
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EfCore22.OwnedTypes
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new TestContext())
            {
                ctx.Database.EnsureCreated();
                ctx.Add(new Order { Items = { new OrderItem { Name = "Just an item." } } });
                ctx.SaveChanges();
            }

            using (var ctx = new TestContext())
            {
                var entry = ctx.Add(new OrderItem { Name = "Other item" });
                entry.Property("OrderId").CurrentValue = 1;
                ctx.SaveChanges();
            }

            Console.ReadKey();
        }
    }

    public class Order
    {
        public int Id { get; set; }
        public List&lt;OrderItem&gt; Items { get; } = new List&lt;OrderItem&gt;();
    }

    public class OrderItem
    {
        public string Name { get; set; }
    }

    public class TestContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=OwnedTypes");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity&lt;Order&gt;(b =&gt;
            {
                b.OwnsMany(m =&gt; m.Items, ob =&gt;
                {
                    ob.Property&lt;int&gt;("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd();

                    ob.HasForeignKey("OrderId");

                    ob.HasKey("Id", "OrderId");
                    ob.ToTable("OrderItems");
                });
            });
        }
    }
}
```

If it is an unintended behaviour it should stay as it is now for some time and here is why:
If you practice DDD then using owned entity types allows to set the shape of aggregate. (I know you have a separate ticket for it to define which navigation properties are always included.)
It is also common to use private access modifier for navigation properties to hide internal structure of an aggregate and provide all access via API of Aggregate Root. It is fine, but at some point you need query side, and in case owned entities cannot be queried independently as any other `DbSet` you are in trouble.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
@voroninp I don't understand what you are trying to show in the example, you still have the navigation to the owned type - `Order.Items`.

Owned types follow roughly the DDD concept of aggregates - you can't reference a part of the aggregate directly, only through the root.

**Comment by AndriySvyryd** [comment]
> I interpreted this statement as navigation properties are the only way to access owned entities, as if I needed to query owner first to get access to owned entity or set owner's navigation property as the only mean to insert owned entity.

This is correct.
>My code shows that I can use Set method to work with owned entities directly, that is owned entities can appear NOT ONLY on navigation properties ;-) So statement is ambiguous for interpretation.

I don't see the `Set` method being used in your code and if you did it shouldn't work unless there's a bug in EF.

**Comment by voroninp** [comment]
@AndriySvyryd, it works, I tried it.

```CSharp
var entry = ctx.Add(new OrderItem { Name = "Other item" });
                entry.Property("OrderId").CurrentValue = 1;
                ctx.SaveChanges();
```
Are not you confused that I am able to insert `OtderItem` owned entity not via `Order`?

**Comment by AndriySvyryd** [comment]
@voroninp Since you are setting the FK value you are asserting that the owner exists in the database, but you still had to query the owner at some point to get the value. This way of persisting changes to the owned types is a bit more elaborate, so we don't mention it in the introductory docs. Besides it wouldn't work if the owned type was sharing the table with the owner.

**Comment by voroninp** [comment]
@AndriySvyryd , ok, version with `Set` method:

```CSharp
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace EfCore22.OwnedTypes
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new TestContext())
            {
                ctx.Database.EnsureCreated();
                ctx.Add(new Order { Items = { new OrderItem { Name = "Just an item." } } });
                ctx.SaveChanges();
            }

            using (var ctx = new TestContext())
            {
                var items = ctx.Set<OrderItem>().ToList();
                Console.WriteLine($"I managed to successfully get '{items.Count}' order items.");
            }

            Console.ReadKey();
        }
    }

    public class Order
    {
        public int Id { get; set; }
        public List<OrderItem> Items { get; } = new List<OrderItem>();
    }

    public class OrderItem
    {
        public string Name { get; set; }
    }

    public class TestContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=OwnedTypes");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Order>(b =>
            {
                b.OwnsMany(m => m.Items, ob =>
                {
                    ob.Property<int>("Id")
                        .IsRequired()
                        .ValueGeneratedOnAdd();

                    ob.HasForeignKey("OrderId");

                    ob.HasKey("Id", "OrderId");
                    ob.ToTable("OrderItems");

                });
            });
        }
    }
}
```

**Comment by AndriySvyryd** [comment]
@voroninp I see, I filed https://github.com/aspnet/EntityFrameworkCore/issues/14153
