### ISSUE TITLE
Rename Foreign Key Index

### ISSUE THREAD

**Issue by efrainsteinbach** [aspnet/EntityFramework.Docs#1169]
I'm looking for a way to rename the index which is automatically created on every foreign key (i.e. navigation property). I need this because the generated index names are too long (MySql only allows 64 chars). 
How can I override the default naming using the fluent API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@efrainsteinbach Explicitly configure an index on the FK properties and then use HasName: See https://docs.microsoft.com/en-us/ef/core/modeling/relational/indexes

**Comment by efrainsteinbach** [comment]
I tried this, but it did not work - I think it just created an extra index...? 
Will EF then always prefix those names with IX_ and FK_ ? 

Btw, why I wanted to do this: I'm migrating from EF6 and we use a MySql DB, which has a max length for index and FK names of only 64 characters. With the new naming convention for IXs and FKs in EF Core my model exceeded this quite frequently.

I found a workaround in simply truncating the names after I'm done defining the model using:

    foreach(var entity in builder.Model.GetEntityTypes())
    {
            foreach(var key in entity.GetForeignKeys())
            {
                key.Relational().Name = Truncate(key.Relational().Name);
            }

            foreach(var index in entity.GetIndexes())
            {
                index.Relational().Name = Truncate(index.Relational().Name);
            }
     }

(from: https://andrewlock.net/customising-asp-net-core-identity-ef-core-naming-conventions-for-postgresql/)

**Comment by ajcvickers** [comment]
@efrainsteinbach If it doesn't work with the MySQL provider, then you'l want to file an issue on that provider.

**Comment by ajcvickers** [comment]
@efrainsteinbach Which part is not documented? That an index explicitly specified over the same properties as an index created by convention will replace the index created by convention?
