### ISSUE TITLE
Database Update on Initial Migration

### ISSUE THREAD

**Issue by scottkuhl** [aspnet/EntityFramework.Docs#1174]
The documentation states that after you apply the initial migration you need to run a database update to update the schema.  It appears (maybe with a new tooling release?) that the database update automatically runs against your database when you run your initial migration.

Example:

Add-Migration Initial

This will create the initial migration file, the snapshot and create the database with a matching schema.

**Comment by ajcvickers** [comment]
@scottkuhl This should not happen. Can you please file an issue on https://github.com/aspnet/EntityFrameworkCore/issues including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
