### ISSUE TITLE
Deprecated Filtering method

### ISSUE THREAD

**Issue by yringler** [aspnet/EntityFramework.Docs#1179]
The docs show a constructor to use filtering.
It is marked as deprecated, and should be updated.
		[Obsolete("This method is obsolete and will be removed in a future version. The recommended alternative is using LoggerFactory to configure filtering and ConsoleLoggerOptions to configure logging options.")]
		public ConsoleLoggerProvider(Func&lt;string, LogLevel, bool&gt; filter, bool includeScopes);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83069f-39a8-e992-95f7-a8b41154b6f4
* Version Independent ID: 144fe168-080f-6557-e4b2-a18adb4b89ed
* Content: [Logging - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging)
* Content Source: [entity-framework/core/miscellaneous/logging.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/logging.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by sheeri185adidam** [comment]
Has anyone looked into this? I am starting to learn about EF and going through the documentation.
Would appreciate if experts could comment here or can update the documentation. Thanks

**Comment by zerda** [comment]
From https://github.com/aspnet/EntityFramework.Docs/pull/1164#issuecomment-451748026,  ignore the warnings and/or adding a suppression in the code would be enough for 2.2.

And from https://github.com/aspnet/Extensions/issues/615#issuecomment-447061661, We may use [`LoggerFactory.Create`](https://github.com/aspnet/Extensions/blob/v3.0.0-preview.19074.2/src/Logging/Logging/src/LoggerFactory.cs#L50) in .Net Core 3.0.

```csharp
var loggerFactory = LoggerFactory.Create(builder => { 
    builder.AddConfiguration(loggingConfiguration.GetSection("Logging"))
        .AddFilter("Microsoft", LogLevel.Warning)
        .AddFilter("System", LogLevel.Warning)
        .AddFilter("SampleApp.Program", LogLevel.Debug)
        .AddConsole()
        .AddEventLog();
});
```

**Comment by yringler** [comment]
Thank you, @zerda. I read #1164, and that is the same issue as described here. Also, @0xced has a PR!
