### ISSUE TITLE
Issues running the project

### ISSUE THREAD

**Issue by gsulc** [aspnet/EntityFramework.Docs#1192]
Changing the Working directory as per the instructions does not fix the problem described. I also tried the bin/Debug/netcoreapp2.1 and solution directories to no avail. I also tried using the package manager console, changed to the project directory and used, "dotnet run". Same problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite#vs)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gsulc** [comment]
My mistake. I skipped a step in the instructions. Apologies.

**Comment by spankr** [comment]
If you want to avoid using migrations (which I don't normally recommend) and just want your sqlite db created and your models registered, you can just ```ctx.Database.EnsureCreated()``` before any operations on the db context.

```
using (var db = new BloggingContext())
{
     db.Database.EnsureCreated();
     db.Blogs.Add(new Blog { Url = "http://blogs.msdn.com/adonet" });
     var count = db.SaveChanges();
     Console.WriteLine("{0} records saved to database", count);
}
```

This will dynamically create your database from wherever you are running your application. For me, in Visual Studio, it was in ```<projectdir>/bin/Debug/netcoreapp2.2/```.
