### ISSUE TITLE
How do I call a db function that returns a primitive type?

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework.Docs#1194]
I want to call a built-in db function that returns a `bit`, how would I achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by ErikEJ** [comment]
Create a QueryType

     public class BitValue()
     {
         public bool Bit { get; set; }
      }

And get it using FromSQL

**Comment by weitzhandler** [comment]
@ErikEJ Funny but thanks. Would be a great idea to get the results directly for primitive types.

**Comment by ErikEJ** [comment]
Yes, agree on "funny" - making it simpler is under consideration!

**Comment by ErikEJ** [comment]
See https://github.com/aspnet/EntityFrameworkCore/issues/11624

**Comment by weitzhandler** [comment]
It's possible using the connection to create a command:

```c#
public static async Task<T> ExecuteScalarAsync<T>(this DbContext context, string rawSql,
  params object[] parameters)
{
  var conn = context.Database.GetDbConnection();
  using (var command = conn.CreateCommand())
  {
    command.CommandText = rawSql;
    if (parameters != null)
      foreach (var p in parameters)
        command.Parameters.Add(p);
    await conn.OpenAsync();
    return (T)await command.ExecuteScalarAsync();
  }
}
```
