### ISSUE TITLE
Please add docs on this method

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework.Docs#1197]
As I understand this is the extension point to adding custom annotations to model to be later consumed by DB providers.
Please add docs to clarify what annotations are in general, where they're added, and they can be consumed later on using the `MigrationBuilder`.

[Related](https://github.com/aspnet/EntityFramework.Docs/issues/1203)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07249adc-d265-e97e-784a-b7a346da903c
* Version Independent ID: 569ce427-477b-7721-688b-c1251f77b111
* Content: [EntityTypeBuilder.HasAnnotation(String, Object) Method (Microsoft.EntityFrameworkCore.Metadata.Builders)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder.hasannotation?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
This should be part of docs on writing a new provider.

**Comment by weitzhandler** [comment]
I've read it, still haven't been able to find the specific criterion of "inject my custom migrations using the `ModelBuilder`. Again, I do believe it's related to migration operations and implementing a custom `SqlServerMigrationsSqlGenerator`, which would be easy to inject. Question is how do I store model metadata to be later read by the migrations routine.

**Comment by weitzhandler** [comment]
I think I actually found it [here](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations#using-migrationbuildersql), I'm gonna close this issue for now.
