### ISSUE TITLE
References in owned entities?

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework.Docs#1199]
Is it possible to have relational columns / navigation properties in owned entities? 

For example:

```c#
public class User {
  ...
}

public class Picture { 
    ...
  public ICollection<Comment> Comments { get; }
}
public class Post { 
    ...
  public ICollection<Comment> Comments { get; }
}

[Owned]
public class Comment
{
  public int UserId { get; set; }
  public User User { get; set; }  

  public string Content { get; set; }
}
```

Where `Picture` and `Post` have an owned collection `Comments`, and each `Comment` has a reference to `User`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
Yes, this is supported. Have you run in any issues?

**Comment by weitzhandler** [comment]
No, I have an existing model and wanted to ask before I start fiddling around.
Will re-open if I bump into any issues.
Thank you!

**Comment by weitzhandler** [comment]
@AndriySvyryd Thank you, will report if I bump into issues.

Can a nested collection entity have an inner nested collection? How about a hierarchy?

I want to achieve this:

```c#
public class Blog {
  public int Id { get; set; }
  //shared owned collection of Comment
  public virtual ICollection<Comment> { get; set; }
}
public class Post {
  public int Id { get; set; }
  //shared owned collection of Comment
  public virtual ICollection<Comment> { get; set; }
}
public class Comment
{
  public int Id { get; set; }
  // should be the FK of either Blog or Post
  public int ForeignId { get; set; }
  //nested owned collection
  public virtual ICollection<Comment> { get; set; }
}
```

Is this possible?

**Comment by AndriySvyryd** [comment]
> Can a nested collection entity have an inner nested collection?

Yes, but you need to configure each level

> How about a hierarchy?

Yes in theory, but I don't think it's supported in 2.2

**Comment by AndriySvyryd** [comment]
@weitzhandler If the above is actually what you want to model it might make more sense to avoid owned collections and instead make `Comment` an abstract class without `ForeignId` with 4 implementations:
```C#
public class BlogComment : Comment
{
  public int BlogId { get; set; }
}
public class PostComment : Comment
{
  public int PostId { get; set; }
}
public class BlogCommentComment : BlogComment
{
  public int CommentId { get; set; }
}
public class PostCommentComment : PostComment
{
  public int CommentId { get; set; }
}
```

I can also show how to configure relationships if you'd like.
Obviously if your actual model is more complex this approach won't scale well.

**Comment by weitzhandler** [comment]
Thanks for your response @AndriySvyryd.
1. First, I thought the `Comment`s should have been hierarchical (like a tree), maybe it's not a good idea after all, and only allow 2 levels.
2. It would be nice if we can later to easily retrieve all data per user, will all comments be stored in a single table because of TPH?

**Comment by weitzhandler** [comment]
The problem is I have more types I need `Comment`s on, and I also have `Vote` for any of those types, and `Vote` should be applied to `Comment`s too.
Is there a way to create a contained one-to-many relationship without having to have it all scattered over the entire place? In your last post, how did you mean on configuring with the `ModelBuilder`? For each `Comment` type set up a many-to-many?

**Comment by weitzhandler** [comment]
I ended up creating two nullable FKs on `Comment`: `PostId` and `CommentId`, and set them up as two independent one-to-one optional relationships. Thank you for your advice!
