### ISSUE TITLE
How do intercept annotations?

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework.Docs#1210]
Hi,

I set up my model adding custom annotations to some entities with the fluent API in the `OnModelCreating` call.  
How can I intercept this data when generating the tables when overriding the Generate methods?

Please see this issue: https://github.com/aspnet/EntityFramework.Docs/issues/1203

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7090a5e2-9109-264e-5b55-cc6505a522c3
* Version Independent ID: b81a4fe0-42b5-92c0-8534-db0580d01be8
* Content: [SqlServerMigrationSqlGenerator Class (System.Data.Entity.SqlServer)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlservermigrationsqlgenerator?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity.SqlServer/SqlServerMigrationSqlGenerator.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.SqlServer/SqlServerMigrationSqlGenerator.xml)
* Product: **entity-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by weitzhandler** [comment]
Ok got it

    protected override void Generate(CreateTableOperation operation, IModel model, MigrationCommandListBuilder builder)
   {
       var entity = model.GetEntityTypes().Single(et => et.GetSql().TableName == operation.Name);
       var annotations = entity.GetAnnotations().Where(an => an.Name.StartsWith(myAnnotationScope));
       // do my stuff
   }

But it would be nice to have it documented somewhere, @divega @AndriySvyryd.

**Comment by pcopley** [comment]
Is it possible to do this if you are overriding `Generate` with the base `MigrationOperation`? I would like to be able to get the entity and their annotations for all operations not just `CreateTable`.
