### ISSUE TITLE
EFGetStarted could not be found

### ISSUE THREAD

**Issue by ChefSQL** [aspnet/EntityFramework.Docs#1218]
In my Startup.cs after the existing using's I've added:
(Per: Register and configure your context in Startup.cs)

using EFGetStarted.AspNetCore.ExistingDb.Models;
using Microsoft.EntityFrameworkCore;

And now I get this error: CS0246 : The type or namespace name 'EFGetStarted' could not be found (are you missing a using directive or an assembly reference?)

I am using: Microsoft Visual Studio Enterprise 2017 Version 15.9.4
and
.NET Core 2.1 SDK
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db?view=aspnetcore-2.2)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ChefSQL** [comment]
It was not clear that the "EFGetStarted.AspNetCore.ExistingDb" was named this because of the name of the project. I am using this tutorial to help me connect a project with a different name to an existing database. When I changed "EFGetStarted.AspNetCore.ExistingDb" to my project name it works.

**Comment by divega** [comment]
@ChefSQL, I added in https://github.com/aspnet/EntityFramework.Docs/commit/618a7c19c3b56b49b9c07cc50cac07c6784bfe96 some clarification, but not sure it will help.
