### ISSUE TITLE
RC2: Update docs generated property docs since triggers will be supported

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#122]
In RC1 you can't really setup `ValueGeneratedOnAddOrUpdate` for properties other than `ROWVERSION` because you can't use triggers (due to aspnet/EntityFramework#1441).

We should update the following docs with examples once they work end-to-end:
- generated-properties.rst
- explicit-generated-values.rst

**Comment by rdefreitas** [comment]
Adding a reference to aspnet/EntityFramework#5793 so this can be easily found by those getting here from the docs.
