### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by rolandwales10** [aspnet/EntityFramework.Docs#1224]
I tried running this code in Studio 2017, and I'm getting errors.  I added system.data.entity and system.data.sqlClient.  It's getting further, but is still missing things, like app.config.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8be815-df51-dc77-fb5b-ccfa7f742e10
* Version Independent ID: 353c54e3-b7c9-fcdd-ca71-2a11beab19fd
* Content: [Code First to a New Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/new-database.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/workflows/new-database.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@rolandwales10 The steps in this document normally work correctly in Visual Studio 2017. The step in which you install the EntityFramework NuGet package should be sufficient and you shouldn't need to add any assembly references. 

If that doesn't work, it is possible that something specific in your solution or your Visual Studio installation is preventing things from working. If you still think you are hitting a bug, please create an issue in the product repository: https://github.com/aspnet/entityframework6/.
