### ISSUE TITLE
Some of these examples look like they will deadlock SQL server or create a race condition

### ISSUE THREAD

**Issue by StingyJack** [aspnet/EntityFramework.Docs#1232]
Using the IF-EXISTS-UPDATE-ELSE-INSERT pattern in SQL can create deadlocks unless transacted and/or `UPDLOCK`'ed (or `MERGE`/`HOLDOCK`).  This pattern in code is a race condition.  

A good example here of the correct pattern to avoid these problems with EF will save a lot of bugs and time wasted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9826f28-46b2-e845-f1bf-5cbc2d940208
* Version Independent ID: 9c4a46cf-daa2-0e14-7ff1-c195db237cd0
* Content: [Disconnected Entities - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities)
* Content Source: [entity-framework/core/saving/disconnected-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/disconnected-entities.md)
* Product: **entity-framework**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
@StingyJack Could you provide a runnable project that causes a deadlock?

**Comment by StingyJack** [comment]
> Deadlock or create a race condition.

I forget the specific examples but it was within the first few I looked at did not wrap the operation sequence of "IF EXIST THEN UPDATE ELSE INSERT" in a TransactionScope or similar construct. Is there a different repo for EF samples that would have directed me to here for documentation issues?

**Comment by AndriySvyryd** [comment]
You can see the sample code under https://github.com/aspnet/EntityFramework.Docs/tree/master/samples/core
