### ISSUE TITLE
Getting Started for UWP is missing Properties/Default.rd.xml entry

### ISSUE THREAD

**Issue by LanceMcCarthy** [aspnet/EntityFramework.Docs#124]
Go to [this section in the docs](https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/platforms/uwp/getting-started.rst#create-a-new-project) and see the bulleted line stating "Add the highlighted line shown below"

There is no highlighted line to use.

**Comment by rowanmiller** [comment]
Are retying to read the docs on GitHub? If so, they won't render properly as they are written in RST which GitHub does not support. Here is the hosted version of the doc http://docs.efproject.net/en/latest/platforms/uwp/getting-started.html and I do see the line highlighted.

**Comment by rowanmiller** [comment]
Are trying to read the docs on GitHub? If so, they won't render properly as they are written in RST which GitHub does not support. Here is the hosted version of the doc http://docs.efproject.net/en/latest/platforms/uwp/getting-started.html and I do see the line highlighted.

**Comment by LanceMcCarthy** [comment]
Thanks Rowan, silly me :)
