### ISSUE TITLE
Need examples

### ISSUE THREAD

**Issue by LJ9999** [aspnet/EntityFramework.Docs#1240]
This documentation is worthless without examples to demonstrate its intended usage.

Entity Framework creates the following:
     public System.Data.Entity.DbSet&lt;TheGLJ.Models.SearchMusic&gt; SearchMusic { get; set; }

What the hell is this? What do I do with it? Does something happen behind the curtains? If so, what? Do I add methods to it to access stuff? Nope. Tried that. VS pukes it out.

Do I have to read an 800-page book to figure it out? Okay. Then at least tell me what the book title is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59700745-ebd6-0a07-ec1f-3bff787b6aa1
* Version Independent ID: 5f45a6cf-f0b1-11c0-384b-bacd2a4aa988
* Content: [DbSet&lt;TEntity&gt; Class (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbset-1?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/DbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbSet`1.xml)
* Product: **entity-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by REscobar** [comment]
I agree, the documentation should point to `DbContext` docuementation for guidance on how to use this, but even then, there are no examples on how to write code that uses this classes

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
