### ISSUE TITLE
What about relation in tables

### ISSUE THREAD

**Issue by cristiangiagante** [aspnet/EntityFramework.Docs#1244]
What if i need to put ON identity_insert in more than one table?, I need to turn on and off but SaveChanges() cannot let to do it progressively. This is a big stopper to work with updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e621a525-7104-74bf-5a17-9f5761f75fab
* Version Independent ID: 3d0e675b-3b2a-ebd9-273b-312c5c6ac092
* Content: [Setting Explicit Values for Generated Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/explicit-values-generated-properties)
* Content Source: [entity-framework/core/saving/explicit-values-generated-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/explicit-values-generated-properties.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@cristiangiagante I'm having difficult following what exactly you are asking for. Can you provide some more details?

**Comment by smitpatel** [comment]
Closing due to lack of response.
