### ISSUE TITLE
Client evaluation logging needs more details

### ISSUE THREAD

**Issue by axdiamond** [aspnet/EntityFramework.Docs#1252]
Its awesome that EF core logs client side evaluation, but this article doesn't tell me what they it looks like or what verbosity it logs at.

I would like an example of where this would be logged and what it looks like, so I can look for these logs in my own system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd35b912-445c-e801-7f70-de73839db80d
* Version Independent ID: e558a081-5397-1e3f-1d58-abea3f72cad6
* Content: [Client vs. Server Evaluation - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/client-eval)
* Content Source: [entity-framework/core/querying/client-eval.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/client-eval.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
No longer relevant in 3.0 since this warning has been removed.

**Comment by ygoe** [comment]
Oh. How can I know then when it does some of the dangerous stuff mentioned above (like potential memory leaks)?

**Comment by jpmckearin** [comment]
@ygoe it throws an application-level exception now.
