### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by sfeierabend** [aspnet/EntityFramework.Docs#1253]
You write "Run the Enable-Migrations command in Package Manager Console"

In Visual Studio 2017 15.8.9 the command returns:
Enable-Migrations is obsolete. Use Add-Migration to start using Migrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Code First Migrations - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/index)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by th0mk** [comment]
In Entity Framework Core, Enable-Migrations is obsolete. The documentation you're reading is for Entity Framework 6.
For migrations in EF Core please check out [this documentation](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/) instead.

**Comment by sfeierabend** [comment]
Sorry, you're right. All the different versions are sometimes confusing.
Thanks for your response.

**Comment by Venkat-ramana-reddy** [comment]
no Enable-Migrations command is not working in visual studio 2017 community edition it gives the following error,

The term 'Enable-Migrations' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was inc
luded, verify that the path is correct and try again.
At line:1 char:18
+ Enable-Migrations <<<< 
    + CategoryInfo          : ObjectNotFound: (Enable-Migrations:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException.

please help me how to solve this so i can go further.
