### ISSUE TITLE
I have no clue what Step 4 is telling me.

### ISSUE THREAD

**Issue by LJ9999** [aspnet/EntityFramework.Docs#1254]
In competent English, please? Just give me the list stuff I need to do. Not the list of stuff I MIGHT need to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d5d89c-2648-4ce8-d5c3-4fb2371e6128
* Version Independent ID: 20e9f35b-8bb2-2bc0-c032-e4be1915997f
* Content: [Upgrading to Entity Framework 6](https://docs.microsoft.com/en-us/ef/ef6/what-is-new/upgrading-to-ef6)
* Content Source: [entity-framework/ef6/what-is-new/upgrading-to-ef6.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/what-is-new/upgrading-to-ef6.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@LJ9999 We can't know if you're using pre-DbContext APIs or not, hence you might need to do this, but you might not. Not sure why you are having trouble understanding--is there something specific that isn't clear?

**Comment by REscobar** [comment]
@LJ9999 Just so you are clear, this steps are for migration a code base that uses a previous version of EntityFramework (v4,v5) to use EntityFramework6

Is this your scenario?
