### ISSUE TITLE
Private field without a property does not work 

### ISSUE THREAD

**Issue by vihorlat** [aspnet/EntityFramework.Docs#1257]
I have tried to use this sample
[Fields without a property](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field#fields-without-a-property) with an XUnit test, with inmemory SQLite database but it does not work. _validatedUrl is never set with values from database, wheter it is private or public.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e162696-b19f-d73f-8b1f-d1b4c3048b62
* Version Independent ID: a83e4fb5-e4ae-a46f-7248-487ea2679ac5
* Content: [Backing Fields - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field#fields-without-a-property)
* Content Source: [entity-framework/core/modeling/backing-field.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/backing-field.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by shravan2x** [comment]
I have the same issue.

**Comment by jalchr** [comment]
I'm getting this: The specified field '_validatedUrl' cannot be used for the property 'Url' because it does not match the property name.
