### ISSUE TITLE
Why is it important to use a new DbContext for each schema creation/ test run/ verification step?

### ISSUE THREAD

**Issue by gusmally** [aspnet/EntityFramework.Docs#1258]
What does this achieve as opposed to initializing a private context with the necessary schema, and testing and verifying against that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7b56f-7f91-2f15-1fb6-4f481e97534f
* Version Independent ID: 6d9c65c6-f159-b234-48fd-f25da05f0f32
* Content: [Testing with SQLite - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite)
* Content Source: [entity-framework/core/miscellaneous/testing/sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/sqlite.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
@gusmally This is closer to how a context is used in a typical application.
