### ISSUE TITLE
Saving Data

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#126]
Required pages:
- [ ] basics
- [ ] related data
- [ ] cascade delete
- [ ] async
- [ ] explicit values into generated columns
- [ ] handling concurrency conflicts

**Comment by rowanmiller** [comment]
Some of this is covered in https://github.com/aspnet/EntityFramework.Docs/pull/127

**Comment by YehudahA** [comment]
Handling concurrency.

**Comment by tmds** [comment]
After reading the current doc on concurrency I have two questions related to ConcurrencyCheck.

* can the ConcurrencyCheck check be used on the property being updated itself?

e.g. Retrieve -> check current value -> update to new value -> Commit. Commit should fail if no longer current value in db

* is there a way to disable the ConcurrencyCheck during certain operations or is it always enforced?

**Comment by tmds** [comment]
- it isn't documented how to implement a nullable foreign key.

**Comment by rowanmiller** [comment]
> can the ConcurrencyCheck check be used on the property being updated itself?

Yes, it is no different than a property that is not being updated. EF stores the original values for a property when the entity was loaded from the database and always uses the original value for concurrency check.

> is there a way to disable the ConcurrencyCheck during certain operations or is it always enforced?

It is always enforced.

> it isn't documented how to implement a nullable foreign key.

See this section for some info - https://docs.efproject.net/en/latest/modeling/relationships.html#required. But in general, the nullability is controlled by whether the CLR type of the foreign key property is nullable or not.

**Comment by YehudahA** [comment]
Disconnected-entities.
https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities
