### ISSUE TITLE
Oracle provider release dates

### ISSUE THREAD

**Issue by SychevIgor** [aspnet/EntityFramework.Docs#1272]
We need an update in an article, because q3 2018 was 4 months ago. 
If we have any updates from Oracle side about EF Core support/roadmap/release dates?
I see that ado.net provider available for a long time, but EF Core state is interesting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9338b2a-93b1-595a-2e8e-86119e6eecbd
* Version Independent ID: 9890ab79-bc72-6075-4294-5450e6693668
* Content: [Database Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/#oracle)
* Content Source: [entity-framework/core/providers/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ssougnez** [comment]
I did some research, as I also need a provider and it seems that a private beta version of the ODP provider exists but you need to send a mail to Oracle to get access to it... I guess they don't know what pre-releases are... Anyway, no release date so far...

**Comment by SychevIgor** [comment]
@ssougnez at least we need to fix in ef documentation, because "q3 2018" was 4 months ago

**Comment by mahanmawadj** [comment]
Public beta 2 is coming to Nuget soon (was told on Feb 8th that it should be within a week).

**Comment by ssougnez** [comment]
It also possible to ask for access to the private beta by sending a mail to dotnet_us@oracle.com

I did, I got the link the day after. The provider seems to be working as expected for basic use cases.
