### ISSUE TITLE
Addition of  IBM Data Server EF 7.0 Provider (Beta) support for Entity Framework 7

### ISSUE THREAD

**Issue by PrashanthIBM** [aspnet/EntityFramework.Docs#128]
Hi @rowanmiller @ErikEJ  @natemcmaster ,

We have released IBM Data Server EF 7.0 Provider (Beta) support for Entity Framework 7 in nuget.org .
http://www.nuget.org/packages/EntityFramework.IBMDataServer/7.0.0-beta1

Can you please add this provider support to your documentation under "Database Providers" section :
https://ef.readthedocs.org/en/latest/providers/index.html

Thanks and Regards,
Prashanth.

**Comment by ErikEJ** [comment]
@PrashanthIBM Great news! Do you have links to documentation, source repo and/or getting started guides, similar to what is available for the other providers?

**Comment by PrashanthIBM** [comment]
Hi @ErikEJ ,

We have added details about prerequisite,samples, limitations as a part of readme.txt file.

Sharing the details here :

**Prerequisites:
-----------------**
1. Download DB2 Version 10.5 Fix Pack 6 DS Driver Special Build for Windows:
   http://www-933.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=All&platform=All&function=fixId&fixids=special_35031_DSClients-ntx64-dsdriver-10.5.600.232-FP006%3A733394676089653120&includeSupersedes=0

2. Full .Net framework with version 4.5.1 onwards.

**Sample EF7 Application for IBM Data Server:**
https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/sample_ef7_application_for_ibm_data_servers?lang=en

**For latest updates and limitations, please refer to the following link: **
https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/latest_updates_and_limitations_for_ibm_data_server_entityframework_7


Thanks and Regards,
Prashanth

**Comment by rowanmiller** [comment]
@PrashanthIBM great news! I'll get the changes in a pull request later today and cc you for a review of them

**Comment by rowanmiller** [comment]
Change is out for review https://github.com/aspnet/EntityFramework.Docs/pull/130

**Comment by PrashanthIBM** [comment]
The changes have been merged and able to see the addition IBM Data Server under Database Providers list. Hence closing the issue. 

Thank you.

**Comment by quasney** [comment]
Is the going to be support for this on dnxcore50? I'd like to use it in Bluemix.

**Comment by PrashanthIBM** [comment]
It is supported for dnx451 and net451. dnxcore50 support is present in the future plans.
