### ISSUE TITLE
LocalDBConnectionFactory Typo

### ISSUE THREAD

**Issue by kalittles** [aspnet/EntityFramework.Docs#1282]
System.Data.Entity.Infrastructure defines LocalDBConnectionFactory as "LocalDbConnectionFactory".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb983de-7c86-dfeb-6548-dde4a9f17379
* Version Independent ID: 547e9c6a-75e6-da12-f60b-93b767eed3f7
* Content: [Code-based configuration - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/code-based)
* Content Source: [entity-framework/ef6/fundamentals/configuring/code-based.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/configuring/code-based.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Fixed https://github.com/aspnet/EntityFramework.Docs/commit/1f23314da7315334b6469e83a034dd23b7594221
