### ISSUE TITLE
EF6: What unit is being used for DbMigrationsConfiguration.CommandTimeout?

### ISSUE THREAD

**Issue by sp4rc** [aspnet/EntityFramework.Docs#1283]
As the title says, what unit is the property using? Seconds? Minutes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aeb3b9b-c4e7-c548-e1eb-01ca6f9e6178
* Version Independent ID: 9c583239-f9a4-de68-962d-51aa0b7f4ef3
* Content: [DbMigrationsConfiguration.CommandTimeout Property (System.Data.Entity.Migrations)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.dbmigrationsconfiguration.commandtimeout?view=entity-framework-6.2.0#System_Data_Entity_Migrations_DbMigrationsConfiguration_CommandTimeout)
* Content Source: [EF/xml/System.Data.Entity.Migrations/DbMigrationsConfiguration.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Migrations/DbMigrationsConfiguration.xml)
* Product: **entity-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by divega** [comment]
I assume you are asking about CommandTimeout. The time is in seconds. IT actually delegates to a similar property on the underling ADO.NET provider DbCommand, e.g. [SqlCommand.CommandTimeout](https://docs.microsoft.com/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout).

**Comment by sp4rc** [comment]
Thanks. This should be reflected in the documentation.
