### ISSUE TITLE
EF6: issue with pattern used for one-to-zero-or-one relationships

### ISSUE THREAD

**Issue by guardinfo-spam** [aspnet/EntityFramework.Docs#1286]
This feedback related to the advice given in "Configuring a Required-to-Optional Relationship (One-to–Zero-or-One)" section. Having a table where the primary key is that one from another entity is confusing. I think it would be much better if OfficeAssignment table had a primary key called OfficeAssignmentID or simply ID and then a unique index would be placed on the InstructorID in that table. 

The main issue is that production systems and databases are usually quite big and hard to understand when simple and clear conventions are not followed.  If you were to design such a system with a database first approach, would this still be the advice you give? if it's not then I'd suggest to make that clear in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1251b7a8-a4d4-7664-d1f3-5447f47315a8
* Version Independent ID: bf0ecf4c-1dd9-6cfd-32ea-86fcc619164e
* Content: [Fluent API - Relationships - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/relationships)
* Content Source: [entity-framework/ef6/modeling/code-first/fluent/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/fluent/relationships.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
If I understand this correctly, the issue is about providing an example of 1:0..1 relationship using a unique constrain on the FK instead of shared PK. AFAIR, this is possible in EF6. 

Note that the EF Core documentation already includes an example that uses unique FK. That said, I don't know on what basis I would recommend this pattern over the shared PK. Both seem valid and shared PK is slightly more normalized and efficient because it avoids creating an artificial surrogate key for the dependent entity.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
