### ISSUE TITLE
Document SQL Server Compact limitations

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework.Docs#129]
Similar to the sqlite limitations page.
I this proposal is accepted, I will be happy to author the page

**Comment by rowanmiller** [comment]
No objections to having this page... though I do wonder how much you want to keep all the docs together in one place? My thoughts were that we'd just have the summary page for CE and then folks would head to your docs for more detail. Thoughts?

**Comment by ErikEJ** [comment]
Lets just keep the summary page...
