### ISSUE TITLE
I tried to use DbContext. Database. UseTransaction, and found that this method can only be used normally under Sqlserver, throwing an exception after replacing it with Mysql database.

### ISSUE THREAD

**Issue by git102347501** [aspnet/EntityFramework.Docs#1290]
I encountered a problem using multiple contexts of the same connection in EFCore. The error message was:The specified transaction is not associated with the current connection. Only transactions associated with the current connection may be used.
After testing, it is found that this method can be used normally under SqlServer 2017 and throw the above exception after replacing it with MYsql.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions#cross-context-transaction-relational-databases-only)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@git102347501 It is possible that you have hit a product issue in the MySQL provider. Which MySQL provider are you using?

**Comment by qgxcry** [comment]
I just ran into this too. my using MySql.Data.EntityFrameworkCore,When I run, I got error: Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported.

**Comment by git102347501** [comment]
> @ git102347501您可能在MySQL提供程序中遇到了产品问题。您使用的是哪个MySQL提供商？

Hello, I'm sorry I didn't reply to you in time, as you said downstairs，is MySql.Data.EntityFrameworkCore

**Comment by smitpatel** [comment]
@git102347501 - Please file an issue with author of the MySQL provider you are using at this seems to be issue with that package rather than EF Core.
