### ISSUE TITLE
Suggested improvement to the wording of the warning for the EF Core Raw SQL Document

### ISSUE THREAD

**Issue by HockeyJustin** [aspnet/EntityFramework.Docs#1295]
The documentation for [EF Core Raw SQL](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql) is excellent, however the warning at the end is a little [confusing](https://github.com/aspnet/EntityFramework.Docs/issues/1127).

The wording of string concatenation provides confusion over whether string *interpolation* is 'safe'.

I feel it is also important to clarify, due to questions on the internet such as [this question](https://stackoverflow.com/questions/41960481/parameters-vs-string-interpolation) on stackoverflow.

I have proposed an edit.

https://github.com/aspnet/EntityFramework.Docs/compare/master...HockeyJustin:master

Please review and incorporate if you also feel it provides clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@HockeyJustin I looked at your proposed text. I think it would add value to add it (please send a PR), but instead of deleting the current text I would add it afterwards. 

Given that we are not trying to convey at all that string interpolation is safe, I would change the current text to say "if you are using string concatenation or interpolation...".

**Comment by HockeyJustin** [comment]
@divega . Thank you for considering the update.

I have created a [pull request](https://github.com/aspnet/EntityFramework.Docs/pull/1318) and tried to update the wording in line with your suggestion, though it's tricky to get perfect.

I am keen to convey two things:
1. Even though history has told us not to use string interpolation anywhere near SQL, it is now definitely safe to use in the `FromSql` and `ExecuteSqlCommand`.

2. Even the `params` method of `FromSql` will not provide complete protection against SQL Injection attacks. If you are calling a stored procedure that uses non-parameterised dynamic sql (i.e. string concatenation within the stored procedure), that stored procedure will _still_ be susceptible to attack.
