### ISSUE TITLE
A commit failure scenario isn't mentioned

### ISSUE THREAD

**Issue by timmi4sa** [aspnet/EntityFramework.Docs#1296]
A one important scenario that may lead to the confusing error below (that references this page) has been missed. In our case the error has been reported due to us subscribing to a transaction that is coordinated by DTC (Distributed Transaction Coordinator) a "benign" code such as "new TransactionScope(..)". It worked for years, but (perhaps) due to some odd DTC failure our coded started to fail and reported this error. We ended up rewriting the code to remove TransactionScope in favor of the built-in SQL transaction provided by the SaveChanges method of the DbContext. 

 "An error was reported while committing a database transaction but it could not be determined whether the transaction succeeded or failed on the database server. See the inner exception and http://go.microsoft.com/fwlink/?LinkId=313468 for more information"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af0b8bf0-8cdb-e5ae-0344-e2e281f41969
* Version Independent ID: 90d5f106-4bee-1075-3e43-054556a301df
* Content: [Handling transaction commit failures - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/commit-failures)
* Content Source: [entity-framework/ef6/fundamentals/connection-resiliency/commit-failures.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/connection-resiliency/commit-failures.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by roji** [comment]
Here's a wayback machine link for the article: https://web.archive.org/web/20190123153156/https://blogs.msdn.microsoft.com/adonet/2013/03/11/sql-database-connectivity-and-the-idempotency-issue/

But not sure if the ADO.NET blog is supposed to come back under a new address...

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
