### ISSUE TITLE
Is it possible to permanently specify --startup-project?

### ISSUE THREAD

**Issue by jaworek** [aspnet/EntityFramework.Docs#1299]
I would like to specify --startup-project for the solution so there is no need to pass it every time I want to run migrations.

Is it possible to specify it on the project basis (or any way at all)?

If it is not possible, is there an option in .Net CLI similar to package.json "scripts"?
https://medium.freecodecamp.org/introduction-to-npm-scripts-1dbb2ae01633

**Comment by bricelam** [comment]
The closest thing we have is the ability to use response files.

Create a file named `defaults.rsp` with the default arguments:

    --startup-project
    ..\StartupProject

Then invoke `dotnet ef` using that file:

    dotnet ef @defaults.rsp database update

The other alternative is just to create a batch file called `ef.cmd`:

``` cmd
@dotnet ef --startup-project ..\StartupProject %*
```

..and just use it instead:

    ef database update

**Comment by jaworek** [comment]
Thank you for your answer!

Are there any plans to improve this experience? I know that Package Manager Console in Visual Studio supports it much better, but I am working on a Mac and had a lot of issues to make it work for me.
