### ISSUE TITLE
Consecutive Numbers

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/EntityFramework.Docs#1316]
In the post there should be a remark that Sequences are not consecutive (1,2,3) vs (1,2,3,7,8,10). In the example it's not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cada79d3-c141-0a42-2fc1-522d7aa408a5
* Version Independent ID: d1afcfe2-99d4-d7bf-f632-17be38cef2e3
* Content: [Sequences - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/sequences)
* Content Source: [entity-framework/core/modeling/relational/sequences.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/sequences.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@vertonghenb Can you explain in more detail what you mean by "Sequences are not consecutive?"

**Comment by vertonghenb** [comment]
Meaning that the sequences are not strictly sequential, there can be "holes" in the numbering.
for example,
1,3,6 is a valid sequence, but it's not strictly consecutive(1,2,3,4,5,6), so they're not a good idea to use in countries where the order or invoice numbers have to be strictly consequtive.

**Comment by ajcvickers** [comment]
@vertonghenb If you're seeing this using the code from this page, then that's likely a bug. Please file a new issue at https://github.com/aspnet/EntityFrameworkCore/issues and include a small, runnable project/solution or complete code listing that demonstrates this behavior.
