### ISSUE TITLE
Clarify sync/async equivalency

### ISSUE THREAD

**Issue by gaazkam** [aspnet/EntityFramework.Docs#1332]
From this piece of documentation:

&gt; Depending on the database provider being used, values may be generated client side by EF or in the database. If the value is generated by the database, then EF may assign a temporary value when you add the entity to the context. This temporary value will then be replaced by the database generated value during `SaveChanges()`.

I ASSUME `SaveChangesAsync`, once it completes, has the same effect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties#feedback)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Note for triage: We (or at least I) tend to assume that when I say `SaveChanges` or `ToList` that people will understand that I also mean the equivalent async methods. Maybe this isn't the case?

**Comment by divega** [comment]
Triage: Add a note on a new general "using EF Core async APIs"  page.
