### ISSUE TITLE
EntityFramework CodeFirst

### ISSUE THREAD

**Issue by Gluups** [aspnet/EntityFramework.Docs#1336]
Hello,

Could anybody provide an example of using Scaffold-DbContext to create a DbContext to a new database created by EntityFramework CodeFirst in a DotNetCore environment ?
It would be fine if it was in a WebAPI project ...

**Comment by ajcvickers** [comment]
@Gluups If the database is being created by Code First, then can you provide some details as to how it is useful to show the same database being reverse engineered back to a `DbContext`?

**Comment by smitpatel** [comment]
Closing due to lack of response.
