### ISSUE TITLE
EF6 Fluent API: unidirectional one-to-zero-or-one

### ISSUE THREAD

**Issue by GoFightNguyen** [aspnet/EntityFramework.Docs#1343]
# Scenario

Given these entities
```
public class EntityAAA
    {
        public int Id { get; set; }
        public EntityBBB EntityBBB { get; set; }
    }

public class EntityBBB
    {
        public int EntityAAAId { get; set; }
        public DateTime Created { get; set; }
    }
```

Configured as
```
modelBuilder.Entity<EntityAAA>().HasKey(e => e.Id);
modelBuilder.Entity<EntityAAA>().Property(e => e.Id).HasColumnName("EntityAAAID");

modelBuilder.Entity<EntityBBB>().HasKey(e => e.EntityAAAId);
```

# Action
When executing, the generated SQL is
```
SELECT 
    [Extent1].[EntityAAAId] AS [EntityAAAId], 
    [Extent2].[EntityAAAId] AS [EntityAAAId1], 
    [Extent2].[Created] AS [Created]
    FROM  [EntityAAA] AS [Extent1]
    LEFT OUTER JOIN [EntityBBB] AS [Extent2] ON [Extent1].[EntityBBB_EntityAAAId] = [Extent2].[EntityAAAId]
```

# Result
This produces an error `Invalid column name 'EntityBBB_EntityAAAId'`  
Notice the join is using `Extent1.EntityBBB_EntityAAAId`

# Expectation
I expected the join to be `[Extent1].[EntityAAAId] = [Extent2].[EntityAAAId]`  

In EF6, using the fluent API, how do I configure a unidirectional one-to-zero-or-one relationship in which EntityAAA is the principal and EntityBBB is the dependent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1251b7a8-a4d4-7664-d1f3-5447f47315a8
* Version Independent ID: bf0ecf4c-1dd9-6cfd-32ea-86fcc619164e
* Content: [Fluent API - Relationships - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/relationships)
* Content Source: [entity-framework/ef6/modeling/code-first/fluent/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/fluent/relationships.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by GoFightNguyen** [comment]
I apologize if this issue was too detailed for EntityFramework.Docs.  

I also think I stumbled upon the answer. It seems to be functioning, at least for querying, after I added this to the configuration.
```
modelBuilder.Entity<Opportunity>()
                .HasOptional(o => o.SalesProfile)
                .WithRequired();
```

Let me know if you know of any other ways, or you see an issue with this approach.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
