### ISSUE TITLE
Document FK convention changes

### ISSUE THREAD

**Issue by sfinotto** [aspnet/EntityFramework.Docs#1346]
Hi. 
Regarding "The foreign key property convention no longer matches same name as the principal property" &gt;"Starting with 3.0, EF Core won't try to use properties for foreign keys by convention if they have the same name as the principal property. Principal type name concatenated with principal property name, and navigation name concatenated with principal property name patterns are still matched."

When I read the Relationships docs https://docs.microsoft.com/en-us/ef/core/modeling/relationships , as I understand it describes the 2.2 behaviour, right?
I wonder how the section "Relationships" &gt; "Conventions" &gt; "Fully Defined Relationships" would change it's wording for version 3.0.
Now it says "If the dependent entity contains a property named &lt;primary key property name&gt;, &lt;navigation property name&gt;&lt;primary key property name&gt;, or &lt;principal entity name&gt;&lt;primary key property name&gt; then it will be configured as the foreign key."
For version 3.0, would that paragraph be the same minus "&lt;primary key property name&gt;,"?
I'm trying to understand well the breaking change and I'm not totally sure I got it right.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#the-foreign-key-property-convention-no-longer-matches-same-name-as-the-principal-property)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
@sfinotto Correct, we'll update that page once 3.0 ships.

**Comment by IanYates** [comment]
Suspected copy/paste issue.  The body of the heading irelationaldatabasecreatorhastableshastablesasync-have-been-made-public seems to relate to the topic above it (about foreign key constraint names)
