### ISSUE TITLE
You should add a reference to EntityFramework Reverse POCO Generator

### ISSUE THREAD

**Issue by mattslay** [aspnet/EntityFramework.Docs#1347]
You should add a reference to a very popular Visual Studio extension called **EntityFramework Reverse POCO Generator** which is available at the Visual Studio Marketplace.

https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875eb79-99ff-662b-c189-86eb8cdb5488
* Version Independent ID: fa03a7fa-1922-7aa1-acda-b0d216ef37cb
* Content: [Tools & Extensions - EF Core](https://docs.microsoft.com/en-us/ef/core/extensions/)
* Content Source: [entity-framework/core/extensions/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md)
* Product: **entity-framework**
* GitHub Login: @ErikEJ
* Microsoft Alias: **divega**

**Comment by mattslay** [comment]
I see I placed this comment in EF Core, and I used this with EF . I see from the Q & A for this tool that the author has said "I've not yet tested with .net standard, but I will make sure I test for this when the .net core code is completed."  So, I bet he will have it ready for EF Core ASAP after release.

**Comment by ErikEJ** [comment]
So currently it does not support EF Core...

**Comment by divega** [comment]
We can add this when the extension supports EF Core.
