### ISSUE TITLE
Document Date issue.

### ISSUE THREAD

**Issue by ZhanglongWu** [aspnet/EntityFramework.Docs#1356]
As far as I know, .entity framework core 2.2 is released in Dec 2018, but this document updated date is 10/27/2016. is it outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0036f8c5-d838-69a5-cc09-dc74df09bc07
* Version Independent ID: 5335749f-e32f-979f-7139-f5f14373e283
* Content: [Compare Entity Framework 6 and Entity Framework Core](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/#feedback)
* Content Source: [entity-framework/efcore-and-ef6/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@ZhanglongWu The major feature in 2.2 was spatial, which is included here, so I think it is up-to-date.
