### ISSUE TITLE
What is the difference between Owned Entity Types (OET) and Inheritance (TPT) ?

### ISSUE THREAD

**Issue by Yuant-tobing** [aspnet/EntityFramework.Docs#1364]
What is the difference between Owned Entity Types (OET) and Inheritance table-per-type (TPT) features on EF Core 3?
Please explain in more detail, for use options it is better to apply "**Polymorphic relationship**".

This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by AndriySvyryd** [comment]
OET represent entity types that are part of an aggregate, they can be mapped to the same table as the owner or to a different one.
TPT is a mapping pattern that's not yet supported in EF Core, it uses a separate table in the database to maintain data for non-inherited properties and key properties for each type in the inheritance hierarchy.
