### ISSUE TITLE
Clarify how this configuration play along when using MigrateDatabaseToLatestVersion

### ISSUE THREAD

**Issue by Luis-Palacios** [aspnet/EntityFramework.Docs#1365]
Hello everyone!,

Thank you for this docs, they are very helpful however I have ran into an issue

This works just fine when using as the docs suggest "the Package Manager Console, Enable-Migrations, Add-Migration and finally Update-Database" but what happens when you are using some sort of initialization such as MigrateDatabaseToLatestVersion? I have run into an issue where my app crash because the MigrateDatabaseToLatestVersion seem to not be aware of the new name of the migration history table hence it is trying to run the migrations again and saying "SomeDatabaseObject already exist on the database" I suppose is because the  Initializer is declared like this: `MigrateDatabaseToLatestVersion<SomeDbContext, SomeDbMigrationsConfiguration>` and DbMigrationConfiguration is not the same as a DBConfiguration which hold my custom migration history table name. I don't know how to make the Initializer be aware of my DbConfiguration on my context since it appears to be ignoring the Decorator.

Some Code: 

```C#
// The DBContext
 [DbConfigurationType(typeof(FooDbConfiguration))]
    public class FooDbContext : DbContext
    {
        public FooDbContext () : base("FooDbContext")
        {
            // Notice here FooDbConfiguration is not the same as FooDbMigrationsConfiguration
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<FooDbContext , FooDbMigrationsConfiguration>());
            Configuration.LazyLoadingEnabled = false;
        }
....

// The FooDbConfiguration
public class FooDbConfiguration : DbConfiguration
    {
        public FooDbConfiguration()
        {
            this.SetHistoryContext("System.Data.SqlClient",
                (connection, defaultSchema) => new FooMigrationHistoryContext(connection, defaultSchema));
        }
    }
...
// The FooMigrationHistoryContext
 public class FooMigrationHistoryContext : HistoryContext
    {
        public FooMigrationHistoryContext(DbConnection dbConnection, string defaultSchema)
                : base(dbConnection, defaultSchema)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<HistoryRow>().ToTable(tableName: "__FOO_MigrationHistory", schemaName: "dbo");
        }
    }
...
// The FooDbMigrationsConfiguration
internal sealed class Configuration : DbMigrationsConfiguration<FooDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
           // The FooSqlServerMigrationSqlGenerator just set some default values for some date fields
          // If you think this code may be relevant let me know to add it
            SetSqlGenerator("System.Data.SqlClient", new FooSqlServerMigrationSqlGenerator());
            CommandTimeout = 180;  // 3 minute timeout
        }
//
```
I can make the problem go away if I directly modify the  FooDbMigrationsConfiguration to tell it explicitly about my FooMigrationHistoryContext however, I don't like this approach because It violates DRY as I'm Setting the HistoryContextFactory twice

```C#
// The FooDBMigrationsConfiguraiton with the fix
    internal sealed class Configuration : DbMigrationsConfiguration<FooDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            SetSqlGenerator("System.Data.SqlClient", new CustomSqlServerMigrationSqlGenerator());
            CommandTimeout = 180;  // 3 minute timeout
            // This is the fix, however is repeated code with my FooDbConfiguration
            SetHistoryContextFactory("System.Data.SqlClient",
                (connection, defaultSchema) => new FooMigrationHistoryContext(connection, defaultSchema));
            
        }
```

My question is, is there a better way to make both my DbConfiguration and DbMigrationsConfiguration use my custom Migration History table name?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86069e83-0f9e-6714-c287-73d8a2e26615
* Version Independent ID: 5c976d32-f7a1-e8ed-c442-037d452a243b
* Content: [Customizing the migrations history table - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/history-customization#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/history-customization.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/history-customization.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
