### ISSUE TITLE
nuget package project site contibute link is out of date

### ISSUE THREAD

**Issue by CZEMacLeod** [aspnet/EntityFramework.Docs#1368]
When going to the project url for the existing nuget package it takes you to a Microsoft redirect page then to https://msdn.microsoft.com/en-us/library/aa937723(v=vs.113).aspx
This page has a contribute link and blub that mentions and takes you to the old codeplex website.
Now that the project is maintained on GitHub, this should be updated...
Interestingly the page updated date is listed as October 23, 2016 and the codeplex project moved text was added on Jul 26, 2016 at 10:47 PM by RoMiller

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
