### ISSUE TITLE
Wiki - Building the Runtime - Missing details

### ISSUE THREAD

**Issue by brandondahler** [aspnet/EntityFramework.Docs#1369]
On step 4, it states that you need to install the SQL Server CLR Types and links to the SQL Server 2012 SP1 Feature Pack download page where you can get the installers for Microsoft.SqlServer.Types version 11.0.0.0; however, it fails to also include a link to the installers for Microsoft.SqlServer.Types version 10.0.0.0 .

The file \test\EntityFramework\UnitTests\SqlServer\SqlTypesAssemblyLoaderTests.cs line 11 defines a constant assembly string referencing the 10.0.0.0 version, and that constant is then used by GetSqlTypesAssembly_returns_specified_assembly to verify that 10.0.0.0 is the exact version loaded by that particular test.

I believe that we need to add a link to the install packages for Microsoft.SqlServer.Types version 10.0.0.0 (aka Microsoft SQL Server 2008 Service Pack 4 Feature Pack) to step 4 as well.  I was able to find the download at https://www.microsoft.com/en-us/download/details.aspx?id=44277 .

Brandon Dahler

(I did check this time that the links are, in fact, different downloads :) )

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
