### ISSUE TITLE
transaction.Rollback() is not working.

### ISSUE THREAD

**Issue by divakarganta** [aspnet/EntityFramework.Docs#1375]
Hi,

I am working EF core code, I tried as below, any exception occur in _saveDocumentToDb or SaveFile catch block is executing but Rollback not happen. 

```C#
try
                {
                    await _saveDocumentToDb(entityId, file, docRequest, guid, transaction);
                    await EntityDocumentsStorageHelper.SaveFile(file, guid);
                    
                    transaction.Commit();
                }
                catch (Exception e)  
                {
                    // TODO: BUG: This rollback does not rollback the database operation.
                    transaction.Rollback();
                    throw;
                }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions#feedback)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@divakarganta This GitHun repo is for documentation issues. To report a bug, please file an issue at https://github.com/aspnet/EntityFrameworkCore/issues and include a small, runnable project/solution or complete code listing that demonstrates the bug you are seeing.
