### ISSUE TITLE
Add VB sample to EF Core Overview

### ISSUE THREAD

**Issue by mairaw** [aspnet/EntityFramework.Docs#1382]
This topic is C# only right now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by mairaw** [comment]
Also @divega, should I update the author metadata from Rowan to you?

**Comment by divega** [comment]
@mairaw I don't know. I guess it depends on whether it is used for something different from what the word suggests. He was the author of many of the pages so I have left it as is.

**Comment by zspitz** [comment]
@mairaw What's the policy here? Is there going to be a separate set of documentation with samples for VB? Or are the VB samples supposed to be integrated into these docs somehow?

**Comment by Rick-Anderson** [comment]
@mairaw  why the issue to provide a VB sample? Who's going to maintain it? We don't provide VB samples in the ASP.NET Core repo. cc @tdykstra

**Comment by ajcvickers** [comment]
Closing; we have no plans to create VB examples.
