### ISSUE TITLE
Add remark that this method is called when doing manual migrations via EF tools.

### ISSUE THREAD

**Issue by gregfra** [aspnet/EntityFramework.Docs#1396]
Running EF tools in the PMC confirms that the Seed override in your project is called to seed a database update with data.

&gt;update-database -ConnectionStringName MyProjectAppConfigContext -Verbose
Using StartUp project 'MyProject'.
Using NuGet project 'MyProject'.
Target database is: 'MyProjectDB' (DataSource: .\SQLEXPRESS, Provider: System.Data.SqlClient, Origin: Explicit).
[.... CREATE TABLE ... INSERT TABLE ....]
Running Seed method.
&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e34ed4-b05b-7b0b-aee7-d74a468c5156
* Version Independent ID: 29419a44-128a-5876-f660-885e5605d416
* Content: [DbMigrationsConfiguration&lt;TContext&gt;.Seed(TContext) Method (System.Data.Entity.Migrations)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.dbmigrationsconfiguration-1.seed?view=entity-framework-6.2.0#System_Data_Entity_Migrations_DbMigrationsConfiguration_1_Seed__0_)
* Content Source: [EF/xml/System.Data.Entity.Migrations/DbMigrationsConfiguration`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Migrations/DbMigrationsConfiguration`1.xml)
* Product: **entity-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
