### ISSUE TITLE
Changes in the MaxLength annotation of a string property are not migrated

### ISSUE THREAD

**Issue by nikolaschou** [aspnet/EntityFramework.Docs#140]
I tried the following: 

Add this property to a model class: 

```
        [MaxLength(50)]
        public string SerialNumber { get; set; }
```

Run the following commands: 

```
dnx ef migrations add v3
dnx ef database update
```

At this point the table in the database will correctly contain a column named SerialNumber with type nvarchar(50).

I now change the property to 

```
        [MaxLength(60)]
        public string SerialNumber { get; set; }
```

Repeat these commands:
Run the following commands: 

```
dnx ef migrations add v4
dnx ef database update
```

At this point the SerialNumber column in the database is still nvarchar(50) and not nvarchar(60) as expected. 

When I look through the generated migration files I observe this:
20160223200300_v3.cs: Does not contain an AlterColumn statement as I would have expected. 
20160223200300_v3.Designer.cs: Contains this line of code:

```
                    b.Property<string>("SerialNumber")
                        .HasAnnotation("MaxLength", 56);
```

ApplicationDbContextModelSnapshot.cs: Contains this line of code:

```
                    b.Property<string>("SerialNumber")
                        .HasAnnotation("MaxLength", 56);
```

**Comment by rowanmiller** [comment]
This should be resolved in 1.1. Please open a new issue in the product repository (this one is for docs) if you are still seeing this https://github.com/aspnet/EntityFramework/issues/new.
