### ISSUE TITLE
how to add post

### ISSUE THREAD

**Issue by newpost** [aspnet/EntityFramework.Docs#1409]
https://github.com/aspnet/EntityFramework.Docs/blob/03751561fa706edd0e2c09d5b7d34adfbe094a7f/samples/core/GetStarted/NetCore/ConsoleApp.SQLite/Program.cs#L12

in the following code , posts of blog is null
```
db.Blogs.Add(new Blog
                {
                    Url = "http://blogs.msdn.com/adonet"
                });
               
                Post post = new Post()
                {
                    Title = "post title",
                    Content = "post content",
                    BlogId = db.Blogs.Count() + 1
                };
                db.Posts.Add(post);

                var count = db.SaveChanges();
```

**Comment by roji** [comment]
@newpost this repo is for only for documentation issues, whereas you seem to need guidance with using EF Core. Can you please open an issue on [the main EF Core repo](http://github.com/aspnet/EntityFrameworkCore/), or open a question on stackoverflow with the entity-framework-core label? 

Please also include a full code sample, as it isn't possible to know exactly what's going on from the fragment above. You may have omitted loading the new post in a later query - related entities aren't automatically loaded ([see this page](https://docs.microsoft.com/en-us/ef/core/querying/related-data)).
