### ISSUE TITLE
Ef Core should never automatically delete related entities

### ISSUE THREAD

**Issue by prince272** [aspnet/EntityFramework.Docs#1410]
Ef Core should never automatically delete related entities even if the foreign key is not nullable.  A user may delete a related entity without knowing that's why deleting related entities should be done manually.

Adding this feature to the breaking changes would be great so that related entities are not automatically deleted.

        public static void SetRelatedEntityTypesToRestrict(this ModelBuilder modelBuilder)
        {
            foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
            {
                relationship.DeleteBehavior = DeleteBehavior.Restrict;
            }
        }

**Comment by ajcvickers** [comment]
@prince272 Can you give some details on what you mean by "Adding this feature to the breaking changes"?

**Comment by prince272** [comment]
I mean if you can add it to the upcoming release of Ef Core 3.0 Preview 4.

**Comment by roji** [comment]
@prince272 it seems that you are asking for EF Core itself to be changed - and not just the docs - so that it doesn't automatically deleted entities? If so, that belongs as an issue on [the main EF Core repo](http://github.com/aspnet/EntityFrameworkCore/), could you close this and reopen there for discussion?

**Comment by prince272** [comment]
Yes

**Comment by roji** [comment]
Closing this as a product request, not a doc request - please reopen in the main repo.

Beyond that, cascading deletes are a pretty standard database feature used by many users, so I'm skeptical it would be a good idea to remove them.
