### ISSUE TITLE
Publish api documentation for 2.2 and 3.0

### ISSUE THREAD

**Issue by Blanen** [aspnet/EntityFramework.Docs#1411]
2.2 is published but there's no api documentation here yet: 

https://docs.microsoft.com/en-us/dotnet/api/

![image](https://user-images.githubusercontent.com/7236824/55734886-a712ef00-5a20-11e9-9a85-0a6fa70a04d3.png)
Currently only for 1.0, 1.1, 2.0 and 2.1.

**Comment by ajcvickers** [comment]
@divega moved this to docs.

**Comment by smitpatel** [comment]
Marking as duplicate of https://github.com/aspnet/EntityFramework.ApiDocs/issues/41
Will cover it for 3.0 release too.

**Comment by smitpatel** [comment]
Resolves by https://github.com/aspnet/EntityFramework.ApiDocs/pull/63
