### ISSUE TITLE
Document 3.0 query tracking behavior

### ISSUE THREAD

**Issue by jwatkin** [aspnet/EntityFramework.Docs#1412]
You might want to consider adding an exception to the documentation, which currently states the default behavior is that entities returned from queries are tracked. If a DbSet-derived entity is returned from a query that uses a Join or GroupJoin with any DbQuery types, then the returned DbSet-derived entities aren't tracked. See this GitHub issue:
https://github.com/aspnet/EntityFrameworkCore/issues/14680#issuecomment-480936091

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ffc114-df51-0be7-8972-6fcead14e011
* Version Independent ID: 94c34571-7314-aab1-7898-93ac6d0f3430
* Content: [Tracking vs. No-Tracking Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/tracking)
* Content Source: [entity-framework/core/querying/tracking.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/tracking.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
This is no longer correct in 3.0.

**Comment by smitpatel** [comment]
Fixed in #1837
