### ISSUE TITLE
EF6 what's new section is out of date

### ISSUE THREAD

**Issue by fLLHMD4A** [aspnet/EntityFramework.Docs#1414]
This page could use updating to reference versions released since it was written.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4197360f-ffba-2764-52d9-b74b21c2150b
* Version Independent ID: dd2b3627-6d8b-b7b8-e711-0c35a519ae78
* Content: [Past Releases of Entity Framework - EF6](https://docs.microsoft.com/en-us/ef/ef6/what-is-new/past-releases#feedback)
* Content Source: [entity-framework/ef6/what-is-new/past-releases.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/what-is-new/past-releases.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by roji** [comment]
@fLLHMD4A can you be more specific about which versions need to be updated? This page surveys all past releases of Entity Framework 6 and discusses those versions only.

**Comment by fLLHMD4A** [comment]
EF 6.2 specifically, there is nothing that explains the differences between EF 6.1.3 and 6.2

* The page looks backwards from 6.1.3
* The page links to the Roadmap which looks forwards from 6.2
* There is no details (or reference to some other resource with details) that bridges the gap between 6.1.3 and 6.2

**Comment by divega** [comment]
@fLLHMD4A are you looking for the information in https://docs.microsoft.com/ef/ef6/what-is-new/?

**Comment by roji** [comment]
@divega we could consider unifying these two pages into a single "Release history" page, or otherwise add a link from the "Past releases" to the "what's new page".

**Comment by fLLHMD4A** [comment]
@divega aha, yes indeed I am. A user-interface navigation error on my part. It also doesn't help that the search I ran sent me to the "past releases" page instead of the current release notes. I also overlooked the fact that part of the change history could be recorded at a higher navigational level than other parts, when manually browsing.

Consolidating 3 pages into two, might help reduce the confusion for clumsy users like myself. Or at the very least embedding bi-directional links between all the pages to each other...

**Comment by divega** [comment]
@roji, @fLLHMD4A, let me provide some context: - There is a reason the two are split: too much information about past releases that isn’t relevant if you are just looking for what is new. 

- However maybe search could use some hints to return the right thing. It would help to know, if you remember, what exact terms you searched for. 

- Anyway, I agree that there may be ways to improve navigation back and forth.

- One option in this sense would be changing the EF6 what’s new section to look more like the EF Core what’s new section, with separate entries for each past release (including the most recent), and then redirect the past releases page to the index, where everything would be reachable.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
