### ISSUE TITLE
MVC Controller with views, using Entity Framework not an option.

### ISSUE THREAD

**Issue by j1dopeman** [aspnet/EntityFramework.Docs#1424]
Add: MVC Controller with views, using Entity Framework

That option is not there. I'm using VS2019.

I have MVC Empty, MVC with R/W, API Empty, API with R/W, and API with actions using EF. There is no MVC with EF.

**Comment by j1dopeman** [comment]
Having a Pages folder present for some reason triggers this. [https://developercommunity.visualstudio.com/content/problem/431328/scaffolding-error-there-are-no-scaffolders-support.html?childToView=558097#comment-558097](https://developercommunity.visualstudio.com/content/problem/431328/scaffolding-error-there-are-no-scaffolders-support.html?childToView=558097#comment-558097)

**Comment by ajcvickers** [comment]
MVC scaffolding is not owned by the EF team. Please report through Visual Studio feedback so that it can be routed to the correct team.
