### ISSUE TITLE
Consider publishing weekly status update

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#1435]
We had a discussion in ASP.NET leads sync around reporting of the current status of EF Core. This would include things like:
* What is currently being worked on
* What was checked in since the last status update
* What our immediate priorities are
* Burn-down for current release

I was thinking about this over the weekend, and realized that this would likely be useful to many, not just internal people. Therefore, this issue is to consider ways of doing this publicly.

/cc @divega

**Comment by divega** [comment]
@ajcvickers curious what you have in mind. Twitter? Announcements repo? Both? Something else?

**Comment by ajcvickers** [comment]
@divega I don't know. I have considered:
* Announcements, but they will be mixed in with everything else, and while we are in the ASP.NET org, it still seems a bit weird for EF to announce in ASP.NET Announcements.
* A new docs page, that we update with the latest status at the top, with everything below turning into history. Or with some form of archiving.

I think we can Tweet and Facebook it anyway, but I don't think the content should be there.

Do you have any ideas?

**Comment by ErikEJ** [comment]
A Github issue, locked for comments - makes it easy to follow (adding comments for each update) ??
