### ISSUE TITLE
Please share more information about internal EF Core reverse engineering services.

### ISSUE THREAD

**Issue by HamedFathi** [aspnet/EntityFramework.Docs#1438]
One of the greatest features you can find in EF Core is `Scaffolding`.
We can use this via the following command as a sample:
```
dotnet ef dbcontext scaffold "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Chinook" Microsoft.EntityFrameworkCore.SqlServer
```

Iد some scenarios like CI/CD integration We need to work with reverse engineering APIs directly instead of passing arguments to the command line system. (Less trouble/better performance)

You can find an article show us the way [here](https://romiller.com/2017/02/13/ef-core-1-1-run-reverse-engineer-from-code/).

> **Warning: Internal Services In Use**
> In EF Core everything is public, including all the inner workings of EF that would historically have been internal. We did this so that folks that really want to mess around with internal services can do so without using reflection.
> We put these services into *.internal namespaces and reserve the right to break the APIs at any point. This code listing uses a number of these services – so be aware that future versions of EF may break this code.

As outlined in the article, this information is outdated for future releases.

I hope your documentation will be up-to-date on this information as well.

How can we use reverse engineering APIs instead of the command line way with the latest version of EF Core? 

It can be an interesting subject for your documentation to be more complete.

**Comment by ErikEJ** [comment]
I have some sample 2.x code here! https://github.com/ErikEJ/EFCorePowerTools/blob/21e4e5be1de5cae06187aebb4e701eeddcdb9443/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L36

**Comment by smitpatel** [comment]
> How can we use reverse engineering APIs instead of the command line way with the latest version of EF Core?

Scaffolding at runtime is not a good idea from customer perspective. If you are writing a tool which uses EF Scaffolding then please file a product issue if you are running into issues or need to use internal API. There is nothing actionable to document here as the warning says, use .Internal APIs at your own risk.
