### ISSUE TITLE
Define difference between IXyzDatabase and IXyzStore better

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework.Docs#144]
Our docs basically say "read the code" to produce a new provider. But the code doesn't really well distinguish between what goes in an `IXyzDatabase` (really necessary and part of the expected architecture) and `IXyzStore` (may or may not be necessary - depends on what you're doing). Would be good to provide this.

**Comment by rowanmiller** [comment]
Superseded as we now use Arthur's blog post series as the provider guidance
