### ISSUE TITLE
"sing System.Transactions;"

### ISSUE THREAD

**Issue by shadow7412** [aspnet/EntityFramework.Docs#1446]
Minor typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e17e30-4349-3193-01f1-5eb33cb88546
* Version Independent ID: dcb6d719-ffc2-2796-c82c-b9873b74cb76
* Content: [Working with Transactions - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/transactions)
* Content Source: [entity-framework/ef6/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by roji** [comment]
Thanks @shadow7412, I've corrected the typo!
