### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ulflunde** [aspnet/EntityFramework.Docs#1447]
"ModelBuidler" in the above text should be "ModelBuilder". :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829ab2eb-ae81-a74e-fcd4-187fd29e0142
* Version Independent ID: 6575d23f-b467-7f58-1e8e-9c3ba142a3fb
* Content: [DbContext.OnModelCreating(DbModelBuilder) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.onmodelcreating?view=entity-framework-6.2.0#feedback)
* Content Source: [EF/xml/System.Data.Entity/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbContext.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by roji** [comment]
Thanks @ulflunde, opened https://github.com/aspnet/EntityFramework.ApiDocs/pull/51.

**Comment by roji** [comment]
Pushed 539116acfd5b0d0455ab409117a5c21a69c4bf39 to the EF6 repo as well.
