### ISSUE TITLE
Prerequisites can include EF core Preview 3.0 

### ISSUE THREAD

**Issue by noman9607** [aspnet/EntityFramework.Docs#1450]
Works fine with EF core Preview 3.0 (4).  For this line, dotnet new console -o ConsoleApp.SQLite, there is no mention of the -o flag if you type this at cmd: dotnet /? . I am not clear what this means. Thanks for this tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite#feedback)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by noman9607** [comment]
I left this message too soon, before I finished. Does not work with EF 3.0 because the last version of the tool dotnet -ef  is version 2.24. Mea culpa.

**Comment by divega** [comment]
@noman9607 In case it helps, if you are using the .NET Core 3.0 SDK, you should be able to install dotnet-ef 3.0 preview as a global or local tool. Currently you need to specify the version explicitly to install a preview tool. The instructions are at https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes#the-ef-core-command-line-tool-dotnet-ef-is-no-longer-part-of-the-net-core-sdk.
