### ISSUE TITLE
Ignoring properties in an owned type using fluent API

### ISSUE THREAD

**Issue by coder925** [aspnet/EntityFramework.Docs#1457]
How should one ignore properties in an owned type using fluent call? I have figured out how to do this with attributes by adding `[NotMapped]` to the property, but not how the same is done using Fluent API.

In EF 6 I was able to ignore properties on a complex type like this:
`modelBuilder.ComplexType<StreetAddress>().Ignore(a => a.City);`

In EF Core 2.2, it is possible to define the type but not continue with Ignore:
`modelBuilder.Owned<StreetAddress>();`

The by-design restrictions tell me I cannot do this:
`modelBuilder.Entity<StreetAddress>().Ignore(a => a.City);`

I think it would be helpful with a section in the [documentation of Owned Entity Types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities) about ignoring properties in an owned type using both attributes and fluent API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
Currently it's only possible to do for a specific reference.

```C#
modelBuilder.Entity<Order>().OwnsOne(
    o => o.ShippingAddress,
    sa =>
    {
        sa.Ignore(p => p.City);
    });
```
