### ISSUE TITLE
Documentation not up-to-date

### ISSUE THREAD

**Issue by JohanHeyvaert** [aspnet/EntityFramework.Docs#1459]
This documentation seems outdated. Migrate.exe v6.2 does allow to generate the SQL script.
It offers (among others) the following extra parameters:
- scriptFile: output file of the SQL script  (equivalent of the -script option when using the powershell script update-database)
- sourceMigration: migration to update the DB from (if omitted, current model is used)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 105c0f35-0426-b31e-c804-c45bbb0a6f48
* Version Independent ID: 0d3bdfd4-be64-3251-703e-7173d3b3c6eb
* Content: [Using migrate.exe - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/migrate-exe#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/migrate-exe.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/migrate-exe.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
