### ISSUE TITLE
Separation of Services for Providers

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework.Docs#146]
There are some 93 services that are setup for e.g. the `SqlServer` (see `SqlServerServiceCollectionExtensions`). The docs for setting up a new provider say "read the code". But reading through the documentation for 93 services can be hard. In a lot of the `AddEntityFrameworkXyz` methods in such classes there is already an `AddQuery()` method - which simply partitions out those services which are necessary for creating the part of the provider which responds to queries.

It would be good if we can provide, either through docs or better comments or even through partitioning the code, a better way for "grouping" the services. It's good for a provider-writer to be able to "bite off a chunk" of the work - say getting Query to work - and to know which services the provider needs to provide to do this - without getting involved in all the other services and without being confused as to which services are needed/not needed to get that chunk to work.

Not sure whether this is a doc issue or a coding issue but it does feel like we could provide better/more clear partitioning and/or guidance.

**Comment by natemcmaster** [comment]
Related to #61

**Comment by rowanmiller** [comment]
No longer needed as we have overhauled the provider writing section
