### ISSUE TITLE
Revert migration powershell cmdlet syntax incorrect

### ISSUE THREAD

**Issue by sdeluca** [aspnet/EntityFramework.Docs#1462]
In order to revert back to a previous migration, I had to use the syntax "update-database -TargetMigration". The snippet above omits the -TargetMigration flag. Using EF version 6 and Visual Studio 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
😁 Correct; the EF6 and EF Core commands are different. The EF6 doc is here: https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/#migrate-to-a-specific-version-including-downgrade

**Comment by sdeluca** [comment]
Ugh. Tough times to be a developer... so many flavors of frameworks...!

-Sid
