### ISSUE TITLE
Document that the ThenInclude VS Intellisense bug has been fixed in VS2019

### ISSUE THREAD

**Issue by stuarthallows** [aspnet/EntityFramework.Docs#1466]
VS bug referenced in this article has been closed: https://github.com/dotnet/roslyn/issues/8237
I've not tested this in the current release of VS though. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by roji** [comment]
Confirmed that the issue is resolved, will remove the doc warning.
