### ISSUE TITLE
EnlistTransaction is missing

### ISSUE THREAD

**Issue by Laurianti** [aspnet/EntityFramework.Docs#1468]
https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Saving/Saving/Saving.csproj
"Saving" project references "Microsoft.EntityFrameworkCore 2.0.0.0".

https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Saving/Saving/Transactions/CommitableTransaction/Sample.cs
"Sample.cs" uses "EnlistTransaction", that was missing, because was introduced in "Entity Framework Core 2.1".

EDIT:
Maybe I should have opened the issue here:
https://github.com/aspnet/EntityFramework.Docs/issues

**Comment by ZCplayground** [comment]
I meet the same problem, could you tell me how do you fix it?

**Comment by ajcvickers** [comment]
EF Core 2.0 is now out-of-support.
