### ISSUE TITLE
Fluent API documentation is missing something...

### ISSUE THREAD

**Issue by StingyJack** [aspnet/EntityFramework.Docs#1469]
CS1061	'EntityTypeConfiguration&lt;MyObj&gt;' does not contain a definition for 'HasAlternateKey' and no accessible extension method 'HasAlternateKey' accepting a first argument of type 'EntityTypeConfiguration&lt;MyObj&gt;' could be found (are you missing a using directive or an assembly reference?)	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2799173-ee3e-5650-14a8-b9185d45f730
* Version Independent ID: 36181ef7-bcb6-62a8-653d-3b89c8a11dd8
* Content: [Alternate Keys - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/alternate-keys)
* Content Source: [entity-framework/core/modeling/alternate-keys.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/alternate-keys.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@StingyJack If this isn't working, then it may be a product bug. Please file a new issue at https://github.com/aspnet/EntityFrameworkCore/ and include a simplified, runnable project or code listing so that we can reproduce what you are seeing.
