### ISSUE TITLE
Add more spatial examples

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#1471]
Originally filed as https://github.com/aspnet/EntityFrameworkCore/issues/1100#issuecomment-491697516 by @zp987

----

Cant find much documentation on how to use NetTopologySuite with Entity Core. Looking for stuff like
Inserting a Poligon suing Entity Core Classes and NetTopologySuite, Inserting a Location Point using Enity Core with NetTopologySuite datatypes/property.

Links to any documentation on CRUD operations using Enitity Core/NetTopologySuite will be great.

Was looking for examples of CRUD operations to geography type columns .

Inserting a new row using (entity core/nettopologysuite) in DB with a Geography column type that will store a Polygon ? or Even inserting a new row in the DB with column (geography) storing location pount?

Have also checked http://www.npgsql.org/efcore/mapping/nts.html not much info there either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dcf82b-f177-e91b-96a5-67f2f57bd6c4
* Version Independent ID: 89c0803f-570f-07a6-6dc2-285678712c86
* Content: [Spatial Data - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/spatial#feedback)
* Content Source: [entity-framework/core/modeling/spatial.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/spatial.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by Kurtbaby** [comment]
Ditto.  I am converting .NET Framework v4.8/EF code with a DbGeography data type to .NET Core/EF Core 2.2, and am getting a "cannot bind 'spatialServices', 'spatialProviderValue' in DbGeography(DbSpatialServices, object spatialProviderValue)" exception when I am trying to use this POCO.  Cannot find good examples that use the DbGeography type as a column in the new Core.

**Comment by ajcvickers** [comment]
@Kurtbaby `DbGeography` and `DbGeometry` are specific to EF6. They cannot be used with EF Core. The NTS types are essentially replacements for these types.

**Comment by ajcvickers** [comment]
Duplicate of #1118
