### ISSUE TITLE
Tutorial feels incomplete since no handling of Posts

### ISSUE THREAD

**Issue by aveer28** [aspnet/EntityFramework.Docs#1474]
The tutorial feels incomplete since there is no handling of Posts. This would be beneficial to show how relational data is handled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@aveer28 see [Additional Resources](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=netcore-cli#additional-resources) at the end of this tutorial.  You probably want the 3rd which shows relational and POSTs.

**Comment by aveer28** [comment]
Thanks.  I didn’t look at that option since I was interested in MVC, not Razor pages. 

Perhaps you also link to https://docs.microsoft.com/en-gb/aspnet/core/data/ef-mvc/?view=aspnetcore-2.2
