### ISSUE TITLE
update for vs2019

### ISSUE THREAD

**Issue by jpeckham** [aspnet/EntityFramework.Docs#1477]
is this viable in vs2019? the object type of ado.net edmx is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63be9b09-2dde-819c-72a9-874182a92113
* Version Independent ID: 0ef66141-904a-34b2-b2a1-b090c5d62339
* Content: [Database First - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first)
* Content Source: [entity-framework/ef6/modeling/designer/workflows/database-first.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/designer/workflows/database-first.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by saimasalman** [comment]
You need to choose the project type of .Net framework rather than .Net core. While adding a new item to your project, "ADO.NET Entity Data Model" is available under the "Data" option, if your project type was .Net Framework.

**Comment by jpeckham** [comment]
I am working with a .net core project though for Linux/docker

**Comment by mohamedElkast** [comment]
I have the same issue, what the solution for that?
