### ISSUE TITLE
> EF Core does not support the EDMX file format for models. 

### ISSUE THREAD

**Issue by StingyJack** [aspnet/EntityFramework.Docs#1478]
Why not?  

It makes more sense to give customers a minimal effort upgrade path, meaning MSFT has to do the work to permit the EDMX file, and only has to do it one time. 

This page describes the effort that each customer must now follow. Cumulatively thats way more time than MSFT continuing the existing EF6 feature set into EF core.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 422e4c63-a5c0-76ef-b30d-5e6ed7a32fe6
* Version Independent ID: 56cadf01-60b9-a9e4-919c-efbb894cabdb
* Content: [Porting from EF6 to EF Core - Porting an EDMX-Based Model](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-edmx)
* Content Source: [entity-framework/efcore-and-ef6/porting/port-edmx.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/porting/port-edmx.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Answered in https://github.com/aspnet/EntityFrameworkCore/issues/630

**Comment by StingyJack** [comment]
No it is not. There are too many transition gaps to netcore, and soon the work required to bridge those gaps will be forced on us customers via important/critical windows update. All pretty much at once. From every MSFT product line.

I don't see what the problem is with continuation of features people are using. The code already exists and has been well tested. A rewrite was an expensive decision on your part, any cost savings should not be coming at the expense of features that users depend on.

**Comment by AndriySvyryd** [comment]
The fastest way to port to .NET Core is by upgrading to [EF 6.3](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-8-and-entity-framework-6-3-preview-8/)
EDMX has many features that aren't supported by EF Core, so unless you have a relatively simple model it's unlikely that it would be compatible even if we added a converter.

**Comment by StingyJack** [comment]
@AndriySvyryd - then EF Core kills dynamic data since that depends on the edmx. This was probably the last avenue for quick and easy CRUD apps that can be spun up to manage data. The alternatives are to write a replacement technology or to revert to creating bespoke data administration programs for every business database (or teach business users how to craft TSQL). 

I don't see how this choice of feature exclusions has any benefit to the user base. What equivalent time saving features did we get from the ORM instead of the continuance of features?

**Comment by ajcvickers** [comment]
@StingyJack Why do you want to use EF Core for this? Why not use EF6?

**Comment by StingyJack** [comment]
It's a coercion, not a want. 

Everything that is not netcore has been getting the unsupported/EOL treatment for the last year or so, and this  will only get worse when .net 5 is released (core only).

I'd rather stay with the .net that has a proper configuration system, has wcf technology available, and is far better tested.  That's just not the direction that results in supported tools that get bug fixes and features (and gainful employment).
