### ISSUE TITLE
Injectable connection string?

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/EntityFramework.Docs#1488]
Hi,

I want to create a multi-tenant app, and I want to register an `ITenantService` with the container, then, I want the `DbContext` to be created with a connection-string according to the current tenant.
What's the recommended way to do that?

I thought about inheriting from `DbContextOptions`, but I found no way to address the connection-string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47bf610-692d-9d40-d85f-aec1e2a87a07
* Version Independent ID: 3c94634a-4b17-bc13-7436-0c61aea03ab6
* Content: [Configuring a DbContext - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext)
* Content Source: [entity-framework/core/miscellaneous/configuring-dbcontext.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/configuring-dbcontext.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by TrieBr** [comment]
You can inject ITenantService  into your DbContext, and then in you can dynamically set the connection string in `OnConfiguring`.

**Comment by weitzhandler** [comment]
@TrieBr thanks.

Question is when to call `Database.Migrate`.

**Comment by TrieBr** [comment]
Good question, I can't think of any way that is very elegant.

You could loop through each tenant, create a ServiceProvider Scope, have a way to manually override the value that ITenantService returns, then instantiate your DbContext from the scope, and it would connect to your "faked" tenantId

**Comment by weitzhandler** [comment]
What I ended up doing is, in the controller, upon the creation of the tenant, I call an explicit DbContext with a dummy `ITenantProvider`, that provides the newly created tenant, and migrate it.
