### ISSUE TITLE
UWP guide: improvements

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#149]
- [x] For RC2, users will need 1.3.1 tooling or greater. Otherwise .NET Native will crash
- [ ] Help users understand the magic of `ApplicationData.Current.LocalFolder` and relative paths
- [ ] Add section (or guide) for existing sqlite databases. Importantly, the necesity of copying from InstalledLocation to local folder. See [this snippet](https://github.com/natemcmaster/EntityFramework.PlatformTesting/blob/3b85413d8431ee0874f634d1ad017abb62458498/test/UWP.SQLite/UnitTestApp.xaml.cs#L30-38)
- [ ] Warn users: Don't use anonymous types in query!

**Comment by rowanmiller** [comment]
This has all been superseded now
