### ISSUE TITLE
No SaveChanges() called in Add_writes_to_database()

### ISSUE THREAD

**Issue by robfarmergt** [aspnet/EntityFramework.Docs#1492]
SaveChanges() needs to be called after adding the service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c95e5c7e-882f-76f7-5301-2a5d1ede39d3
* Version Independent ID: 8754aa99-67a7-98ac-a51e-0ba995f96414
* Content: [Testing with InMemory - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#feedback)
* Content Source: [entity-framework/core/miscellaneous/testing/in-memory.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/in-memory.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by billnguyentvlk** [comment]
Learning C#, try to follow this sample and face the same issue. Test failed because SaveChanges() was not called.
