### ISSUE TITLE
Can this be used to synchronize related table

### ISSUE THREAD

**Issue by hoksource** [aspnet/EntityFramework.Docs#1494]
lets say we have a Student table and StudentGrades table.

I don't want other requests to edit the grades at the same time.

can i do 
BeginTransaction

var Student = db.Students.Find(...);
Student.LastModified = DateTimeOffset.Now;
db.SaveChanges();// this will update the rowversion

query StudentGrades;
edit StudentGrades;
db.SaveChanges();

Commit Transaction;

or do i have to put RowVersion on each StudentGrade?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@hoksource you specify what properties act as row version in the model. No need to do it for each individual instance.
