### ISSUE TITLE
Handling strategies and transactions across separate contexts

### ISSUE THREAD

**Issue by WhitWaldo** [aspnet/EntityFramework.Docs#1495]
If I'm setting up a transaction across multiple contexts, I can use the following:

using (var transA = contextA.Database.BeginTransaction()) {
  using (var transB = contextB.Database.UseTransaction(transA.GetDbTransaction())) {
    //etc
  }
}

I don't see any methods available that explain how to combine a strategy that spans transactions across multiple contexts. Is this currently possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 876c88d4-2972-d905-28d7-56f9e589f309
* Version Independent ID: 29002343-fa42-2f49-3362-53592039b26d
* Content: [Connection Resiliency - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency)
* Content Source: [entity-framework/core/miscellaneous/connection-resiliency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-resiliency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Yes.
