### ISSUE TITLE
Rationalize list of additional tutorials 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1499]
From discussion in https://github.com/aspnet/EntityFramework.Docs/pull/1475, figure out what to do with list of additional ASP.NET Core tutorials at the bottom of some of ours:

- Should it be the same at the bottom of all ASP.NET Core-related tutorials? 
- Should it be a single link? 
- Should it be moved to the ToC as external links?

**Comment by ajcvickers** [comment]
Duplicate of #481
