### ISSUE TITLE
Reorganize ToC for new pattern with expandable nodes

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1517]
Some users had difficulties navigating the documentation with topics that where expandable and at the same time had content. For that reason, changes have been made across all documentation so that any content has been moved as the first item under expandable topics. 

Because the change was automatic, the results are less than ideal. For example, the names of the topics is duplicated. In some cases, the content isn't very useful:

![image](https://user-images.githubusercontent.com/1253414/59217679-5aa87480-8b73-11e9-86d0-83fc941351d2.png)

A few ideas to start a discussion:

- Should we come up with a new way to name the node that was created pointing to the contents of the root? 
- In many cases that page is currently almost empty. 
   - Should we try to fill it with introductory contents? 
   - Should we duplicate the child ToC items inside it? 
   - Remove it?

**Note: I am not even sure there is anything we can do about this other than removing the index pages that are currently empty in which we cannot add much value. It seems that the source code for our ToC wasn't changed. It is implemented as a change on how it is parsed.**

**Comment by ajcvickers** [comment]
I noticed the change last week (I think). It may not be ideal, but I like it much better than before!

**Comment by divega** [comment]
I like the simplification in the navigation, but I find the duplicated titles very confusing.
