### ISSUE TITLE
Improve Guide fonts and Style

### ISSUE THREAD

**Issue by SunnyGurnani** [aspnet/EntityFramework.Docs#152]
The technical documents fonts are very small and the style is not user friendly.

This is not the issue only to EF related docs.
http://docs.efproject.net/en/latest/platforms/aspnetcore/existing-db.html

**Comment by rowanmiller** [comment]
cc @danroth27 to comment on this -  the styles we use are used in several Microsoft sites and aren't specific to EF.

**Comment by danroth27** [comment]
We'll be doing a style update when we move to [docfx](https://dotnet.github.io/docfx).
