### ISSUE TITLE
Rationale on Automatic Code Migration no longer recommended?

### ISSUE THREAD

**Issue by minoseah629** [aspnet/EntityFramework.Docs#1520]
This area has this note about no longer recommended for automatic code migration.  

Please provide some rationale or explanation of this note. 

![image](https://user-images.githubusercontent.com/1980068/59444615-31365580-8dcc-11e9-857b-1a299fdf83a1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d06865-183f-140e-a1f1-099cd36b93fe
* Version Independent ID: 401fd98e-66bf-acbc-50f8-16af48c90adf
* Content: [Get started with Entity Framework 6 - EF6](https://docs.microsoft.com/en-us/ef/ef6/get-started)
* Content Source: [entity-framework/ef6/get-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/get-started.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
