### ISSUE TITLE
Should RowVersion comply with: CA1819: Properties should not return arrays

### ISSUE THREAD

**Issue by Orion-TLN** [aspnet/EntityFramework.Docs#1529]
Should the RowVersion comply with: CA1819: Properties should not return arrays?

I see the RowVersion column being a byte[] in most cases but is it affected by the risks described by CA1819?

For reference: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1819-properties-should-not-return-arrays?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041e7a47-a632-132a-3c9e-db46e3782a63
* Version Independent ID: a5de9c4c-56fe-416e-0801-f6acd061f25e
* Content: [Concurrency Tokens - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/concurrency#feedback)
* Content Source: [entity-framework/core/modeling/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
No. Those FxCop rules are old and often not appropriate.
