### ISSUE TITLE
no "Exception" for Add

### ISSUE THREAD

**Issue by DickBaker** [aspnet/EntityFramework.Docs#1531]
other methods list each Exception that could occur, but there is no equivalent for Add method. IMHO if calling this method is guaranteed to be exception-free this should be explicitly stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11437597-e632-34f4-cc94-aac316f28ef0
* Version Independent ID: 9090c5f3-0aab-9a0c-e5ec-e141663ea9df
* Content: [IDbSet&lt;TEntity&gt;.Add(TEntity) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.idbset-1.add?view=entity-framework-6.2.0#System_Data_Entity_IDbSet_1_Add__0_)
* Content Source: [EF/xml/System.Data.Entity/IDbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/IDbSet`1.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
