### ISSUE TITLE
EF7 core not supported MYSQL DB

### ISSUE THREAD

**Issue by sachinverma2** [aspnet/EntityFramework.Docs#154]
Please provide solution for this.

**Comment by natemcmaster** [comment]
@sachinverma2 there are no plans by our team (the EF Core team) to create a MySQL provider. However, if community-members or MySQL themselves create one, we happily add a link in our documentation to this provider.

Closing as there isn't any action to take on the docs repo until MySQL becomes available.

**Comment by rowanmiller** [comment]
Just also adding that we have been actively working with several provider writers to help them support EF Core. Some of those efforts are open source and public, others are not.
