### ISSUE TITLE
Commit Async

### ISSUE THREAD

**Issue by e-davidson** [aspnet/EntityFramework.Docs#1544]
Is there an async version of Transaction.Commit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
It's planned for 3.0--see https://github.com/aspnet/EntityFrameworkCore/issues/15917

**Comment by e-davidson** [comment]
Thank you.
