### ISSUE TITLE
Question : how to use logging only for 1 instance from the DbContext ?

### ISSUE THREAD

**Issue by StefH** [aspnet/EntityFramework.Docs#155]
As described on the wiki page: http://docs.efproject.net/en/latest/miscellaneous/logging.html, when a logger is attached, all instances share it.

**Note**
_You only need to register the logger with a single context instance. Once you have registered it, it will be used for all other instances of the context in the same AppDomain._

How to avoid this ?

In my unit-tests, I only want logging for a specific unit-test, not for all tests.

**Comment by rowanmiller** [comment]
The only way to do this at the moment would be to use a service provider to control the scope of logging. It would be the same as controlling the scope of the InMemory database - as shown in http://docs.efproject.net/en/latest/miscellaneous/testing.html.

We are going to bring back `DbContext.Database.Log` so that this is easier to do in the future.

**Comment by ajcvickers** [comment]
@StefH @rowanmiller As of RC2, you should be able to do something like this:

```C#
public class MyContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
        => optionsBuilder.UseLoggerFactory(new LoggerFactory());
}
```

Every time we create a new context instance we will call OnConfiguring, at which point the new LoggerFactory will be created and will be used for just that context instance.

**Comment by rowanmiller** [comment]
@ajcvickers nice, I'll make sure we include that in the docs when we update to RC2 😄

**Comment by StefH** [comment]
Any timeline for rc2?

**Comment by rowanmiller** [comment]
@StefH nothing to share yet, but we will have a timeline shortly.

**Comment by StefH** [comment]
Thats good to know.

Can I find / download and build the latest code from here (github)  in an easy way?

**Comment by rowanmiller** [comment]
@StefH you can try getting the packages from http://myget.org/Gallery/aspnetrelease. Just make sure you get the new package names (`Microsoft.EntityFrameworkCore.SqlServer` etc.). You may have issues installing some of the packages until an updated version of NuGet becomes available.
