### ISSUE TITLE
External code snippet does not render CSS correctly

### ISSUE THREAD

**Issue by Inzanit** [aspnet/EntityFramework.Docs#1555]
For example:
```
[!code-csharp[Main](../../../samples/core/Saving/Saving/Transactions/ControllingTransaction/Sample.cs?name=Transaction&highlight=3,17,18,19)]
```
does not render correctly in the browser, when viewing on docs.Microsoft.com and results in code that cannot be compiled due to the malformed HTML that is output.

![image](https://user-images.githubusercontent.com/1341180/60755193-15495c80-9fe4-11e9-98ea-de7b35a28d94.png)

It seems the code is put into the correct attribute, `data-author-content`, but then _also_ inserted into the `<code>` element, whereas it should be `...` as per the other snippets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions#feedback)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by Rick-Anderson** [comment]
I'm sorry for the inconvenience. This is a system wide problem that's tracked in #13143
#13143
