### ISSUE TITLE
Connection to Local SQL Server instead of Local DB failed 

### ISSUE THREAD

**Issue by chanmmn** [aspnet/EntityFramework.Docs#1557]
I try to connect to Local SQL Server instead of Local DB using "Data Source = 127.0.0.1; Initial Catalog = Blogging; persist security info = True; user id = sa; password = abc". I got the error "Cannot open database "Blogging" requested by the login. The login failed.
Login failed for user 'sa'.'". 
I have verified the login and password has no problem. 
What is the right Connection String for SQL Server instead of localDB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ErikEJ** [comment]
Use (local) or . for data source

**Comment by chanmmn** [comment]
I did try
"optionsBuilder.UseSqlServer(@"Server=(local);Database=Blogging;Integrated Security=True");"
I got error
"Cannot open database "Blogging" requested by the login. The login failed.
Login failed for user 'WIN-DL44PDBKCA4\Administrator'.'"
I was thinking I don't need to create database with this code? Or I am wrong, I have to create the database manually?

**Comment by nateowen93** [comment]
Yes, you will need to create the database manually by using migrations. You can find the instructions under Get Started -> .NET Core ->New Database under the 'Create the Database' section.

**Comment by chanmmn** [comment]
Thanks. After I did dotnet ef database update, I did see blogging.db in the folder but I gave me "SqliteException: SQLite Error 1: 'no such table: Blogs" error when I executed the program.

**Comment by ajcvickers** [comment]
Mixing SQL Server and SQLite in this way will not work.
