### ISSUE TITLE
Code snippet is not displaying properly

### ISSUE THREAD

**Issue by anuraj** [aspnet/EntityFramework.Docs#1558]
Under the "Register the context with dependency injection" section - the code for AddDbContext is not displaying properly. It is proper in GitHub, in the docs it is showing some code is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio#register-the-context-with-dependency-injection)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm sorry for the inconvenience. This is a system wide problem that's tracked in #13143
