### ISSUE TITLE
Support Sqlite file locations

### ISSUE THREAD

**Issue by sjb-sjb** [aspnet/EntityFramework.Docs#156]
It doesn't seem to be possible (at least not in a straightforward way) to locate an Sqlite database in the user's document directory. Specifying an absolute path results in error 14 unable to open file (and this is not due to a lack of permissions). 

Being able to store the file in arbitrary locations is important to apps where the file is being used as a document format or where it is otherwise desired to allow the user to move, copy or backup the file, or even just because the user wants to be able to see it in with their other files. 

I know the file should be on a local drive but I think we can do better than having it hidden away in a directory that most users can't find. 

All the best,

sjb

**Comment by natemcmaster** [comment]
@sjb-sjb absolute paths are already be supported.  If you are still having issues with this in the 1.0.0 release, please open an issue on https://github.com/aspnet/Microsoft.Data.Sqlite along with your error message and repro steps.

**Comment by sjb-sjb** [comment]
Are you referring to 7.0.0-rc1-final? Because in that version, you can specify an absolute path but it has to be a path to the app dir.
