### ISSUE TITLE
More context please!

### ISSUE THREAD

**Issue by CmdrBeavis** [aspnet/EntityFramework.Docs#1568]
"If you need to test code that makes use of the Find method it is easiest to create a test DbSet for each of the entity types that need to support find. You can then write logic to find that particular type of entity, as shown below." 

While I'm fairly decent at extrapolation, I'd REALLY like to see some context around HOW to use that `TestBlogDbSet`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9696766-8f5f-f762-e4f1-1d403b0b3276
* Version Independent ID: a6df7c92-facc-8fd5-d8c6-ac3d2668d9e8
* Content: [Testing with your own test doubles - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/writing-test-doubles#feedback)
* Content Source: [entity-framework/ef6/fundamentals/testing/writing-test-doubles.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/testing/writing-test-doubles.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)

**Comment by CmdrBeavis** [comment]
I thought my comments were pretty self-explanatory. Guess not.  :(
