### ISSUE TITLE
Isolation Level-specific behavior details

### ISSUE THREAD

**Issue by timmi4sa** [aspnet/EntityFramework.Docs#1577]
Hi, this document needs to be enhanced to include more than just a simple mention of the Isolation Levels (as a parameter of BeginTransation method). Also it needs to explain that even though there is a deceptively simple "Entity Framework does not wrap queries in a transaction." behavior in place, the actual queries are subject to default isolation level of [the database provider connection?]. And the most critical for the "queries that aren't wrapped in a transation" once an attempt is made to BeginTransation(&lt;my isolation level&gt;) method the isolation level will affect queries even AFTER the transaction.Rollback() / transation.Commit() / transation.Dispose() have been called to complete the transaction FOR THE DURATION OF THE AppDomain (recreating the DbContext doesn't seem to reset a default isolation level). Developers MUST know that, and even though I feel that this is a huge bug in EF6, I don't think it will be ever fixed so the documentation must explain the behavior, and that the only recourse is to create yet another transaction with isolation level of ReadCommitted, which must be simply rolled back and disposed off to restore the normal isolation level for queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e17e30-4349-3193-01f1-5eb33cb88546
* Version Independent ID: dcb6d719-ffc2-2796-c82c-b9873b74cb76
* Content: [Working with Transactions - EF6](https://docs.microsoft.com/en-us/ef/ef6/saving/transactions#feedback)
* Content Source: [entity-framework/ef6/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
