### ISSUE TITLE
Out-of-date if using Preview 3.0.0-*

### ISSUE THREAD

**Issue by Allann** [aspnet/EntityFramework.Docs#1578]
Could this page be updated to reflect the requirements of this tool since it now is a separate global tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#feedback)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Didn't we just do that in #1569? What's missing?

**Comment by Allann** [comment]
the Content Source does not appear to have made it to content.  I didn't know about the GitHub page, google took me to the Content url.  I will go through the instructions later today and close this if I have no problems.
Thanks for the update.
