### ISSUE TITLE
Code Generation Strategy unchangeable from "T4"

### ISSUE THREAD

**Issue by ianw1223** [aspnet/EntityFramework.Docs#1579]
With VS 2017 (15.9.13) and EF 6.2.0, when following step 2, the code generation strategy is fixed at "T4" and cannot be changed from None to Default.  Perhaps the article is specific to older version(s) of VS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f906ae00-465e-6553-e037-741a82d5485e
* Version Independent ID: 962225b7-2e86-0845-1aa3-baf466b86e63
* Content: [Reverting to ObjectContext in Entity Framework Designer - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/codegen/legacy-objectcontext#feedback)
* Content Source: [entity-framework/ef6/modeling/designer/codegen/legacy-objectcontext.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/designer/codegen/legacy-objectcontext.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ianw1223** [comment]
After some experimentation, I see this issue occurs (in VS2017) for EF6.0 - 6.2.0, but not for EF5 or EF 4.3.1.  Note this is the EF6 documentation!

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
