### ISSUE TITLE
How and where to call this

### ISSUE THREAD

**Issue by CeciAc** [aspnet/EntityFramework.Docs#1595]
@huxiaozhong commented on [Sun Jul 21 2019](https://github.com/aspnet/EntityFramework.Docs.zh-cn/issues/51)

How and where to call this: myDbContext.Database.Migrate();
give some example code please!!!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [迁移 - EF Core](https://docs.microsoft.com/zh-cn/ef/core/managing-schemas/migrations/#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

---

@srvbpigh commented on [Sun Jul 21 2019](https://github.com/aspnet/EntityFramework.Docs.zh-cn/issues/51#issuecomment-513557091)

Hello, @huxiaozhong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the user is requesting aditional examples
best regards

**Comment by ajcvickers** [comment]
@huxiaozhong Can you provide more details what you are trying to achieve?

**Comment by smitpatel** [comment]
Closing due to lack of response.
