### ISSUE TITLE
"Create the database" is not accurate

### ISSUE THREAD

**Issue by mszixie** [aspnet/EntityFramework.Docs#1611]
Database is already created and specified in the connection string, so it's not accurate to do "Create the database" step, which may cause misunderstanding to readers, (especially new users). Suggest we can change to some thing more specific, e.g. "Create the table for the model", or "Apply the change in the database", etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db?tabs=visual-studio#create-the-database)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, that step creates the DB.
