### ISSUE TITLE
Remove '$' and 'PM>' prefix from command line samples for copy&paste

### ISSUE THREAD

**Issue by Eilon** [aspnet/EntityFramework.Docs#1614]
Some command line samples include the `$` or `PM>` prefix in them, which means the `Copy` button on them will produce incorrect results.

E.g. this page (now fixed): https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

Has this:
![image](https://user-images.githubusercontent.com/202643/62307901-509b4780-b439-11e9-9aae-de5346fa6b3e.png)

So when you press `Copy`, you end up with this in your clipboard:

```
$ dotnet tool install --global dotnet-ef --version 3.0.0-*
```

And if you paste that into a command window, it certainly won't work.

So, we should remove the `$` and `PM>` prefixes from command line samples.

**Comment by smitpatel** [comment]
This is already fixed in current docs.
