### ISSUE TITLE
Which primary key are you referring?

### ISSUE THREAD

**Issue by pstricks-fans** [aspnet/EntityFramework.Docs#1617]
The documentation says:

> If the dependent entity contains a property named 
> 
> - `<primary key property name>`, 
> - `<navigation property name><primary key property name>`, or 
> - `<principal entity name><primary key property name>` 
> 
> then it will be configured as the foreign key.

Because the dependent entity can also have a `primary key`, the description above becomes unclear. In order to  avoid this confusion, my suggestion is to replace `primary key`  with `principal key` as follows.

- `<`**principal**` key property name>`

- `<navigation property name><`**principal** ` key property name>`

- `<principal entity name><`**principal**` key property name>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Triage: Try to clarify this more.
