### ISSUE TITLE
EnlistTransaction does not exist in EF 2.0

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/EntityFramework.Docs#1622]
https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Saving/Saving/Transactions/CommitableTransaction/Sample.cs#L37
```
context.Database.EnlistTransaction(transaction);
```

EnlistTransaction  was added in 2.1 https://github.com/aspnet/EntityFrameworkCore/issues/5595

So this stops the samples from compiling for me. any ideas why it doesnt break other people?

**Comment by ajcvickers** [comment]
EF Core 2.0 and lower are out-of-support, so closing docs issues specific to these releases.

**Comment by SimonCropp** [comment]
This wasnt about v2. It was about not being able to build the current version of docs

**Comment by ajcvickers** [comment]
@SimonCropp My mistake. Duplicate of #1074

**Comment by SimonCropp** [comment]
Cool. Thanks for the forward
