### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by rrusson** [aspnet/EntityFramework.Docs#1623]
A quick example is always appreciated. It took me a few minutes to figure out that I needed something like this to "upsert" records based off matching FK and Key (in a key-value pair table):

dbContext.UserOptions.AddOrUpdate(x =&gt; new { x.UserId, x.Key }, optArray);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c039f208-975d-ae8d-54c4-3b0299a669e9
* Version Independent ID: ea1e78cd-a152-f6af-254d-599236c6133b
* Content: [IDbSetExtensions.AddOrUpdate Method (System.Data.Entity.Migrations)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.idbsetextensions.addorupdate?view=entity-framework-5.0.0#System_Data_Entity_Migrations_IDbSetExtensions_AddOrUpdate__1_System_Data_Entity_IDbSet___0__System_Linq_Expressions_Expression_System_Func___0_System_Object_____0___)
* Content Source: [EF/xml/System.Data.Entity.Migrations/IDbSetExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Migrations/IDbSetExtensions.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
