### ISSUE TITLE
System.TypeInitializationException

### ISSUE THREAD

**Issue by AlexandriaBoxCrush** [aspnet/EntityFramework.Docs#1624]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

I keep getting this unhandled Exception while working on your example linked below:
https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database

If you could help me to learn to handle this exception that would be dandy.

**Comment by ajcvickers** [comment]
Duplicate of #481
