### ISSUE TITLE
Incorrect lambda parameter in fluent one-to-one example

### ISSUE THREAD

**Issue by James-Lester** [aspnet/EntityFramework.Docs#1626]
Greets.
I believe since the lamba parameter _p_ refers to type Blog, the lambda parameter should instead be _b_.
Is:
```
        modelBuilder.Entity<Blog>()
            .HasOne(p => p.BlogImage)
            .WithOne(i => i.Blog)
            .HasForeignKey<BlogImage>(b => b.BlogForeignKey);
```

Should be:
```
        modelBuilder.Entity<Blog>()
            .HasOne(b => b.BlogImage)
            .WithOne(i => i.Blog)
            .HasForeignKey<BlogImage>(b => b.BlogForeignKey);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#feedback)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by eduuh** [comment]
I think it does not matter since each of this method are returning an object.  p or i are object references

**Comment by James-Lester** [comment]
> I think it does not matter since each of this method are returning an object. p or i are object references

Syntactically it doesn't matter, but I tripped on this when I was learning how to set up relationships. I mistakenly thought `p` and `b` were used because they were referring to different `Type`s until I realized that it was actually just a typo and they both referred to `Blog`.
