### ISSUE TITLE
Add explanation and examples for conventions related to Owned -> Owner Navigational Properties

### ISSUE THREAD

**Issue by douglasg14b** [aspnet/EntityFramework.Docs#1628]
There seems to be a convention that a property matching the type of the Owner entity on the Owned entity will be automatically used as a navigation back to the owner.

This isn't documented, and presents challenges when trying to work around this.

**Example:**

**Note:** This is a crappy example that doesn't really convey a real-life use case, but does highlight the confusion from the conventions being unknown...

```cs
    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public RelatedPerson Related { get; set; }
    }

    [Owned]
    public class RelatedPerson
    {
        // Is this now a navigation property back to the owner, or is this a distinct Person separate from the owner?
        // What if this is supposed to not be a navigation property? How is that configured?
        public Person Person { get; set; }

        // If Person is a navigational property to the owner, is this Id set appropriately? If not?
        public int PersonId { get; set; }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#feedback)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
@douglasg14b The convention is the same as for any other relationship, but I see why it's confusing for ownership.
