### ISSUE TITLE
Add more conceptual documentation around aggregates

### ISSUE THREAD

**Issue by BahKoo** [aspnet/EntityFramework.Docs#1629]
The documentation makes the following claim about references from owned types:

> In addition to nested owned types, an owned type can reference a regular entity, it can be either the owner or a different entity as long as the owned entity is on the dependent side.

It is not made clear **why** the owned entity must be on the dependent side of the relationship. Is this limitation by-design or a current shortcoming?

A concrete example of a scenario that would benefit from this capability was outlined in the stackoverflow question:
[https://stackoverflow.com/q/54647000/2196664](https://stackoverflow.com/q/54647000/2196664)

When talking about DDD, having value objects reference a collection of entities does not seem to be a restriction:

> VALUE OBJECTS can even reference ENTITIES. For example, if I ask an online map service for a
scenic driving route from San Francisco to Los Angeles, it might derive a Route object linking L.A.
and San Francisco via the Pacific Coast Highway. That Route object would be a VALUE, even though
the three objects it references (two cities and a highway) are all ENTITIES.
> _-- Eric Evans, Domain-Driven Design: Tackling Complexity in the Heart of Software, page 98_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#feedback)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
This is by design. Owned types are part of an aggregate and only the aggregate root can be referenced from outside.

>VALUE OBJECTS can even reference ENTITIES. For example, if I ask an online map service for a
scenic driving route from San Francisco to Los Angeles, it might derive a Route object linking L.A.
and San Francisco via the Pacific Coast Highway. That Route object would be a VALUE, even though
the three objects it references (two cities and a highway) are all ENTITIES.
-- Eric Evans, Domain-Driven Design: Tackling Complexity in the Heart of Software, page 98

This doesn't say that Route is the principal, it has three references to three entities.

**Comment by BahKoo** [comment]
On closer inspection of my model, I think that table splitting is a better fit for my problem than owned entities. Thanks for the feedback.
