### ISSUE TITLE
When is MaxLength null?

### ISSUE THREAD

**Issue by ite-klass** [aspnet/EntityFramework.Docs#1632]
&gt; The maximum length of the property.

So when is this null? Never? When the database does not impose a limit? When no explicit value is set but it may still have an implicit one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5a182c-9e29-3bdb-10ff-0ca5286a1b9e
* Version Independent ID: 178d744e-faa5-f02a-87a3-b057d8b84198
* Content: [EdmProperty.MaxLength Property (System.Data.Entity.Core.Metadata.Edm)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.core.metadata.edm.edmproperty.maxlength?view=entity-framework-6.2.0#System_Data_Entity_Core_Metadata_Edm_EdmProperty_MaxLength)
* Content Source: [EF/xml/System.Data.Entity.Core.Metadata.Edm/EdmProperty.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.Core.Metadata.Edm/EdmProperty.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
