### ISSUE TITLE
Update description of what targets EF Core supports

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1635]
- It no longer supports .NET Framework in 3.0. Mentions of .NET Standard 2.0 are also scattered in other pages. We should probably put together all the information about compatibility in a single place like [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/platforms/) and make all the updates there
- Any new features in 3.0 worth adding to the matrix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0036f8c5-d838-69a5-cc09-dc74df09bc07
* Version Independent ID: 5335749f-e32f-979f-7139-f5f14373e283
* Content: [Compare Entity Framework 6 and Entity Framework Core](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/#entity-framework-core)
* Content Source: [entity-framework/efcore-and-ef6/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by lauxjpn** [comment]
The [MSDN docs](https://docs.microsoft.com/en-us/ef/core/platforms/) need to be updated for 3.1 again, because of the reintroduced compliance with .NET Standard 2.0.

**Comment by bricelam** [comment]
Submitted PR https://github.com/aspnet/EntityFramework.Docs/pull/1980
