### ISSUE TITLE
EF Core Version Number on Doc Pages

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/EntityFramework.Docs#1645]
Is there plans to implement the version number dropdown like on ASP.NET Core doc pages?  

![image](https://user-images.githubusercontent.com/14079228/63204576-1d76cc00-c067-11e9-8c4f-3f5193f0428d.png)

Maybe there's already an issue logged for this that I couldn't find?

**Comment by smitpatel** [comment]
@spottedmahn - We don't have any plan to add version number. We did not have many significant change to have different documentation for each version. For now, we decided that when we add a new feature, in the doc page we would mention which version it was introduced. If a functionality changed during any version then we will documentation behavior in latest the page and also mentioned past behaviors at the bottom of the page.

In future, if we really need drop-down menu we'll reconsider.

**Comment by spottedmahn** [comment]
I see, thanks for the response.
