### ISSUE TITLE
Document optional owned types

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/EntityFramework.Docs#1646]
I opened an issue [asking for null owned types support](https://github.com/aspnet/EntityFrameworkCore/issues/17201) and it was closed as a duplicate.  The duplicate issue appears to be [closed as implemented in 3.0 preview 4](https://github.com/aspnet/EntityFrameworkCore/issues/9005#issuecomment-477741082).

I don't see an open issue to update the documentation for 3.0 changes so I'm opening one 😊

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by spottedmahn** [comment]
looks like this needs to be changed:

>Reference navigations to owned entity types cannot be null unless they are explicitly mapped to a separate table from the owner

[since it was implemented](https://github.com/aspnet/EntityFrameworkCore/issues/9005#issuecomment-477741082) 😀

**Comment by spottedmahn** [comment]
nice, thanks!!

**Comment by matteocontrini** [comment]
> looks like this needs to be changed:
> 
> > Reference navigations to owned entity types cannot be null unless they are explicitly mapped to a separate table from the owner

@spottedmahn I read your comment but it seems that that statement still applies? From what I understand a property that references an owned entity can be null only if table splitting is used. Is that correct?

**Comment by spottedmahn** [comment]
Hi @matteocontrini - owned entities can be null **w/o** table splitting as of 3.0.

Sample code is here: https://stackoverflow.com/a/57596415/185123

**Comment by matteocontrini** [comment]
I then found that I was incurring in issue https://github.com/aspnet/EntityFrameworkCore/issues/18066, that's why I thought support wasn't there :)
Thanks!
