### ISSUE TITLE
Update client eval page for 3.0

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1648]
Points to cover:
1. EF Core 3.0 does very limited client eval
2. Explicitly switching to client eval can be done, for example, with AsEnumerable, AsAsyncEnumerable, ToList, ToListAsync. Each has trade-offs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd35b912-445c-e801-7f70-de73839db80d
* Version Independent ID: e558a081-5397-1e3f-1d58-abea3f72cad6
* Content: [Client vs. Server Evaluation - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/client-eval)
* Content Source: [entity-framework/core/querying/client-eval.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/client-eval.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
I updated to add AsEnumerable/AsAsyncEnumerable. Does anyone know any benefits of ToList/ToListAsync?

**Comment by AndriySvyryd** [comment]
No multiple evaluation when used again?

**Comment by ygoe** [comment]
ToList also fetches the data immediately. This may be necessary if the underlying cursor cannot stay open while doing other queries on the same connection, or if the enumeration being iterated will be changed (less relevant for database queries).
