### ISSUE TITLE
Add-Migration InitialMigration Command Issue

### ISSUE THREAD

**Issue by utpal-patel** [aspnet/EntityFramework.Docs#165]
## Code Downloaded From Sample

PM> Add-Migration InitialMigration
Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:1 char:1
- Add-Migration InitialMigration
- ~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

---
## Code I Wrote

 PM> Add-Migration InitialMigration
System.BadImageFormatException: Could not load file or assembly 'projectname' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'projectname'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Data.Entity.Design.Internal.StartupInvoker..ctor(String startupAssemblyName, String environment)
   at Microsoft.Data.Entity.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment)
   at Microsoft.Data.Entity.Design.MigrationsOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment, String projectDir, String rootNamespace)
   at Microsoft.Data.Entity.Design.OperationExecutor.<>c__DisplayClass3_0.<.ctor>b__3()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Design.OperationExecutor.<AddMigrationImpl>d__7.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.Execute(Action action)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Could not load file or assembly 'projectname' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by rowanmiller** [comment]
@utpal-patel which sample were you using? Can you also share Windows and VS version.

**Comment by natemcmaster** [comment]
Stack trace included "Microsoft.Data.Entity" namespaces. I assume this means your project is using RC1. FYI we just released RC2. See https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html

**Comment by colhountech** [comment]
On the following page :  https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html#create-your-model

> Locate the tools section and add the `ef` command as shown below
```
 "tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
```
the sample below is the wrong gist as it does not contain a reference to ef.

**Comment by MaxxDelusional** [comment]
I can confirm that this isn't working. Running the commands from the command line still seems to work, but you can't use Add-Migration from the Package Manager Console.

```dotnet ef migrations add InitialMigration```

**Comment by rowanmiller** [comment]
You would use `Add-Migration InitialMigration` in Package Manager Console. The `dotnef ef` commands are for use outside of Visual Studio.

**Comment by MaxxDelusional** [comment]
Yes, I know, but ```Add-Migration InitialMigration``` isn't currently working in Package Manager Console. I included the alternate command line text as a "workaround", but my comment wasn't very clear.

**Comment by utpal-patel** [comment]
Thanks @rowanmiller and @MaxxDelusional...
i was stuck so i decided other way to accomplish the task...
but i will check and reply soon...

Appreciate it!!

**Comment by utpal-patel** [comment]
@rowanmiller, i am using windows 10 Pro (Build: 10586.318) and Visual studio 2015 Update 2

**Comment by rowanmiller** [comment]
@MaxxDelusional 

>  Add-Migration InitialMigration  isn't currently working in Package Manager Console.

Are you seeing the same `System.BadImageFormatException` as @utpal-patel ? If not, can you open a separate issue with details of the issue you are having as it is a different issue. Be sure to include your project.json file.

**Comment by rowanmiller** [comment]
@utpal-patel is this a .NET Core project?

**Comment by utpal-patel** [comment]
@rowanmiller it is windows universal application.

**Comment by rowanmiller** [comment]
@utpal-patel thanks for the info. This isn't an issue we are currently aware of - we do have some architecture issues in .NET Core in RC2. Any chance you could share the project that reproduces the issue, so that we can debug it?

**Comment by utpal-patel** [comment]
@rowanmiller i will do that by today end...hope it helps!!
Appreciate your efforts!!

**Comment by allanrsmith** [comment]
@utpal-patel @rowanmiller what happened with this?  I am now hitting a similar issue when trying to add a migration.
```PM> Add-Migration -Name Initial_Create -Context ApplicationContext -Project Procore.DB -Verbose
Using startup project 'Procore'.
Using project 'Procore.DB'
Build started...
Build succeeded.
Using application base 'C:\Users\Allan\Source\Repos\uwp\src\Procore\bin\x64\Debug\'.
No configuration file found.
Using current directory 'C:\Users\Allan\Source\Repos\uwp\src\Procore\bin\x64\Debug\'.
Microsoft.EntityFrameworkCore.Design.OperationException: Could not load assembly 'Procore.DB'. Ensure it is referenced by the startup project 'Procore'. ---> System.BadImageFormatException: Could not load file or assembly 'Procore.DB' or one of its dependencies. An attempt was made to load a program with an incorrect format.```

**Comment by utpal-patel** [comment]
@rowanmiller Sorry!! I was stucked with some work so could not able to submit the code...i will do ASAP.
@allanrsmith Could not able to figure it out yet!!

But primary solution may be update entity framework package...

**Comment by dvdobrovolskiy** [comment]
add-migration : The term 'add-migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ add-migration
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (add-migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rowanmiller** [comment]
Closing as these issues should be fixed now. There is guidance on getting tools to work in https://github.com/aspnet/EntityFramework/issues/7358. If you hit issues with this, please open an issue on the main EF repo (https://github.com/aspnet/EntityFramework). This repo is specific to the documentation.
