### ISSUE TITLE
Example code risks

### ISSUE THREAD

**Issue by space-alien** [aspnet/EntityFramework.Docs#1653]
In the final example which avoids the `ILazyLoader` service reference, a null-safe navigation is used for `loader?.Invoke()` in the `Load` extension method. That makes sense because it needs to be possible to use newly instantiated entities without a lazy loader reference. However, given the potentially dire consequences of lazy loading silently failing, would it be prudent to include a null check on the `lazyLoader` constructor parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@space-alien Not sure what you mean by, "Include a null check on the lazyLoader constructor parameter." Can you explain in a bit more detail?

**Comment by space-alien** [comment]
Something like this?

```csharp
private Post(Action<object, string> lazyLoader)
{
    LazyLoader = lazyLoader ?? throw new ArgumentNullException(nameof(lazyLoader));
}
```

**Comment by smitpatel** [comment]
Throwing in constructor will disallow to initialize entity without lazyloader. If the entity is created without lazyloader then it will not lazyload but throwing exception may not be right thing to do always. If for use case, you want to disallow entity without lazyloader then feel free to add null check.
