### ISSUE TITLE
Add a page for working with nullable reference types in 3.0

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1655]
From the discussion at https://github.com/aspnet/EntityFrameworkCore/issues/17212, here are a few things we know are affected:
1. You can now use NRTs to express requiredness (#1654)
2. Defining a `DbContext` with automatic `DbSet<T>` properties that EF Core takes care of initializing can lead to possible null exception warnings.
3. Creating a non-nullable reference type property on an entity can lead to null warnings.
5. Writing perfectly valid EF Core queries using LINQ can result into null warnings. 
6. Configuring models, in particular using the relationships configuration APIs can lead to null warning.
7. Note on scaffolding (where we haven't yet done anything). https://github.com/aspnet/EntityFrameworkCore/issues/15520.

For all issues from 2 to 6, we can basically guide customers to add the null-forgiving operator (`!`) as appropriate (although other adequate patterns may exist for some cases).

@roji, Apparently I didn't have this in the docs backlog (or I am unable to find it). Could you own this?

cc @ajcvickers

**Comment by roji** [comment]
Yes, will work on a proposal after Wednesday.
