### ISSUE TITLE
Small typo..

### ISSUE THREAD

**Issue by tudort-iquest** [aspnet/EntityFramework.Docs#1664]
At 'Option 2: Update the model snapshot in the last migration', step 1, it's written that:
'Ensure any pending model changes in your local code base have been written to a migration. This step ensures you don’t miss any legitimate changes when it comes time to generate the blank migration.'
- for this solution there is no blank migration as far as I can tell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b72ecde8-e983-8583-7c3f-6e0e4ff404fb
* Version Independent ID: 6ed79d63-19a7-c527-b383-c5faf4beba55
* Content: [Code First Migrations in Team Environments - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/teams#option-2-update-the-model-snapshot-in-the-last-migration)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/teams.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/teams.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)

**Comment by tudort-iquest** [comment]
It's just a simple error that you could fix in 5 minutes.. As you wish.. :)
