### ISSUE TITLE
Why the example subject to SQL Injection attack?

### ISSUE THREAD

**Issue by kgreed** [aspnet/EntityFramework.Docs#1667]
One of the examples has FromSql($"SELECT * FROM dbo.SearchBlogs({searchTerm})")
There is a warning not to do this
Why give an example and then warn not to use it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1289d5-8364-18a4-3445-6bba05c6854b
* Version Independent ID: 2680e647-f64a-7991-f821-3b5e2a845960
* Content: [Raw SQL Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#feedback)
* Content Source: [entity-framework/core/querying/raw-sql.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/raw-sql.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by craig-b** [comment]
If you look at the api or IntelliSense you'll see it's not accepting a string but instead a FormattableString, this means the string isn't actually interpolated and is actually safe.

**Comment by ajcvickers** [comment]
Duplicate of #410
