### ISSUE TITLE
Move Table Splitting under Relational Modeling

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework.Docs#1668]
Or remove the Relational Database Modeling section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c847da37-ca7d-1c42-8acf-405167085d27
* Version Independent ID: bd4fe1c7-514d-cfb1-d975-4096306b06e9
* Content: [Table Splitting - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting)
* Content Source: [entity-framework/core/modeling/table-splitting.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/table-splitting.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by roji** [comment]
+1 for removing the Relational Database Modeling section, opened #1669 to track.

**Comment by ajcvickers** [comment]
Decided to remove relational separation.
