### ISSUE TITLE
Merge relational database modeling into general modeling

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework.Docs#1669]
As discussed offline, we should consider removing the separate "relational database modeling" subsection and merge its contents into general modeling. 99% of EF Core users are relational (so information is split across two places), and the split between relational and non-relational isn't very meaningful or interesting to the vast majority of users.

Where we think it's really important to highlight that something is relational, we can call it out.

**Comment by AndriySvyryd** [comment]
Related: https://github.com/aspnet/EntityFramework.Docs/issues/862

**Comment by roji** [comment]
PRs are out merging all relational model building pages into non-relational.
