### ISSUE TITLE
Write a documentation page explaining EF.Functions 

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/EntityFramework.Docs#1676]
Write a documentation page explaining EF.Functions 
in https://docs.microsoft.com/en-us/ef/core/querying/

**Comment by xrkolovos** [comment]
this is useful 
[](https://entityframework.net/knowledge-base/45708715/entity-framework-ef-functions-like-vs-string-contains)

**Comment by ajcvickers** [comment]
Duplicate of #1134
