### ISSUE TITLE
.NET Core with MSDTC

### ISSUE THREAD

**Issue by pappasa** [aspnet/EntityFramework.Docs#1686]
How do you use .NET Core with MSDTC? For example, I want to remove a message from an IBM WebSphere MQ queue and put it to the database in one transaction. I do not want for example to remove the message from the queue, and the put to the database to fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by roji** [comment]
.NET Core doesn't support distributed transactions at this point - see https://github.com/dotnet/corefx/issues/13532. Note that this isn't related to Entity Framework Core in any way.
