### ISSUE TITLE
CommitableTransaction\Sample.cs does not compile

### ISSUE THREAD

**Issue by pappasa** [aspnet/EntityFramework.Docs#1688]
With Visual Studio 2019 I get the following compilation error:

`EntityFramework.Docs-master\samples\core\Saving\Saving\Transactions\CommitableTransaction\Sample.cs(37,42,37,59): error CS1061: 'DatabaseFacade' does not contain a definition for 'EnlistTransaction' and no accessible extension method 'EnlistTransaction' accepting a first argument of type 'DatabaseFacade' could be found (are you missing a using directive or an assembly reference?)`

What is wrong?

**Comment by Rick-Anderson** [comment]
Looks like you are using ASP.NET Core/Entity Framework Core 3.0 on a older tutorial.  
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
