### ISSUE TITLE
why i can't use uint for primary key?

### ISSUE THREAD

**Issue by dxq0126** [aspnet/EntityFramework.Docs#1689]
i an using code first.
```
public class zhb_order
    {
        public uint id { get; set; }
        public string sign_date { get; set; }
```
when run at this line:
modelBuilder.Entity<zhb_order>().HasKey(x => x.id);
i got an error:
The property 'id' cannot be used as a key property on the entity 'Picc.Models.zhb_order' because the property type is not a valid key type. Only scalar types, string and byte[] are supported key types.

how can i fix it,with not modify database

**Comment by ajcvickers** [comment]
@dxq0126 Are you using EF6 or EF Core?

**Comment by dxq0126** [comment]
EntityFramework 6.2.0

**Comment by dxq0126** [comment]
> @dxq0126 Are you using EF6 or EF Core?

EntityFramework 6.2.0

**Comment by dxq0126** [comment]
> @dxq0126 Are you using EF6 or EF Core?

EntityFramework 6.2.0

**Comment by dxq0126** [comment]
@ajcvickers EF 6.2.0

**Comment by smitpatel** [comment]
uint is not one of the EDMX type hence it is not support. Therefore you cannot use it for any property.
