### ISSUE TITLE
SaveChanges with SQL trigger

### ISSUE THREAD

**Issue by pappasa** [aspnet/EntityFramework.Docs#1690]
On my SQL tables, I have the columns TraceVersion and UTimestamp, which get updated by an AFTER UPDATE trigger. The column TraceVersion is incremented by 1, and the UTimestamp is set to the current date and time. How can I get SaveChanges to return these values, so that my entity is updated with the new TraceVersion and UTimestamp?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a489ad3-46e5-865f-09f8-b9be45788b8b
* Version Independent ID: e38f9319-2483-f96f-1d12-51c1489514e5
* Content: [DbContext.SaveChanges Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.savechanges?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbContext.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
