### ISSUE TITLE
Add documentation on non-Windows machines

### ISSUE THREAD

**Issue by AskYous** [aspnet/EntityFramework.Docs#1694]
I was reading until I got to #reverse-engineer-your-model, and I don't know how to do the equivalent on a mac. Please add documentation to support more than just Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Get started on ASP.NET Core - existing database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#reverse-engineer-your-model)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by bricelam** [comment]
Superseded by #481
