### ISSUE TITLE
Question - PDF

### ISSUE THREAD

**Issue by NoralK** [aspnet/EntityFramework.Docs#17]
I found two PDFs on readthedocs.org for EF and MVC dated mid-July.  Were these PDFs done by this group or someone else, if it was this group a hyperlink somewhere would be nice to get the PDFs - if there is one I cannot find it :)

On to the real question - I can compile the project into HTML but I cannot get rst2pdf integrated properly with Sphinx to compile to PDF.  Has anyone here done this on Windows?  When I try integrating rst2pdf I get an exception occurred - I am not look to troubleshoot that exception.

**Comment by NoralK** [comment]
After looking at ReadTheDocs.org they product the PDF automatically for hosted content.  I also checked the rst2pdf project out and this is a know issue - the rst2pdf project is just starting backup so I don't expect anything soon.

If anyone knows of way to product that documentation outside of ReadTheDocs.org on Windows please let me know.

**Comment by rowanmiller** [comment]
@NoralK readthedocs is built using Sphinx (sphinx-doc.org/). You'd have to dig into it though to see if PDF generation is part of Sphinx or something readthedocs adds on (I'm not sure).
