### ISSUE TITLE
Please clarify the last two lines: "The dependents/children (posts) will only be deleted if the database has a corresponding cascade behavior configured. If you use EF to create the database, this cascade behavior will be setup for you."

### ISSUE THREAD

**Issue by PeterOeClausen** [aspnet/EntityFramework.Docs#1707]
I've set up Cascade behavior between model classes in a hierarchy, and I'm running tests with an InMemory database, to make sure it cascades as intended when I am to run on the database server.
I noticed that when I include the children before calling remove(), the children are also deleted. If I do not include the children, the cascade behavior is not happening.
However is this line saying that this will work differently when running on an SQL database instead of InMemory?
It seems weird to me that I have to include children, and childrens children to force the cascade delete. Will I have to do the same when running EF CORE against an SQL Server or not? And if yes, why is the behavior different between InMemory and SQL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete#feedback)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by PeterOeClausen** [comment]
I got confused while running my tests with an InMemory configuration. It was only when I included members that cascade delete happened. However when running EF CORE with an SQL database, cascade delete works.
This shows that the behavior is different when running InMemory configuration versus running with an SQL server configuration.
I would expect the two to work the same way, and that I was able to test cascade delete behavior in my tests with an InMemory database before running it against the SQL database. Perhaps you could either change the InMemory configuration to work more like a real database (with working cascade deletes), or you could state it more explicitly in the documentation, that the InMemory database configuration doesn't support cascading 
deletes.

This is just some feedback for EF CORE and the documentation. I really like using it, and thanks for making and maintaining it :-)

**Comment by smitpatel** [comment]
We configure cascade delete for the database which supports it. InMemory database does not have concept of referential integrity constraint so cascade delete wouldn't work the same way there.

**Comment by smitpatel** [comment]
Product issue https://github.com/aspnet/EntityFrameworkCore/issues/3924

Filed #1791 to add limitations to InMemory db.
