### ISSUE TITLE
Consider documenting how to use a SQLite :memory: database

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#171]
_From @Tragetaschen on May 25, 2016 16:22_

The [documentation](https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/miscellaneous/testing.rst#inmemory-is-not-a-relational-database) mentions SQLite's special file name `:memory:`, but to use this (for example during development), there are some hoops to jump through.

[#5086](https://github.com/aspnet/EntityFramework/issues/5086#issuecomment-210783773) contains the necessary code to make this work in an application using EF. Please consider adding this to the documentation, so users (like me :smile:) don't have to search the GitHub issues for `no such table: __EFMigrationsHistory`.

_Copied from original issue: aspnet/EntityFramework#5516_

**Comment by divega** [comment]
The pattern described in https://github.com/aspnet/EntityFramework/issues/5086#issuecomment-210783773 consists in opening a connection and then passing it to every single `DbContext` instance. We should check if a working pattern in which an in-memory SQLite database can be kept alive by a connection but we let each `DbContext` create its own connection (similar to the perf workaround commonly used for SQL CE). The concern is that sharing the same connection object across all `DbContext` instance can cause multi-threading issues.

**Comment by rowanmiller** [comment]
Done https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite

**Comment by vmrocha** [comment]
Can we also consider documentation for Entity Framework 6?
