### ISSUE TITLE
"code first"  ? 

### ISSUE THREAD

**Issue by pentjak** [aspnet/EntityFramework.Docs#1711]
This doesn't seem to be different from a database-first model in the EF Designer section.  It seems like for this to be "code first" you would start by creating an example class that you want to store, then show how the data model for a few different backing stores can be generated from the class since.  Then answer a few questions like "if I want to control some elements of the backing store, how do I affect the table / column mapping from the class members without creating a data model " if that's even possible.  If it's not possible, then there really is no such thing as a "code first" model. Maybe I'm missing something obvious. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6327694-56ae-2d48-11c3-d6e1af422531
* Version Independent ID: c5280888-67b5-4c13-bdc6-3a0ec6bfbe20
* Content: [Code First to an Existing Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/existing-database#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/workflows/existing-database.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/workflows/existing-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
To be more accurate this should be called "code second"

**Comment by smitpatel** [comment]
@pentjak - It may not be accurately code first but that has been naming for years now and we don't plan to change it.

**Comment by pentjak** [comment]
Fair enough. I just wanted to make sure I wasn't missing something.
