### ISSUE TITLE
How to perform database update in code

### ISSUE THREAD

**Issue by tmds** [aspnet/EntityFramework.Docs#172]
How can the database update ("dotnet ef database update") be performed in code?

**Comment by tmds** [comment]
Related: when I execute "dotnet ef database update" it uses the Debug configuration, is there a way to make it use the "Release" configuration?

**Comment by rowanmiller** [comment]
To apply migrations from code, you would use the `DbContext.Database.Migrate()` API. If you want to apply them during app startup on an ASP.NET Core application, you would put some code like this in the `Configure(...)` method in `Startup.cs`.

```c#
using (var context = new MyContext(app.ApplicationServices.GetRequiredService<DbContextOptions<MyContext>>()))  
{  
    context.Database.Migrate();  
}  
```

**Comment by rowanmiller** [comment]
cc @natemcmaster regarding the Debug/Release question. I assume this would be a general .NET CLI thing, I think you can `SET Configuration=Release` to change this?

**Comment by natemcmaster** [comment]
`dotnet ef --configuration Release database update` should work. https://docs.efproject.net/en/latest/cli/dotnet.html#dotnet-ef

You can also specify "environment" if that's how you pivot on which connection string to use. `dotnet ef database update --environment Production`
https://docs.efproject.net/en/latest/cli/dotnet.html#dotnet-ef-database-update

**Comment by tmds** [comment]
@rowanmiller Thanks. I don't mind you closed the issue since I know how to do it now. I put it in the docs repo because I think it should be documented.

**Comment by tmds** [comment]
Note: you need "Microsoft.EntityFrameworkCore.Relational" in project.json to get the Migrate extension method

**Comment by tmds** [comment]
Also, it seems I need to create a scope to properly resolve the DbContext in Configure (see https://github.com/aspnet/EntityFramework/issues/3070#issuecomment-142752126)

**Comment by rowanmiller** [comment]
@tmds you don't need to create a scope, not that the code I posted is creating an instance of the context rather than resolving it from DI. Creating a scope was required when we had some magic to sneak DbContextOptions into the context... but we removed that magic and now it is just a constructor parameter (hence the simpler code).

**Comment by tmds** [comment]
Isn't this resolving from DI?
`app.ApplicationServices.GetRequiredService<DbContextOptions<MyContext>>()`

**Comment by rowanmiller** [comment]
@tmds yes, but just the options (which are singleton) rather than the context which needs to be scoped.

**Comment by tmds** [comment]
@rowanmiller aha, I was mislead by the ServiceLifetime argument, but yes: https://github.com/aspnet/EntityFramework/blob/9186d0b78a3176587eeb0f557c331f635760fe92/src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs#L150-L151. Thanks!
