### ISSUE TITLE
Effects of renaming context

### ISSUE THREAD

**Issue by ps-tb** [aspnet/EntityFramework.Docs#1734]
I recently made a change to a context class and removed several `DbSet`s. The class wasn't named accurately when it was created and now the name doesn't match what it does at all. I'd like to rename it but when I do so, it affects the naming in the migration. What is the recommended way to make this type of change? Does it even matter? Thanks for any input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/#customize-migration-code)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Could you provide a specific example? I'm having a hard time following what you're saying.

To prevent a rename after removing a DbSet property, you can configure the table name in OnModelCreating:

``` csharp
modelBuilder.Entity<MyEntity>().ToTable("OldDbSetPropertyName");
```

**Comment by ps-tb** [comment]
Sorry, I'll be more specific. 

I have a file called `VotingContext`, which doesn't contain anything related to an act of voting and would be more accurately named `FeedbackContext`. When I refactor the name, `VotingContextModelSnapshot` is no longer accurately named and it also has an annotation that changes from `DbContext(typeof(VotingContext))]` to `DbContext(typeof(FeedbackContext))]`.  Are there any underlying or non-obvious issues with me making these changes that would affect migrations?

**Comment by bricelam** [comment]
Feel free to change the name of the model snapshot class. The name is actually never used--It just needs to inherit from ModelSnapshot and have a DbContext attribute pointing to the right context.

**Comment by ps-tb** [comment]
Does the fact that the DbContext attribute has changed have any effect?

**Comment by bricelam** [comment]
Yes, it won't work without the change.
