### ISSUE TITLE
Where is the automatically created database?

### ISSUE THREAD

**Issue by yuechiang** [aspnet/EntityFramework.Docs#1737]
I did not specify any database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73b2e5a-9526-e664-a2da-556717d344e1
* Version Independent ID: 93442b78-6869-139c-bdbc-9a1efa21b7a6
* Content: [Databinding with WPF - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf#feedback)
* Content Source: [entity-framework/ef6/fundamentals/databinding/wpf.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/databinding/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
@bricelam to answer.

**Comment by bricelam** [comment]
See [Where’s My Data?](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/new-database#wheres-my-data)
