### ISSUE TITLE
Targeting class library projects is not supported => workaround does not work!

### ISSUE THREAD

**Issue by bastienJS** [aspnet/EntityFramework.Docs#174]
The 2nd workaround: 

"To make a desktop .NET app, ensure you project targets "net451" or newer (example "net461" also works) and ensure the build option "emitEntryPoint" is set to true."

does not work because when compiling I get the error: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		C:\TGB.Core\DataProvider\error CS5001: Program does not contain a static 'Main' method suitable for an entry point	DataProvider	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	241	
```
I will not enter a program.cs with main method thats just stupid. Then I could also initially create a console app, but actually I want a class library...

Thus please remove your 2nd workaround!

Its even worse than I thought, the 2nd workaround does NOT work at all:

I added a program.cs file with the static Main method. Now the code compiles.

But when I run in the project Directory on the CMD:

dotnet ef migrations add Init

I get the same error message/hint as before:
```
This preview of Entity Framework tools does not support targeting class library projects in ASP.NET Core and .NET Core applications. See http://go.microsoft.com/fwlink/?LinkId=798221 for details and workarounds.

```

![image](https://cloud.githubusercontent.com/assets/5945955/15620469/b1b02ab2-245a-11e6-80ac-cf3f0fce42fc.png)

**Comment by natemcmaster** [comment]
@bastienJS you are probably hitting this issue: https://github.com/dotnet/cli/issues/3164. I'll update the workaround docs for reflect this.
