### ISSUE TITLE
Migrate ToC from markdown to YAML format

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1742]
Just creating this because I remember @mairaw mentioned we should do it, but I actually don't have the full perspective on why. 

I think it would help with https://github.com/aspnet/EntityFramework.Docs/issues/1119. We currently have a subset of the structure of the ToC in a yaml file that is used to drive the breadcrums.

**Comment by mairaw** [comment]
According to https://review.docs.microsoft.com/en-us/help/contribute/toc-management?branch=master

"A table of contents (TOC) is used to define the structure of a docset. TOCs for docs.microsoft.com should be created in YAML, but you may already have a TOC in Markdown. Markdown TOCs are deprecated and should be converted to YAML."

**Comment by divega** [comment]
Thanks @mairaw. Looks like that page also contains instructions to get it converted for us.

**Comment by divega** [comment]
Fixed in #1749.

**Comment by mairaw** [comment]
Oh nice! I've filed the request but I didn't see that they had made the conversion already.
