### ISSUE TITLE
'DbContext' does not contain a definition for 'ObjectContext'

### ISSUE THREAD

**Issue by pappasa** [aspnet/EntityFramework.Docs#1744]
I have this class:
```C#
using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB1Entities : DbContext
    {
        public DB1Entities()
            : base("name=DB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var objc = base.ObjectContext;
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet&lt;CUser&gt; CUsers { get; set; }
    }
```
However, I get the compilation error:

Model1.Context.cs(25,29,25,42): error CS0117: 'DbContext' does not contain a definition for 'ObjectContext'

It seems the property ObjectContext does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6105276-f920-4784-121b-a5f0d851e4f6
* Version Independent ID: cdd9c0ff-7557-6aa2-c7af-0e5afaf9df0c
* Content: [DbContext.IObjectContextAdapter.ObjectContext Property (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.system-data-entity-infrastructure-iobjectcontextadapter-objectcontext?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbContext.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
@bricelam to write answer.

**Comment by AndriySvyryd** [comment]
```C#
var objc = ((IObjectContextAdapter)this).ObjectContext;
```

**Comment by bricelam** [comment]
``` csharp
var objc = ((IObjectContextAdapter)base).ObjectContext;
```
