### ISSUE TITLE
Consider Change BeginScope API

### ISSUE THREAD

**Issue by bnayae** [aspnet/EntityFramework.Docs#175]
You should consider to change the IDisposable BeginScope<TState>(TState state) API,
to something that return IScopedLogger (which is sub set of the logging functionality) 
this way you can encapsulate the scope and can log dat to different scope simultaneously on different threads.
when encapsulating the log this way it is easier to maintain and understand logging data related to specific scope.

    public interface IScopedLogger : IDisposable
    {
        bool IsEnabled(LogLevel logLevel);
        void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);
    }

**Comment by natemcmaster** [comment]
@bnayae thanks for the suggestion. This is just a documentation repo, however. For issues and discussion regarding the logging APIs, see https://github.com/aspnet/Logging.
