### ISSUE TITLE
misspelling, no mention of InMemory provider?

### ISSUE THREAD

**Issue by wizofaus** [aspnet/EntityFramework.Docs#1752]
"ingore"-&gt;"ignore".
I was hoping to read about what (if anything) had been improved with the InMemory provider for EF Core 3.0? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b660a3-4b81-2f6e-fd19-a2c71e9f3b5b
* Version Independent ID: 5552bf61-9cfb-5152-0bc1-903cd4bd417d
* Content: [New features in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/features)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/features.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/features.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
@divega - Can you incorporate this in #1751

**Comment by divega** [comment]
@smitpatel do you think there are any improvements specific to in-memory that are worth mentioning?

**Comment by smitpatel** [comment]
@divega - I mainly referred for typo. InMemory the only major thing we did was to improve key generation. I am not sure if it is worth mentioning.
