### ISSUE TITLE
Use Case that is not clear

### ISSUE THREAD

**Issue by rmagruder** [aspnet/EntityFramework.Docs#1764]
Suppose I have a SQL View which acts as a proxy to a lookup table.  For example, suppose I am editing Orders, and I have a Customer SQL View.  It selects only a few columns from Customer, including its primary key (CustomerId).  An Order must have a customerId, so I if we were dealing with Entities, Order would have a Customer property w/ Foreign Key of CustomerId, and Customer would have an Id field and both would have navigational properties.  If I "lie" to EF and say that Customer is a Table, it works, but EF wants to act like Customer is updatable (It isn't - it's just a lookup).  If I use the above method and say this is a View, albeit with a key (presumably because the View is defined as returning, say, the Customer ID and Name), what happens?  Do I trigger errors because I defined a View as 'keyless'?  Do the navigational property restrictions kick in and prevent one side from seeing the other?   In short, is there any reason to stop 'lying' to EF and telling it that the View is really a table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types#feedback)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
If you have a view with properties that can be used as keys just map it to a normal entity with `ToView`.
