### ISSUE TITLE
Broken links to GitHub; dev branch does not exist

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [aspnet/EntityFramework.Docs#1768]
These links in the "Upgrading applications from previous versions to EF Core 2.0" topic lead to error 404:
- _"The event IDs for messages sent to an [ILogger](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs) have changed in 2.0."_  
  The "dev" branch does not exist. Should perhaps link to <https://github.com/aspnet/Logging/blob/rel/2.0.0/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs> instead. That repository has been archived but the "rel/2.0.0" tag in the replacement repo <https://github.com/aspnet/Extensions/> did not yet contain the logging files.
- _"Logger categories have also changed. There is now a well-known set of categories accessed through [DbLoggerCategory](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/DbLoggerCategory.cs)."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/DbLoggerCategory.cs>.
- _"The event payloads are all nominal types derived from [EventData](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Diagnostics/EventData.cs)."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/Diagnostics/EventData.cs>.
- _"Event IDs, payload types, and categories are documented in the [CoreEventId](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Diagnostics/CoreEventId.cs) and the [RelationalEventId](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Relational/Diagnostics/RelationalEventId.cs) classes."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/Diagnostics/CoreEventId.cs> and <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore.Relational/Diagnostics/RelationalEventId.cs>.
- _"EF Core 2.0 will now build a different [IModel](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Metadata/IModel.cs) for each different provider being used."_  
  Should perhaps link to <https://github.com/aspnet/EntityFramework/blob/rel/2.0.0/src/EFCore/Metadata/IModel.cs>.
- _"If an application does need to call `UseInternalServiceProvider`, then please consider [filing an issue](https://github.com/aspnet/EntityFramework/Issues) so we can investigate other ways to handle your scenario."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/issues> ("issues" must be in lower case).
- _"`IsReadOnlyBeforeSave`, `IsReadOnlyAfterSave`, and `IsStoreGeneratedAlways` have been obsoleted and replaced with [BeforeSaveBehavior](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Metadata/IProperty.cs#L39) and [AfterSaveBehavior](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Metadata/IProperty.cs#L55)."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/Metadata/IProperty.cs#L39> and <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/Metadata/IProperty.cs#L55>.
- _"Properties marked as [ValueGenerated.OnAddOrUpdate](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Metadata/ValueGenerated.cs) (for example, for computed columns) will by default ignore any value currently set on the property."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/Metadata/ValueGenerated.cs#L44> (optionally with a line number).
- _"In previous releases, [DeleteBehavior.Restrict](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore/Metadata/DeleteBehavior.cs) had a behavior for entities tracked by the context that more closed matched `SetNull` semantics."_  
  Should perhaps link to <https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.0/src/EFCore/DeleteBehavior.cs#L62> (without the "Metadata" subdirectory).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921bc335-e001-201a-6835-a386cbd73c46
* Version Independent ID: b03c14ba-c941-2a54-be95-5f4c89400787
* Content: [Upgrading from previous versions to EF Core 2 - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/1x-2x-upgrade#feedback)
* Content Source: [entity-framework/core/miscellaneous/1x-2x-upgrade.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/1x-2x-upgrade.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
You are right, all links should contain reference to blob data in tags. Would you like to submit a PR?

**Comment by KalleOlaviNiemitalo** [comment]
A PR from me is unlikely at this time.

**Comment by smitpatel** [comment]
@KalleOlaviNiemitalo - No worries, we will get it sorted out.

**Comment by smitpatel** [comment]
It should reference API docs.

**Comment by roji** [comment]
Will correct, but @mairaw aren't broken links supposed to be automatically flagged?

**Comment by mairaw** [comment]
External links are not automatically flagged @roji. Only relative and xref links.
For external links, you need to run https://contentqacats.azurewebsites.net/ from time to time. You can configure them to run on a weekly basis. Do you want me to set up that for you?

**Comment by roji** [comment]
> You can configure them to run on a weekly basis. Do you want me to set up that for you?

Yes please, that would be great! Does it automatically open issues on the repo for us?

**Comment by mairaw** [comment]
Nope. It'll send an email to you with the issues report. I'll include @smitpatel as well.

Here's an example for the .NET docs: https://contentqacats.azurewebsites.net/CheckResults/2019091600009/Report/

**Comment by roji** [comment]
OK, thanks @mairaw!

**Comment by roji** [comment]
@mairaw, could you please include @ajcvickers as well please?

**Comment by mairaw** [comment]
Ok. I've set up a weekly P0/P1 issue report and I'm running right now a full report as well.
