### ISSUE TITLE
Breaking changes note on new single-query behavior and cartesian explosion

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework.Docs#1769]
Now that we generate a single SQL query for a LINQ query, users will start running into the cartesian explosion problem when joining multiple tables (e.g. https://github.com/aspnet/EntityFrameworkCore/issues/18022). ~We should add a section in the [loading related data page](https://docs.microsoft.com/en-us/ef/core/querying/related-data) with a code sample.~

Add a breaking change note.

**Comment by KevinMallinson** [comment]
So the docs will essentially have an example of a query which generates dozens or hundreds of joins, with a proposed alternative style of structuring such a query?

In my case, my project is not very mature so it wouldn't be a problem to convert my one query which does this, but I imagine others who have mature projects would be left with a choice, either don't upgrade, or refactor dozens of queries.

Is it possible for there to be an opt out of single linq query so we can have our cake, and at least partially eat it?

**Comment by brunom** [comment]
Why can't you use Nested FOR XML Queries?

    db.Blogs
    .Include(b => b.Posts)
    .Include(b => b.Post2s)

would become

    SELECT
        *,
        (select * from Posts where Posts.BlogId = Blogs.BlogId FOR XML AUTO),
        (select * from Post2s where Post2s.BlogId = Blogs.BlogId FOR XML AUTO)
    FROM Blogs

Note that this is better than EF6 since you require no sort or memory grant.
