### ISSUE TITLE
Only works for SQL API

### ISSUE THREAD

**Issue by MisinformedDNA** [aspnet/EntityFramework.Docs#1771]
It should be specified that this provider only works for SQL API of Cosmos DB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by roji** [comment]
This seems more like an implementation detail of how the provider works... Any particular reason you think this needs to be mentioned?

**Comment by alexdrenea** [comment]
It's an implementation detail if you're starting from scratch and build your app using EF core 
If you want to update your existing Cosmos DB Graph database you will be disappointed to find out you can't actually connect to it using EF Core.
