### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by Genysis78** [aspnet/EntityFramework.Docs#1774]
Hi, create the database section, shouldn't it be dotnet-ef, not dotnet ef (just going off the post-install instruction of 'You can invoke the tool using the following command: dotnet-ef')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **divega**

**Comment by Rick-Anderson** [comment]
`dotnet ef ` is correct. See https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet
