### ISSUE TITLE
Asynchronous streams missing a namespace?

### ISSUE THREAD

**Issue by christiannagel** [aspnet/EntityFramework.Docs#1778]
The documentation for the **async streams** with EF Core 3.0 shows a simple LINQ query to use await foreach. I tried that and it's not working as shown (at least a namespace is missing).

https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/index.md#asynchronous-streams

The DbSet<T> implements IAsyncEnumerable, but the IQueryable extension methods don't.
Does a specific namespace need to be opened? I tried it with *Microsoft.EntityFrameworkCore*, but here other extension methods are not used. 
The correct namespace should be documented, or if there is a different way what needs to be done to make it work.
 
Thanks,
Christian

**Comment by HSchwichtenberg** [comment]
@smitpatel @divega 
Thank you for this fix. I suggest that you correct this in the blog post too ;-)

https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/

var orders =   from o in context.Orders  where o.Status == OrderStatus.Pending  select o; await foreach(var o in orders){  Process(o);}

**Comment by divega** [comment]
@christiannagel, @HSchwichtenberg thank you. The blog post is now also corrected. 

FWIW, our LINQ queries cannot be directly consumed directly with `await foreach`, but there is a chance this can be enabled in the future. 

See https://github.com/dotnet/roslyn/issues/32289#issuecomment-535804031.
