### ISSUE TITLE
 Circular Object References using JSon

### ISSUE THREAD

**Issue by DJKampouris** [aspnet/EntityFramework.Docs#178]
I am using AspNetCore RC2 and I am tring to remove Circular Object References using JSon

With RC1 I could add the following snippet to my Startup.cs and it would work.

```
services.AddMvc().AddMvcOptions(options => {

options.OutputFormatters.RemoveType<JsonOutputFormatter>();
var jsonOutputFormatter = new JsonOutputFormatter();
jsonOutputFormatter.SerializerSettings.ReferenceLoopHandling 
  = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
options.OutputFormatters.Insert(0, jsonOutputFormatter);
});
```

In RC2 it doesn't work anymore and I would rather not revert to using  [JsonIgnore] on my model navigation properties.

Any suggestions ?

**Comment by divega** [comment]
This issue was moved to aspnet/Mvc#4782
