### ISSUE TITLE
"The database provider identifies which parts of the query can be evaluated in the database"

### ISSUE THREAD

**Issue by ExploreNcrack** [aspnet/EntityFramework.Docs#1783]
Does Entity Framework Core also contribute to identify which parts of the query can be evaluated in the database, which parts of the query need to be run in the client-side during the LINQ query translation (when building the representation) such that database provider can just identify it by the representation result passed from Entity Framework Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3208b215-1bac-c110-12f4-e1a6b448fdaf
* Version Independent ID: 3f6fb56f-0a79-8861-f8c4-ea5969a9aff5
* Content: [How Queries Work - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/overview#feedback)
* Content Source: [entity-framework/core/querying/overview.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/overview.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Consolidated into #1720
