### ISSUE TITLE
Does ef core cosmos provider has database first support

### ISSUE THREAD

**Issue by saitejaprattipati** [aspnet/EntityFramework.Docs#1796]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

**Comment by saitejaprattipati** [comment]
@AndriySvyryd

**Comment by AndriySvyryd** [comment]
No, Cosmos is a schema-less database, and trying to guess the expected shape of the entities from data would only work for the simplest cases.
