### ISSUE TITLE
Group By

### ISSUE THREAD

**Issue by MCFHTAGENTS** [aspnet/EntityFramework.Docs#1800]
Hi there, based on my code that no longer works post .Net Core 3.0 I believe keyless queries do not support Group By LINQ operations.

They are also complicated to seed data for when unit testing as the Add method no longer works.

Please can you confirm this is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types#feedback)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
Group By always was client-evaluated, in 3.0 EF Core no longer performs client evaluation automatically , see https://github.com/aspnet/EntityFrameworkCore/issues/17068
Query Types couldn't be seeded either, you can use a defining query for testing
