### ISSUE TITLE
Excellent and concise documentation

### ISSUE THREAD

**Issue by vizznr** [aspnet/EntityFramework.Docs#1809]
This is the best documentation I've ever seen, I don't know about you guys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b97c27-6026-d52a-6955-eb7696e3a204
* Version Independent ID: ee8cecea-7ff2-bd7b-bea3-4c50da8860a3
* Content: [Migrator Class (Microsoft.EntityFrameworkCore.Migrations.Internal)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.internal.migrator?view=efcore-2.1#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Migrations.Internal/Migrator.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Migrations.Internal/Migrator.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by bricelam** [comment]
lol, we're in the process of removing the all the `.Internal` types from the API docs. See [the interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.imigrator?view=efcore-2.1) for (slightly) more substantial docs.

**Comment by bricelam** [comment]
Should read, "Pay no attention to the man behind the curtain!"

**Comment by vizznr** [comment]
To be fair, I was warned many times not to use these types, my code is full of green squiggles

**Comment by mairaw** [comment]
I've opened the PR to push the changes live:
https://github.com/aspnet/EntityFramework.ApiDocs/pull/61

BTW, do you want to keep receiving the issues for API docs here or would you prefer to go to https://github.com/aspnet/EntityFramework.ApiDocs/?

**Comment by smitpatel** [comment]
@ajcvickers @bricelam - Should we get issues for API docs filed on product repo directly? Since that is where we need to make change anyway.

**Comment by mairaw** [comment]
Cool. Thanks for confirming @smitpatel.  
I'm closing this issue since the page no longer exists and I'll ask the engineering team to reindex the data for the API browser search: https://docs.microsoft.com/en-us/dotnet/api/?view=efcore-2.1.
