### ISSUE TITLE
Update docs for RTM

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#183]
Tracking work for updating docs to RTM

 - [x] Remove "imports" from guides
 - [x] Update workarounds and known issues
 - [x] Ensure PMC cmdlets and .NET Core CLI commands syntax match code
 - [x] Ensure stubbed out provider to actually build against RTM APIs
 - [x] Show how to use `--startup-project`

**Comment by natemcmaster** [comment]
Include this known issue on UWP https://github.com/dotnet/coreclr/issues/5714#issuecomment-227891727 and it's workaround.

**Comment by weshaggard** [comment]
@ericstj is trying to see if we can get https://github.com/dotnet/coreclr/issues/5714#issuecomment-227891727 fixed for RTM.
