### ISSUE TITLE
Formatting a title

### ISSUE THREAD

**Issue by thalaeg** [aspnet/EntityFramework.Docs#1836]
This title is not formatting for some reason

"## Creating the in-memory test doubles".

It is about half way down the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9696766-8f5f-f762-e4f1-1d403b0b3276
* Version Independent ID: a6df7c92-facc-8fd5-d8c6-ac3d2668d9e8
* Content: [Testing with your own test doubles - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/testing/writing-test-doubles#feedback)
* Content Source: [entity-framework/ef6/fundamentals/testing/writing-test-doubles.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/testing/writing-test-doubles.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
Fixed via #1839
