### ISSUE TITLE
Connection strings should not be hard coded

### ISSUE THREAD

**Issue by scottrudy** [aspnet/EntityFramework.Docs#184]
This sample should pull the connection string from a config file.

**Comment by rowanmiller** [comment]
I want to keep things as simple as we can for the tutorials, so I added a note stating that and pointing folks to the docs that show the options for where to put connection string.

> Note
> In a real application you would typically put the connection string in a configuration file. For the sake of simplicity, we are defining it in code. For more information, see [Connection Strings](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings).
