### ISSUE TITLE
Teradata.EntityFrameworkCore prerelease

### ISSUE THREAD

**Issue by MaxG117** [aspnet/EntityFramework.Docs#1840]
A prerelease version of Teradata.EntityFrameworkCore is now available: https://www.nuget.org/packages/Teradata.EntityFrameworkCore/

Supported database engines: Teradata Database 16.10 onwards.

Maintainer / Vendor: [Teradata](https://downloads.teradata.com/download/connectivity/net-data-provider-for-teradata)

Notes / Requirements: Prerelease

Useful links: [NuGet](https://www.nuget.org/packages/Teradata.EntityFrameworkCore/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9338b2a-93b1-595a-2e8e-86119e6eecbd
* Version Independent ID: 9890ab79-bc72-6075-4294-5450e6693668
* Content: [Database Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@MaxG117 Please submit a PR.

**Comment by MaxG117** [comment]
@ajcvickers What's a PR and how do I submit it?

**Comment by MaxG117** [comment]
The providers aren't listed in any obvious order. Should I feel free to rearrange them, say, alphabetically?

**Comment by MaxG117** [comment]
PR submitted - #1849
