### ISSUE TITLE
Will property be included in the mpdel if it was declared using Interface or Abstract class?

### ISSUE THREAD

**Issue by DeveloperLookBook** [aspnet/EntityFramework.Docs#1841]
Can Interfaces or Abstract classes be used to create model properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c24b57-557f-a6d6-16f1-1da50e4744cd
* Version Independent ID: 8bee29c6-58e4-1d07-025e-0bdcead9b5a1
* Content: [Including & Excluding Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/included-properties)
* Content Source: [entity-framework/core/modeling/included-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/included-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@DeveloperLookBook I assume you mean entity types that have properties where the property type is an interface or an abstract type. If so, yes for abstract types. For interfaces, see https://github.com/aspnet/EntityFrameworkCore/issues/13344 and https://github.com/aspnet/EntityFrameworkCore/issues/757
