### ISSUE TITLE
is Timestamp properties Shadow Properties?

### ISSUE THREAD

**Issue by FlippieCoetser** [aspnet/EntityFramework.Docs#1845]
is Timestamp properties Shadow properties by convention? Timestamp properties are used by the API to generate ETag's. Other than using ETag's in HTTP Headers I do not have the need to return Timestamp properties in my API Response. If I understood the idea behind Shadow properties correctly then I believe a Timestamp shadow property will help me achive the above mentioned goal. The documentation does not cover this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 550a3c36-7f1d-efa7-3ed8-769720168da4
* Version Independent ID: 627c4301-e00d-826e-d545-3a244305dec9
* Content: [Shadow Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties)
* Content Source: [entity-framework/core/modeling/shadow-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/shadow-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@FlippieCoetser You could make it a shadow property if you want, but that isn't the default.
