### ISSUE TITLE
Document table name metadata breaking change

### ISSUE THREAD

**Issue by benmccallum** [aspnet/EntityFramework.Docs#1863]
I previously had some code in `OnModelCreating` doing the following: `entityType.Relational().TableName = "Xyz";`

After updating to 3.0.0, `.Relational()` ceased to exist and I had to swap over to: `entityType.SetTableName("Xyz");`

Looks like it could be mentioned specifically alongside the changes under ["Provider Specific Metadata API Changes"](https://docs.microsoft.com/en-au/ef/core/what-is-new/ef-core-3.0/breaking-changes#provider-specific-metadata-api-changes).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-au/ef/core/what-is-new/ef-core-3.0/breaking-changes#provider-specific-metadata-api-changes)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@benmccallum The section you linked is intended to cover this change. Are you suggesting we add an exhaustive list of all the extension methods that changed in this way?

**Comment by benmccallum** [comment]
Note sure, I've got no idea how many there are. I can PR this particular one as it's probably a common one. Whatever you think is best.

**Comment by ajcvickers** [comment]
@benmccallum Sure, a PR to add the one you hit would be welcome.
