### ISSUE TITLE
Wrong SQL generation

### ISSUE THREAD

**Issue by samkbit** [aspnet/EntityFramework.Docs#1865]
Per documentation, the following LINQ

```c#
var searchTerm = ".NET";

var blogs = context.Blogs
    .FromSqlInterpolated($"SELECT * FROM dbo.SearchBlogs({searchTerm})")
    .Where(b => b.Rating > 3)
    .OrderByDescending(b => b.Rating)
    .ToList();
```

generates the following SQL

```sql
SELECT [b].[BlogId], [b].[OwnerId], [b].[Rating], [b].[Url]
FROM (
    SELECT * FROM dbo.SearchBlogs(@p0)
) AS [b]
WHERE [b].[Rating] > 3
ORDER BY [b].[Rating] DESC
```

Where is the __searchTerm__? Shouldn't this be mentioned in the generated SQL?

**Comment by ajcvickers** [comment]
@samkbit The searchTerm becomes parameter `p0`. Are you saying this should be explicitly documented?

**Comment by smitpatel** [comment]
Already written in docs https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#passing-parameters
