### ISSUE TITLE
How to force EF to check Concurrency Token even if entity is not modified?

### ISSUE THREAD

**Issue by crclz** [aspnet/EntityFramework.Docs#1876]
I need something like a shared lock to guarantee consistency. EF checks ConcurrencyToken of an entity only when it was modified. How can I force EF to check the concurrency token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649fbab8-b960-6873-14bf-188d14757fee
* Version Independent ID: f5ee3135-54c8-689c-e28b-b203b376bd6f
* Content: [Handling Concurrency Conflicts - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/concurrency)
* Content Source: [entity-framework/core/saving/concurrency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/concurrency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
See https://github.com/aspnet/EntityFrameworkCore/issues/18536#issuecomment-546514593
