### ISSUE TITLE
EF Core 3 - Skip() not working

### ISSUE THREAD

**Issue by sfrobous** [aspnet/EntityFramework.Docs#1884]
Paging is not working on my queries:
![image](https://user-images.githubusercontent.com/19509475/67865627-57079100-fb06-11e9-8187-3b656bdf3aaa.png)

I'm using the UseRowNumberForPaging option, but seems to be ignored.
I'm using EF Core 3.0.0 with SQL Server 2008 R2. Aand this is how its configured.
![image](https://user-images.githubusercontent.com/19509475/67865655-65ee4380-fb06-11e9-8e93-58d0886f23f5.png)

**Comment by smitpatel** [comment]
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#urn
