### ISSUE TITLE
Where do GetObjectType and ObjectContext come from?

### ISSUE THREAD

**Issue by Mamikel** [aspnet/EntityFramework.Docs#1897]
Where do ObjectContext and GetObjectType in the code sample come from?
My class inherits from DbContext and Visual Studio doesn't know what they are.  

using (var context = new BloggingContext())
{
    var blog = context.Blogs.Find(1);
    var entityType = ObjectContext.GetObjectType(blog.GetType());
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4977dc-7dec-ced6-177d-4204345130a3
* Version Independent ID: fcf75747-ae44-3e72-7615-36c03475ba63
* Content: [Working with proxies - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/proxies#feedback)
* Content Source: [entity-framework/ef6/fundamentals/proxies.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/proxies.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@Mamikel `((IObjectContextAdapter)context).ObjectContext`
