### ISSUE TITLE
Using links in docs

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework.Docs#1900]
Add this to guidelines somewhere

When referencing
- Topic on same page => Use id => #previous-versions
- Topic in EF docs => use unique doc id with xref => xref:core/querying/raw-sql (you can also append above here)
- Topic in non-EF docs => use path starting with / ignoring docs.microsoft.com part => /dotnet/csharp/programming-guide/concepts/linq/basic-linq-query-operations (this makes sure that language is preserved navigating through docs)
- Code from samples => use relative path => ../../../samples/core/Querying/Basics/Sample.cs#Filtering
- Also link to sample, we need to use absolute link since it is different site. Use master branch for all samples link. (e.g. https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types The link used in the tip.) 

Unless referencing something very external, we should not be using absolute links. (else who moved my cheese?)

**Comment by smitpatel** [comment]
@ajcvickers - Can you update the links being changed in #1891 to above? There are build warnings in PR now.

**Comment by AndriySvyryd** [comment]
We already have guidelines: https://github.com/dotnet/docs/blob/master/styleguide/template.md#links
