### ISSUE TITLE
UseIdentityColumn(1001, 1) does not work

### ISSUE THREAD

**Issue by iwhp** [aspnet/EntityFramework.Docs#1905]
I am using UseIdentityColumn(1001, 1); but when inserting a new raw, the first ID ist not 1001, it is still 1. Also, when I check the table definition it does not say 1001, it still says 1.
Are there any dependencies I have to look for?
Thankx, Harry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c22063-1b14-cfea-b91d-75c9f421bd97
* Version Independent ID: ef6c8fab-f7f3-d391-cb08-b41cc4ed8043
* Content: [SqlServerPropertyBuilderExtensions.UseIdentityColumn Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverpropertybuilderextensions.useidentitycolumn?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.SqlServerPropertyBuilderExtensions.UseIdentityColumn%60%601);k(SolutionItemsProject);k(SolutionItemsProject);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-3.0)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerPropertyBuilderExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerPropertyBuilderExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@iwhp I am not able to reproduce this--see my code below. Please post a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

```C#
public class Blog
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly ILoggerFactory Logger = LoggerFactory.Create(x => x.AddConsole());
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>().Property(e => e.Id).UseIdentityColumn(1001, 1);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog());
            
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            Console.WriteLine(context.Set<Blog>().First().Id);
        }
}
```

**Comment by iwhp** [comment]
Thankx @ajcvickers ! I have used your sample and it works just fine. I have played around in my code and it is working now as well!
