### ISSUE TITLE
"Download PDF" link returns 404

### ISSUE THREAD

**Issue by dzsoundnirvana** [aspnet/EntityFramework.Docs#1912]
When the "Download PDF" link on the bottom left is clicked, a 404 page is returned. The link resolves to: https://docs.microsoft.com/en-us/dotnet/opbuildpdf/ef_full_dotnet_toc/api/dotnet-template/_splitted/System.Data.Entity/toc.pdf?branch=live&view=entity-framework-6.2.0

![EFDocsDownloadPDF](https://user-images.githubusercontent.com/3346180/68535629-7e2e4180-0302-11ea-91d2-84755ea954db.PNG)

![DownloadPDF404ErrorEFDocs](https://user-images.githubusercontent.com/3346180/68535616-31e30180-0302-11ea-890a-c639ca2b214b.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e689b56a-27e6-b91c-e8a5-1d351ed88506
* Version Independent ID: c8d2a8a8-f178-ae07-996c-f514f23404ee
* Content: [EntityState Enum (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.entitystate?view=entity-framework-6.2.0)
* Content Source: [EF/xml/System.Data.Entity/EntityState.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/EntityState.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@mairaw Any ideas on this?

**Comment by ajcvickers** [comment]
@smitpatel to transfer issue.

**Comment by smitpatel** [comment]
Fixed.

**Comment by mairaw** [comment]
One thing that was brought to my attention is that now the link doesn't 404 anymore but the file only contains the TOC. We should follow up with engineering on that.
