### ISSUE TITLE
Database schema issues

### ISSUE THREAD

**Issue by karenpayneoregon** [aspnet/EntityFramework.Docs#1931]
[Improvement.txt](https://github.com/aspnet/EntityFramework.Docs/files/3855957/Improvement.txt)

I want to point these issues out to improve user experience  
(https://github.com/aspnet/EntityFramework.Docs/files/3855956/Improvement.txt)
Upon examining the database schema there appears to be several design issues. For instance, in the OnsideCourse table the field "Days" contains (which it seems like) a one character code for day of the week e.g. M is Monday, F is Friday while H seems to be Thursday.  Would be a better design to normalize this table as presently one pulling up a SELECT needs to closely examine the data while in a Visual Studio project needs to dissect the chars and form day names, when edited build a new string. By normalizing (which I have done) selecting data with two child table is easy to see what days a course is offered along with changing days the course is offered. The table OfficeAssignment has a Location field which doesn't make sense. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba1f3f2-8c1f-c913-dcfb-4c3332ef9c22
* Version Independent ID: 273274cb-72b7-1696-32eb-a5d2f7d6c0dd
* Content: [School Sample Database - EF6](https://docs.microsoft.com/en-us/ef/ef6/resources/school-database?source=docs)
* Content Source: [entity-framework/ef6/resources/school-database.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/resources/school-database.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
