### ISSUE TITLE
VS 2010

### ISSUE THREAD

**Issue by ChefSQL** [aspnet/EntityFramework.Docs#1932]
How about VS 2019. Not sure which 'model content' to select as 2019 is so much different than 2010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63be9b09-2dde-819c-72a9-874182a92113
* Version Independent ID: 0ef66141-904a-34b2-b2a1-b090c5d62339
* Content: [Database First - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first?redirectedfrom=MSDN#feedback)
* Content Source: [entity-framework/ef6/modeling/designer/workflows/database-first.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/designer/workflows/database-first.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by scottheckel** [comment]
I just did this in VS 2019. There is a step before where you select the Tables checkbox; otherwise, it's the same as what is on the page.
