### ISSUE TITLE
EF Core 3.x installation doesn't work

### ISSUE THREAD

**Issue by Leon99** [aspnet/EntityFramework.Docs#1948]
the very first step, `dotnet tool install --global dotnet-ef`, fails with 
```
error NU1202: Package dotnet-ef 3.0.1 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any. Package dotnet-ef 3.0.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
The tool package could not be restored.
```
If the tool requires .NET Core 2.1, it should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f21d6-6edc-7582-e0e2-fa1c9670bcc0
* Version Independent ID: b3dd8c84-18b1-f98d-64f1-7897d1482692
* Content: [EF Core tools reference (.NET CLI) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#using-the-tools)
* Content Source: [entity-framework/core/miscellaneous/cli/dotnet.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dotnet.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by smitpatel** [comment]
It is a bug in the product as tracked at https://github.com/aspnet/EntityFrameworkCore/issues/18977

**Comment by FrankSilano** [comment]
As a workaround downgrade your project from 3.0.1 EF Core packages to 3.0.0. Then install the EF 3.0.0 tools from the CLI if youdidn't already do it from the package manager. Then restart your project. This is the only thing that has worked for me so far. Good luck.
