### ISSUE TITLE
Blog.TenantId property is missing and will cause error

### ISSUE THREAD

**Issue by wswind** [aspnet/EntityFramework.Docs#1949]
modelBuilder.Entity<Blog>().Property<string>("TenantId").HasField("_tenantId");
will throw an error .

There is no property : Blog.TenantId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters#feedback)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @anpete
* Microsoft Alias: **avickers**

**Comment by VictorioBerra** [comment]
? Unless i am missing something TenantId is a shadow property and as such it is not defined for that entity type in the EF Core model.

https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties

**Comment by wswind** [comment]
Yes, the sample is fine.
