### ISSUE TITLE
Migrations limitations question

### ISSUE THREAD

**Issue by doggy8088** [aspnet/EntityFramework.Docs#1960]
For the **Migrations limitations** section, does these limitations **temporary** unavailable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc4d900-28a8-9c04-2443-7407f15a684f
* Version Independent ID: 545bb0b5-f15b-584e-cef7-7283a0e0729f
* Content: [SQLite Database Provider - Limitations - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations)
* Content Source: [entity-framework/core/providers/sqlite/limitations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sqlite/limitations.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@doggy8088 Depends what you mean by "temporary". These things are not currently supported, but some of them may be supported in future versions.
