### ISSUE TITLE
Data annotation

### ISSUE THREAD

**Issue by RemiGri** [aspnet/EntityFramework.Docs#1964]
It says that Data Annotations cannot be used to specify a key, but what about [Key] data annotation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a38fe8f-c674-0673-a13f-b87a7a9edf78
* Version Independent ID: fad97301-bb2b-f974-bf1c-c80c9d143b3d
* Content: [Primary Keys - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/primary-keys#feedback)
* Content Source: [entity-framework/core/modeling/relational/primary-keys.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/primary-keys.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
> No relational database specific aspects of a primary key can be configured using Data Annotations.

Only relational aspects cannot be specified. KeyAttribute can be used to configure a key but you cannot specify a name for it using annotation.
