### ISSUE TITLE
.netStandard version. 2.1 or 2.0?

### ISSUE THREAD

**Issue by JesperNoerregaard** [aspnet/EntityFramework.Docs#1966]
Isn't it true that EFCore3.0 is .netstandard2.1 while EFCore3.1 is .netstandard2.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5747ad3-edd5-1977-883c-2cf77112306c
* Version Independent ID: d66d0616-2aa2-8be4-5ab6-24201ef00b59
* Content: [Installing Entity Framework Core - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/install/)
* Content Source: [entity-framework/core/get-started/install/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/install/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Yes, this is correct.
