### ISSUE TITLE
What they forgot to tell you !!

### ISSUE THREAD

**Issue by JanWijninckx** [aspnet/EntityFramework.Docs#1969]
The tutorial above is incomplete. If you run the application you still get that message "no such table: Blogs" even though you added that fix! 
There are two key steps missing:
Before you run it you must first create the database.
Do this from the package manager:
PM&gt; add-migration CreateBlogDB   
notice the code it generate under the project; "CreateBlogDB" is the name you gave to this migration. Now you need to update the DB with that code:
PM&gt; update-database –verbose
Bingo, now the database is created! and you can compile and run the program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/index?tabs=visual-studio)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
That's in the instructions:

```
Install-Package Microsoft.EntityFrameworkCore.Tools
Add-Migration InitialCreate
Update-Database
```

**Comment by JanWijninckx** [comment]
I have no idea where you find that. Do a search on the page with ctrl+F and you’ll only find “add-migration” in my post

I got mightily stuck on this example and it took a day before I found it on another site. 

Surely we would like this tutorial to work? At present it doesn’t.  

Rule #1 in review, is that comments are always valid, and if it helps the understanding then just add it.  Even if the statements were there, it would be good to have my comment added that the error message does not necessarily mean what it says.

**Comment by ErikEJ** [comment]
Enable the Visual Studio "Tab"!

![image](https://user-images.githubusercontent.com/4169187/70386154-59c39480-1996-11ea-978f-19afd1ba7955.png)

**Comment by ErikEJ** [comment]
"no such table: Blogs" is a unclear SQLite error message, not an EF Core message

**Comment by ErikEJ** [comment]
"no such table: Blogs" is a unclear SQLite error message, not an EF Core message

**Comment by JanWijninckx** [comment]
Indeed; But if a novice like me didn't pick up on the two steps for execution in the package manager, then if one compiles and runs, the run time message is "no such table: Blogs". I assumed that the EF core code would be compiled and executed as part of the executable.
