### ISSUE TITLE
Dependency Injection and Singleton Pattern with Cosmos Provider

### ISSUE THREAD

**Issue by thisisbrianstewart** [aspnet/EntityFramework.Docs#1974]
Is there guidance on how to use EF Core Cosmos provider with Dependency Injection?  Does the cosmos DbContext use the singleton pattern?  

Of particular interest is around ensuring singleton pattern and the overarching best practice from the Cosmos docs to use a single static client for the lifetime of web apps.  My use-case is to use the EF Core Cosmos provider in an Azure Function, and as such, since both Functions and Cosmos docs strongly advise static clients, I am curious how to properly use DI with the Cosmos provider to ensure a single static client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738deb7b-d752-f628-3860-fe53891cadb0
* Version Independent ID: e0a18db9-d605-2a78-b77a-d22375dcfd4e
* Content: [Azure Cosmos DB Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/cosmos/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/cosmos/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
CosmosClient is registered as a singleton in the internal service provider used by EF. You can access it by calling `context.Database.GetCosmosClient()` see https://docs.microsoft.com/en-us/ef/core/providers/cosmos/unstructured-data#using-cosmosclient

If you need to be able to access CosmosClient without going through an EF context let me know.

**Comment by thisisbrianstewart** [comment]
Great!  In this case, I won't need to access the CosmosClient, but I did see the docs that show how to obtain a ref to it:   `context.Database.GetCosmosClient();`

Thanks for the info @AndriySvyryd -- closing this out as answered.
