### ISSUE TITLE
This needs to be updated for EF Core 3.1

### ISSUE THREAD

**Issue by xantari** [aspnet/EntityFramework.Docs#1982]
EF Core 3.1 was recently released and all this documentation needs to be updated for EF Core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ec70a8-5402-78da-2a4d-c3d2c1e59f97
* Version Independent ID: da449417-8152-ce2d-4aec-fbd9b692e432
* Content: [What's new - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/#feedback)
* Content Source: [entity-framework/core/what-is-new/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by paolofulgoni** [comment]
The reintroduced support for .NET Standard 2.0 in EF Core 3.1 is such a big change for those using .Net Framework, please highlight this in the docs

**Comment by lebartha** [comment]
When will this be updated? It should have been done on day one when 3.1 was released :(

**Comment by smitpatel** [comment]
Will be updated on Jan 8 (tomorrow)

**Comment by lebartha** [comment]
It's Jan 9, and nothing changed.

**Comment by lebartha** [comment]
Is it Jan 8 2021?

**Comment by ajcvickers** [comment]
Fixed by #2050
