### ISSUE TITLE
How to switch this page to EF Core 2.1?

### ISSUE THREAD

**Issue by doggy8088** [aspnet/EntityFramework.Docs#1987]
How to switch this page to EF Core 2.1 version? I need to reference some code sample for my EF Core 2.1 app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc10f39-8fe5-e856-5839-9aa5e9d435c6
* Version Independent ID: 10ddba97-42d2-0cda-3e7f-eaeb4fda74b0
* Content: [Keyless Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types)
* Content Source: [entity-framework/core/modeling/keyless-entity-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/keyless-entity-types.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
Due to lack of resources we don't maintain documentation for old versions, but you can see it in GitHub history: https://github.com/aspnet/EntityFramework.Docs/blob/29daa818215d63060417ca1b3047bffcd874137e/entity-framework/core/modeling/query-types.md
