### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by ghost** [aspnet/EntityFramework.Docs#1991]
This is not telling me much.  Do I have to download the sample, study the code to understand these MS SQL topics?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef8271d-8d22-fb0c-240d-0ff9c97d38b3
* Version Independent ID: af433371-e282-4b89-7b09-6caf43af83e0
* Content: [Microsoft SQL Server Database Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/?tabs=dotnet-core-cli#feedback)
* Content Source: [entity-framework/core/providers/sql-server/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sql-server/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
This section just explains topic specific to Microsoft SQL Server EF Core database provider.
Are you looking for [general EF Core documentation](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli) or [SQL Server documentation](https://docs.microsoft.com/en-us/sql/sql-server/?view=sql-server-ver15)?
