### ISSUE TITLE
Conceptual confusion between Aggregates and Owned Entities

### ISSUE THREAD

**Issue by mvelosop** [aspnet/EntityFramework.Docs#1998]
Hi,

The second paragraph states that:
&gt; Owned entities... ... are conceptually similar to aggregates.

But... Owned entities are the way to implement Value Objects, because they don't have an identity of their own, while Aggregates do have an identity, as a part of their key fundamentals.

So they're actually completely different, by large.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment]
@mvelosop This is basically true--see https://github.com/aspnet/EntityFrameworkCore/issues/17836#issuecomment-565786234
