### ISSUE TITLE
Add EFCore.TimeTraveler to the list of EF Core Extensions

### ISSUE THREAD

**Issue by bbrandt** [aspnet/EntityFramework.Docs#2000]
I would like to add [EFCore.TimeTraveler](https://github.com/VantageSoftware/EFCore.TimeTraveler) to the list of EF Core Extensions as well as expand on differences between EFCore.TimeTraveler and EfCoreTemporalTable.

**Comment by ajcvickers** [comment]
@bbrandt Send a PR and we;ll take a look.

**Comment by bbrandt** [comment]
Thanks @ajcvickers !  PR is #2001
