### ISSUE TITLE
Adding records to tables with data

### ISSUE THREAD

**Issue by sergtk** [aspnet/EntityFramework.Docs#2008]
I need to create a migration. It adds some columns to tables, no problems with this.

But I also need to add records as seed data to the tables which already contains data. The issue is that I can't add records with a fixed Id, they may be already used.

How to add seed data in such a case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding?source=docs)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
@sergtk What type is your id column? If it's `int` you can use a negative value. Otherwise you'll have to add the data through the context normally and once the id is known add it to the model and then edit the migration to remove the inserts.

**Comment by sergtk** [comment]
I use the following definition for the entity property in C#:

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

To use negative `int`-s for id is like a hack, but I am looking for a clean approach. I mean autogenerated value for keys as usual.

> once the id is known add it to the model and then edit the migration to remove the inserts.

Ids are never known during development. This is because I test on test db, but in production can be anything else.
Note, this is a quite usual use case, so that is why I ask if there is something suitable in EF Core I missed.

AFAIK you provide me to hardcode ids in migrations?
If so, this is not a solution I am looking for.

Thank you.
