### ISSUE TITLE
Reinsert EF Core usage in UWP projects into documentation

### ISSUE THREAD

**Issue by CeciAc** [aspnet/EntityFramework.Docs#2012]
Hi team, 
I moved this from here: https://github.com/aspnet/EntityFramework.Docs.pt-br/issues/18

The comments below were machine-translated.

@joaosantana commented 6 hours ago 
By adapting the steps described in a solution with a UWP project and a .NET Standard project to the program logic, by running `Add-Migration InitialMigrate` you receive the following error message:
`Startup project 'Recibos' is a Universal Windows Platform app. This version of the Entity Framework Core Package Manager Console Tools doesn't support this type of project. For more information on using the EF Core Tools with UWP projects, see https://go.microsoft.com/fwlink/?linkid=858496`

The referenced page is the same, without any information on how to use EF Core tools with UWP projects. as the error message tells you.

Changing the startup project to the .NET Standard project and running the same command returns the following error message:
`Startup project 'Recibos.Core' targets framework '.NETStandard'. There is no runtime associated with this framework, and projects targeting it cannot be executed directly. To use the Entity Framework Core Package Manager Console Tools with this project, add an executable project targeting .NET Framework or .NET Core that references this project, and set it as the startup project; or, update this project to cross-target .NET Framework or .NET Core. For more information on using the EF Core Tools with .NET Standard projects, see https://go.microsoft.com/fwlink/?linkid=2034705`

This time, the referenced link has sensitive information about the problem, which is the absence of a console project whose function is to be used to run the tools. This scheme was described at https://docs.microsoft.com/ef/core/get-started/uwp/getting-started, which today returns to this page, which in turn does not have any information about using SQLite in UWP applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/index?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by hitchcockdev** [comment]
I'm also experiencing this issue with UWP apps and Entity Framework Core.

**Comment by joaosantana** [comment]
The previous page is here https://web.archive.org/web/20190305215707/https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started

**Comment by ajcvickers** [comment]
See https://docs.microsoft.com/en-us/ef/core/platforms/#universal-windows-platform and also #1838

**Comment by joaosantana** [comment]
> See https://docs.microsoft.com/en-us/ef/core/platforms/#universal-windows-platform and also #1838

I had read this articlhe. I'm using EF Core 3.0 and Microsoft.NETCore.UniversalWindowsPlatform 6.2.0 already. Not working. I saw the Issue #1838 too. As I stated in my original Issue (https://github.com/aspnet/EntityFramework.Docs.pt-br/issues/18), I'm following the steps described in https://docs.microsoft.com/sv-se/ef/core/get-started/?tabs=netcore-cli and these steps are not working. Unfortunately.

**Comment by e-leoni** [comment]
@joaosantana you saved my life.
I was unable to find the original post, and now it works.
Thank you very much for your search!

**Comment by joaosantana** [comment]
> @joaosantana you saved my life.
> I was unable to find the original post, and now it works.
> Thank you very much for your search!

Always a pleasure to be useful to a fellow developer.

**Comment by iUnknwn** [comment]
@ajcvickers You marked this as closed-duplicate, however the [original issue referenced in the Portuguese docs](https://github.com/dotnet/EntityFramework.Docs.pt-br/issues/18#issuecomment-569740713) closed their version of the bug, and made this as the primary. Is this issue tracked on another bug?

Also, issue #1838 that you referenced seems to be more about usage within the UWP sandbox (what paths should be used for sqlite), rather than this issue, which specifically has to do with inability to do migrations (and the need to for a .NET Core project do run migrations). As joaosantana linked, a previous version of the Microsoft EF docs included this workaround, but the current ones are missing it. 

@joaosantana Thank you for the link.

**Comment by ajcvickers** [comment]
@iUnknwn We're tracking this holistically with other related things in #1838.

**Comment by suchja** [comment]
@ajcvickers Thanks for taking care of this. However (at least in my opinion) neither https://docs.microsoft.com/en-us/ef/core/platforms/#universal-windows-platform nor #1838 address this issue. A friend of mine called me for help and spend 15 hours on this issue. After finding this issue, a simple change in the documentation could have avoided that.
