### ISSUE TITLE
Update table to reflect 3.1 support for 2.0

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework.Docs#2014]
Currently the table shows 3.x is compatible with 2.1. And you made that awesmoe change to 3.1 so that it supports .NET Standard 2.0. I thought about just creating a PR but not sure about formatting....a separate column for 3.0 and another for 3.1+? But then 3.0 is not LTS anyway...so .... ¯\_(ツ)_/¯. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7cee01-ae77-571c-5517-8037428a2277
* Version Independent ID: 832b8636-b005-c397-dbb4-0ad7f9c0b43d
* Content: [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/platforms/#feedback)
* Content Source: [entity-framework/core/platforms/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/platforms/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ErikEJ** [comment]
Looks like it is already fixed, and ready to be merged; https://github.com/aspnet/EntityFramework.Docs/pull/1980

**Comment by julielerman** [comment]
Thanks. I did look but didn't look hard enough I guess . :)
