### ISSUE TITLE
Need to show Database First procedure - using the Wizard and by  hand.

### ISSUE THREAD

**Issue by edhansen** [aspnet/EntityFramework.Docs#2029]
You need to show how to use EF Core when you already have the database and tables established, using the Wizard AND by hand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Getting Started - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@edhansen Which wizard are you referring to and what do you mean specifically when you say, "by hand"? Do you mean without any tooling at all?

**Comment by edhansen** [comment]
[cid:image001.png@01D5C47D.28D1ECA0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by edhansen** [comment]
Here it is…

[cid:image001.png@01D5C47E.63988140]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Rick-Anderson** [comment]
@edhansen you can't email images, you need to paste them in at this GitHub issue.

**Comment by shadinamrouti** [comment]
@edhansen, what you need is to read about db scaffolding.
For example, Running the following command in the Package Manager Console, would create the DB context from the model:

Scaffold-DbContext "Server=.\sqlexpress;Database=DatabaseName;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -Force

Note: You may need to install the following first on the same Console:

Install-Package Microsoft.EntityFrameworkCore.Tools 
Install-Package Microsoft.EntityFrameworkCore.Design
install-package Microsoft.EntityFrameworkCore.SqlServer

**Comment by edhansen** [comment]
Thanks for getting back to me on this.  I appreciate it.
