### ISSUE TITLE
This page?

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework.Docs#2030]
Self-explanatory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d812cf-79c0-ad23-e2d6-0f56d8c7c4dc
* Version Independent ID: eb5b040a-d1f0-9423-16ab-2714a258509c
* Content: [Relational Database Modeling - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/index)
* Content Source: [entity-framework/core/modeling/relational/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@smitpatel to "deploy live."
