### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by hamayobe** [aspnet/EntityFramework.Docs#2033]
In paragraph "Using nullable reference types is recommended since it flows the nullability expressed in C# code to EF Core's model and to the database, and obviates the use of the Fluent API or Data Annotations to express the same concept twice.", I think 'flows' should be 'follows'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4381838-81bb-52c6-d921-f8b9ae8163d2
* Version Independent ID: 892a8dd8-7a63-ce0b-de20-27e92b88f971
* Content: [Entity Properties - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#feedback)
* Content Source: [entity-framework/core/modeling/entity-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/entity-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
"flows" is intentional: the C# code nullability is *flowed* to the EF Core model, and from there to the database, much like information can flow.
