### ISSUE TITLE
Option 2 won't work for anything but this simple scenario.

### ISSUE THREAD

**Issue by cjmairair** [aspnet/EntityFramework.Docs#2035]
Imagine pulling in (syncing) multiple migrations from other code branches. When you go to re-scaffold the metadata of these (or just the first of these) "foreign" migrations, the metadata for these "intermediate" migrations will change to what it should be for the final migration.'

And another problem with Option #2. In step #1, you generate that "placeholder" migration. This should eventually be the last migration applied which has the current model's metadata. But instead, you apply the current model's metadata to the migration before this one.

This is even true for Option #1. You can't get the metadata right for these "intermediate foreign" migrations.

Another thing... Because of this, if you need to rollback some migrations (in some code branch) later, how are you going to do that, when the metadata for many of your migrations is wrong?

I don't see any way to correctly manage migrations with code branches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b72ecde8-e983-8583-7c3f-6e0e4ff404fb
* Version Independent ID: 6ed79d63-19a7-c527-b383-c5faf4beba55
* Content: [Code First Migrations in Team Environments - EF6](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/teams#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/teams.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/modeling/code-first/migrations/teams.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
