### ISSUE TITLE
Provide more details on customizing the Migrations history table

### ISSUE THREAD

**Issue by mjehle82** [aspnet/EntityFramework.Docs#2037]
Hello

Pleas add an example on how to use the MigrationsHistoryTable Method in .NET Core. 
Preferably not only with SQL Database (we are using PostgreSQL).

This would be greatly appreciated.

Kind regards, Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390f9258-6f7c-dbe8-3e79-c83446ba6192
* Version Independent ID: 38896138-0566-d481-2c91-8158f6d8f274
* Content: [Custom Migrations History Table - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/history-table.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/history-table.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@mjehle82 Can you give some more details of what you mean by "use the MigrationsHistoryTable"? Use in what way?

**Comment by mjehle82** [comment]
I would like to have the MigrationsHistoryTable in a specific database schema.
As I am using PostgreSQL, currently the Table is placed in the public schema.

I am referring to this part of the page: "You can change the schema and table name using the MigrationsHistoryTable() method in OnConfiguring() (or ConfigureServices() on ASP.NET Core). Here is an example using the SQL Server EF Core provider."

There is only an example for the usage in the OnConfiguringMethod. An example for the usage in ConfigureServices would be appreciated, since I am using ASP.NET Core.

Additionally, it would be great, to have this documented not only for SQL Server but also for other database providers such as PostgreSQL.

Kind regards, Mike

**Comment by bricelam** [comment]
```csharp
services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(
        Configuration.GetConnectionString("DefaultConnection"),
        x => x.MigrationsHistoryTable("__MyMigrationsHistory", "not-public")));
```
