### ISSUE TITLE
Trouble deriving new DbContext

### ISSUE THREAD

**Issue by derth** [aspnet/EntityFramework.Docs#2038]
I want to derive a new dbcontext, in order to use multiple migration sets.
I use the following code from the 'Two migration sets' sample code above:
----------------------------------------------

```C#
    public class MariaDBDbContext : ApplicationDbContext
    {
        public MariaDBDbContext(DbContextOptions<MariaDBDbContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite("Data Source=my.db");
    }
```
----------------------------------------------
If i don't use the constructor, i get an error about not supplying the 'options' constructor param, and if use it, i get an error about not being able to convert it.

Please provide the correct code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b011c7a-3534-78e3-b491-addd96fb5ba1
* Version Independent ID: 371826c5-3ef2-4eef-32e9-d55c777cd9d3
* Content: [Migrations with Multiple Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=vs#feedback)
* Content Source: [entity-framework/core/managing-schemas/migrations/providers.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/providers.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@derth There's nothing obviously wrong in the code you're posting. Please post a small project that reproduces the error you are seeing so that we can investigate.

**Comment by derth** [comment]
Just create a new project with auth (to include a dbcontext). Try to add a new dbcontext like the docs say.

It can't convert from:
DbContextOptions<MySqliteDbContext> options
to:
DbContextOptions<ApplicationDbContext> options

error:
------
Error	CS1503	Argument 1: cannot convert from 'Microsoft.EntityFrameworkCore.DbContextOptions<WebApplication2.Data.MySqliteDbContext>' to 'Microsoft.EntityFrameworkCore.DbContextOptions<WebApplication2.Data.ApplicationDbContext>'

**Comment by ajcvickers** [comment]
@derth See #594. What does your `ApplicationDbContext` class look like? It should have a protected constructor that takes a non-generic `DbContextOptions` parameter. This is the constructor that should be called from the public constructor of your class.

**Comment by derth** [comment]
Thank you for your answer but I'll wait for the [#594](https://github.com/aspnet/EntityFramework.Docs/issues/594) issue to be resolved and use the official code.

Until then i managed to solve my problem, by simply using a different migrations folder for each db and excluding from the project the ones not currently used.
