### ISSUE TITLE
The example does not work.

### ISSUE THREAD

**Issue by CeciAc** [aspnet/EntityFramework.Docs#2043]
This comment was machine-translated

@Metalstyle commented on [Thu Jan 09 2020](https://github.com/aspnet/EntityFramework.Docs.ru-ru/issues/16)

Does not work. Video link

https://youtu.be/VXtL_rY4Gv8

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Начало работы — EF Core](https://docs.microsoft.com/ru-ru/ef/core/get-started/index?tabs=netcore-cli)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

---

@srvbpigh commented on [Thu Jan 09 2020](https://github.com/aspnet/EntityFramework.Docs.ru-ru/issues/16#issuecomment-572811343)

Hello, @Metalstyle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The tutorial work. It has 20K PV/month.  Will reopen if you provide information on what specifically does not work.

**Comment by Metalstyle** [comment]
Video your staff can 't watch? Ok. Np. Gl.
