### ISSUE TITLE
Is case with 2+ splitted entities supported? 

### ISSUE THREAD

**Issue by norvegec** [aspnet/EntityFramework.Docs#2048]
Does EF support table splitting with multiple 1-to-1 properties, e.g. 
```csharp
public class Customer {
    // ...
    public Address HomeAddress { get; set; } 
    public Address OfficeAddress { get; set; } 
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c847da37-ca7d-1c42-8acf-405167085d27
* Version Independent ID: bd4fe1c7-514d-cfb1-d975-4096306b06e9
* Content: [Table Splitting - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting)
* Content Source: [entity-framework/core/modeling/table-splitting.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/table-splitting.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment]
@norvegec Yes.

**Comment by norvegec** [comment]
Could you please point me to an example? I've been struggled to find a correct fluent/attributive setup in such case.

**Comment by AndriySvyryd** [comment]
https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#sharing-the-same-net-type-among-multiple-owned-types
