### ISSUE TITLE
Not enough information

### ISSUE THREAD

**Issue by Leon99** [aspnet/EntityFramework.Docs#2056]
Given that this page is meant to be an entry point for anyone looking to use this provider, I reckon it should, at the very least, mention how to use in-memory mode and reference a page that describes using SQLite for testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102ba5fa-9b7a-2d9d-06aa-9c5208605ee5
* Version Independent ID: 55c2150e-2afa-0dca-0db6-9a5105312e73
* Content: [SQLite Database Provider - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/?tabs=dotnet-core-cli)
* Content Source: [entity-framework/core/providers/sqlite/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sqlite/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
Covered by #934

**Comment by JGregoryAtiba** [comment]
I think this is the link everyone's looking for:  https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli
