### ISSUE TITLE
Wrong target framework is listed for 3.1

### ISSUE THREAD

**Issue by BalassaMarton** [aspnet/EntityFramework.Docs#2058]
.NET Standard 2.0 is listed as target framework for EF Core 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05ec70a8-5402-78da-2a4d-c3d2c1e59f97
* Version Independent ID: da449417-8152-ce2d-4aec-fbd9b692e432
* Content: [EF Core releases and planning](https://docs.microsoft.com/en-us/ef/core/what-is-new/index)
* Content Source: [entity-framework/core/what-is-new/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@BalassaMarton That's correct. Curious why you think it's wrong.

**Comment by BalassaMarton** [comment]
My bad, it seemed too good to be true to step backwards in dependencies 🙂
