### ISSUE TITLE
Are these issues fixed in .Net Core 3.1?

### ISSUE THREAD

**Issue by vedeevi** [aspnet/EntityFramework.Docs#2061]
Please let us know are these issues are fixed in .NET Core 3.1 which was GA in Dec-2019.... OR Still we need to work with stabilized .NET Core 2.0 versions.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4d0e044-b0cb-21e2-19c1-2f137da671ac
* Version Independent ID: 1cbedd95-8640-1649-9967-d0ef71633534
* Content: [Breaking changes in EF Core 3.0 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#feedback)
* Content Source: [entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@vedeevi These are not issues to be fixed. These are intentional changes that, to the best of our ability,  move the project forward and make it better.
