### ISSUE TITLE
DbContext.Add() assigns related entities

### ISSUE THREAD

**Issue by ihorbond** [aspnet/EntityFramework.Docs#2062]
Is it normal behavior for EF to pull related entities when adding entity to context by calling .Add() and then .SaveChanges() ? 
```C#
public class Foo2 {}

public class Foo {
    public int id {get; set;}
    public int foo2Id {get; set;}
    public virtual Foo2 foo2 {get;set;}
}

var foo = new Foo {
    id = 1,
    foo2Id = 1
}

_dbContext.Set<Foo>().Add(foo);
_dbContext.SaveChanges();
````

Result: foo object now also has its prop2 populated with Foo2 entity that is related to Foo via FK. Is this the expected behavior ? I've set the LazyLoadingEnabled to false for this _dbContext

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db8f8c4-6cd1-0569-e1e6-7c7c3718ab88
* Version Independent ID: e6a01804-8d33-d4f5-a77c-07c560b6f924
* Content: [DbSet&lt;TEntity&gt;.Add(TEntity) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.add?view=efcore-3.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbSet`1.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@ihorbond Not expected. Please attach a small, runnable project/solution or post a complete code listing that reproduces this so that we can investigate.

**Comment by ihorbond** [comment]
@ajcvickers after more testing I realized this only happens if I loaded the related entity before. so going with example above I first loaded Foo2, then created new Foo object and assigned its foo2Id property to the loaded Foo2 primary key/Id. Guess this is normal ? Here is small example 
https://github.com/ihorbond/EF-demo thanks

**Comment by ajcvickers** [comment]
@ihorbond Nothing is being loaded here. EF is just setting the navigation properties correctly for the two related tracked entities.

```C#
 // `Find` starts tracking the Address entity with ID 1
 var address = ctx.Set<Address>().Find(1);

 var id = new Random().Next(10, 4000);
 newUser = new User()
 {
     Id = id,
     Name = $"user{id}",
     // This tells EF that the new User is associated with the Address with ID 1
     AddressId = address.Id
 };

 // This starts tracking the newUser.
 // EF sees that it is related to the already tracked Address with ID 1 and sets the navigation properties appropriately.
 ctx.Set<User>().Add(newUser);

 ctx.SaveChanges();
 Console.WriteLine(newUser.Address == null);
```
