### ISSUE TITLE
ForSqlServerInclude is not obsolete in 2.2

### ISSUE THREAD

**Issue by thegeekyglass** [aspnet/EntityFramework.Docs#2067]
Documentation is wrong ForSqlServerInclude is not obsolete in 2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 920f20f6-a1b8-af5b-b83f-319e3d99147b
* Version Independent ID: 3cd8ab2e-3f12-e740-3a35-9ac4039351ed
* Content: [SqlServerIndexBuilderExtensions.ForSqlServerInclude Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverindexbuilderextensions.forsqlserverinclude?view=efcore-2.2#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerIndexBuilderExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerIndexBuilderExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@thegeekyglass The transition from one set of docs to per-version docs happened part way through the 2.x release cycle. Some of the 2.2 docs are not completely correct because of this. However, given that 2.2 is now out-of-support we're not going to fix this.
