### ISSUE TITLE
CosmosDB - Is SaveChanges transactional?

### ISSUE THREAD

**Issue by florianeidner** [aspnet/EntityFramework.Docs#2069]
"For most database providers, SaveChanges is transactional. This means all the operations will either succeed or fail and the operations will never be left partially applied."
- Does this apply for CosmosDB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f8db8b-8ee6-86c9-7cb2-b5802214ec13
* Version Independent ID: b959839c-684e-5d60-650e-0af17c971c79
* Content: [Basic Save - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/basic#feedback)
* Content Source: [entity-framework/core/saving/basic.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/basic.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by AndriySvyryd** [comment]
> Does this apply for CosmosDB?

No. As mentioned [here](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/limitations#azure-cosmos-db-limitations) Cosmos doesn't support client-initiated transactions
