### ISSUE TITLE
reverting migration cli command is missing parameter -Target

### ISSUE THREAD

**Issue by Crare** [aspnet/EntityFramework.Docs#2073]
"Update-Database LastGoodMigration" - Doesn't work. 
It needs parameter "-Target" before migration's name, example: 
"Update-Database -Target LastGoodMigration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=vs#revert-a-migration)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
It looks like you're using EF6, not Core. It's documentation is here: https://docs.microsoft.com/ef/ef6/modeling/code-first/migrations/
