### ISSUE TITLE
HasComputedColumnSql is not available for EntityTypeBuilder<T>

### ISSUE THREAD

**Issue by AhmadKelany** [aspnet/EntityFramework.Docs#2087]
I use a separate configuration class for many models  to decrease the complexity of the dbContext, by implementing the IEntityTypeConfiguration&lt;T&gt; interface..

The EntityTypeBuilder&lt;T&gt; doesn't expose HasComputedColumnSql , so I added the code in the dbContext class.. 

Would it be possible to use it in the configuration class? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d622b2-1e4b-4d76-b3df-fefaa5ba99cb
* Version Independent ID: ec833af2-275e-981f-689f-8c65edfc00cd
* Content: [Generated Values - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/generated-properties.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/generated-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by ajcvickers** [comment]
@AhmadKelany This is configured for the property, not the entity type. Something like:
```C#
public class PersonConfiguration : IEntityTypeConfiguration<Person>
{
    public void Configure(EntityTypeBuilder<Person> builder)
    {
        builder
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("[LastName] + ', ' + [FirstName]");
    }
}
```
