### ISSUE TITLE
Issue with Entity Framework 6.4.0 when updating Windows Workflow Foundation project

### ISSUE THREAD

**Issue by EEaglehouse** [aspnet/EntityFramework.Docs#2089]
The NuGet package does not handle all project types correctly. I had a Windows Workflow (WF) project that was created for EF 6.1.4. When updating to 6.4.0, the changes in namespace broke the build and operation of the project. The components that were originally in the System.Data.Entity namespace (in System.Data assembly) were moved into System.Data.Entity.Core (in EntityFramework assembly). The automatic migration did not fix this.
I had to manually edit the project's .xaml file. I added xmlns:ef="clr-namespace:System.Data.Entity.Core;assembly=EntityFramework" to the list of namespaces and removed xmlns:sd="clr-namespace:System.Data;assembly=System.Data.Entity" (and renamed "sd1" to "sd" for System.Data). Then I had to find all classes that were moved into the new namespace and change the prefix from "sd:" to "ef:" so the project would be editable and compilable. In my case, it was the EntityException and EntityCommandExecutionException classes that were orphaned. It cost me the better part of my day to address these errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d5d89c-2648-4ce8-d5c3-4fb2371e6128
* Version Independent ID: 20e9f35b-8bb2-2bc0-c032-e4be1915997f
* Content: [Upgrading to Entity Framework 6 - EF6](https://docs.microsoft.com/en-us/ef/ef6/what-is-new/upgrading-to-ef6#feedback)
* Content Source: [entity-framework/ef6/what-is-new/upgrading-to-ef6.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/what-is-new/upgrading-to-ef6.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@EEaglehouse These are expected changes moving from EF5 to EF6.

**Comment by EEaglehouse** [comment]
I was moving from EF 6.1.4 to 6.4.0. Nothing in the "Upgrading to Entity Framework 6" guide told me to expect it would break my WF project. What did I miss?

**Comment by ajcvickers** [comment]
https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/what-is-new/upgrading-to-ef6.md#4-update-namespaces-for-any-core-ef-types-being-used
