### ISSUE TITLE
Please add detail about the effect of using this configuration

### ISSUE THREAD

**Issue by bbrandt** [aspnet/EntityFramework.Docs#2107]
When EF Core migrations is invoked this affects whether the key is created as clustered or nonclustered.

Does this also affect how queries are built against the DB or any other app run-time behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87caff3a-0ed3-8806-87a2-b9fd25f442a5
* Version Independent ID: 2fe216a5-17a4-f231-ff86-2710d702dcf8
* Content: [SqlServerKeyBuilderExtensions.IsClustered Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.sqlserverkeybuilderextensions.isclustered?view=efcore-3.1#Microsoft_EntityFrameworkCore_SqlServerKeyBuilderExtensions_IsClustered_Microsoft_EntityFrameworkCore_Metadata_Builders_KeyBuilder_System_Boolean_)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerKeyBuilderExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/SqlServerKeyBuilderExtensions.xml)
* Product: **entity-framework-core**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@bbrandt No, EF doesn't use this to do anything different outside of Migrations.
