### ISSUE TITLE
An Owned Entity is NOT similar to an Aggregate. It is similar to the Value-Object pattern

### ISSUE THREAD

**Issue by CESARDELATORRE** [aspnet/EntityFramework.Docs#2109]
It is wrong to say that Owned "they are conceptually similar to aggregates." as the article states at the begining.
An "Owned Entity" is NOT similar to an Aggregate. It is similar to the "Value-Object" pattern (although not exactly the same).
An Aggregate can contain multiple Value-Objects along with multiple fields.

Then, a link pointing to the Value-Object pattern should be added at the begining of the article, like this:
https://www.martinfowler.com/bliki/ValueObject.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities#feedback)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by AndriySvyryd** [comment]
@CESARDELATORRE Entities that own other entities are conceptually similar to aggregates. Value objects don't have an explicit identity and are usually compared using value equality, however owned entities have a primary key, that like in other entities can't be changed while it is being tracked.

Proper value object support is planned: https://github.com/dotnet/efcore/issues/9906
We also plan to make improvements to entities that own other entities to make them behave more like aggregates: https://github.com/dotnet/efcore/issues/1985
