### ISSUE TITLE
EF Core 3.1 .NET Framework dependency listed as 4.7.2, should be 4.6.1

### ISSUE THREAD

**Issue by mycroes** [aspnet/EntityFramework.Docs#2119]
EntityFramework Core 3.1 targets NetStandard 2.0, which is supported by .NET Framework 4.6.1 (as per https://docs.microsoft.com/en-us/dotnet/standard/net-standard). The same actually applies for EntityFramework Core 2.x, while only EntityFramework Core 3.0 targets NetStandard 2.1 (which is indeed not supported by any .NET Framework version as of now).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7cee01-ae77-571c-5517-8037428a2277
* Version Independent ID: 832b8636-b005-c397-dbb4-0ad7f9c0b43d
* Content: [Supported .NET implementations - EF Core](https://docs.microsoft.com/en-us/ef/core/platforms/#feedback)
* Content Source: [entity-framework/core/platforms/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/platforms/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@mycroes It doesn't really work on 4.6.1. See this footnote in the document you linked:

> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.
