### ISSUE TITLE
Unresolved dependencies in .NETCore Console Application

### ISSUE THREAD

**Issue by ManuLin** [aspnet/EntityFramework.Docs#220]
I'm currently putting some hands on .NETCore and EF Core, and recently ran into the following issue.
After trying out and following the sample (https://docs.efproject.net/en/latest/platforms/netcore/new-db-sqlite.html) step-by-step, I recieve the following error messages:

The dependency Microsoft.EntityFrameworkCore.Sqlite >= 1.0.0 could not be resolved.
The dependency Microsoft.EntityFrameworkCore.Design >= 1.0.0-preview2-final could not be resolved.

My project.json looks as follows (and as required according to the sample).

{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": {
      "version": "1.0.0-preview2-final",
      "type": "build" 
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final" 
  } 
}

I'm using the latest visual studio update (3) and .NETCore SDK. Any suggestions what I'm doing wrong?

Regards,

Manuel

**Comment by rowanmiller** [comment]
Can you post the full output from running `dotnet restore -v information`. My guess is that you don't have `https://api.nuget.org/v3/index.json` configured as a NuGet feed.

**Comment by ManuLin** [comment]
Thank's Rowan. The problem was not the I haven't configured the latest NuGet version, but instead an additional (local) NuGet feed was configured. That somehow messed the package restore up. Thank's for guiding me into the right direction.
