### ISSUE TITLE
Confused by "Which one is right for you"

### ISSUE THREAD

**Issue by bennedik** [aspnet/EntityFramework.Docs#226]
On https://docs.efproject.net/en/latest/efcore-vs-ef6/choosing.html you write:

> Applications that target .NET Core, such as Universal Windows Platform (UWP) and ASP.NET Core applications. These applications can not use EF6.x as it requires the Full .NET Framework (i.e. .NET Framework 4.5).

However, ASP.NET Core can target both .NET 4.5 as well as .NET Core.
So, this seems confusing.

I wonder if it is possible to actually use EF6 in an ASP.NET Core project targeting .NET 4.5?

**Comment by natemcmaster** [comment]
ASP.NET Core here is given as an example of an application model that uses .NET Core runtime. EF6 can be used in ASP.NET Core applications that target .NET Framework as this document demonstrates: ["Getting Started with ASP.NET Core and Entity Framework 6"](https://docs.asp.net/en/latest/data/entity-framework-6.html).

Feel free to continue discussion if you have more questions.
