### ISSUE TITLE
Beta 7 todos

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#23]
Update docs for beta 7 changes

 - [x] Fix up migration commands - https://github.com/aspnet/EntityFramework/pull/2723
 - [x] Mono 4.2.0 https://github.com/aspnet/EntityFramework/issues/2708

**Comment by natemcmaster** [comment]
- [ ] Mono 4.2.0 https://github.com/aspnet/EntityFramework/issues/2708

**Comment by smitpatel** [comment]
Include DataAnnotations ? aspnet/EntityFramework#107
