### ISSUE TITLE
ArgumentException on db.Database.Migrate()

### ISSUE THREAD

**Issue by hendraanggrian** [aspnet/EntityFramework.Docs#230]
After following this [fantastic step-by-step tutorial](https://docs.efproject.net/en/latest/platforms/uwp/getting-started.html#upgrade-microsoft-netcore-universalwindowsplatform), I'm getting `ArgumentException` on `db.Database.Migrate()` on `App.xaml.cs`.

```
public App()
{
            this.InitializeComponent();
            this.Suspending += OnSuspending;

            using (var db = new ItemContext())
            {
                db.Database.Migrate(); // this line causes error
            }
}
```

**Comment by divega** [comment]
In case this is a product bug, could you create an issue in the product repo (https://github.com/aspnet/EntityFramework/issues)? Please follow the issue template and include the repro code.

**Comment by hendraanggrian** [comment]
@divega I appreciate the quick reply. Sure, I'll post it there. Someone can close this now.
