### ISSUE TITLE
Adding a related entity: Code sample doesn't match docs

### ISSUE THREAD

**Issue by LayZeeDK** [aspnet/EntityFramework.Docs#249]
In Related Data: Adding a related entity, the code sample doesn't match the docs. Docs explain that a Post is inserted to the database, because it is assigned as a property to a Blog entity. However, that is not the case in the code sample.
<img width="562" alt="adding-a-related-entity" src="https://cloud.githubusercontent.com/assets/6364586/17816309/e2a8b02e-6638-11e6-91d9-bf1acd479c66.PNG">

**Comment by smitpatel** [comment]
@LayZeeDK - What is incorrect here?
`blog.Posts.Add(post);` indeed adds post to property of blog entity.

**Comment by LayZeeDK** [comment]
@smitpatel You are right. I must have read `blog.Posts.Add(post)` as `context.Posts.Add(post)`. Closing issue.
