### ISSUE TITLE
Removing relationships: Code sample doesn't match the docs

### ISSUE THREAD

**Issue by LayZeeDK** [aspnet/EntityFramework.Docs#250]
The Related Data: Removing relationships docs mention that the Post entity is removed because of cascade on delete. However, in the code sample the Post entity is deleted explicitly.
<img width="558" alt="removing-relationships" src="https://cloud.githubusercontent.com/assets/6364586/17820374/d265b090-664c-11e6-86a3-2e9b76526cba.PNG">

**Comment by smitpatel** [comment]
`blog.Posts.Remove(post)` deletes the post from collection navigation of blog. Since cascade delete is configured, the post will be removed.

**Comment by LayZeeDK** [comment]
@smitpatel Thank you for getting back to me. Again, I must have read `blog.Posts.Remove(post)` as `context.Posts.Remove(post)`. Closing issue.
