### ISSUE TITLE
in testing page 

### ISSUE THREAD

**Issue by arielcloud** [aspnet/EntityFramework.Docs#251]
the caution need to deleted or refactored once it says:

> In the next release after RC2,

and it seem to solved already

**Comment by smitpatel** [comment]
Which page?

**Comment by arielcloud** [comment]
https://docs.efproject.net/en/latest/miscellaneous/testing.html

**Comment by rowanmiller** [comment]
Fixed in 05a0b2f89340675c815b39ff1726554ceb9cc49d
