### ISSUE TITLE
Worked through this a few times, every time stuck with following error on create.cshtml and index.cshtml

### ISSUE THREAD

**Issue by lwschultz** [aspnet/EntityFramework.Docs#254]
Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'Models' does not exist in the namespace 'EFGetStarted.AspNetCore.ExistingDb' (are you missing an assembly reference?)   EFGetStarted.AspNetCore.ExistingDB..NETCoreApp,Version=v1.0 H:\Projects\EFGetStarted.AspNetCore.ExistingDB\src\EFGetStarted.AspNetCore.ExistingDB\Views\Blogs\Create.cshtml 1   Active

Please report bugs on Entity Framework Core to https://github.com/aspnet/EntityFramework

**Comment by rowanmiller** [comment]
Closing in favor of https://github.com/aspnet/EntityFramework.Docs/issues/338
