### ISSUE TITLE
"ASP.NET Core App to New DB" tutorial refers to missing "ef" command

### ISSUE THREAD

**Issue by MikeWasson** [aspnet/EntityFramework.Docs#257]
In the tutorial [ASP.NET Core Application to New Database](https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html), it says

> Locate the tools section and add the ef command as shown below

But the snippet doesn’t show an “ef” command – and I don’t see one in the [source file](https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/Platforms/AspNetCore/AspNetCore.NewDb/project.json).

**Comment by garfbradaz** [comment]
Same here, i was wondering this.

**Comment by tdykstra** [comment]
The highlighted line in the project.json code block is what adds the ef command.  See also the new ASP.NET Core / EF Core tutorial series on the ASP.NET site -- https://docs.asp.net/en/latest/data/ef-mvc/intro.html

**Comment by rowanmiller** [comment]
Closing in favor of https://github.com/aspnet/EntityFramework.Docs/issues/338
