### ISSUE TITLE
UWP.SQLite Issues

### ISSUE THREAD

**Issue by snehitv** [aspnet/EntityFramework.Docs#265]
I get the below error even on a vanilla UWP project when I try to setup and add migration to SQLite:

PM> Add-Migration MyFirstMigration 
Add-Migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"
At line:1 char:1
- Add-Migration MyFirstMigration
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
  - FullyQualifiedErrorId : FileLoadException,Add-Migration

**Comment by divega** [comment]
@snehitv see issue aspnet/EntityFramework/issues/6551 for a workaround. This should be fixed as part of https://github.com/aspnet/EntityFramework/issues/5471.

**Comment by snehitv** [comment]
I have tried that and now I end up with the below:

add-migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The 
located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"
At line:1 char:1
+ add-migration InitialMigration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : FileLoadException,Add-Migration
