### ISSUE TITLE
the IQueryable.Concat<> method is incorrect

### ISSUE THREAD

**Issue by simpleway2016** [aspnet/EntityFramework.Docs#274]
**EF version:1.0.1.0**

``` C#
var q1 = from m in db.Table1
                     select new
                     {
                         name = m.Name,
                     };
            var q2 = from m in db.Table2
                     select new
                     {
                         name = m.Name,
                     };
            q1 = q1.Concat(q2);
            var result = q1.ToArray();
```

I watch the sql string by ILogger, the sql string is not union two table, the dbconnection will excute two dbcommand for each table like this:
command 1:

``` SQL
SELECT "m"."Name"
FROM "Table1" AS "m"
```

command 2:

``` SQL
SELECT "m"."Name"
FROM "Table2" AS "m"
```

at EF 6.1 version, it's make a sql string like this:

``` SQL
(SELECT "m"."Name"
FROM "Table1" AS "m") union
(SELECT "m"."Name"
FROM "Table2" AS "m")
```

**Comment by rowanmiller** [comment]
This is by design. EF Core will often break queries up into multiple round trips. Obviously it depends on database latency, but in general this has produced better performance.
