### ISSUE TITLE
UWP.SQLITE, How can i set Posts Properties in Blog Model

### ISSUE THREAD

**Issue by chyccs** [aspnet/EntityFramework.Docs#278]
This issue tracker is for ***documentation***

For ***product*** issues, use https://github.com/aspnet/EntityFramework/issues

I am debugging uwp sample now.

why Posts Properties in Blog class is always null ??

Is it a problem or my mistake?

i did edit source code.

**Comment by smitpatel** [comment]
You need to include related data to have navigation properties populated. Read the article at https://docs.efproject.net/en/latest/querying/related-data.html

**Comment by chyccs** [comment]
thank you for your answer
i can find a  that lazy loading is not implemented
