### ISSUE TITLE
Possible to reuse DbContextOptions?

### ISSUE THREAD

**Issue by strohhut** [aspnet/EntityFramework.Docs#279]
The [docs](https://docs.efproject.net/en/latest/miscellaneous/configuring-dbcontext.html#configuring-dbcontextoptions) show creating a `DbContextOptions` right before the context. Is it necessary to do this before instantiating each context or can I reuse the options object (is it accessed read-only and is it thread-safe)?

Also the `BloggingContextFactory` code is invalid because it doesn't implement 

```
TContext Create([NotNull] DbContextFactoryOptions options);
```

**Comment by ajcvickers** [comment]
@strohhut DbContextOptions can be reused.
