### ISSUE TITLE
stub-icon

### ISSUE THREAD

**Issue by NoralK** [aspnet/EntityFramework.Docs#29]
I am getting this error when compiling the docs:
```
stub-topic.txt:1: ERROR: Invalid character code: U+1F527
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
stub-topic.txt:1: WARNING: Substitution definition "stub-icon" empty or invalid.
```
Is there fonts that need to be installed as well?

**Comment by rowanmiller** [comment]
There shouldn't be. Are you building on Windows... or a different OS?

**Comment by NoralK** [comment]
Windows - W2K12R2 with update 1
Python 2.7.10 (64-bit)
Sphinx 1.3.1

**Comment by natemcmaster** [comment]
+1  
I seem the same error on OS X, Python 2.7.0, Sphinx 1.3.1

**Comment by natemcmaster** [comment]
This is a regression bug in python 2.7.10. I tried 2.7.6 and it works just fine.

ref: http://sourceforge.net/p/docutils/mailman/docutils-users/?viewmonth=201308

**Comment by natemcmaster** [comment]
...and reopening. Still an issue on other platforms.

**Comment by rowanmiller** [comment]
I'm using phython 3.4.3. @natemcmaster do you think it is still a phython issue on OSX? Or something we need to fix.

**Comment by natemcmaster** [comment]
@rowanmiller  It's a Python issue. Using python 3 fixes the issue on OS X.
@NoralK  I got around the python2/3 issue by running docs in a virtualenv.

```
virtualenv -p /usr/local/bin/python3 venv
source venv/bin/activate
pip install sphinx sphinx_autobuild
```

**Comment by NoralK** [comment]
@natemcmaster  Please reopen this - I have tried to install Python v3.4.3 on three different flavours of clean installed Windows VMs and get the same thing:
```
C:\Docs\EntityFramework.Docs\docs>make html
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\sphinx-build.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "C:\Python34\lib\site-packages\sphinx\__init__.py", line 61, in build_mai
n
    from sphinx import cmdline
  File "C:\Python34\lib\site-packages\sphinx\cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\Python34\lib\site-packages\sphinx\application.py", line 37, in <modul
e>
    from sphinx.builders import BUILTIN_BUILDERS
  File "C:\Python34\lib\site-packages\sphinx\builders\__init__.py", line 23, in
<module>
    from sphinx.util import i18n, path_stabilize
  File "C:\Python34\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>

    from babel.messages.pofile import read_po
  File "C:\Python34\lib\site-packages\babel\messages\__init__.py", line 12, in <
module>
    from babel.messages.catalog import *
  File "C:\Python34\lib\site-packages\babel\messages\catalog.py", line 23, in <m
odule>
    from babel.dates import format_datetime
  File "C:\Python34\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Python34\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "C:\Python34\lib\site-packages\babel\localtime\__init__.py", line 21, in
<module>
    from babel.localtime._win32 import _get_localzone
  File "C:\Python34\lib\site-packages\babel\localtime\_win32.py", line 18, in <m
odule>
    tz_names = get_global('windows_zone_mapping')
  File "C:\Python34\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
```
I have no issues with Python v2.7.10.

@rowanmiller -  You said you were using v3.4.3 of Python.  What vers/edition/arch of Windows?

All VMs have been base OS / Python v3.4.3 x64, installed for all users and setting the environment variables, I then run:
```
pip install sphinx
pip install sphinx_rtd_theme
make html
```
Thank you for all the help.

**Comment by rowanmiller** [comment]
@NoralK Win 8.1 and Win10 for me (both x64)

Are you running English OS? I ask because the error seems to be rooted in [babel](https://pypi.python.org/pypi/Babel), which is used for internationalization 

This [StackOverflow question](http://stackoverflow.com/questions/31722210/typeerror-an-integer-is-required-got-type-str) suggests Babel doesn't support 3.4, though I haven't been able to find anything more official that states what versions are supported. It sounds like 3.3 is a supported version though.

**Comment by NoralK** [comment]
Thank you Nate @natemcmaster 

@rowanmiller Yes, I am running the English(en-us) versions of the OSs and so far this problem happens on Win7 x86/x64, Win2K8 x32/x64, W2K8R2, W2K12R2 with Update.  I have not had a chance to try Win 8.1 or Win10 since my organization does not utilize them as of yet but I can get the bits from my MSDN subscription and build a base VMs for each architecture type. 

I did not see the StackOverflow question you pointed out but based on the responders claim I have checked out babel's github page.  It turns out that they just released 2.0 of babel 5 days ago.  So I uninstalled babel 2.0 and tried version 1.3, the prior version, and low and behold it works now, at least on W2K12R2 with update.  I plan on opening a ticket with Sphinx about this issue so they are informed about this issue.  I never thought to check the automatically installed packages of Sphinx, but I am still learning after 25+ year in IT LOL

Python v2.7 does not seem to have this problem with babel 2.0 installed.  So here is what I had to do to get Sphinx working with Python v3.4:

Install Python v3.4 with "Add python.exe to Path" option selected
Open a command prompt, after installation completes
pip install Sphinx (NOTE that sphinx-rtd-theme-0.1.8 is included during this install so a separate pip install is not needed)
pip uninstall babel (had to type a y to confirm to remove babel)
pip install babel==1.3
change directory to where I want to compile some documentation
make html

I can now compile the html but it gives me new errors.  Here is the output as of the most current master branch:
```
E:\Projects\EntityFramework.Docs-master\docs>make html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 13 source files that are out of date
updating environment: 13 added, 0 changed, 0 removed
reading sources... [100%] providers/index
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:16: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\project.json' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:92: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\Model.cs' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:100: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\Model.cs' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:109: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\Model.cs' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:156: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\Program.cs' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:193: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\Program.cs' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:211: WARNING: Include file 'E:\\Projects\\EntityFramework.Docs-master\\docs\\getting-started\\x-plat\\x-plat\\sample\\src\\ConsoleApp\\Migrations\\20150729221913_MyFirstMigration.cs' not found or reading it failed
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\issues.rst:9: ERROR: Unknown target name: "workarounds".
looking for now-outdated files... none found
pickling environment... done
checking consistency... E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\guide.rst:: WARNING: document isn't included in any toctree
E:\Projects\EntityFramework.Docs-master\docs\getting-started\x-plat\issues.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] providers/index
generating indices... genindex
writing additional pages... search
copying images... [100%] getting-started\uwp/_static/list.png
copying static files... WARNING: html_static_path entry 'E:\\Projects\\EntityFramework.Docs-master\\docs\\_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 11 warnings.

Build finished. The HTML pages are in _build/html.
```
I really appreciate all the help from you both!

**Comment by rowanmiller** [comment]
@NoralK just checking that you have confirmed that those files are present on disk?

**Comment by NoralK** [comment]
If you are referring to warnings above yes they do exist.  I have tinkered around and solved those issues.  In conf.py the `exclude_patterns = ['_build','**/sample']` need to be changed to `exclude_patterns = ['_build','*/sample/*','*/x-plat/*']` and creating an empty directory `EntityFramework.Docs-master\docs\_static` solves all the message.  Now I get what I expect:
```
E:\Projects\EntityFramework.Docs-master\docs>make html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 11 added, 0 changed, 0 removed
reading sources... [100%] providers/index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] providers/index
generating indices... genindex
writing additional pages... search
copying images... [100%] getting-started\aspnet5/_static/index.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build/html.
```
Based on that the ticket can be closed.

BTW - I did install Python 3.4 on Windows 8.1/10 all architectures and in all cases babel 2.0 has to be uninstalled and babel 1.3 installed, also It does not look like Sphinx will update their web page to reflect this.  Might I suggest that the installation instructions be changed here and on ASP.Net Docs.

**Comment by rowanmiller** [comment]
@danroth27 do you want to add info about the supported versions of Python to the [instructions](https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md)?

**Comment by rowanmiller** [comment]
@NoralK we do need to sort out that excluded directories issue. I think we'll probably just start using _static at the top level of things that should be excluded.

**Comment by spboyer** [comment]
This is still an issue on OSX,Python version 2.7.10. Best option is to use virtualenv for python 3.x as @natemcmaster mentioned.

**Comment by natemcmaster** [comment]
We basically require Python 3 to build our docs. Our build script uses Python 3.4.

https://github.com/aspnet/EntityFramework.Docs/blob/master/.travis.yml#L4

**Comment by spboyer** [comment]
@natemcmaster thanks, the aspnet docs does as well but for contributors 2.7.x or higher is acceptable.  Really the only issue is the "wrench" icon.
