### ISSUE TITLE
Show how to use --startup-project

### ISSUE THREAD

**Issue by VahidN** [aspnet/EntityFramework.Docs#294]
A lot of developers don't know how to use the `--startup-project` parameter for moving their `DbContext` to another assembly and then run the migrations. They are still creating `static void main` in other assemblies which is not necessary if `--startup-project` is specified.
```
dotnet ef  --configuration Release --startup-project ../TestPrj/ migrations add V1
dotnet ef  --configuration Release --startup-project ../TestPrj/ database update
```

**Comment by rowanmiller** [comment]
Consolidating with #204
