### ISSUE TITLE
Filtering what is logged

### ISSUE THREAD

**Issue by 1amirjalai** [aspnet/EntityFramework.Docs#297]
This issue tracker is for https://docs.efproject.net/en/latest/miscellaneous/logging.html

in the section **Filtering what is logged** it is been written that using

 ` typeof(Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory).FullName,`
          

can filter out ef core executed command but since ef core 1.1 preview1 it has changed to this

` typeof(Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory).FullName`

**Comment by rowanmiller** [comment]
Fixed in 3c3448c66351fef9c21d1384f105886f3c55d9a3
