### ISSUE TITLE
Can't view or edit docs or sample provider on GH

### ISSUE THREAD

**Issue by kierenj** [aspnet/EntityFramework.Docs#298]
From this page:

https://docs.efproject.net/en/latest/miscellaneous/internals/writing-a-provider.html

The "Edit on GitHub" link gives a 404: https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/miscellaneous/internals/writing-a-provider.rst

The "full stubbed-out provider" link gives a 404: https://github.com/aspnet/EntityFramework.Docs/tree/master/samples/Miscellaneous/Internals/WritingAProvider

**Comment by kierenj** [comment]
@roawnmiller could be as a result of https://github.com/aspnet/EntityFramework.Docs/commit/455da9b06c94226cea1cdc3c261431437d8dbe52 ?

**Comment by rowanmiller** [comment]
This is a result of us moving to a new doc system. The content on docs.efproject.net is currently static and no longer built from the repo as we are going to be cutting over to the new site shortly. The URLs from the current site will redirect once we do the cut over.

**Comment by kierenj** [comment]
(Where can I find the full stubbed out provider then please?)

**Comment by rowanmiller** [comment]
https://github.com/aspnet/EntityFramework.Docs/tree/master/samples/core/Miscellaneous/Internals/WritingAProvider
