### ISSUE TITLE
Adding EF Core to a standalone class library

### ISSUE THREAD

**Issue by AlexChesser** [aspnet/EntityFramework.Docs#30]
I spent yesterday getting tripped on on why I was unable to create a working EF7 standalone class library. Specifically a pattern that I like to use is to create a Model project so that additional applications can be created to load models and data access on their own without WEB.

This can allow for a console app, web app (and other projects) to use the same set of models, services and interfaces.

While following the guide, I tried choosing File -> New -> `Class Library (Package)` instead of console application or ASP.NET web application.

This failed because the default `project.json` file on a class lib comes in with 

```
"frameworks": {
  "dotnet": { }
}
```

instead of 

```
"frameworks": {
  "dnx451": { },
  "dnxcore50": { }
}
```

I'd like to suggest adding a note to getting started aspnet as seen in the following commit https://github.com/AlexChesser/EntityFramework.Docs/commit/ac3ae509d7925b7130065d89561ac1547c0c3b2f

```
.. note::
    If you are attempting to create a standalone class library as data layer shared across multiple applications, ensure that the ``frameworks`` section of the ``project.json`` is updated to replace ``dotnet`` with ``dnx451`` and ``dnxcore50``.  This will ensure that the library has a reference to the ``Microsoft.Data.Entity`` namespace.

.. literalinclude:: aspnet5/sample/src/EFGetStarted.AspNet5/project.json
        :language: json
        :linenos:
        :lines: 25-28
        :emphasize-lines: 2-3
```

It's not so much extra but could help save someone a few extra minutes.

**Comment by natemcmaster** [comment]
Go ahead and create a pull request for this.

**Comment by AlexChesser** [comment]
Hi Nate, I hope the PR is in the correct format. Let me know if I got something wrong.

**Comment by rhires** [comment]
On a related note: how is this similar or different from using separate projects? I'm referencing an issue [https://github.com/aspnet/EntityFramework.Docs/issues/43] I came across that's been added to the 7.0.0 milestone. It seems close, but I don't completely understand the subtleties of these things very well.

**Comment by AlexChesser** [comment]
hey Rhires - I have a similar configuration as you've talked about in #43 and in the thing I'm working on and yes, I created a startup.cs to live in my "Model" project (your business project) I have found that it does take less duplicated code to run the ef commands from the web project with params like '-StarupProjectName Web -ProjectName Business'

there are probably better ways maybe calling the startup.cs in the business project from the startup in web project and keeping the two properly separated

**Comment by rhires** [comment]
Hey @AlexChesser - I stumbled on this (https://github.com/aspnet/EntityFramework/pull/3589) looking around for something else. I tried it on the project I left in a stalled state, and it seems to work. I have to go about fixing the other dependencies and renaming all the assemblies and such (it was beta7), but it didn't fail for the reason that it didn't know what I'm talking about. :-)

**Comment by rowanmiller** [comment]
Closing as this is specific to project.json tooling, which is being replaced by MSBuild based tooling in VS2017
