### ISSUE TITLE
Examples: Bower, Gulp... should not be installed globally

### ISSUE THREAD

**Issue by tkrotoff** [aspnet/EntityFramework.Docs#313]
In your examples [here](https://github.com/aspnet/EntityFramework.Docs/blob/3c3448c66351fef9c21d1384f105886f3c55d9a3/samples/core/GetStarted/AspNetCore/AspNetCore.NewDb/project.json#L62) and [here](https://github.com/aspnet/EntityFramework.Docs/blob/3c3448c66351fef9c21d1384f105886f3c55d9a3/samples/core/GetStarted/AspNetCore/AspNetCore.ExistingDb/project.json#L63), you expect Bower and gulp to be installed globally.

[This is not a good practice](https://www.smashingmagazine.com/2016/01/issue-with-global-node-npm-packages/). These dependencies should be installed locally using package.json and managed with [`scripts`](https://docs.npmjs.com/misc/scripts) or by calling `node_modules/.bin/myclitool`.

Also this has some bad consequences when you deploy the examples, see https://github.com/heroku/dotnet-buildpack/pull/10#issuecomment-268562590. This is for Heroku but I guess the same problem will happen with Azure/Kudu.

Btw Bower is kind of obsolete: [1](https://github.com/bower/bower/issues/2298), [2](https://www.quora.com/Is-Bower-dying), [3](https://twitter.com/dan_abramov/status/654406112180047872). Asking people to understand npm, NuGet and also Bower in your "Get started" examples is kind of arsh.

**Comment by tkrotoff** [comment]
Any news on this? I can make a PR

**Comment by rowanmiller** [comment]
These were built off the default ASP.NET project templates, so they are what you should get if you follow the ASP.NET tutorials step-by-step. So this was probably an issue in the project templates, rather than the EF docs. 

That said, I just moved the tutorials over to VS2017 (csproj rather than project.json), so I don't think this applies any more.
