### ISSUE TITLE
"ASP.NET Core - New Database" tutorial, Add-Migrations says "Build failed."

### ISSUE THREAD

**Issue by unfalse** [aspnet/EntityFramework.Docs#315]
I'm doing this tutorial: https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db
On step "Create your database" I ran the command `Add-Migration MyFirstMigration` but it's output is:

PM> **Add-Migration MyFirstMigration**
Unable to resolve startup project ''.
Add-Migration : A parameter cannot be found that matches parameter name 'Raw'.
At line:1 char:1
+ Add-Migration MyFirstMigration
     CategoryInfo          : InvalidArgument: (:) [Add-Migration], ParameterBindingException
     FullyQualifiedErrorId : NamedParameterNotFound,Add-Migration

My project.json: [gist](https://gist.github.com/unfalse/2e498565fb41312096deacfef54e05f7)
.Net framework is 4.5

**Comment by rowanmiller** [comment]
Closing in favor of https://github.com/aspnet/EntityFramework.Docs/issues/338
