### ISSUE TITLE
Docs for InMemory testing should show how to create new context/database instances

### ISSUE THREAD

**Issue by denisz1** [aspnet/EntityFramework.Docs#325]
My tests were failing, and I couldn't understand why, and it was very hard to track down.

[The doc related to InMemory](http://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory#writing-tests) correctly says *"Typically you want a clean database for each test method"*.

But the code shown results in all test methods sharing the same context and database, even though I `Dispose()` after each test method. So that code is wrong.

I found [a workaround here](http://stackoverflow.com/a/38897560/7059613). It should be added to the official docs to avoid confusion.

Please update the docs.

**Comment by rowanmiller** [comment]
You don't need to do any of the IServiceProvider related stuff starting with EF Core 1.1. The docs correctly show using the database name to control whether any tests share a database, or if they target an isolated one.

**Comment by denisz1** [comment]
@rowanmiller I'm not sure I follow... If I want to use a new database for each test (like the article says), then should I generate a random name for each test? Something like that?

**Comment by rowanmiller** [comment]
@denisz1 or just use the name of the test (which is what the sample in that doc does).

**Comment by denisz1** [comment]
Thanks for your advice.
