### ISSUE TITLE
EF6: Simplify transaction handling samples

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#327]
Our current set of [documentation for using transactions with EF6](https://msdn.microsoft.com/en-us/data/dn456843.aspx) includes some samples that follow this pattern:

```
using (var context = new BloggingContext()) 
{ 
    using (var dbContextTransaction = context.Database.BeginTransaction()) 
    { 
        try 
        { 
            DoSomeWork(context);
            context.SaveChanges(); 
            dbContextTransaction.Commit(); 
        } 
        catch (Exception) 
        { 
            dbContextTransaction.Rollback(); 
        } 
    } 
} 
```

It turns out that:
1. The explicit call to `dbContextTransaction.Rollback()` is in most cases unnecessary, because disposing the transaction at the end of the using block will take care of rolling back.
2. If an error of sufficient severity occurs in SQL Server, the transaction will get automatically rolled back, and the call to `dbContextTransaction.Rollback()` in the catch block will actually fail.

For the second, note that our implementation of `Rollback()` simply delegates to the ADO.NET provider `Rollback()` method so the following note from the remarks in [the underlying method's documentation](https://msdn.microsoft.com/en-us/library/zayx5s0h%28v=vs.110%29.aspx) apply:

> Try/Catch exception handling should always be used when rolling back a transaction. A Rollback generates an InvalidOperationException if the connection is terminated or if the transaction has already been rolled back on the server.

The sample code has proven to be confusing at least for one of our customers and relying on the automatic rollback behavior of disposing without first calling `Commit()` works more reliably and leads to simpler code, so I propose we fix the samples to use that pattern:

```
using (var context = new BloggingContext()) 
{ 
    using (var dbContextTransaction = context.Database.BeginTransaction()) 
    { 
        DoSomeWork(context);
        context.SaveChanges(); 
        dbContextTransaction.Commit(); 
    } 
} 
```

Note that this pattern applies to EF Core 1.0 as well, when we write the corresponding documentation.

**Comment by rowanmiller** [comment]
Putting on backlog as the EF6.x docs have not migrated to this repo yet.

**Comment by ErroneousFatality** [comment]
@rowanmiller Why was this issue closed?
I can see that the documentation wasn't updated as suggested, but I see no reason why.
I came to this since I was looking for an answer if I need to explicitly catch exceptions and rollback on them or if I can just context.SaveChanges and transaction.Commit without worrying about that.

**Comment by ajcvickers** [comment]
@ErroneousFatality The issue isn't closed. That being said, the issue is about the need to call Rollback, not about the need to call Commit. If you're using explicit transactions, like this example, then you will need to call Commit to commit that transaction.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
