### ISSUE TITLE
Document ef.exe

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework.Docs#328]
It lives in both the `Microsoft.EntityFrameworkCore.Tools` and `Microsoft.EntityFrameworkCore.Tools.DotNet` package. There are three versions of it:

Assembly | Notes
-------- | -----
`tools/net451/ef.exe` | For `.NETFramework` and `UAP`
`tools/net451/ef.x86.exe` | Same as above but for x86 assemblies on an x64 OS
`tools/netcoreapp1.0/ef.dll` | For `.NETCoreApp` and `.NETStandard`

To run on .NET Core, use the following. (This is shown in the the verbose output on PMC and `dotnet ef`.)

    dotnet exec --depsfile MyApp.deps.json --runtimeconfig MyApp.runtimeconfig.json ef.dll ...

**Comment by bricelam** [comment]
@ajcvickers was testing this on an x86 OS and found that `ef.exe` didn't work and he needed to use `ef.x86.exe` instead.

**Comment by bricelam** [comment]
Got to the bottom of it. It's not AnyCPU as it's expected to be. Filed aspnet/EntityFramework#7401

**Comment by rowanmiller** [comment]
Consolidating with #204

**Comment by bricelam** [comment]
Reopening since I'm closing #204 without this.
