### ISSUE TITLE
Add list of EF Core extensions on Nuget to extensions section

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework.Docs#329]
https://github.com/aspnet/EntityFramework.Docs/pull/326 

http://erikej.blogspot.dk/2016/12/entity-framework-core-extensions.html 

https://github.com/aspnet/EntityFramework.Docs/pull/326/files

**Comment by ErikEJ** [comment]
@rowanmiller Do you prefer just a single page listing, similar to my blog post? (Or individual pages?)

**Comment by rowanmiller** [comment]
I think individual pages for each extension would be good.

**Comment by ErikEJ** [comment]
OK... Another question (sorry) - how do I fill in the various header fields? (see below)

Or should I just leave them to someone else?

---
title: LLBLGen Pro | Microsoft Docs
author: rowanmiller
ms.author: rowmil
ms.date: 10/27/2016
ms.assetid: d66b9e4d-1ed9-4ac5-a473-957a7d82ea92
ms.technology: entity-framework-core
uid: core/extensions/llbl-gen-pro
---

**Comment by rowanmiller** [comment]
title - leave the ` | Microsoft Docs` on the end and fill in the rest with something short
author - your GitHub handle
ms.author - leave me
ms.date - put in todays date
ms.assetid - I use https://guidgenerator.com/
ms.technology - leave what is there
uid - use the path of the file (minus the `.md`)
