### ISSUE TITLE
How to use EF with Azure and non-Visual Studio tools

### ISSUE THREAD

**Issue by rhires** [aspnet/EntityFramework.Docs#342]
I've looked everywhere and cannot find any documentation that tells how to start with EF and dotnet core and then publish to Azure, but not using Visual Studio. I'm on a Mac, and running everything locally works very well! But getting my db structure up to the cloud is not going over so well (via migrations). So far, I've been able to get the basic project with authentication and authorization up to Azure, but I have no idea how to get the migration to run in Azure. 

First, is there any documentation regarding this? Second, if not, I request that some be made. 

Thanks!

**Comment by rowanmiller** [comment]
This is on the list to be documented (#204). Here are your main options at the moment:
* Use `Script-Migration -Idempotent` or `dot net ef migrations script--idempotent` to create a script that can be applied during deployment.
* Use `DbContext.Database.Migrate()` to apply migrations from code during app start.

We need to come up with some better patterns though, and we'll do this as part of #204.
