### ISSUE TITLE
Enable PDF generation

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#350]
Moved from https://github.com/aspnet/EntityFramework/issues/7534

Enable generation of PDF (for offline reading etc.).

**Comment by Rick-Anderson** [comment]
@dend  can do this for you.

**Comment by rowanmiller** [comment]
Sounds good! Saves me having to work it out 😄.

**Comment by rowanmiller** [comment]
@Rick-Anderson did you get a chance to look at this?

**Comment by Rick-Anderson** [comment]
Sorry, @dend  can you enable PDF generation for EF - or tell me how you did it on  https://github.com/aspnet/Docs/

**Comment by Rick-Anderson** [comment]
@dend  Can you let me know the right contact to enable PDF? you hooked it up on our repo.
