### ISSUE TITLE
Questions on ASP.NET Core - Existing Database sample

### ISSUE THREAD

**Issue by adriatic** [aspnet/EntityFramework.Docs#352]
I am trying to separate an aspnet core application that created the database using the code first approach - and then used this database happily from that initial even onward. I used VS 2015 Update 3 and all matching pieces of aspnet / ef core without a hitch

Now, for deployment reasons, I split this app int two, where the first "half" creates the database and the second should be using this database (there is no explicit relationship between these two apps other than using the same database and data model). After having real difficulties to get that second app to use the database created by the first one, I finally found this [example](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db). 

Here I have a couple of questions:

1. This sample specifies VS 2017 as the requirement, while I was able to run it with VS 2015 Update 3. This should not be a surprise, but it would be nice if Rowan can confirm that my finding is correct.

2. It seems that once I correctly connect to my existing database the only thing that is missing from being able to use it is this code section (properly translated from the `Blog` sample to my own app):

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(entity =>
        {
            entity.Property(e => e.Url).IsRequired();
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasOne(d => d.Blog)
                .WithMany(p => p.Post)
                .HasForeignKey(d => d.BlogId);
        });
    }
```

Is this correct? Can you point me to some additional documentation, please?

Thanks in advance.

**Comment by rowanmiller** [comment]
1. The tutorial works pretty much the same on VS2015. The main difference is that ASP.NET Core doesn't have tooling to create a project that targets 1.1, so you get 1.0 by default. The pre-release project.json ASP.NET Core tooling in VS2015 is also being replaced by the csproj based tooling in VS2017 - so soon that won't be a supported scenario.
2. I don't quite understand this one. Are you saying that you reverse engineered your code from the existing database and the code you listed is not being generated when you did that?

**Comment by adriatic** [comment]
Very interesting event - I was just starting to answer my own question three seconds **before** your comment above appeared. It's very likely a random event as I have proven thousands of times that I do have some rudimentary telepathic abilities. 

At the time I wrote my [original questions](https://github.com/aspnet/EntityFramework.Docs/issues/352#issue-208775879) I knew nothing about Visual Studio 2017 - so I did not know that it fully supports the aspnet core database first scenario - feature that VS 2015 is lacking. Specifically, VS 2017 knows how to create C# models from the database, which is what I was looking for.

To explain my situation fully: I created an aspnet core application using the code first approach with VS 2015, and all worked just fine. Then I wanted to split this app in two:

1. database generator (that I would use only occasionally) 
2. aspnet core web api which would serve the data from the database 

I run into problem in app 2, missing this "generate model classes and dbcontext from the database" - and my original question came from this situation (probably formulated less than ideally).

Hope you will allow me to ask one more question: one of my created model classes looks like this:

```
using System;
using System.Collections.Generic;

namespace Carmel.Models
{
    public partial class Components
    {
        public Components()
        {
            ComponentTags = new HashSet<ComponentTags>();
            Samples = new HashSet<Samples>();
        }

        public int Id { get; set; }
        public string CreatorName { get; set; }
        public DateTime DateCreated { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ComponentTags> ComponentTags { get; set; }
        public virtual ICollection<Samples> Samples { get; set; }
    }
}
```

**Question:** 
Given your article [Loading Related Data](https://docs.microsoft.com/en-us/ef/core/querying/related-data) which states that **[Lazy loading](https://github.com/aspnet/EntityFramework/issues/3797)** is not supported at the moment, why are navigation attributes defined as **`virtual`**?

**Comment by rowanmiller** [comment]
Good question... there is no benefit in making the navigations virtual. Is there a doc somewhere that had them virtual? If so, I will change it 😄.

**Comment by adriatic** [comment]
It is VS 2017 that creates such navigation attributes: see [ASP.NET Core - Existing Database](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db) article, section **`Reverse engineer your model`**, showing how the created entity class `Blog.cs` is:

```
using System;
using System.Collections.Generic;

namespace EFGetStarted.AspNetCore.ExistingDb.Models
{
    public partial class Blog
    {
        public Blog()
        {
            Post = new HashSet<Post>();
        }

        public int BlogId { get; set; }
        public string Url { get; set; }

        public virtual ICollection<Post> Post { get; set; }
    }
}
```

Note that this is **`dotnet core`** doc 😸 .

**Comment by rowanmiller** [comment]
Ah, yes, we changed that recently. In 2.0 it won't generate virtual nav props any more - https://github.com/aspnet/EntityFramework/issues/6326.

**Comment by adriatic** [comment]
Great. I have a very strong interest in presenting aspnet core / ef core as the key parts of full stack apps to 5000+ large [aurelia](http://aurelia.io) community - so if you do mind me barging in here, I will try to give you as much feedback from that prospective as I can. (_stickler for the best documentation possible_)

**Comment by rowanmiller** [comment]
Sounds good, I think the doc is correct for the moment. We'll update the docs when we release 2.0.
