### ISSUE TITLE
Add more 3rd party tools

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework.Docs#353]
LinqKit for Microsoft.EntityFrameworkCore with Include(..... By: sheyenrath 

Microsoft.EntityFrameworkCore.DynamicLinq By: sheyenrath 

Microsoft.EntityFrameworkCore.AutoHistory By: RigoFunc 

Microsoft.EntityFrameworkCore.UnitOfWork By: RigoFunc

**Comment by bricelam** [comment]
[Devart Entity Developer](https://www.devart.com/entitydeveloper/)

**Comment by rowanmiller** [comment]
@ErikEJ were you planning to send a PR for these?

**Comment by ErikEJ** [comment]
Yes

**Comment by rowanmiller** [comment]
Fixed by PR #359

**Comment by axelheer** [comment]
How about [NeinLinq](https://github.com/axelheer/nein-linq)? 🤓
