### ISSUE TITLE
How to use winsqlite3, SQLCipher, etc. with SQLitePCL.raw

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework.Docs#354]
Outlined in aspnet/EntityFramework#7667, but it would be nice to put it under the SQLite provider documentation too.

**Comment by rowanmiller** [comment]
This should be done as part of the 2.0 release and show how to do it based on SQLitePCL.raw

**Comment by bricelam** [comment]
This issue was moved to aspnet/Microsoft.Data.Sqlite.Docs#9
