### ISSUE TITLE
more on database migrations (No executable found matching command "dotnet-ef")

### ISSUE THREAD

**Issue by adriatic** [aspnet/EntityFramework.Docs#355]
I did find the existing issue **[Document migrations](https://github.com/aspnet/EntityFramework.Docs/issues/204)** which does not reference what I want to point out here:

The article [Announcing Entity Framework Core 1.1 Preview 1](https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-entity-framework-core-1-1-preview-1/) was the best information I could find to resolve the problem I just encountered trying to add the support for database migration using Visual Studio 2017 RC as the IDE (this same problem was not present a month ago, when I used VS 2015 Update 3 to do the same action):

![image](https://cloud.githubusercontent.com/assets/2712405/23312641/782d8a00-fa88-11e6-8cd6-6f2c1fecb69a.png)

As I do not think that I am the only one puzzled here, without any good idea how to move forward, perhaps you may consider adding some information in this article, so people can find it before the real documentation gets updated.

I would think that my issue is a consequence of the switch from `project.json` to .csproj "equivalent" - but it's just a guess. Given the fact that my dotnet.exe version is `1.0.0-rc4-004771`, it should be able to handle this situation,

**Comment by adriatic** [comment]
### Solved: 
I needed to run **`Install-Package Microsoft.EntityFrameworkCore.Tools -Version 1.1.0-msbuild3-final`** in the Package Manager Console (note the **`msbuild3-final`**) - and then **`Add-Migration InitialDatabase`** (still in the Package Manager Console), while a few weeks ago, I was using the command **`dotnet ef migrations add InitialDatabase`** in cmd.exe

**Comment by rowanmiller** [comment]
We're going to be re-doing this doc as part of the release of VS2017 next week, so it will be overhauled with exact guidance then.
