### ISSUE TITLE
How to deal with issues caused by the switch from project.json to the .csproj equivalent

### ISSUE THREAD

**Issue by adriatic** [aspnet/EntityFramework.Docs#357]
My **[previous post](https://github.com/aspnet/EntityFramework.Docs/issues/355)** is related to this (_although both could belong in a different docs repo_). Both posts try to indicate a need for a document that handles all problems related to subject line above.

I am encountering warning messages like **`Detected package downgrade: Microsoft.NETCore.App from 1.1.0 to 1.0.3`** after changing the target framework to the most current dotnet core:

![image](https://cloud.githubusercontent.com/assets/2712405/23335839/b69b8ca2-fb8b-11e6-917c-d0f55b75d14a.png)

It is by no means obvious what to do here - because the process of editing the **`.csproj`** file 

![image](https://cloud.githubusercontent.com/assets/2712405/23335864/173a189e-fb8c-11e6-9e6d-8af6e95a10cc.png)

is not "interactive" as **`project.json`** was. Ideally, I would like a helper tool that could guide me through process of selecting the optimal collection of compatible parts (by version number). 

A good document explaining the issue in this "transition time" would be of great value.

**Comment by rowanmiller** [comment]
With the RTM of VS2017 this should all be handled by the `dotnet migrate` command (or the project upgrade experience when you open an xproj in VS2017). This includes bumping up your tools version to the csproj compatible version (which will be a stable 1.1.0 release of tools, not a preview).

If you have a situation where the RTM doesn't handle this, then please open an issue on our product repository - https://github.com/aspnet/EntityFramework.
