### ISSUE TITLE
EF6: Remove IDbSet<T> guidance from Entity Framework Defining DbSets

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#360]
As reported in https://github.com/aspnet/EntityFramework6/issues/210#issuecomment-282996221 we should update this doc to not suggest IDbSet, since we now suggest just mocking DbSet directly.

I think this doc https://msdn.microsoft.com/en-us/library/jj592675(v=vs.113).aspx might need an update. It states  

> There a situations, such as when creating mocks or fakes, where it is more useful to declare your set properties using an interface. In such cases the IDbSet interface can be used in place of DbSet. [...] This context works in exactly the same way as the context that uses the DbSet class for its set properties.

but that would not be true if your code uses the async functions already.

**Comment by rowanmiller** [comment]
Need to wait for EF6.x docs to land in this repo in order to make the change.

**Comment by ajcvickers** [comment]
Thank you for requesting a change to the EF6 documentation. We are prioritizing improvements to the EF Core documentation and at this time we are not making changes to the EF6 documentation.

However, we will consider well-written community pull requests to improve the EF6 documentation. The documentation source is located in the [EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs) repository on GitHub. To submit a pull request:
* Find the file to update and click on it to open

![image](https://user-images.githubusercontent.com/1430078/64454137-10199400-d09f-11e9-9d1a-b7fdca2c518e.png)
* Click on the edit button (✏️) to edit in your web browser

![image](https://user-images.githubusercontent.com/1430078/64454321-85856480-d09f-11e9-85a6-1c93bc6611e2.png)
* When done, add a title and description, then use the "Create a new branch and start a pull request." option.

![image](https://user-images.githubusercontent.com/1430078/64454455-dac17600-d09f-11e9-922b-0346117011f5.png)

(Note that you can also clone the docs repo and do a GitHub PR in the normal way.)
