### ISSUE TITLE
Better Titles for SEO

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#362]
The titles of our docs are pretty concise at the moment. 

For example, see https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md

```
---
title: .NET Core - New Database | Microsoft Docs
---

# .NET Core - New Database
```

Renders like this in search results...

![seo](https://cloud.githubusercontent.com/assets/4741851/23688257/3c02877c-0368-11e7-840b-02556bb893af.png)

My proposal is to prefix everything with `EF Core | ` and have more descriptive titles.

So for the above example, something like `EF Core | .NET Core & SQLite Tutorial | Microsoft Docs`

**Comment by Rick-Anderson** [comment]
@tdykstra  and myself can work on this.  While we're at it we'll remove most of the warnings:

```
 [!NOTE]
 This documentation is for EF Core. For EF6.x, see [Entity Framework 6](../../ef6/index.md).
```

**Comment by divega** [comment]
This was fixed some time ago. We did the "EF Core | " prefix but it turned out not to work well for SEO at all. Then @mariaw fixed by replacing it with an "- EF Core" suffix. The "| Microsoft Docs" suffix is added automatically to all titles and should not be in the source.
