### ISSUE TITLE
Some code snippets are still in-line

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#364]
When we migrated from ReadTheDocs, the automated migration turned all our linked source files to inline code listings. These should be turned back into links to the sample source code.

I've generally been fixing these as I've touched each file.

The old includes were using line numbers, so I've been converting them over to `#region`s while I go.

For example, after migration the md looks like this:

```
<!-- [!code-csharp[Main](samples/core/Querying/Querying/Basics/Sample.cs)] -->
````csharp
using (var context = new BloggingContext())
{
    var blogs = context.Blogs.ToList();
}
````

These need to be changed to:

```
[!code-csharp[Main](../../../samples/core/Querying/Querying/Basics/Sample.cs#RegionToInclude)]
```

**Comment by Rick-Anderson** [comment]
@tdykstra  we should add a list here of the tutorials that need this. We can split up the work.

**Comment by smitpatel** [comment]
@Rick-Anderson - I was working on this recently. Having list of files to check would be useful but not necessary for me to work.

**Comment by Rick-Anderson** [comment]
@smitpatel  -  Tom and I can do this. We'll  ping you if we need coding help.
