### ISSUE TITLE
Add Custom Migrations History Table in EF Core

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/EntityFramework.Docs#371]
It feels like the info, [here](http://www.bricelam.net/2017/01/04/efcore-history-table.html), should be in the documentation, no?  Maybe it can go [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#usage) or on separate page about migrations?

**Comment by ajcvickers** [comment]
@bricelam Where do you think is the best place for this in our docs? Are you volunteering to do it? 😁

**Comment by bricelam** [comment]
This could be done as part of #204 (the all-up documenting of Migrations). I'll do it if we agree it's the best use of my time, but I probably won't get to it in my moonlit hours.

**Comment by ajcvickers** [comment]
Added a task to #204

**Comment by bricelam** [comment]
BTW, my [Custom Migrations History Table in EF Core](http://www.bricelam.net/2017/01/04/efcore-history-table.html) post covers how to do this.
