### ISSUE TITLE
New topic: xplat version of ef/core/get-started/aspnetcore/new-db

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/EntityFramework.Docs#372]
I ~could write an xplat version of~ use tabs to make [ASP.NET Core - New Database](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db) xplat.

See [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio) as an xplat sample.

**Comment by tdykstra** [comment]
Or we could do it in the ASP.NET doc set.  But won't MVC Intro xplat version do this?

**Comment by Rick-Anderson** [comment]
Yes, might be best to just add a link in this repro to our doc.

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by Rick-Anderson** [comment]
@divega  I'm  going to make [ASP.NET Core - New Database](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db) xplat.

See [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio) as an xplat sample.

**Comment by Rick-Anderson** [comment]
@ajcvickers    I'm  going to make [ASP.NET Core - New Database](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db) xplat.

See [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio) as an xplat sample.
