### ISSUE TITLE
Consider Moving Command Line Reference Section

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework.Docs#375]
See discussion in https://github.com/aspnet/EntityFramework/issues/7930. 

We should consider moving the "Command Line Reference" section of the docs to be parallel with API Reference (possibly _and_ under "Tools and Extensions"). We have had people not finding it where it is.

**Comment by divega** [comment]
Fixed in 67762a7ae463c186f4f90421ebe02732c49a70ad
