### ISSUE TITLE
Database providers list

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework.Docs#378]
https://docs.microsoft.com/en-us/ef/core/providers/index
We have this page linked for list of database providers. All the providers are subsections so appear in the tree structure but we don't have a single page as a guideline to show providers available.

**Comment by divega** [comment]
@smitpatel are you after just having the same links that are already in the ToC duplicated the page that is going to show up immediately to the right of the ToC? If yes, what is exactly the value? Is there something you think we could do to the appearance of the ToC that would make work better in your opinion? Otherwise what exactly are you after? :smile:

**Comment by smitpatel** [comment]
Following are some of the links I found while looking over other docs Microsoft has published for various products (C#, .NET, ASP.NET, SqlServer)
https://msdn.microsoft.com/library/hh425099(v=vs.110).aspx
https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/
https://docs.microsoft.com/en-us/aspnet/core/publishing/
https://docs.microsoft.com/en-us/sql/t-sql/tutorial-writing-transact-sql-statements

And following is the link for general API reference (I think it is consistent across .NET Core due to being auto-generated.
https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.design

While the ToC is good for navigating around the topics, it does not seem to be primary place for reading content. It is repetition of information but there are several places where docs do that to improve exposure. I consider it is good to have continuous flow on the content page for docs. Like at the end of chapter link to next one even though it is in navigation tree or after basic tutorial, links to advanced one.

**Comment by bricelam** [comment]
I think a high-level table with framework support would be super useful when deciding what provider to use in a project.

Provider | .NET Framework | .NET Standard
-------- | -------------- | -------------
Microsoft.EntityFrameworkCore.SqlServer | 4.5.1 | 1.3
Microsoft.EntityFrameworkCore.SQLite | 4.5.1 | 1.3
Npgsql.EntityFrameworkCore.PostgreSQL | 4.5.1 | 1.3
IBM.EntityFrameworkCore | 4.6 | 1.6
MySql.Data.EntityFrameworkCore | 4.5.1 | 1.6
Pomelo.EntityFrameworkCore.MySql | 4.5.1 | 1.3
SapientGuardian.EntityFrameworkCore.MySql | 4.5.1 | 1.3
EntityFrameworkCore.SqlServerCompact40 | 4.5.1 | n/a
Microsoft.EntityFrameworkCore.InMemory | 4.5.1 | 1.3

**Comment by divega** [comment]
@bricelam ok. BTW, it is also common for providers to have different levels of support in different platforms/OS, e.g. whether they work in Xamarin or UWP which is not covered by the version of .NET Framework or .NET Standard. E.g. SqlServer supports .NET Standard 1.3 but does not work in UWP (at least currently).

**Comment by bricelam** [comment]
True. Concrete platforms might be better than listing the .NET Standard version.

**Comment by smitpatel** [comment]
Optional: to have a column which would mention the databases names.

**Comment by bricelam** [comment]
@smitpatel Agree. lol, it was just a sketch, guys... 🙄

**Comment by bricelam** [comment]
Other good high-level info might be:
* License
* Runtime (OS) support

**Comment by divega** [comment]
I am thinking more and more than we should just replace what we have now (multiple pages with entries in the index) with a single page containing a table. It will potentially have to be updated (or become stale) frequently but we can make it nice with all the useful information mentioned above in a single place. 

@bricelam @smitpatel thoughts?

**Comment by bricelam** [comment]
I agree. The pages we have are pretty sparse. It's easier to make a decision when all the information is presented together. Providers can present best an overview of themselves.
