### ISSUE TITLE
Replace all references to "Full .NET" or "desktop .NET" with ".NET Framework"

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#381]
E.g. in https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md#full-net-applications

**Comment by tdykstra** [comment]
I only found 4 docs with "full .NET" and none with "desktop .NET".  I only changed text, not project names in sample code or article URLs.
