### ISSUE TITLE
Allow Many-to-Many configuration across separate configuration files

### ISSUE THREAD

**Issue by wdhenrik** [aspnet/EntityFramework.Docs#3827]
The samples for configuring M2M relationships all require configuring in OnModelCreating:
```
modelBuilder
    .Entity<Post>()
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
            .UsingEntity<PostTag>(
                j => j
                    .HasOne(pt => pt.Tag)
                    .WithMany(t => t.PostTags)
                    .HasForeignKey(pt => pt.TagId),
                j => j
                    .HasOne(pt => pt.Post)
                    .WithMany(p => p.PostTags)
                    .HasForeignKey(pt => pt.PostId),
                j =>
                {
                    j.Property(pt => pt.Description).HasMaxLength(50);
                    j.HasKey(t => new { t.PostId, t.TagId });
                });
```
We've standardized on dedicated configuration classes and would like M2M to work with this, but haven't been able to determine how best to implement it without configuring multiple entity types from a single entity.

Please extend the M2M configuration options to work better with dedicated configuration files.  For example:
```
//Post Configuration
builder
    .HasMany(p => p.Tags)
    .WithMany(p => p.Posts)
    .UsingEntity<PostTags>();

//Tags Configuration
builder.
    .HasMany(t => t.Posts)
    .WithMany(t => t.Tags)
    .UsingEntity<PostTags>();

//PostTags Configuration
builder
    .JoinEntities(pt=> 
                 pt.Posts(p=>p.PostsId),
                 pt.Tags(t=>t.TagsId));
builder.HasKey(pt => new { pt.PostId, pt.TagId });
builder.Property(pt=> pt.Description).HasMaxLength(50);
builder.HasData(new { PostsPostId = 1, TagsTagId = "ef" }); 
```
I'd like the UsingEntity clause to only require the join entity type.  The join entity can then use a new configuration method "JoinEntities" to configure the intermediate relationship within its own configuration class along with all the other configurations for it.   _(I've used the composite key as a PK, but it could just as easily have used a typical Id.)_

This puts all the configurations for the three entities in a consistent and intuitive location, and the primary entity configurations don't have to know anything about the join entity's definition. 

If it is already possible to use configurations like I've described here, please update the samples with dedicated configuration files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relationships - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@wdhenrik Regardless of many-to-many, it's generally not possible to separate configuration for each entity type completely from configuration for other entity types, since configuration is needed to describe how the types relate to each other.
