### ISSUE TITLE
Travis builds failing due to folder changes

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/EntityFramework.Docs#384]
Builds for travis are failing because [build.sh](https://github.com/aspnet/EntityFramework.Docs/blob/master/build.sh#L10) references a folder `docs` which no longer exists. If we want to keep running tests against travis we should update `build.sh` to reflect the new structure of the repo, if we don't care about having travis builds we should just delete `.travis.yml` (although I would imagine we should still update build.sh so that people can run it locally).

**Comment by divega** [comment]
Fixed in 1cd73c88984744244540f5b9a8a23bc113dc3f52 289bbc10cc4921f0c6ccd675acaebb6fd9878f72 which remove travis build and other remnants from when we used Read the Docs.
