### ISSUE TITLE
and choose the EntityFramework package - WHICH ONE!

### ISSUE THREAD

**Issue by semberley** [aspnet/EntityFramework.Docs#3878]
and choose the EntityFramework package - WHICH ONE!  There are 10 to choose from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73b2e5a-9526-e664-a2da-556717d344e1
* Version Independent ID: 93442b78-6869-139c-bdbc-9a1efa21b7a6
* Content: [Databinding with WPF - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf)
* Content Source: [entity-framework/ef6/fundamentals/databinding/wpf.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/ef6/fundamentals/databinding/wpf.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by smitpatel** [comment]
@nvnfdddddddd - Every participants in this repository are required to follow https://github.com/dotnet/EntityFramework.Docs/blob/main/CODE-OF-CONDUCT.md
I would suggest reviewing them.
