### ISSUE TITLE
Reverse engineering in Linux and MacOS

### ISSUE THREAD

**Issue by hamzatrq** [aspnet/EntityFramework.Docs#392]
I am a ubuntu user and trying to reverse engineer a database but because I do not have visual studio I can not run `Scaffold-DbContext` command. Please update this guide to cover other OS.

**Comment by bricelam** [comment]
`dotnet ef dbcontext scaffold`

**Comment by ajcvickers** [comment]
Make sure that the docs make it clear what works in VS only and what works everywhere.

**Comment by divega** [comment]
Closing as duplicate of the main reverse engineering topic, which should cover non-Windows platforms anyway: #508.
