### ISSUE TITLE
Add even more 3rd party tools 

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework.Docs#395]
https://github.com/aspnet/EntityFramework/issues/3797#issuecomment-289581186 

https://github.com/aspnet/EntityFramework/issues/2341#issuecomment-290541515 

https://github.com/aspnet/EntityFramework/issues/795#issuecomment-301159333

**Comment by gnaeus** [comment]
Hello! I created an extension [EntityFramework.CommonTools](https://github.com/gnaeus/EntityFramework.CommonTools)

https://www.nuget.org/packages/EntityFrameworkCore.CommonTools

It provides three main features:
* Expansion of `IQueryable` extension methods inside lambda expressions ([example](https://github.com/gnaeus/EntityFramework.CommonTools#ef-querying))
* Application-level transaction logs ([example](https://github.com/gnaeus/EntityFramework.CommonTools#ef-transaction-logs))
* Utility for storing complex types in JSON columns ([example](https://github.com/gnaeus/EntityFramework.CommonTools#ef-json-field))

And I want to add some info about this extension to the EFCore docs.

**Comment by divega** [comment]
For this too (like providers), I am thinking about having a single page listing all tools in a table rather than separate pages referenced in the index. It may make sense to do some house cleaning if some of the tools are not being maintained or useful.

**Comment by ErikEJ** [comment]
Good idea - any starting point/template for the table?

**Comment by divega** [comment]
@ErikEJ sorry for the long delay answering. I think having a table that normalizes the information on the existing extension pages would be a good starting point. It would be good to include a column for compatibility and a description.

**Comment by ErikEJ** [comment]
Do you have an exsisting page I can use a inspiration/template?

**Comment by divega** [comment]
@ErikEJ you may now want to check the new provider list. The PR was #632. 
- This should be similar, although the columns may be different. 
- There is the need to redirect stuff to the index.md containing the table. 
- Tables in markdown are better than html but still hard to manage. You may want to use some editor add in that automates markdown tables fixup. You may also want to use two monitors :smile:
