### ISSUE TITLE
Differences between, and porting from, EF6 and EF Core

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#40]
E.g. lazy loading.

**Comment by divega** [comment]
Another example of removed features that recently came up is data validation.

**Comment by bitcrazed** [comment]
Can I also add:
* Lack of many-to-many support
* Lack of explicit DB seeding / data-migration during schema-migrations

**Comment by natemcmaster** [comment]
Add conventions (see [this SO question](http://stackoverflow.com/questions/33036030/entityframework7-conventions-properties-and-configurations)).

**Comment by natemcmaster** [comment]
@rowanmiller anything else here to do? cref  e9d06718a0f9776d9429c71d3b9154ba5f9365b1

**Comment by rowanmiller** [comment]
Nope, think I got everything
