### ISSUE TITLE
Inheritance Discriminator should be included as property?

### ISSUE THREAD

**Issue by ferrx** [aspnet/EntityFramework.Docs#400]
The doc for Inheritance (relational) that covers the Discriminator here https://docs.microsoft.com/en-us/ef/core/modeling/relational/inheritance may need some tweaking.

When you create the `blog_type` discriminator via Fluent API (or automatically via inheritance), should you also create a property in the Blog class called `blog_type` ?

In Visual Studio, when you try to add a controller that uses the Blog model, it will extract blog_type as a property it should be using and fail to work. For example, if you created a PostsController where there is a 1-to-many relationship with Blog-Posts, Visual Studio will automatically toss in "blog_type" in a number of areas in the generated view and controller files.

**Comment by ajcvickers** [comment]
@divega This looks like it could be a scaffolding issue. If so, we should file a issue there. Thoughts?

**Comment by divega** [comment]
@ajcvickers Definitively an issue in scaffolding. From the description there is no support for shadow-properties. 

On the other hand, EF Core could help by creating a way to get a serializable representation of shadow properties, required original values, concurrency tokens, etc.

**Comment by divega** [comment]
This issue was moved to aspnet/Scaffolding#508
