### ISSUE TITLE
Unable to remove table mapping with Migrations

### ISSUE THREAD

**Issue by ferrx** [aspnet/EntityFramework.Docs#401]
I applied a table mapping like the following,

```
    [Table("blogs", Schema = "blogging")]
    public class Blog
```
Upon using `Add-Migration` and `Update-Database` I see the changes in my DB. The table went from "Blogs" to "blogs (blogging)".

However, if I remove the data annotation like so,

```
    public class Blog
```
Upon using `Add-Migration` and `Update-Database` I get an error `Cannot find the object "Blogs" because it does not exist or you do not have permissions.` 

I can force it work if I do the following,

```
    [Table("blogzzz", Schema = "blogging")]
    public class Blog
```
followed by `Add-Migration` + `Update-Database` and then,
```
    public class Blog
```
It's as if there is a case sensitivity issue? Hard to make sense of it, but it seems like renaming from blogs->Blogs does not work somewhere. It seems that renaming Blogs->blogs worked fine when applying the original data annotation.

While that work-around does fix the issue, the table still shows up with the `blogging` schema as "Blog (blogging)"

**Comment by ajcvickers** [comment]
@ferrx What version of EF Core and which database provider are you using?

**Comment by ferrx** [comment]
@ajcvickers For EF Core I have the following,

Microsoft.EntityFrameworkCore.Design 1.1.1
Microsoft.EntityFrameworkCore.SqlServer 1.1.2
Microsoft.EntityFrameworkCore.SqlServer.Design 1.1.2
Microsoft.EntityFrameworkCore.Tools 1.1.1

Using SQL Server (localdb).

**Comment by ferrx** [comment]
Updated to 1.1.2 and ran `Update-Database` again and received the same error,

> Cannot find the object "Blog" because it does not exist or you do not have permissions.

**Comment by ferrx** [comment]
I created a project from scratch and after some testing I see that the add-migration script does not remove a schema when either removing the entire DA or removing the schema property of the DA. The associated designer performs a `ToTable` without a schema parameter, so any further updates to that table will return an error because the actual table is still associated with a schema that is not dbo. I also tested changing the schema from "blogging" to "dbo" in the DA and saw that it updated properly, after which I was able to remove the DA entirely and perform valid updates to dbo.Blogs

You can replicate this by creating a baseline project with a model, applying a schema to it via data annotation (unsure if Fluent API has the same problem), then either remove the entire DA or remove the schema property from the DA. Any future updates will throw an error of table not found.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework#8726
