### ISSUE TITLE
"Add-Migration" In UWP

### ISSUE THREAD

**Issue by hippieZhou** [aspnet/EntityFramework.Docs#419]
When I follow this [link](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started) Sample Step by Step, When I Run Add-Migration MyFirstMigration to scaffold a migration to create the initial set of tables for my model.I got something wrong,the error info is that  **" Could not load type 'System.ComponentModel.DataAnnotations.Schema.InversePropertyAttribute' from assembly 'System.ComponentModel.Annotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"**,all of this package is  latest version ,and the UWP SDK version is  15063 .Can you tell me what should I do to fix it. thank you.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework#9141
