### ISSUE TITLE
Update Configuring a DbContext (configuring-dbcontext.md) to use IDesignTimeDbContextFactory

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/EntityFramework.Docs#420]
Update configuring-dbcontext.md to use the IDesignTimeDbContextFactory instead of the deprecated IDbContextFactory.

**Comment by jsacapdev** [comment]
If you approve, I am happy to raise the PR to do this work (keen to contribute!)

**Comment by divega** [comment]
@jsacapdev sorry, I did not see your message volunteering and I did this already :relaxed:. Feel free to look into this or other parts of the docs and improve them. I am sure I have introduced issues with all the recent churn.

**Comment by divega** [comment]
Fixed in b42bf9cedcd2aa11d975eed13ce164915563c636.
