### ISSUE TITLE
Example C# code only has single Include for split query

### ISSUE THREAD

**Issue by hugh-maaskant** [aspnet/EntityFramework.Docs#4280]
Hi,

In the examples of the split query section (https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries#split-queries), the code only has a single `Include` statement:

```C#
using (var context = new BloggingContext())
{
    var blogs = context.Blogs
        .Include(blog => blog.Posts)
        .AsSplitQuery()
        .ToList();
}
```

This is confusing, I think the following was intended:

```C#
var blogs = ctx.Blogs
    .Include(b => b.Posts)
    .Include(b => b.Contributors)
    .AsSplitQuery()
    .ToList();

```

Note this happens twice, i.e. also in the global split query setting section.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43baa9f3-c415-c328-6c10-53aabaaec652
* Version Independent ID: 4e789a1b-aa88-d194-dc2e-0a23251250d7
* Content: [Single vs. Split Queries - EF Core](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries)
* Content Source: [entity-framework/core/querying/single-split-queries.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/querying/single-split-queries.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment]
@hugh-maaskant what do you find confusing about this? I agree that clearest case where split queries make sense is cartesian explosion - which requires two collection joins - but it can just as well be used with a single join. This can be useful, for example, when the principal row has very large rows that you don't want duplicated (see Cartesian explosion vs. Data duplication at the top of the page).

**Comment by hugh-maaskant** [comment]
Hi Shay,

I do understand that it can make sense to do a projection to a subset of the properties in order to reduce the amount of data returned from the database. I also understand this means the returned data is not tracked (as it is not a full entity but a “subset”.

I find it confusing what a “split query” would mean when there is only one Include on the table. This is a screenshot of the section i refer to:



The text says “split queries generate an additional SQL query for each included collection navigation”. This makes a lot of sense, but then the example code has only one collection navigation: Include(blog => blog.Posts). However, the genrated SQL has two queries. I guess the idea is to not have the [b].[BlogId], [b].[OwnerId], [b].[Rating], [b].[Url] returned for every PostId, so I assume this technically is also split query (on two navigation properties, but but not on two collections).

I would expect the Split query example from the problem description to be used as the primary example to show the split query:



This would then very clearly show the cartesian explosion issue.

Once that is clear, the case of the Owner and Blogs navigatiuons would indeed be helpfull too. This is a case I had not considered, but now also starts to make sense (thanks for the education btw ;-).

It probably does not help that I am not very conversant with databases and their terminology.

Hope this helps, feel free to contact me again if I can clarify further, and thanks for all the great work you and the team are doing on EF Core (and the PosgreSQL provider)!

Hugh

——
Hugh Maaskant
The Netherlands

**Comment by roji** [comment]
> I find it confusing what a “split query” would mean when there is only one Include on the table.

Well, in a split query, every (collection) Include is split out to an additional separate query, instead of adding a JOIN to the main one. So for a LINQ query with one collection include, two database queries are sent.

I understand that the cartesian explosion scenario is the more "canonical" one for split queries - and that it does imply at least two collection Includes - but the idea here was to keep the examples short and to the point, and I believe that adding another Include will just make things longer and more complex for the newcomer.

**Comment by hugh-maaskant** [comment]
Hi Shay,

Thanks I understand it now, whether to use one or two includes in the example is your prerogative. My take, as a database newly, is that the cartesian explosion example makes more sense, but the example given is usefull too and certainly taught me something (with the aid of your remarks).

Cheers, Hugh

——
Hugh Maaskant
The Netherlands

**Comment by roji** [comment]
Great, thanks for keeping an open mind. I'll keep an eye out, in case this is the source of confusion for other users - if it is we can definitely change it.

**Comment by oasaleh** [comment]
Yep. That was a source of confusion to me as well, and came here to provide feedback. I think @roji's comment here should be added to the documentation for increased clarification.

> Well, in a split query, every (collection) Include is split out to an additional separate query, instead of adding a JOIN to the main one. So for a LINQ query with one collection include, two database queries are sent.
