### ISSUE TITLE
Optional one-to-one - code example not complete - missing the mentioned nullable foreign key property

### ISSUE THREAD

**Issue by jsonserverkit** [aspnet/EntityFramework.Docs#4356]
It seems that in the in the expample of the "Optional one-to-one" the code does not show the mentioned (within the text below) nullable foreign key property. This might be somewhat missleading despite the minimal footprint of the example :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93b48a8b-469b-1dbe-e6b9-66a58d29e841
* Version Independent ID: 93b48a8b-469b-1dbe-e6b9-66a58d29e841
* Content: [One-to-many relationships - EF Core](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/one-to-many)
* Content Source: [entity-framework/core/modeling/relationships/one-to-many.md](https://github.com/dotnet/EntityFramework.Docs/blob/main/entity-framework/core/modeling/relationships/one-to-many.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@jsonserverkit Thanks--I submitted https://github.com/dotnet/EntityFramework.Docs/pull/4357 to fix this. The wrong code sample was referenced in the document.
