### ISSUE TITLE
New feature topic: Documentation for owned types 

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#466]
Copied from https://github.com/aspnet/EntityFrameworkCore/issues/9620 by @FransBouma

Hi,

For LLBLGen Pro v5.3 I'm updating our EF Core support to v2.0 and as our designer supports table splitting and value types / complex types (DDD), we can support table splitting and owned types for EF Core 2.0. However there appears to be no documentation (that I could find) about owned types mapping for code first.

For table splitting there also appears to be no documentation, e.g. what the limitations are, and how to set it up. I can assume a few things, e.g. that the split off entity can be mapped the same way as the root entity but if there are limitations, e.g. fields have to be nullable in the DB, navigational properties are/aren't supported, that's unknown, as there's no documentation at all about this.

For owned type mappings there's also no documentation: as they appear to have no PK, I can't use regular entity mappings (I think, but again: no idea) so how to set it up is unclear. I know there's 1 single example in the 'what's new' page in the documentation but that maps everything with conventions which is unusable for us as we need to cover all scenarios, e.g. a field is renamed and we need to explicitly specify the mapping. Also with this, there is no description about what the limitations are, e.g. whether the owned type can or can't be null, whether the fields have to be null or don't have to be...

TIA

**Comment by FransBouma** [comment]
Is there an ETA for this? As currently it's IMHO impossible to use the feature to begin with. 'Backlog' suggests it will take a long time before we'll see any docs in this case, but I frankly don't really understand why there's not a single line of documentation about the feature at all today and why it has to take that long. 

Are there tests I can look at? Is there a design doc with more info, or commits I can look at? 

For us it's unacceptable if we have to postpone EF core 2.0 support in our upcoming release (which ships in a few weeks)

**Comment by divega** [comment]
@FransBouma This is one among other updates we need to do in the documentation. There is no clear ETA right now, but I am happy to help you with answers on specific questions if you want to implement support in LLBLGen Pro. 

BTW, we haven't heard from many customers having difficulty figuring out how to use the feature. I think the examples we have provided were simple to understand. We actually have had a few customers hitting the edges of what is supported and issues reported on those cases.  

Besides the description of the feature in the what is new page and in the blog post, there are a few details from the top of my head (so of it might be too low level for app development):

- Owned types are defined when you configure a navigation property to a type using the `OwnsOne` fluent API 
- The definition of an owned type in our metadata model is a composite of: the owner type, the navigation property, and the CLR type of the owned type
- The identity (key) of an owned type instance in our system is a composite of the identity of the owner type and the definition of the owned type

Capabilities:
- Owned type can reference other entities, either owned (nested owned types) or non-owned (regular reference navigation properties to other entities)
- You can map the same CLR type as different owned types in the same owner entity
- Table splitting setup by convention, but you can opt out 
- Eager loading is performed automatically on owned types, i.e. no need to call Include() on the query

Limitations:
- You cannot create `DbSet<T>` of owned types (by design)
- You cannot call `ModelBuilder.Entity<T>()` on owned types (currently by design)
- No collections yet (but we want to do this in the future)
- No support for configuring them via an attribute
- No support for optional (i.e. nullable) owned types that are mapped with the owner in the same table (i.e. using table splitting). This because we don't have a separate sentinel for the null 
- No inheritance mapping support for owned types, but you should be able to map two leaf types of the same inheritance hierarchies as different owned types. EF Core will not reason about the fact that they are part of the same hierarchy

Summary of main differences with EF6's complex types
- Table splitting is optional, i.e. they can optionally be mapped to a separate table and still be owned types
- They can reference other entities (i.e. they can act as the dependent side on relationships to other non-owned types)

**Comment by FransBouma** [comment]
Thanks @divega for the info :) I'll use this to implement the feature and see how far we get. It's a small piece of code for us to emit the mappings in the fluent api, the work is in what features of our designer to exclude in validation so the user doesn't use things which aren't supported (yet) by EF Core at runtime. 

If I've questions / probs I'll keep you posted :)

**Comment by FransBouma** [comment]
Have it all working now. 

For reference (On northwind). This is all generated btw: 

### Table splitting: 
```cs
/// <summary>Defines the mapping information for the entity 'Employee'</summary>
/// <param name="config">The configuration to modify.</param>
protected virtual void MapEmployee(EntityTypeBuilder<Employee> config)
{
	config.ToTable("Employees");
	config.HasKey(t => t.EmployeeId);
	config.Property(t => t.EmployeeId).HasColumnName("EmployeeID").ValueGeneratedOnAdd();
	config.Property(t => t.LastName).HasMaxLength(20).IsRequired();
	config.Property(t => t.FirstName).HasMaxLength(10).IsRequired();
	config.Property(t => t.Title).HasMaxLength(30);
	config.Property(t => t.TitleOfCourtesy).HasMaxLength(25);
	config.Property(t => t.BirthDate);
	config.Property(t => t.HireDate);
	config.Property(t => t.AddressAddress).HasColumnName("Address").HasMaxLength(60);
	config.Property(t => t.AddressCity).HasColumnName("City").HasMaxLength(15);
	config.Property(t => t.AddressCountry).HasColumnName("Country").HasMaxLength(15);
	config.Property(t => t.HomePhone).HasMaxLength(24);
	config.Property(t => t.Extension).HasMaxLength(4);
	config.Property<System.String>("Region");
	config.Property<System.String>("PostalCode");
	config.Property<System.String>("PhotoPath");
	config.Property<Nullable<System.Int32>>("RegionID");
	config.Property<Nullable<System.Int32>>("ReportsTo");
	config.HasOne(t => t.Manager).WithMany(t => t.ManagedEmployees).HasForeignKey("ReportsTo").IsRequired();
	config.HasOne(t => t.Region_).WithMany(t => t.Employee).HasForeignKey("RegionID").IsRequired();
}

/// <summary>Defines the mapping information for the entity 'EmployeeLargeData'</summary>
/// <param name="config">The configuration to modify.</param>
protected virtual void MapEmployeeLargeData(EntityTypeBuilder<EmployeeLargeData> config)
{
	config.ToTable("Employees");
	config.HasKey(t => t.EmployeeId);
	config.Property(t => t.EmployeeId).HasColumnName("EmployeeID");
	config.Property(t => t.Photo).IsRequired();
	config.Property(t => t.Notes).HasMaxLength(1073741823).IsRequired();
	config.HasOne(t => t.Employee).WithOne(t => t.EmployeeLargeData).HasForeignKey<EmployeeLargeData>(t => t.EmployeeId).IsRequired().OnDelete(DeleteBehavior.Cascade);
}
```
Here EmployeeLargeData is split off from Employee

### Owned types 
Valuetypes (DDD) in our modeling system are now mapped to Owned types. I validate on nullability so a nullable field which is has as its type a valuetype definition is not allowed.

```cs
/// <summary>Defines the mapping information for the entity 'Customer'</summary>
/// <param name="config">The configuration to modify.</param>
protected virtual void MapCustomer(EntityTypeBuilder<Customer> config)
{
	config.ToTable("Customers");
	config.HasKey(t => t.CustomerId);
	config.Property(t => t.CustomerId).HasColumnName("CustomerID").HasMaxLength(5);
	config.Property(t => t.CompanyName).HasMaxLength(40).IsRequired();
	config.Property(t => t.ContactName).HasMaxLength(30);
	config.Property(t => t.ContactTitle).HasMaxLength(30);
	config.Property(t => t.PostalCode).HasMaxLength(10);
	config.Property(t => t.Phone).HasMaxLength(24);
	config.Property(t => t.Fax).HasMaxLength(24);
	config.OwnsOne(t => t.Address).Property(t => t.Address).HasColumnName("Address").HasMaxLength(15);
	config.OwnsOne(t => t.Address).Property(t => t.City).HasColumnName("City").HasMaxLength(15);
	config.OwnsOne(t => t.Address).OwnsOne(t => t.Country).Property(t => t.Country).HasColumnName("Country").HasMaxLength(15);
	config.Property<System.String>("Region");
}
```

type is also used in Supplier:
```cs
/// <summary>Defines the mapping information for the entity 'Supplier'</summary>
/// <param name="config">The configuration to modify.</param>
protected virtual void MapSupplier(EntityTypeBuilder<Supplier> config)
{
	config.ToTable("Suppliers");
	config.HasKey(t => t.Id);
	config.Property(t => t.Id).HasColumnName("SupplierID").ValueGeneratedOnAdd();
	config.Property(t => t.CompanyName).HasMaxLength(40).IsRequired();
	config.Property(t => t.ContactName).HasMaxLength(30);
	config.Property(t => t.ContactTitle).HasMaxLength(30);
	config.Property(t => t.Region).HasMaxLength(15);
	config.Property(t => t.PostalCode).HasMaxLength(10);
	config.Property(t => t.Phone).HasMaxLength(24);
	config.Property(t => t.Fax).HasMaxLength(24);
	config.Property(t => t.HomePage).HasMaxLength(1073741823);
	config.OwnsOne(t => t.Address).Property(t => t.Address).HasColumnName("Address").HasMaxLength(15);
	config.OwnsOne(t => t.Address).Property(t => t.City).HasColumnName("City").HasMaxLength(15);
	config.OwnsOne(t => t.Address).OwnsOne(t => t.Country).Property(t => t.Country).HasColumnName("Country").HasMaxLength(15);
}
```

Simple usage:
```cs
[Test]
public void LoadCustomers()
{
    using(var db = new NorthwindEFCoreDataContext())
    {
        var orders = db.Customers.Where(c => c.Address.Country.Country=="USA").ToList();
        Assert.AreEqual(13, orders.Count);
    }
}
```

**Comment by FransBouma** [comment]
One remark tho: 

If I do:
```cs
/// <summary>Defines the mapping information for the entity 'Customer'</summary>
/// <param name="config">The configuration to modify.</param>
protected virtual void MapCustomer(EntityTypeBuilder<Customer> config)
{
	config.ToTable("Customers");
	config.HasKey(t => t.CustomerId);
	config.Property(t => t.CustomerId).HasColumnName("CustomerID").HasMaxLength(5);
	config.Property(t => t.CompanyName).HasMaxLength(40).IsRequired();
	config.Property(t => t.ContactName).HasMaxLength(30);
	config.Property(t => t.ContactTitle).HasMaxLength(30);
	config.Property(t => t.PostalCode).HasMaxLength(10);
	config.Property(t => t.Phone).HasMaxLength(24);
	config.Property(t => t.Fax).HasMaxLength(24);
	config.OwnsOne(t => t.Address).Property(t => t.Address).HasMaxLength(15);
	config.OwnsOne(t => t.Address).Property(t => t.City).HasMaxLength(15);
	config.OwnsOne(t => t.Address).OwnsOne(t => t.Country).Property(t => t.Country).HasMaxLength(15);
	config.Property<System.String>("Region");
}
```

I get: 
```
Failed executing DbCommand (100ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [c].[CustomerID], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region], [c].[CustomerID], [c].[Address_Address], [c].[Address_City], [c].[CustomerID], [c].[Address_Country_Country]
FROM [dbo].[Customers] AS [c]
WHERE [c].[Address_Country_Country] = N'USA'
An exception occurred in the database while iterating the results of a query for context type 'NWEFCore2.NorthwindEFCoreDataContext'.
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Address_Country_Country'.
Invalid column name 'Address_Address'.
Invalid column name 'Address_City'.
Invalid column name 'Address_Country_Country'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
...
```

So I have to explicitly specify the column name, even though it's the same as the field. This requirement is the same as in EF6 btw, and likely you have a reason for that (multiple usage of same valuetype in entity-> alias issues) but I'd expect this to be transparent, i.e. now the user has to know this up front and it's thus a leaky abstraction.

**Comment by JeanCollas** [comment]
I have got the same issue as @FransBouma

**Comment by daerhiel** [comment]
For Table Splitting, can I have Employee inherited from EmployeeLargeData or these should be separate types?

**Comment by AndriySvyryd** [comment]
@daerhiel If you inherit Employee from EmployeeLargeData and use table splitting the table would have the EmployeeLargeData columns duplicated. Why would you need to use table splitting in this case?

**Comment by daerhiel** [comment]
@AndriySvyryd I'm always lacking of having 2 separate models for the same table one short version for large lists, and another 'full' one for getting the full data with all the related records. Basically the full one has all the properties from the 'list' version this is why it makes it 'logical' to use inheritance to make code dry. Is there another reasonable approach for building this feature apart from table splitting and inheritance?

**Comment by AndriySvyryd** [comment]
@daerhiel If you just use inheritance with EmployeeLargeData deriving from the abstract Employee then you can query either EmployeeLargeData or Employee from the same table. You don't need to use table splitting.

**Comment by daerhiel** [comment]
@AndriySvyryd how do I map the properties then? I need them to be different for different models..

**Comment by AndriySvyryd** [comment]
@daerhiel If you are really using two different models as in two different DbContext classes then just map one of the classes in each model and ignore the other one.

**Comment by daerhiel** [comment]
@AndriySvyryd, no same DbContext

**Comment by AndriySvyryd** [comment]
@daerhiel Then it won't be possible to map the same columns differently in different entity types.

**Comment by virtualcca** [comment]
"No support for configuring them via an attribute" said in Limitations,
does it mean that I use attribute(using System.ComponentModel.DataAnnotations.Schema, for example [Column("columnName")]) to define in subtype is invalid?
Will there be any plan to support this function?

**Comment by divega** [comment]
@virtualcca it is referring to the fact that in 2.0 there is no way to specify that a type is an owned type by placing an attribute on the navigation property or on the type itself.
