### ISSUE TITLE
NuGet version for VS2015

### ISSUE THREAD

**Issue by mehrt** [aspnet/EntityFramework.Docs#48]
I tried to run ...
```
Install-Package EntityFramework.SqlServer –Pre
```
... on an existing project that was under source control. This produces lots of errors like *There is no working folder for (path)* as described [here](https://github.com/NuGet/Home/issues/1004).
Installing the [nuget 3.2RC](http://blog.nuget.org/20150902/nuget-3.2RC.html) vsix fixed this. So, the Getting Started series of documents should be changed to reflect that, especially the one for Full.NET, as there's explicit hints to update the NuGet version for the older versions of Visual Studio.

**Comment by rowanmiller** [comment]
Done... the docs now tell you to get the latest nuget (since things are always updating and while EF is prerelease it will likely require the latest update)
