### ISSUE TITLE
Model building: Under relational modeling, PK/Index/AK/FK has only constraint name

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#496]
Do we need separate pages?

Originally from https://github.com/aspnet/Release/issues/189 and #424.

**Comment by ajcvickers** [comment]
@smitpatel to see if more content should go here, or might go here in the future.

**Comment by smitpatel** [comment]
Assigning to @AndriySvyryd  if Relational has any additional metadata which we need to document.
