### ISSUE TITLE
Document how to use EF command line in different environments

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#506]
There is quite a large matrix of different environments that the EF commands (Migrations and reverse engineering) can be used in. It's very hard for developers to know both what will work and what is the best approach.  We should document this matrix so that somebody can easily ask a question such as, "What do I do if I want to put my EF code into a .NET Standard class library and then use it with a UWP application?"

Initial cut of the matrix is:
* Target app platform (.NET Core app, UWP, Xamarin, .NET Framework, none--i.e. .NET Standard class library)
* Type of project (Class library, ASP.NET Core, all others)
* Development platform (Visual Studio/GUI tooling (use community power tools), Visual Studio/command line (use PMC), Windows/Linux/etc. command line (use dotnet ef)).

We should also make sure that the walkthroughs are consistent with this and point to this information clearly where appropriate.

**Comment by ajcvickers** [comment]
From triage: Also look at #507, #508, #485, and #481 and consider how to separate the content effectively and how to reference between these areas.

**Comment by bricelam** [comment]
This is a subset of #204
