### ISSUE TITLE
Document Reverse Engineering at the conceptual level

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#508]
Issue #506 is about how to use the command line tools, but we also need better documentation on why and how to use reverse engineering at the conceptual level.

**Comment by bricelam** [comment]
I think Rowan's original intentions were to add a new node under EF Core with these sub-nodes:

* Schema management
  * Migrations
  * Reverse engineering

I'll add it as part of #507

**Comment by bricelam** [comment]
This issue is a subset of #204

**Comment by bricelam** [comment]
Note to documentor: don't forget to mention `Name=`

**Comment by cccuscott** [comment]
I see this didn't make it into 2.1 release. I am currently transitioning our SaaS product to .netcore (Great work) but we are a heavy DB first/reverse engineer shop for our EF stuff. Is there a quick and dirty on disabling migrations and doing reverse engineering?

**Comment by ErikEJ** [comment]
Have a look at EF Core Power Tools (I am the author) https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering

**Comment by bricelam** [comment]
Some ideas:
* Connection strings
  * escaping in PS and command-line
  * from config (Name=)
* Provider name is NuGet package/assembly name
* Specifying tables (--schema, --table)
* Preserve database names (--use-database-names)
* What we reverse engineer
  * foreign key columns
  * Bi-directional navigations
  * All constraints (safe to remove some)
  * Sequences
* What we don't reverse engineer
  * Inheritance
  * Table splitting/owned types
  * Concurrency tokens
  * Views/tables without PK--Query types (TODO)
  * Unsupported Column Types
  * Data Annotations or Fluent API
* You can change it, but changes are blown away without update from database
* Re-scaffolding (--force)

**Comment by bricelam** [comment]
(Poaching this from @smitpatel)
