### ISSUE TITLE
UWP limitations and workarounds

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework.Docs#51]
RC1 will not resolve completely all issues in using EF with UWP. We should document and provide work arounds for some likely scenarios:

### 1. SQlite with transactions. 
(Cref https://github.com/aspnet/Microsoft.Data.Sqlite/issues/116) 

Users need to explicitly specify the temporary directory for SQLite as the default working directory is unwritable. Transactions will throw ``"SQLite Error 1: 'SQL logic error or missing database'"``.

### 2. .NET Native query limitations
Support for query drastically improves with https://github.com/aspnet/EntityFramework/pull/3516. However, the static analysis run in the ILC step cannot completely identify all possible uses of user types inside of the query pipeline (e.g. anonymous types.) Users are likely to encounter strange `MissingRuntimeArtifactException`'s. This can be avoid by simplifying the query or running on the client. For SQLite, this may be the better solution.

### 3. Default folder for relative paths is unwritable
(cref https://github.com/aspnet/Microsoft.Data.Sqlite/issues/55)
Sqlite attempts to use the package folder by default, which is unwritable.
E.g. 
```c#
options.UseSqlite("Filename=./blog.db"); // this throws
options.UseSqlite("Filename=" + ApplicationData.Current.LocalFolder.Path + "/blog.db"); // workaround
```

**Comment by rowanmiller** [comment]
Item 1 & 3 are now fixed in the product (as of RC1). I've added docs for item 2 in https://github.com/aspnet/EntityFramework.Docs/commit/f51d9e5657e7e6eaaaa902b0c9d81ce5f323816e
