### ISSUE TITLE
Update API link on TOC to point to new API

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/EntityFramework.Docs#515]
![image](https://user-images.githubusercontent.com/3605364/31404266-4069a5be-ad97-11e7-8356-d8376961b81d.png)

Currently the API link goes to https://docs.microsoft.com/en-us/ef/core/api/
change it to https://docs.microsoft.com/en-us/dotnet/api/?view=efcore-2.0

Consider moving API TOC element near the  bottom of the list like we do at https://docs.microsoft.com/en-us/aspnet/core/

**Comment by divega** [comment]
This appears to be already fixed according to the suggestions.
