### ISSUE TITLE
API docs missing references to external types

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework.Docs#530]
E.g. in https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.metadata.changetrackingstrategy 

The descriptions should say
> the entity class must implement [INotifyPropertyChanged](https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifypropertychanged.aspx).

**Comment by ajcvickers** [comment]
Fixed in "new and fancy" API docs: https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetrackingstrategy?view=efcore-2.0
