### ISSUE TITLE
I'm missing release management scenarios in the docs

### ISSUE THREAD

**Issue by SetTrend** [aspnet/EntityFramework.Docs#555]
The docs don't give information on how to set up Entity Framework Core for proper release management.

In detail I'm missing: Migrations and database initializers configuration, particularly for scenarios where the application is not supposed to issue DDL statements, instead database admins are involved in running DDL scripts.

I'm also missing information on how to set up Entity Framework Core for continues integration, i.e. unit tests, integration tests and regression tests.

See also: aspnet/EntityFrameworkCore#10205

**Comment by SetTrend** [comment]
Based on experiences with Code-first's approach, I would, for example, expect some kind of a `DropCreateDatabaseAlways` for having continuous integration run automated tests. Or the ability to create some custom kind of database initializer to create and prepare a database for automated tests. If EF Core uses another approach, I'd be missing information in the docs about the transition to the new paradigm.

I'm also missing information in the docs about how to create entities from the database and vice versa. Probably that's something that might be fixed with #506 ?

**Comment by ajcvickers** [comment]
@SetTrend Thanks for the feedback. `context.Database.EnsureCreated` and `context.Database.EnsureDeleted` are intended for this kind of testing scenario. There is some information on this in [in the testing section](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/) of the docs, but it might need some updates.

With regard to creating entities from a database, this is covered by "reverse engineering" docs, which need some love--currently tracked by #508. Updating a model when the database changes is not something for which EF Core yet has good support. The work item tracking this is https://github.com/aspnet/EntityFrameworkCore/issues/831

**Comment by ajcvickers** [comment]
Also, see #549 for more details on EnsureCreated.

**Comment by SetTrend** [comment]
Thanks, @ajcvickers, for your valuable help.

Looking at the documentation bits you highlighted at its current state it appears quite a long way for it to go to become helpful, I fear.

**Comment by SetTrend** [comment]
### Let me add a more general, personal, frank note to this thread:
<br>

I feel that Microsoft should supply more budget to provide an in-depth, thoughtful documentation for their products.

I also feel that Microsoft should refrain from following that rather volatile Open Source path of providing their products in fast pace for free.

I base my observation on the fact that I see Microsoft products reaching less and less professional programmers with their new technologies. I'm consulting quite a number of large companies here in Germany and I'm helping them to modernize their software. My observation is that none of their staff is even aware of any new technology in .NET that came up since NuGet and volatile packaging systems like NPM etc. have been invented. And, frankly, no-one there actually want's to use these new technologies because they are so volatile and poorly documented.

I am hired for modernizing, but I cannot get anyone in these teams to like the current way how development software and libraries are spread. It's too jumpy and unreliable to them to get accepted. None of them finally migrates to anything newer than Windows Forms, ASP.NET, DataSets etc.

The teams I'm working with all have a large budget to spend. Even I myself have a large budget to spend - and I really _want_ to spent it! That's why I'm subscribing to an MSDN Enterprise subscription for decades now. We professionals _want_ to pay for Microsoft .NET software technologies! But we also _expect_ a thorough, book-like documentation. We _expect_ long-term development cycles - we **loathe** getting updates from dozens of different packages every other week, changing the grounds we are working with and adding missing features, thereby giving us the feeling that the previous version was unfinished just like the new version will be - which is something we cannot accept in professional software development.
<br>

I would very much appreciate if my observation and perspective shed some light to the development leads at Microsoft, perhaps leading them to re-think their plans from targeting students to targeting bugdet yet sustainability aware professionals.
