### ISSUE TITLE
 two different DbContexts (one DBContext for command and DBContext readonly for querying) sharing the same in-memory DB using the same database name

### ISSUE THREAD

**Issue by BKnown** [aspnet/EntityFramework.Docs#565]
Trying to write a unit test in EF core that uses two different DbContexts (one DBContext for command and DBContext readonly for querying) sharing the same in-memory DB using the same database name.  Doesn't seem to work .....

**Comment by ajcvickers** [comment]
@BKnown This could be a duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/9613. if not, please file a new issue at https://github.com/aspnet/EntityFrameworkCore/issues including a complete code listing or project that reproduces the issue you are seeing.
