### ISSUE TITLE
Document that FromSql should be given composable SQL

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#585]
See https://github.com/aspnet/EntityFrameworkCore/issues/10474#issuecomment-349236822 and potentially mention that for SQL Server there should be no terminating semicolon.

**Comment by WayPoint7** [comment]
After successfully following the guidelines and implementing the examples for my own database, the API runs on the localhost. But after upoloading to Azure I just get an HTTP 200 (OK) in return and an empty JSON file.
What could be wrong?
