### ISSUE TITLE
Improve migrations guidance

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework.Docs#598]
From comments on Tools page:

I posted this on the GitHub site for the project.  They pointed me to a work-around which worked for me.  Add the following line to the "PropertyGroup" section of you project file which contains your `DBContext<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>`

You'll also need to set your startup project to the project with your DBContext file as well (or at least reference it in you actual desired startup project).  It shouldn't care what the startup project is so long as the project is selected as the Default Project within the Package Manager Console, so I believe that this is a bug as well.

**Comment by ajcvickers** [comment]
This is patched, so the workaround is no longer needed.

**Comment by bricelam** [comment]
Fixed in aspnet/EntityFrameworkCore#10298
Startup project documented here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#using-the-tools
