### ISSUE TITLE
Hello,how to do with dbfirst ,thanks!

### ISSUE THREAD

**Issue by nappinglady** [aspnet/EntityFramework.Docs#602]
Hello,how to do with dbfirst ,thanks!  .net core 2.0 mysql

**Comment by ErikEJ** [comment]
You can use my "EF Core Power Tools" Visual Studio extension https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by nappinglady** [comment]
@ErikEJ  Thank you very much, does it  support mysql? please

**Comment by ErikEJ** [comment]
No, but you can try the command line as described here: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell (Scaffold-DbContext command)

**Comment by nappinglady** [comment]
@ErikEJ  thank you very much, there is so fewer message for mysql  db first with .net core.  thank you
