### ISSUE TITLE
How to write a provider

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#61]
One of the specific things we need to cover is what goes in the DatabaseModel object and how that affects the ScaffoldingModel generation. What goes in  TableModel.Indexes ? Should PK indexes be included or ignored? Does ForeignKeyModel.Name need to be unique? etc.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/EntityFramework/wiki/Writing-an-EF7-Provider is really outdated, but might be a good place to start.

**Comment by natemcmaster** [comment]
Paritally done with #121 but the article doesn't cover specific provider APIs.
