### ISSUE TITLE
What's new page for EF Core 2.1

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#620]
Need to decide if we are going to use new pages for 2.0 and 2.1 and/or use a single page per major version under https://github.com/aspnet/EntityFramework.Docs/tree/master/entity-framework/core/what-is-new.

**Comment by mairaw** [comment]
For .NET, we've being doing in one page:
https://docs.microsoft.com/en-us/dotnet/framework/whats-new/
So you can see what it looks like over time.

For C#, it's broken down: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/

**Comment by divega** [comment]
Thanks @mairaw. We went for something similar to C#.
