### ISSUE TITLE
Consider removing wrench topics

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#644]
We have topics that are empty currently under managing database schema. 

According to @mairaw:

> folks really hate wrench topics. we removed all of them from .NET and ASP.NET docs

Unless we consider these up-for-grabs, the only value I guess is to say "we know this is missing". 

Let's discuss in triage.

@mairaw if you can provide more info about folks hating this, that would be great.

**Comment by ajcvickers** [comment]
Triage: Both of the remaining "wrench" issues will be fixed as part of the 2.1 release. We will then not create new wrenches except temporarily while working on the fixup for new docs in new releases.
