### ISSUE TITLE
Invalid column name when implementing delete behavior

### ISSUE THREAD

**Issue by iriza84** [aspnet/EntityFramework.Docs#686]
Hi,

Is this an issue or am I missing something?
I'm trying to implement delete behavior, as consecuence, deleting records is successful, just as I expected BUT when I try to query the data, I get errors like "Invalid column name 'MetricId1'.", of course is invalid because I never created that column, I created MetricId, so why is looking for that column?
As soon as I remove the delete behavior starts working OK, but of course I don't have this feature and I need it. Could you help me please?

OnModelCreated
```
modelBuilder.Entity<Metric>().ToTable("Metric");
            modelBuilder.Entity<Metric>().HasMany(typeof(BoardMetric)).WithOne().OnDelete(DeleteBehavior.Cascade);
```

Metric class
```
public class Metric
{
        [Some properties here]
        [InverseProperty("Metric"), Display(Name = "Boards")]
        public IList<BoardMetric> BoardMetrics { get; set; }
}
```

BoardMetric class
```
public class BoardMetric
{
       [Some properties here]

        [ForeignKey("Metric")]
        public int MetricId { get; set; }

        public Metric Metric { get; set; }
}
```

Metric Table
```
CREATE TABLE [dbo].[Metric](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Some field here]
 CONSTRAINT [PK_Metric] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

BoardMetric table
```
CREATE TABLE [dbo].[BoardMetric](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MetricId] [int] NOT NULL,
	[BoardId] [int] NOT NULL,
 CONSTRAINT [PK_BoardMetric] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
```

Constraints and foreight keys
```
ALTER TABLE [dbo].[BoardMetric]  WITH CHECK ADD  CONSTRAINT [FK_BoardMetric_Board] FOREIGN KEY([BoardId])
REFERENCES [dbo].[Board] ([Id]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BoardMetric] CHECK CONSTRAINT [FK_BoardMetric_Board]
GO

ALTER TABLE [dbo].[BoardMetric]  WITH CHECK ADD  CONSTRAINT [FK_BoardMetric_Metric] FOREIGN KEY([MetricId])
REFERENCES [dbo].[Metric] ([Id]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BoardMetric] CHECK CONSTRAINT [FK_BoardMetric_Metric]
GO
```

**Comment by divega** [comment]
@iriza84 I only read the first paragraph, but if you think this is an issue with the EF Core product, the right repository to report it is https://github.com/aspnet/entityframeworkcore.

**Comment by divega** [comment]
Other than that, the empty call to `WithOne()` is asserting that there is no navigation property going back from BoardMetric into Metric for that relationship, which doesn't match what the InversePropertyAttribute says. Hence I believe what is happening is that the conventions are inferring that there must be two separate relationships and hence a separate shadow property gets created for the second foreign key, named MetricId1.

**Comment by iriza84** [comment]
ok, thanks a lot for your answer
