### ISSUE TITLE
In .NET Core 2.1 you no longer need to manually add DotNetCliToolReference 

### ISSUE THREAD

**Issue by KathleenDollard** [aspnet/EntityFramework.Docs#708]
DotNetCliToolReference for EF are now bundle in the .NET Core 2.1 SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite#feedback)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
Fixed by #806
