### ISSUE TITLE
Please update these docs for EF core 2.1

### ISSUE THREAD

**Issue by touseefbsb** [aspnet/EntityFramework.Docs#716]
EF Core has a lot of new cool features also for UWP so these docs should be updated according to EF Core 2.1
https://www.youtube.com/watch?v=k55kDH_ixrQ

Also the docs seem to be outdated and have some problem following on, please read the comments on the docs page for those errors or difficulties in following along this tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by scout208** [comment]
It looks like the comments have been removed from the page when it got ported over to the new system. Definitely need to update the docs so they work without problem.

**Comment by ajcvickers** [comment]
@touseefbsb Can you be more specific about what is missing?

**Comment by Noemata** [comment]
For the Getting Started sample, the docs should clearly state that the following needs to be in the csproj of the Model part of the project:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>
    <RootNamespace>EFGetStarted.UWP</RootNamespace>
    <AssemblyName>EFGetStarted.UWP.Model</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0" />
  </ItemGroup>

</Project>

Note that the docs here: https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started

Are missing the addition of this: <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>

And the docs are also referring to a dated version of EF.

Please test your instructions before posting them and issues like this will be avoided.

**Comment by Noemata** [comment]
Also, if you are going to provide a useful tip on the docs page, please provide a working sample.  Assumed knowledge only works for the person that has it.


Specifically, this tip:

[!TIP] SaveChanges() performance can be improved by implementing INotifyPropertyChanged, INotifyPropertyChanging, INotifyCollectionChanged in your entity types and using ChangeTrackingStrategy.ChangingAndChangedNotifications.

… should be incorporated into the sample.

**Comment by touseefbsb** [comment]
I think @Noemata  clarifies it up perfectly

**Comment by ajcvickers** [comment]
Closing this in favor of #748. @divega will test the UWP docs for 2.1. to see what is not working.
