### ISSUE TITLE
Include code for Post class in code snippets in tutorial

### ISSUE THREAD

**Issue by mgulsoy** [aspnet/EntityFramework.Docs#717]
By given only the code of entity class Blog.cs, I try this tutorial but getting unwanted results. Please add Post.cs then it would be easier to realize the relation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by lunidev** [comment]
namespace EFGetStarted.AspNetCore.ExistingDb.Models
{
    public partial class Post
    {
        public int PostId { get; set; }
        public int BlogId { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }

        public Blog Blog { get; set; }
    }
}

**Comment by arifjmamun** [comment]
The document should be updated with EF Core 2.1 features. As EF Core 2.1 supports lazy loading, the database scaffolding not generating virtual keyword with navigation property. Its a major issue..that should be considered.

Hope that, the document gets update with desired feature.

**Comment by ajcvickers** [comment]
@mgulsoy Are you saying that when you ran the command to scaffold the database that it did not create the Post.cs class for you? Or, that you think the document should show all the code that is generated?

**Comment by ajcvickers** [comment]
@bricelam @smitpatel Can you help find the issue about reverse engineering navigations as virtual?

**Comment by smitpatel** [comment]
No tracking issue. Added by PR https://github.com/aspnet/EntityFrameworkCore/pull/11949

**Comment by ajcvickers** [comment]
@arifjmamun See the PR linked by @smitpatel above, With this change, reverse engineering now generates virtual navigation properties suitable for lazy loading.

**Comment by ajcvickers** [comment]
Based on listening to @rowanmiller in his current role, we should add the code to the post even though it is generated.

**Comment by mgulsoy** [comment]
@ajcvickers No. My approach is a little bit different. Possibly scaffolding will produce desired results but I want to understand the mechanism first. In my opinion, adding Post.cs will help in understanding the structure easier. Thank you.

**Comment by divega** [comment]
If we end up replacing the ASP.NET Core walkthroughs with existing ASP.NET Core walkthroughs we should keep this suggestion in mind.
