### ISSUE TITLE
How did you reference the model to uwp?

### ISSUE THREAD

**Issue by dineshns** [aspnet/EntityFramework.Docs#720]
How did you reference the model to uwp?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by djaus2** [comment]
I have covered some of the related issues sat:
http://www.embedded101.com/Blogs/David-Jones/entryid/793/Entity-Framework-with-UWP-and-SQLite-Referencing-the-Model

**Comment by djaus2** [comment]
Its a pity that the detailed comments on the original posting of this info were ditched when the info was moved to docs.microsoft.com

**Comment by ajcvickers** [comment]
@dineshns Can you provide some more details as to what you are asking for?

**Comment by dineshns** [comment]
Hi @ajcvickers 

Thank you for asking. Reply of djaus2 has workaround for my issue. I didn't try it yet. hope it works.

**Comment by christianquirante** [comment]
I really hope this documentation is updated, it doesn't work.... I tried following djaus2 workaround but it doesn't work at all for me... it is frustrating...

**Comment by djaus2** [comment]
I have successfully revisited this methodology.
I'll revisit my documentation.
Nb successfully using EFCore V2.1

Sent from my Windows 10 phone

________________________________
