### ISSUE TITLE
Problem with DefaultValueSql when you use postgresql

### ISSUE THREAD

**Issue by Golars** [aspnet/EntityFramework.Docs#721]
Have problem with include sequence to postgresql database. Problem with default value.
"Obtaining the next value is done using the nextval() function instead of the standard's NEXT VALUE FOR expression." from official postgresql documentation (https://postgrespro.com/docs/postgrespro/10/sql-createsequence).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cada79d3-c141-0a42-2fc1-522d7aa408a5
* Version Independent ID: d1afcfe2-99d4-d7bf-f632-17be38cef2e3
* Content: [Sequences - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/sequences)
* Content Source: [entity-framework/core/modeling/relational/sequences.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/sequences.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@Golars Please file this issue against to the PostgreSQL provider: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL
