### ISSUE TITLE
Is a transaction necessary for a single create, update or delete statement?

### ISSUE THREAD

**Issue by bhlee90** [aspnet/EntityFramework.Docs#723]
Is a transaction necessary for a single create, update or delete statement? If there is an on delete cascade for a foreign key in a table when the primary key in another table that the foreign key references is deleted, would a transaction be necessary, then? I know that a transaction is necessary for more than one create, update or delete statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions#feedback)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
The behavior may be database specific. By default, SQL Server is in _autocommit_ mode, which means that single statements are wrapped in transactions automatically. But we have found that skipping the API calls to explicitly create and commit the transaction when SaveChanges only affects one row has no perceptible performance benefits.
