### ISSUE TITLE
ASPNETCORE_ENVIRONMENT not being honored

### ISSUE THREAD

**Issue by univhack** [aspnet/EntityFramework.Docs#724]
One of the tips in the documentation is to set ASPNETCORE_ENVIRONMENT but as shown in this github issue that variable is not being monitored by EF. https://github.com/aspnet/EntityFrameworkCore/issues/7353

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [Package Manager Console (Visual Studio) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#using-the-tools)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@univhack If you are still having problems with this, then please file a new issue on https://github.com/aspnet/EntityFrameworkCore/issues including a runnable project/solution and complete steps to reproduce the behavior you are seeing.
