### ISSUE TITLE
Error Trying to use authentication in ASP.Net Core with EFCore

### ISSUE THREAD

**Issue by Iymcjames** [aspnet/EntityFramework.Docs#732]
Hello am new to ASP.Net Core( ASP.Net in general) I have followed the series of online tutorial and met with this error after using EF (DB first) with ASP.NET core.
If i run it ..I get this

![error](https://user-images.githubusercontent.com/24244713/40842269-36e80f1e-65a5-11e8-91f8-c3c83d2b1d36.PNG)

-After uninstalling Microsoft.VisualStudio.Web.CodeGeneration.Design from Package Manager Console.
It runs fine but when trying to add a new controller..I get this error

![error 2](https://user-images.githubusercontent.com/24244713/40842352-8760370a-65a5-11e8-9930-7d2791159425.PNG)

Please Help

**Comment by ajcvickers** [comment]
@Iymcjames It looks like you need to update to the latest .NET Core SDK and Visual Studio 15.7.3. If this does not solve the issue, then I would consider filing an issue on https://github.com/aspnet/Scaffolding/issues which is where ASP.NET scaffolding issues are tracked.
