### ISSUE TITLE
Out of date information on Getting Started page

### ISSUE THREAD

**Issue by fmorriso** [aspnet/EntityFramework.Docs#733]
As of June 1, 2018, the information on getting started with EF Core at link https://docs.microsoft.com/en-us/ef/core/get-started/install/ still shows information for EF Core 2.0 instead of the latest EF Core 2.1, which, if I understand correctly, has changed significantly since that page was last updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5747ad3-edd5-1977-883c-2cf77112306c
* Version Independent ID: d66d0616-2aa2-8be4-5ab6-24201ef00b59
* Content: [Installing EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/install/)
* Content Source: [entity-framework/core/get-started/install/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/install/index.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by fmorriso** [comment]
For example, instead of a DbIntitialize class with a method to seed the data, EF.Core 2.1 has a new, buiilt-in HasData() method.  Using the Angular Tour of Heroes as an example, assuming entity Hero is defined with an Id, Name and Created fields, it could be seeded with data using code similar to the following:

`		
               protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			// https://docs.microsoft.com/en-us/ef/core/modeling/relational/columns
			modelBuilder.HasDefaultSchema(DBGlobals.SchemaName);

			modelBuilder.Entity<Hero>()
				.ToTable(nameof(Hero));

			modelBuilder.Entity<Hero>()
				.Property(p => p.Id)
					.HasColumnType(nameof(SqlDbType.BigInt))
					.UseSqlServerIdentityColumn();

			modelBuilder.Entity<Hero>()
				.Property(p => p.Name)
					.HasMaxLength(100)
					.IsUnicode(false) // varchar, not nvarchar
					.IsRequired(true);

			modelBuilder.Entity<Hero>()
				.Property(p => p.Created)
					.HasDefaultValueSql("GetUtcDate()");

			DateTime currentDateTime = DateTime.UtcNow;

			modelBuilder.Entity<Hero>().HasData(
				new Hero { Id = 1, Name = "Mr. Nice" , Created = currentDateTime},
				new Hero { Id = 2, Name = "Narco", Created = currentDateTime },
				new Hero { Id = 3, Name = "Bombasto", Created = currentDateTime },
				new Hero { Id = 4, Name = "Celeritas", Created = currentDateTime },
				new Hero { Id = 5, Name = "Magneta", Created = currentDateTime },
				new Hero { Id = 6, Name = "RubberMan", Created = currentDateTime },
				new Hero { Id = 7, Name = "Dynama", Created = currentDateTime },
				new Hero { Id = 8, Name = "Dr IQ", Created = currentDateTime },
				new Hero { Id = 9, Name = "Magma", Created = currentDateTime },
				new Hero { Id = 10, Name = "Tornado", Created = currentDateTime }
			);

			base.OnModelCreating(modelBuilder);
		}`

**Comment by ajcvickers** [comment]
Triage: We should update Getting Started to use the new seeding, if appropriate.

**Comment by AndriySvyryd** [comment]
`HasData` should only be used to seed entities that are part of the model and should be managed by migrations. Test data should be added using `SaveChanges`.

**Comment by divega** [comment]
It seems the installation page is now up to date. Also, per the conversation here, we are not covering data seeding scenarios in the tutorials.
