### ISSUE TITLE
Update walkthroughs for 2.1

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#734]
We are recommending to set DotNetCliToolReference and referring to the 2.0 SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@divega This article was fixed by #806 but the title refers to multiple walkthroughs, which is a dup of #748 
Should we go ahead and close this one?

**Comment by divega** [comment]
Yes. I agree. Closing in favor of  #748.
