### ISSUE TITLE
Investigate possible issue with connection string or missing additional steps in .NET Core new db tutorial with SQLite

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#735]
I got a report saying that if you follow this instructions migrations commands will create a database on the root folder but then execution will try to look for the database file in bin\debug, which will make the application crash. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Starkie** [comment]
We've tested it and apparently is related to how you execute the project:

- Executing the project from a powershell console using `dotnet run` works great.
- Executing the project from visual studio doesn't work. Throwing a `Microsoft.Data.Sqlite.SqliteException` with the error message ` SQLite Error 1: 'no such table: Blogs'.`
- Similarly, entering the `/bin/debug/netcoreapp2.1` and running `dotnet TestCoreApp.dll` gives the same error.

It seems to be an inconsistency in the way dotnet and visual studio handle the local working directory. So... Changing it from the Project Settings > Debug > Working Directory and setting the path to the root of the project, makes it work again.

Should the tutorial be updated?

**Comment by divega** [comment]
@Starkie well, we could add a note to the walkthrough saying that if you choose to use VS, you can set the working directory manually to be the root of the project, but the truth is that the whole walkthrough currently only covers the instructions for building the app using the command-line tools, so not sure how much value there is in mentioning VS just for this.

Anyway, I agree there is an inconsistency in the working directory between what you get using dotnet command-line and VS, and I am trying to figure out the right place to report it (I doubt it is by-design). 

@DamianEdwards does this ring any bells? Any suggestion on where to report it?

**Comment by divega** [comment]
cc @BillHiebert as he changed this on https://github.com/dotnet/project-system/pull/3073.

**Comment by BillHiebert** [comment]
@Pilchie  - I made the change, but I wasn't the driver for it. If I recall, it was to be consistent with the full framework console project.

**Comment by divega** [comment]
Thanks @BillHiebert, @Pilchie, @davkean: I went ahead and created https://github.com/dotnet/project-system/issues/3619 on your side. 

I will keep this documentation issue open to decide how/if to update the docs after the outcome of https://github.com/dotnet/project-system/issues/3619 is known.

Note to self: the article contains a note that talks about paths in the connection string being relative to the output path, which supposedly became obsolete in 2.0, but may have become relevant again.
