### ISSUE TITLE
Does CommitableTransaction need a Rollback call?

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework.Docs#738]
I was unfamiliar with the difference between TransactionScope and CommitableTransactio and found this in the MS Docs ( https://docs.microsoft.com/en-us/dotnet/framework/data/transactions/implementing-an-explicit-transaction-using-committabletransaction) which says "Unlike the TransactionScope class, the application writer needs to specifically call the Commit and Rollback methods in order to commit or abort the transaction.". I haven't had a chance to try this feature out yet, but was wondering if, based on this description,  does it really auto-rollback when disposed or do we need to call transaction.Rollback() in here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1073c238-9389-d826-a696-f1108a4f2ce0
* Version Independent ID: cf56babd-def0-d76e-8eee-e33341b6a009
* Content: [Transactions - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/transactions)
* Content Source: [entity-framework/core/saving/transactions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/transactions.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@julielerman I don't know the answer to your question (have you tried it?) but I'm curious why is it that you want to use CommitableTransaction?

**Comment by julielerman** [comment]
I will try it tomorrow. It wasn't because I have a need for it but because I'm reading the docs and trying to learn from them and that was one of the examples in the docs. I didn't notice much difference between the ambient and commitable examples so started reading up on it.

**Comment by julielerman** [comment]
It did indeed rollback.  So I don't understand the doc that said you need to do it explicitly. :(
Need to make openconnection called before enlisttransacdtion call BTW. Guess I'll do a PR for that.
Also there are a bunch of projects that aren't updated for 2.1...e.t., the aspnetcore projects. I just removed the test and the UWP after over an hour fighting packages and trying to build. That is too convoluted for me to do a PR on that though.
