### ISSUE TITLE
Test all the walkthroughs with 2.1 release

### ISSUE THREAD

**Issue by Noemata** [aspnet/EntityFramework.Docs#748]
Using VS2017 15.7.3 with latest EF components fails when using the above documentation.  Add-Migration MyFirstMigration does nothing other than rebuilding the solution with the Model.  Please address this ASAP.  This is about the 5th reboot on EF for UWP, and each time the documentation is lacking to get to a working state.

How was this missed?

`<PropertyGroup>
   <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
 </PropertyGroup>`

**Comment by Noemata** [comment]
How was this missed in the docs?

<PropertyGroup>
   <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
 </PropertyGroup>

**Comment by Noemata** [comment]
"<PropertyGroup>
<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
 </PropertyGroup>"

**Comment by Noemata** [comment]
`<PropertyGroup>
   <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
 </PropertyGroup>`

**Comment by Noemata** [comment]
The docs for UWP located here are incomplete: https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started

There are at least two critical steps details missing.  Given this is the 5th reboot on the UWP EF docs, and they were never correct out of the gate, could someone please follow their own instructions to see what the various issues are.

There is also a step missing for creating the initial DB.

How/Why do we keep cycling through repeated mistakes on EF/UWP documentation?  With each update to EF, the UWP side of the documentation is invalidated.  Please keep releases in sync with documentation.

**Comment by ajcvickers** [comment]
Triage: @divega to test the walk-though.

**Comment by ajcvickers** [comment]
@Noemata Some of the guidance/links here may help: https://github.com/aspnet/EntityFrameworkCore/issues/10549

**Comment by Noemata** [comment]
@ajcvickers, please read what has been posted.  The very first item I provided has the same content as your suggested help item.  I guess this is part of the problem, posted content isn't being read fully.  Skimming is for speed readers, not for mere mortals ;-)

**Comment by smitpatel** [comment]
It was missed (or rather excluded) since it is a _work-around_ to an issue which happened in .NET Core release and which has been already fixed in 2.0.x as per https://github.com/aspnet/EntityFrameworkCore/issues/10298
Once bugs are fixed and packages are released to publics, work-arounds shouldn't be documented since customers should be using latest stable set of packages. (at least for patch).

**Comment by Noemata** [comment]
When you have privileged access to working solutions it's unwise to impose your privilege on others.  At present, the docs provided don't work for mere mortals that must use what is generally available.  This is a long standing issue with Microsoft.  It's entirely possible these docs have consistently been one step behind what Microsoft folks use internally, and thus consistently incomplete to the rest of us as a result.

**Comment by smitpatel** [comment]
The _current release_ for SQLite package is 2.1.0 & 2.0.3 according to https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite/
Both of those release has bug fix included which removes requirement of adding such work-around. If you are still seeing that you need to add `GenerateRuntimeConfigurationFiles` in csproj with _current public release_ then please file issue with detailed repro steps at https://github.com/aspnet/EntityFrameworkCore/issues

**Comment by ajcvickers** [comment]
Assigning to @divega to test the walkthrough, especially with reference to whether the workaround described above is still needed for 2.1.

**Comment by ajcvickers** [comment]
Triage: re-purposed this to a more general test walkthroughs issue. Also, when updating walkthroughs, try to make them less version dependent in both tone and content.

**Comment by ajcvickers** [comment]
Consider case in #781 when working on this.

**Comment by Code-ScottLe** [comment]
What is the status for this one? I am currently seeing a lot of mixed says in this (whether we need the `GenerateRuntimeConfigurationFiles` or not, or even modifying the `.csproj` [with additional targeting framework](http://thedatafarm.com/data-access/the-secret-to-running-ef-core-2-0-migrations-from-a-net-core-or-net-standard-class-library/) that isn't mentioned anywhere in the official docs.

This really hindered anybody who is new (myself included) on integrating EF Core into UWP.
