### ISSUE TITLE
When does Lazy Load trigger

### ISSUE THREAD

**Issue by tbrownio** [aspnet/EntityFramework.Docs#751]
It would be helpful to understand when lazy loading is triggered. Perhaps you can provide a quick blurb explaining how how/when this occurs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@thetylerb Can you be more specific? That is, are you saying that it is not clear that lazy-loading happens when the navigation property is accessed, or that you want more details about when using lazy-loading causes a database access?
