### ISSUE TITLE
Add-Migration - Unable to create an object of type DbContext error

### ISSUE THREAD

**Issue by AlissonRS** [aspnet/EntityFramework.Docs#752]
I'm trying to add the first migration with EF Core by running this command in the cmd (Developer Command Prompt VS 2017):

`dotnet ef migrations add InitialCreate`

I was pointing to my project's folder containing the `DbContext` class (not the solution folder), but this gives me an error:

`Unable to create an object of type 'MyDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<MyDbContext>' to the project`

Also tried running `Add-Migration InitialCreate` in the **Package Manager Console** like the old days, but the same error was displayed.

How can I solve this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/index)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@AlissonRS Can you file a new issue on https://github.com/aspnet/EntityFrameworkCore/issues including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by OblivionSY** [comment]
This link was the helpful solution to this: https://github.com/aspnet/EntityFrameworkCore/issues/9467

**Comment by TehWardy** [comment]
Similar issue ...  https://github.com/aspnet/EntityFrameworkCore/issues/16446
