### ISSUE TITLE
FluentAPI code example missing

### ISSUE THREAD

**Issue by mehrt** [aspnet/EntityFramework.Docs#76]
I had a look at the new docs after the release of rc1.

http://docs.efproject.net/en/latest/modeling/relational/inheritance.html#fluent-api says:
"You can use the Fluent API to configure the name and type of the discriminator column and the values that are used to identify each type in the hierarchy."

But, unlike all the other features described, this one has no example code.

**Comment by rowanmiller** [comment]
It was a casing issue in the include directive. It built without issue on Windows, but the docs for the site build on Linux and it was failing to be included there. 

Fixed in https://github.com/aspnet/EntityFramework.Docs/commit/aef9fc2c36a38b4333dcf3d09661bc7edfcfa2c6
