### ISSUE TITLE
Typo in lazy loading with lambda usage section

### ISSUE THREAD

**Issue by Alazari-main** [aspnet/EntityFramework.Docs#760]
public ICollection<Post> Posts
    {
        get => LazyLoader?.Load(this, ref _posts); // should be 'Invoke(...)' here
        set => _posts = value;
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@Alazari-main Can you explain why you think Invoke is needed/better here?

**Comment by Alazari-main** [comment]
@ajcvickers, Yes, I can. Because I took this code from section where "LazyLoader" is provided as a Delegate (Action<object, string> in our case) and there is no `Load` method for the `Action` delegate

**Comment by ajcvickers** [comment]
@Alazari-main The doc says, "The code above uses a Load extension method to make using the delegate a bit cleaner:" and then shows the extension method.

**Comment by Alazari-main** [comment]
Ok. I'm blind. There was a misunderstanding from my side. Thank you for an explanation
