### ISSUE TITLE
Question if maxlength affect the datatype

### ISSUE THREAD

**Issue by evanlarsen** [aspnet/EntityFramework.Docs#761]
If we use the DataAnnotation or Fluent API for MaxLength of 50 on a string value does that set the SQL datatype to nvarchar(50) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b143a3f-aecb-49b6-66e1-0c459af0e2de
* Version Independent ID: 1b594bfc-f0a3-4938-a415-50ea34805d8e
* Content: [Data Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/data-types#feedback)
* Content Source: [entity-framework/core/modeling/relational/data-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/data-types.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@evanlarsen Yes, assuming that EF is being used to create the database through either Migrations or an EnsureCreated call.
