### ISSUE TITLE
Writing, or even reading directly with RDMS Tables is a Security and Extensible nightmare rightfully banned in many shops 

### ISSUE THREAD

**Issue by davidekarasek** [aspnet/EntityFramework.Docs#763]
Writing, or even reading directly with RDMS Tables is a Security and Extensible nightmare rightfully banned in many shops.  We had a workable solution in EF6 to generate C# structures automatically from stored procedures as complex types.  Where is it in .Net Core? Why did we abandon this?  Just to keep developers employed writing CRUD data access layers in C# manually? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@davidekarasek Stored-proc mapping is tracked by https://github.com/aspnet/EntityFrameworkCore/issues/245.
