### ISSUE TITLE
Examples would be nice addition

### ISSUE THREAD

**Issue by cwsDavid** [aspnet/EntityFramework.Docs#765]
For Scaffold-DbContext, an example of stringing together parameters with the command would be nice, especially for -Schemas or -Tables that take a list. Also illustrating use of -Project and -StartupProject with -OutputDir and -ContextDir to show a semi real-world use would probably be useful to may just starting with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [Package Manager Console (Visual Studio) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#using-the-tools)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
Covered by #508
