### ISSUE TITLE
Text-based query language (e.g. Entity SQL)

### ISSUE THREAD

**Issue by miksh7** [aspnet/EntityFramework.Docs#767]
It shows 1.0 in EF6 column, is it correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc2d1a4-a434-69f9-3df3-9818c571c978
* Version Independent ID: a272636c-100d-fb7b-d7a9-713adc0b2b8e
* Content: [EF Core & EF6 Feature by Feature Comparison](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features)
* Content Source: [entity-framework/efcore-and-ef6/features.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/features.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Fixed in https://github.com/aspnet/EntityFramework.Docs/commit/153ba9f76399dcbe021d667e32bc404bac181bff. Thanks!
