### ISSUE TITLE
Document how to combine query filters

### ISSUE THREAD

**Issue by dazinator** [aspnet/EntityFramework.Docs#768]
Can you keep calling .HasQueryFilter()ont he same entity type to add multiple filters? Will they use an AND conjunction to stack, or does the last one overwrite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **anpete**

**Comment by smitpatel** [comment]
Last one wins. You would need to do conjunction yourself before passing in lambda.

**Comment by NetTecture** [comment]
That is a seriously lacking design. I have to write an API where we have 3 optional filters per object. That is 8 combinations. 8 methods instead of 3 - that is nearly 3 tiem the work.

**Comment by TrieBr** [comment]
The docs seem to be misleading by implying that stacking filters work by including the example code:

```
modelBuilder.Entity<Blog>().HasQueryFilter(b => EF.Property<string>(b, "TenantId") == _tenantId);
modelBuilder.Entity<Post>().HasQueryFilter(p => !p.IsDeleted);
```

Took me a while to figure out that they do not stack. It should be added that this is not supported and you have to build your conjunction manually. This is a big problem for me because I have `HasQueryFilter` called from various classes/extensions that don't necessarily have a clear path to provide a conjunction manually.

**Comment by smitpatel** [comment]
@TrieBr - I am not sure what you mean by posting that example code. The example is configuring filters for different entity types and nowhere implying that they stack.

**Comment by TrieBr** [comment]
@smitpatel Ah, my bad I see that now.

**Comment by dazinator** [comment]
Still I remember when first using this feature - it's easy to assume that adding multiple filters would stack. Years of using grid systems - when you add multiple filters - one never overrides or replaces another. I know EF isnt a grid but still it's a trap for the unwary. I'd love for query filters api to make this more explicit by offering more of a filter builder experience when registering filters (and / or conjunctions)

**Comment by roji** [comment]
#10275 tracks adding the ability to define multiple query filters.

Have submitted #1674 to add a note on multiple filters not being supported and suggesting the workaround.
