### ISSUE TITLE
Document on how to store owned types in separate tables

### ISSUE THREAD

**Issue by davidliang2008** [aspnet/EntityFramework.Docs#772]
To store `OrderDetails` into separate tables, should it call `ToTable` on OrderDetails entity instead of on `Order` entity?

On the document:
```c#
modelBuilder.Entity<Order>().OwnsOne(p => p.OrderDetails, od =>
    {
        od.OwnsOne(c => c.BillingAddress);
        od.OwnsOne(c => c.ShippingAddress);
    }).ToTable("OrderDetails");
```

Should it be:
```c#
modelBuilder.Entity<Order>().OwnsOne(p => p.OrderDetails, od =>
    {
        od.OwnsOne(c => c.BillingAddress);
        od.OwnsOne(c => c.ShippingAddress);

        od.ToTable("OrderDetails");
    });
```

**Comment by davidliang2008** [comment]
Oh ok coz I didn't try executing the code myself. Thanks for clarifying 👍

**Comment by AndriySvyryd** [comment]
@smitpatel When the overload with nested lambda is used the returned builder is the original one, so it does make a difference in this case.
@davidliang2008 The second snippet is the right one for your scenario.

**Comment by davidliang2008** [comment]
Oh then the example on the Microsoft doc is indeed wrong then.
