### ISSUE TITLE
Provide an example in remove a selected item

### ISSUE THREAD

**Issue by joaosantana** [aspnet/EntityFramework.Docs#774]
The given examples shows how to remove the first or the last entities, but no code example is supplied for a entity between them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f8db8b-8ee6-86c9-7cb2-b5802214ec13
* Version Independent ID: b959839c-684e-5d60-650e-0af17c971c79
* Content: [Basic Save - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/basic#updating-data)
* Content Source: [entity-framework/core/saving/basic.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/basic.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@joaosantana Using First and Last is just a convenient way of getting a single entity for the example. You could instead query for the entity in any other way. For example, to delete an entity with a specific key:
```C#
var blog = context.Blogs.Find(1);
context.Blogs.Remove(blog);
context.SaveChanges();
```

**Comment by joaosantana** [comment]
*necrotic powers* Thank you for the explanation. EF is completely new to me. *necrotic powers fades*
