### ISSUE TITLE
Document behaviors and conventions for navigation properties and backing fields

### ISSUE THREAD

**Issue by orobert91** [aspnet/EntityFramework.Docs#775]
What about navigational properties? What is the behavior with those? Seems like EFCore completely ignores the convention when the property is configured a navigational property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e162696-b19f-d73f-8b1f-d1b4c3048b62
* Version Independent ID: a83e4fb5-e4ae-a46f-7248-487ea2679ac5
* Content: [Backing Fields - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field)
* Content Source: [entity-framework/core/modeling/backing-field.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/backing-field.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@orobert91 Navigation properties use the same convention. If this isn't working, then please file a new issue on https://github.com/aspnet/EntityFrameworkCore/issues including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by ajcvickers** [comment]
Clarify that navigation properties are by convention always set through the property even if the field has been discovered. This is because setting navigation properties is never considered to be part of entity materialization (because you have to have two materialized entities before a navigation can be set) but this is something that is more due to implementation than an intended conceptual choice.

**Comment by orobert91** [comment]
I think you should consider writing to backing fields the default behavior, whether it's for materialization or setting a navigation. When developer declares a backing field, there's a high chance it's because the getter and setter contains other logic. Also, it keeps everything consistent and will not pollute the DbContext model creation with SetPropertyAccessMode(). Anyway, thanks for clarifying the docs.

**Comment by ajcvickers** [comment]
@orobert91 We were discussing the same thing recently. I filed #12430

**Comment by TristanApc** [comment]
I am similarly confused as to how we can use navigation properties with backing fields.

My navigation getter is private but when it comes to querying the entity with LINQ I stumbled on a few set back.

My user have a navigation to an entity named "Account" and the entity account have a navigation to "Billing".

Using EF.Property to refer to the navigation property throw me an exception

> The Include property lambda expression 'x => Property(x, "Account")' is invalid. The expression should represent a property access: 't => t.MyProperty'.

Using EF.Property for my ``Where`` condition tells me that it can only be used within LINQ queries, but it is being used inside one.

> System.InvalidOperationException: The EF.Property<T> method may only be used within LINQ queries.

```csharp
var usersQuery = _userManager.Users
    .Include(x => EF.Property<Account>(x, nameof(x.Account))) // throws
    .ThenInclude(x => x.Billing)
    .Where(nameof(Account) x => EF.Property<Account>(x, nameof(x.Billing)).IsOwned); // throws

var result = await usersQuery.ToArrayAsync();
```

And while I can use the string method with a combination of ``nameof()`` to keep my type safety, ``ThenInclude`` is not an extension that exists within that context and ``Where`` require a lambda anyway. 

I'm not sure what to do.

```csharp
var usersQuery = _userManager.Users
     .Include(nameof(ApplicationUser.Account))
     // .ThenInclude(x => x.Billing) the method doesn't exists
     .Where(x => EF.Property<Account>(x, nameof(x.Billing)).IsOwned); // throws

var result = await usersQuery.ToArrayAsync();
```

The page on backing fields need more documentation.

**Comment by ajcvickers** [comment]
Consolidated into #699
