### ISSUE TITLE
Ambiguity Big at Microsoft

### ISSUE THREAD

**Issue by crtjr64** [aspnet/EntityFramework.Docs#776]
The unfortunate side of people who are not well versed with the nuances of the English language in America regardless of where they come from, ambiguity creeps into instruction "from the application's service provider" Makes me think  Verizon plays a part in my code...I know it doesn't but it means that its reference remains ambiguous and a waste of my very valuable time. If it comes from the calling program, please say so

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa64390-1232-8dd3-f170-7d5c68e29ad9
* Version Independent ID: 245bbba8-3102-4a66-15eb-650e05eb9e62
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation#from-application-services)
* Content Source: [entity-framework/core/miscellaneous/cli/dbcontext-creation.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dbcontext-creation.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@crtjr64 Thanks for the feedback. Given that the "application" is, well, the application, and the service provider in ASP.NET is the object that the application has that implements IServiceProvider, it's not clear to me what language choices could have been used to improve this, but if you have suggestions they are most welcome.

**Comment by wadebee** [comment]
My guess at original commenter is that Service is such an overloaded term (eg: Web Services, Micro/Mini services, no D/I services). I know Autofac used the term in their D/I as well but as an developer working on mini-services, I sure wish MS would have went with the terms dependencies and dependency providers rather than services and service providers.

**Comment by sadqiang** [comment]
In Asp.net Core 2.1, CreateWebHostBuilder replaces BuildWebHost.
