### ISSUE TITLE
IDbContextFactory<TContext> Interface should explain why it is obsolete

### ISSUE THREAD

**Issue by martingbrown** [aspnet/EntityFramework.Docs#777]
This post states that the IDbContextFactory&lt;TContext&gt; interface is obsolete. I'm looking this up because I don't really know what it does and I've found it in some legacy code. It would be nice to have a description here of why it is obsolete and what should be used instead or whether it can simply be ignored. Also it would be nice to know which version of EntityFramework it became obsolete in.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99875b51-3c42-aa1b-f182-32e22936bf9f
* Version Independent ID: c6809647-7e00-8954-dfbd-c001666791af
* Content: [IDbContextFactory&lt;TContext&gt;(DbContextFactoryOptions) Interface (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-gb/dotnet/api/microsoft.entityframeworkcore.infrastructure.idbcontextfactory-1?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/IDbContextFactory`1.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/IDbContextFactory`1.xml)
* GitHub Login: @dotnet-bot

**Comment by ajcvickers** [comment]
@martingbrown It has been replaced with https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.idesigntimedbcontextfactory-1?view=efcore-2.1 which should be used instead, as indicated by the test in the Obsolete attribute, which is shown in the docs.

**Comment by weitzhandler** [comment]
@ajcvickers 
Hi Arthur and thanks for your reply,

I'm working on a multi tenant system, and I wanted to use `IDbContextFactory` to generate context with connection string according to current tenant, what's the alternative since `IDbContextFactory` is obsolete?
Is there a general guide for developing multi-tenant apps with EF Core?

Thanks!

**Comment by ajcvickers** [comment]
@weitzhandler It was renamed to `IDesignTimeDbContextFactory` to indicate that it is intended for design-time use. Feel free to create your own interface if you need a factory for some other reason.

Unfortunately, the term "multi-tenant" can mean different things to different people when you get down to the specifics of what is shared and how between different tenants. If you're using a separate database for each tenant, then it's usually just a matter of picking the correct connection string, which is in turn dependent on how the connection strings are obtained. EF usually doesn't have any role to play in this.

**Comment by weitzhandler** [comment]
Thanks for your reply.
I was way to have a `DbContext` with a custom connection string per tenant. I think I'm gonna use `SqlServerOptionsExtension` for that.

**Comment by weitzhandler** [comment]
Thanks for your reply.
I was way to have a `DbContext` with a custom connection string per tenant. I think I'm gonna have my `DbContext` rely on a custom `DbContextOptions<DbContext>` for that, would love to hear if there are better ways.

**Comment by weitzhandler** [comment]
Actually I'm just gonna override `OnConfiguring` in the `DbContext`.

**Comment by weitzhandler** [comment]
Thanks for your reply.
I'm trying to create an `IDesignTimeDbContextFactory` with a DI dependent constructor, but when trying to add migrations in the PM I get the following exception:

> PM> add-migration InitialCreate -context AppDbContext
> System.MissingMethodException: No parameterless constructor defined for this object.
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_1.<FindContextTypes>b__9()
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> No parameterless constructor defined for this object.
> PM>

Someone has asked [the same question](https://stackoverflow.com/questions/46587202/constructor-injection-into-idesigntimedbcontextfactory) on SO.

**Comment by weitzhandler** [comment]
Found your answer [here](https://github.com/aspnet/EntityFrameworkCore/issues/9467).
You rock @ajcvickers!
