### ISSUE TITLE
.Net Core 2.1 SDK changes?

### ISSUE THREAD

**Issue by rolandgpainter** [aspnet/EntityFramework.Docs#781]
Hi, thanks for this walk through. I had a few issues trying to get started with it, and noticed a few other differences along the way, might be because I'm using .Net Core 2.1 SDK not 2.0?
* Trying to run the Install-Package commands generated errors saying there was a version mismatch and that I should add it to the project only. In a one project solution that is not an option. Turns out that the first two are already installed, and for the third one I had to use the "Manage Packages for solution..." in order to select version 2.1.0 not latest stable 2.1.1.
* The second OnConfiguring method code snippet is missing some lines.
* Is scaffolding now enabled by default? I did not get anything about Full Dependencies or the readme.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#blogging-database)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by rubekon** [comment]
Getting the same issue as above.  Also when I try to create the controller, I get the message "Method Not Found: Void"

**Comment by ajcvickers** [comment]
Triage: tracking this through #748

**Comment by chengchengba** [comment]
Dont care the Full Dependencies , I didn't find it either, just go to below steps directly, it works
Now that scaffolding is enabled, we can scaffold a controller for the Blog entity.

Right-click on the Controllers folder in Solution Explorer and select Add -> Controller...
Select MVC Controller with views, using Entity Framework and click Ok
Set Model class to Blog and Data context class to BloggingContext
Click Add
