### ISSUE TITLE
Lazy loading without proxies - cant instantiate object not attached to context

### ISSUE THREAD

**Issue by Antevirus** [aspnet/EntityFramework.Docs#782]
Hello.

This is not a bug, but an issue that i stumbled upon today.

When i instantiate objects not attached to the context they get a NULL value, when lazy loading without proxies is used, according to your documentation examples.

Lets look at the Blog and Post classes in your documentation from this page:
https://docs.microsoft.com/en-us/ef/core/querying/related-data

This is how Posts is retrieved inside the Blog class:
```
    public ICollection<Post> Posts
    {
        get => LazyLoader?.Load(this, ref _posts);
        set => _posts = value;
    }
```

LazyLoader? will give me NULL if not attached to the context. Therefor i cant assign a value to it:
`blog.Posts = new ICollection<Posts>(); // <- will be NULL`

I didnt notice this at first, but its quite obvious when you think about it. Its not a bug, but took a while for me to spot. I dont want anyone else to stumble upon this problem and possibly spend hours figuring out what the issue was :-)

My workaround:
```
    public ICollection<Post> Posts
    {
        get 
        {
            if(LazyLoader != null)
            {
                LazyLoader.Load(this, ref _posts);
            }
            
            return _posts;
        }
        set => _posts = value;
    }
```

Keep up the great work! :-)

Thanks

**Comment by ajcvickers** [comment]
@Antevirus Thanks for pointing this out. Actually, the null propagation operator should not have been used in that call--see PR and description here: https://github.com/aspnet/EntityFramework.Docs/pull/783
