### ISSUE TITLE
Clarify when to use tracking versus no-tracking queries

### ISSUE THREAD

**Issue by MohammadMQ** [aspnet/EntityFramework.Docs#788]
I would like this article to mention a little about whether to use tracking on web pages where the environment is pr. default disconnected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ffc114-df51-0be7-8972-6fcead14e011
* Version Independent ID: 94c34571-7314-aab1-7898-93ac6d0f3430
* Content: [Tracking vs. No-Tracking Queries - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/tracking)
* Content Source: [entity-framework/core/querying/tracking.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/tracking.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
Fixed in #1837 
The tracking documentation mentions about it a little. I am not sure if there is value in listing each scenario because even in the scenario things may be different from default based on usage.
