### ISSUE TITLE
ASP.NET Core Example does not work.

### ISSUE THREAD

**Issue by MFry** [aspnet/EntityFramework.Docs#789]
The ASP.NET core example will throw an exception in ASP.NET Core 2.1 with EF Core 2.1. Which will throw the System.InvalidOperationException.
With the message:
 'No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions&lt;TContext&gt; object in its constructor and passes it to the base constructor for DbContext.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by MFry** [comment]
It looks like I was just missing the constructor within a controller. 
If you are going to migrate the default generated connection string don't forget to add to each controller
```
public class SomeController : Controller
{
   // This is needed
    private readonly YourContext _context;

    public SomeController(YourContext context)
    {
         _context = context;
     }
    // Routing and Controller logic...
}
```

**Comment by nadcraker** [comment]
Why isn't this code included in the example if it is needed?
