### ISSUE TITLE
Show DbContext definition including db.BlogPostsCounts property in code snippets

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/EntityFramework.Docs#793]
You don't define where or how to setup db.BlogPostCounts after the query type is defined in OnModelCreating so it comes out of thin air with no way to know how you're supposed to define it. If you add a DbSet with the type BlogPostsCount you'll get an invalidOperationException saying that an entity type with the same name already exists. As a result this sample is not at all clear and cannot lead to success for the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **anpete**

**Comment by ajcvickers** [comment]
@JohnGalt1717 Thanks for reporting this--we will update the document. BlogPostCounts should be defined as a `DbQuery` property on the context:
```C#
public DbQuery<BlogPostCount> BlogPostCounts { get; set; }
```

**Comment by markusschaber** [comment]
It's defined in the linked complete sampel code on GitHub, but I've also been confused by how the article itself skips over this detail... :-(

**Comment by bayangan** [comment]
I found the sample code in https://github.com/aspnet/EntityFrameworkCore/tree/master/samples/QueryTypes

**Comment by DanJ210** [comment]
I agree to the above posts about getting confused with not using the standard `DbSet<>` that I'm used to but instead using the `DbQuery<>` for this specialized situation. I read that the doc was supposed to get updated with this new information and that was over a month ago? I spent an hour trying to figure things out myself before deciding to come here for assistance only to luckily find that I'm not the only one who has run into this.

Before thinking that only a few people have had trouble with this... Image the amount of people who completely give up or don't waste the time to come here and find out there's missing info. Supposedly if a web page doesn't load in 3 second then you've already lost 50% of users. Apply that to how many people would spend 10 minutes trying to figure out the missing code after reading the docs thoroughly.

Just a thought.

**Comment by janis-veinbergs** [comment]
@DanJ2010 it's actually stated in the doc:
> Are mapped on the DbContext through properties of type DbQuery<T> rather than DbSet<T>

But @ajcvickers actually commented that the documentation will include the codeline too.

**Comment by DanJ210** [comment]
@janis-veinbergs Sorry but I was pretty frustrated. I didn't see anything about DbQuery and I've followed docs like that for a long time and scanned over them a few times and still didn't see anything. Not sure why I'm blind or it's so hard to find but in the end I didn't see it.

**Comment by KSib** [comment]
This should be added explicitly in the doc. Thanks for putting in here though.

**Comment by spottedmahn** [comment]
Hi @divega 👋 - PRs #1592 & #1593 submitted 😊

**Comment by divega** [comment]
Thank you @spottedmahn!
