### ISSUE TITLE
Update or replace ASP.NET Core new database walkthrough

### ISSUE THREAD

**Issue by kenyachan** [aspnet/EntityFramework.Docs#794]
The option for "Minimal Dependencies" doesn't exist when I go to add a controller.
I get the following:
- MVC Controller - Empty
- MVC Controller with read/write actions
- MVC Controller with views, using Entity Framework
- API Controller - Empty
- API Controller with read/write actions
- API Controller with views, using Entity Framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c78ab24c-ddc8-521d-f032-68b9dfaab803
* Version Independent ID: 23d99a0f-1eb8-3f0b-5a09-f2520aa3b496
* Content: [Getting Started on ASP.NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db#create-a-controller)
* Content Source: [entity-framework/core/get-started/aspnetcore/new-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/new-db.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kenyachan  that tutorial is out of date. I created https://github.com/aspnet/Docs/issues/7300 to track this. 

I'll have https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro updated to .Net Core 2.1 SDK tomorrow. See https://github.com/aspnet/Docs/pull/7163
 I think redirecting to my tutorial is a better option if I can talk @divega  into the redirect.

**Comment by Rick-Anderson** [comment]
@divega do you want this updated or redirected to https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro

**Comment by Rick-Anderson** [comment]
> At first glance, the ASP.NET Core tutorials use the EnsureCreated() method which I wouldn't recommend besides very simple testing scenarios. I see the clarification that databases created with EnsureCreated() cannot be managed with Migrations, but I would like to see the tutorial to switch completely to using EF Core Migrations. Can we make that happen?

![image](https://user-images.githubusercontent.com/3605364/42601992-d78f2dbe-8524-11e8-8e36-57f8a64dd260.png)

We were under the impression `EnsureCreated` is OK early in development before the first deployment. The tutorial does several migrations as things progress. Is that OK or should we scrap `EnsureCreated`  ASAP?

on points 2 & 3, I think it's better to update this doc and make it xplat. We have xplat version of several tutorials (including a RP/EF tutorials) - although not all our xplat tutorials have been updated to 2.1


cc @tdykstra
