### ISSUE TITLE
Template Processing Failed:(4,47): error CS0234:

### ISSUE THREAD

**Issue by xsqian** [aspnet/EntityFramework.Docs#796]
There was an error running the selected code generator: ‘There was an error running the template C:\User\xsqian\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\2.1.1\Templates\ControlerGenerator\MvcControllerWithContext.cshtml: Template Processing Failed:(4,47): error CS0234: The type of namespace name ‘Hosting’ does not exist in the namespace ‘Microsoft.AspNetCore.Razor’ (are you missing an assembly reference?) (20,41): error CS0234: The type or namespace name ‘Hosting’ does not exist in the namespace ‘Microsoft.AspNetCore.Razor’ (are you missing an assembly reference?)’

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Getting Started on ASP.NET Core - Existing Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@Rick-Anderson Any ideas on this?

**Comment by Rick-Anderson** [comment]
@xsqian  Where exactly in the tutorial did you get that error?

we've had this reported several times but I haven't been able to reproduce the problem. 

What has helped in the past:

* Update VS to the latest version (if you're using VS)
* Make sure you have the .NET Core SDK 2.1 installed (run `dotnet --version` and output should be >= 2.1.300
* If that fails repair .NET SDK and VS

@seancpeters  we've seen this error a few times.

@xsqian  can you try the following:

dotnet new webapp -o ContosoUniversity
cd ContosoUniversity
dotnet run

## Add Student class

```
using System;
using System.Collections.Generic;

namespace ContosoUniversity.Models
{
    public class Student
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
    }
}
```

## Scaffold the student model

dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --version 2.1.0
dotnet aspnet-codegenerator razorpage -m Student -dc ContosoUniversity.Models.SchoolContext -udl -outDir Pages\Students --referenceScriptLibraries

**Comment by yamazaroon** [comment]
I receive this same exact error when performing the "Create a Controller" step:
https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#create-a-controller

After performing these steps:
Right-clicking on the controller folder
Selecting the MVC Controller with views, using Entity Framework option
Selecting the model class and Data context class
After clicking the "Add" button, the above-mentioned error is produced.

**Comment by Rick-Anderson** [comment]
@yamazaroon  can you try the steps I've outlined above  - starting with `dotnet new webapp -o ContosoUniversity`

**Comment by zackshine** [comment]
I met this problem today,and I changed the version of Microsoft.AspNetCore.All in .csproj file then it worked in asp.net core 2.1.

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>

**Comment by Rick-Anderson** [comment]
@zackshine  using M.A.All is discouraged. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1

**Comment by dbiehle** [comment]
I encountered the same error at the Create a Controller step (see @yamazaroon 's comment above) and tried the steps @Rick-Anderson suggested:
* Checked that .NET Core SDK 2.1 is 2.1.3
* Ran a Repair on VS
* Checked that my ContosoUniversity app worked properly (I already had this project, created from a different tutorial)
None of these solved the issue, so I deleted the project and re-ran this tutorial using ASP.NET Core Templates 2.1 instead of  ASP.NET Core Templates 2.0 as directed in the [Create a new project](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#create-a-new-project) section. With this change I was able to complete the tutorial successfully and add new URLs to the Blog table.

**Comment by joelbenford** [comment]
The comment system my csproj as html. Here it is with the angle brackets converted to curly braces...
{Project Sdk="Microsoft.NET.Sdk.Web"}

  {PropertyGroup}
    {TargetFramework}netcoreapp2.1{/TargetFramework}
  {/PropertyGroup}

  {ItemGroup}
    {PackageReference Include="Microsoft.AspNetCore.App" /}
    {PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" /}
    {PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0" /}
    {PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" /}
  {/ItemGroup}

{/Project}

**Comment by Rick-Anderson** [comment]
@joelbenford add version to M.A.App

{PackageReference Include="Microsoft.AspNetCore.App"  Version="2.1.0" /}

but 2.1.1

**Comment by Rick-Anderson** [comment]
Closing. You get this error when you don't have the current .NET Core SDK installed.
