### ISSUE TITLE
System-Versioned Memory-Optimized Table support?

### ISSUE THREAD

**Issue by jsmith-jxe** [aspnet/EntityFramework.Docs#797]
Is there support for Memory-Optimized tables that are System-Versioned as well, as long as the SQL Server DB is &gt;= 2016? See https://docs.microsoft.com/en-us/sql/relational-databases/tables/system-versioned-temporal-tables-with-memory-optimized-tables?view=sql-server-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 677cf50e-f103-6505-fe02-55f8a110598f
* Version Independent ID: 78b4535e-5b37-12aa-19be-229b63700b69
* Content: [Microsoft SQL Server Database Provider - Memory-Optimized Tables - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sql-server/memory-optimized-tables)
* Content Source: [entity-framework/core/providers/sql-server/memory-optimized-tables.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sql-server/memory-optimized-tables.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
Added a note to https://github.com/aspnet/EntityFrameworkCore/issues/4693, which is where support for temporal tables is being tracked.
