### ISSUE TITLE
The link for System.Transactions is wrong

### ISSUE THREAD

**Issue by JasonLoKiSmith** [aspnet/EntityFramework.Docs#798]
Hi Guys,

In the documentation listed here: https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/
the link to System.Transactions points to Querytypes. 

Kindly resolve 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-za/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **anpete**

**Comment by ajcvickers** [comment]
Blog link: https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-entity-framework-core-2-1/

@richlander Can you give access to @divega so he can fix this in the blog?

**Comment by divega** [comment]
The blog post is now updated.
