### ISSUE TITLE
API pages should link to full doco

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/EntityFramework.Docs#802]
While the [API Browser](https://docs.microsoft.com/en-au/dotnet/api/index?view=aspnetcore-2.1) useful, it usually lacks further doco like contextual information and usage snippets

Also often people land on the api from a search, when really they want the doco

It would be good if, where possible, api linked to the most relevant doco page. For example

 * https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.console?view=aspnetcore-2.1 should link to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#built-in-logging-providers
 * https://docs.microsoft.com/en-au/dotnet/api/microsoft.aspnetcore.mvc.controller?view=aspnetcore-2.1 should link to https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?view=aspnetcore-2.1

**Comment by bricelam** [comment]
http://ewsoftware.github.io/XMLCommentsGuide/html/16cdb957-a35b-4c17-bf5e-ea511b0218e3.htm#ExternalRef

**Comment by bricelam** [comment]
Re-opening. I still think this would be super valuable.

**Comment by ajcvickers** [comment]
Covered by https://github.com/aspnet/EntityFrameworkCore/issues/17508
