### ISSUE TITLE
Change nuget urls to point to doco or better landing page

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/EntityFramework.Docs#803]
Often searches will resolve to a nuget package. or people will know the nuget they are using and want to find the doco for it. 

However most MS nuget 

At the moment nugets point to generic getting stated pages. For example 
 
 * [Microsoft.Extensions.Logging.Console](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Console/)
 * [Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/)
* [Microsoft.AspNetCore](https://www.nuget.org/packages/Microsoft.AspNetCore)

All point to https://www.asp.net/

This experience looses all context of the users navigation history, and is unlikely to be the desired page for most people. I would expect the better locations would be

 * https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#built-in-logging-providers
 * https://docs.microsoft.com/en-us/ef/core/providers/sql-server/
 * https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1  (note the view goes to the correct version)

I realise that the history of nuget versions is static, but doco is a changing structure. but you could manage the redirects dynamically with all nuget pointing to a redirector `https://docs.microsoft.com/nugets?Microsoft.EntityFrameworkCore.SqlServer&version=1.2.3`

another option would be ad to nuget the ability to store more urls. eg "project hosting url", "docs url" etc

**Comment by ajcvickers** [comment]
@SimonCropp Thanks for suggesting this--I moved the issue to https://github.com/aspnet/EntityFrameworkCore/issues/12537 since it requires changes to the build.
