### ISSUE TITLE
Ignored includes: show a query that uses blog.Posts

### ISSUE THREAD

**Issue by adamburgess** [aspnet/EntityFramework.Docs#804]
The example currently only shows that the blog posts are ignored because of an optimisation (Posts aren't used in the anonymous type)
I think this should section should be extended to show that even when they *are* used, it still won't work, e.g. :
```
.Select(blog => new
{
    Id = blog.BlogId,
    Url = blog.Url,
    HighlyRatedPosts = blog.Posts.Where(post => post.Rating > 3)
})
```
HighlyRatedPosts will be evaluated lazily in this case
Here's one issue I think that is talking about this: https://github.com/aspnet/EntityFrameworkCore/issues/4641

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@adamburgess This:
```C#
.Select(blog => new
{
    Id = blog.BlogId,
    Url = blog.Url,
    HighlyRatedPosts = blog.Posts.Where(post => post.Rating > 3)
})
```
doesn't require an Include call. Projection of navigation properties is independent of Include.
