### ISSUE TITLE
ConsoleApp.SQLite.csproj missing Microsoft.EntityFrameworkCore.Design PackageReference

### ISSUE THREAD

**Issue by mrward** [aspnet/EntityFramework.Docs#805]
The ConsoleApp.SQLite.csproj content displayed on the page - https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite - section `ConsoleApp.SQLite.csproj should now contain the following:` does not include the 'Microsoft.EntityFrameworkCore.Design' package reference whilst the previous step shows it being added from the command line with 'dotnet add package'. Copying and pasting the ConsoleApp.SQLite.csproj as displayed will not work. You will end up with an error trying to generate the migration:

```
Your startup project 'ConsoleApp.SQLite' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.
```

[Enter feedback here]
Your startup project 'ConsoleApp.SQLite' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mrward  this tutorial is out of date for .NET Core SDK 2.1

The correct *ConsoleApp.SQLite.csproj*

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1" />
  </ItemGroup>

</Project>
```

Skip the step  Manually edit `ConsoleApp.SQLite.csproj` to add a DotNetCliToolReference to Microsoft.EntityFrameworkCore.Tools.DotNet:

**Comment by mrward** [comment]
Was following the steps to try and reproduce a bug filed against VS Mac for this tutorial where the user did not have 2.1 installed. I can see that there are some existing GitHub issues about updating the content for .NET Core 2.1 so maybe this can be closed?

**Comment by Rick-Anderson** [comment]
@mrward  see #806 which is updated for the latest .NET Core SDK
