### ISSUE TITLE
Some problems with foreign key

### ISSUE THREAD

**Issue by antonioapostoliu** [aspnet/EntityFramework.Docs#81]
I start one new project with Visual Studio 2015 with Update 1 RC and ASPNET 5 RC1 and add models from page
http://ef.readthedocs.org/en/latest/modeling/relational/fk-constraints.html
I saved and build .(without errors)
Also I run from command line:

dnvm use  1.0.0-rc1-final
dnx ef migrations add First
dnx ef database update

After scaffold operations, blogs pages works. I create 2 blogs entries.
Also  list view from posts works.
The problem is in create new post page. The combo box blog reference  list is empty. I expected to find the 2 blogs entries from previous action.

Please look again to this web page doc or/and  tell me where I wrong.

Best regards

**Comment by rowanmiller** [comment]
Hey, this looks like a problem with scaffolding itself. EF is correctly returning the data into the `SelectList` that is created in the `PostsController.Create` action. Can you open an issue over on the scaffolding repo https://github.com/aspnet/Scaffolding.
