### ISSUE TITLE
Implicit convertion doesn't work when used in inline entity buildAction

### ISSUE THREAD

**Issue by hulvei3** [aspnet/EntityFramework.Docs#813]
When using a implicit EnumToStringConverter (`.HasConversion<MyEnum>()`) I'm getting this error when running dotnet ef migrations commands:
    
    The property <PROP> is of type <TYPE> which is not supported by current database provider. 
    Either change the property CLR type or ignore the property using the '[NotMapped]' attribute or by 
    using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

This happens when I using the inline entity builder (`modelBuilder.Entity<Tag>(entity =>... `).

It works when using it explicit:

        var converter = new EnumToStringConverter<TagOperator>();

        entity.Property(e => e.<PROP>)
            .IsRequired()
            .HasConversion(converter)
            .HasMaxLength(10);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#limitations)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* GitHub Login: @ajcvickers
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@hulvei3 This looks like an issue with the product rather than the docs. Please file an issue at https://github.com/aspnet/EntityFrameworkCore/issues containing a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
