### ISSUE TITLE
incorrect links

### ISSUE THREAD

**Issue by StillLearnin** [aspnet/EntityFramework.Docs#827]
Two APIs are marked as obsolete but the links to what we should use instead simply take us to the obsolete APIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9c2511-ca2d-999e-dcb9-25a46ba085c3
* Version Independent ID: c5804fd3-45b3-223a-c2be-f40386915fc2
* Content: [InMemoryDbContextOptionsExtensions.UseInMemoryDatabase Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.inmemorydbcontextoptionsextensions.useinmemorydatabase?view=efcore-2.1#Microsoft_EntityFrameworkCore_InMemoryDbContextOptionsExtensions_UseInMemoryDatabase__1_Microsoft_EntityFrameworkCore_DbContextOptionsBuilder___0__System_Action_Microsoft_EntityFrameworkCore_Infrastructure_InMemoryDbContextOptionsBuilder__)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/InMemoryDbContextOptionsExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/InMemoryDbContextOptionsExtensions.xml)
* GitHub Login: @dotnet-bot

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework.ApiDocs#24
