### ISSUE TITLE
Canonical example - Visual Studio 2017 SQLite EF6 example without using App.Config

### ISSUE THREAD

**Issue by thomb1** [aspnet/EntityFramework.Docs#834]
It would be good to have a canonical example that shows very simple implementation.  The idea behind EF6 is very simple and the examples should be presented that way. You don't teach poetry to 1st graders, so show the bone simple way to do things - no fancy constructors, subclassing, don't even use Using( ) constucts. etc etc. Just stone axe least amount of code possible simple. Step 1: Set the EF references + specific ones for your database. Step 2: Create some classes (whose properties have appropriate datatypes)  Step 3: Create a dbContext class that has the dbSets and that decides the CodeFirst behaviors. Step 3.5 the part that's elusive to me - create the connection string stuff.    Step 4 - run it :) ... This is not fully accurate and way to feature rich... but its at was somewhat close. https://www.codeproject.com/Articles/1158937/SQLite-with-Csharp-Net-and-Entity-Framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f431e6c-6c5f-9056-1486-99ba6b02c954
* Version Independent ID: 37943f43-c279-f190-b134-48f54ead1e38
* Content: [Connection strings and models - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings)
* Content Source: [entity-framework/ef6/fundamentals/configuring/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/configuring/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ErikEJ** [comment]
The SQLite provider does not support Code First migrations

**Comment by thomb1** [comment]
Hi Erik,
Thank you for the fast reply!  For my particular needs: I have base set of tables /classes that I need to clone  from a template + I want some degree of “scriptability” afterwards.  I can accomplish what EF6 /codefirst was going to give me , I can handle with a bespoke SQL generator + .NET’s tricks for “auto-understanding” classes + Roslyn for the scripting.

Speaking for just for me, that’s the problem with the “crowdsourced” approach (e.g.StackOverflow etc) – I’d read some articles saying that you can’t do CodeFirst with SQLite – but I can’t count how many times I’ve gotten “not supported” stuff to work. There’s a ton of “noise/misunderstanding out there” – hence my request for the stone simple canonical implementation.

To my (self taught programmer’s mind), EF6 appears a simple concept that fit my needs perfectly, so I figured if its supported by one database – then anything preventing another is just a matter of something simple that I can bumble through – not something fundamentally wrong with the universe beyond my control.

I’m going to take your advice! Call it that I’ve learned enough for one week and am moving along with the approaches I know.

Again, thank you for the reply – I’ve been impressed about how rapidly folks at Microsoft are replying to these comments. I know that’s a thankless job.

Regards,
Thom

Thom C. Blackwell,  VP Technical Services
Boston Software Systems, Inc.
Phone: 866.653.5105 x807
Mobile: 508.423.8463
Fax: 508.319.3015
www.bostonsoftwaresystems.com<http://www.bostonsoftwaresystems.com/>

The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by ajcvickers** [comment]
Triage: we don't intend to update the documentation to include SQLite for EF6. However, we will, as part of other work, attempt to make some of the walkthroughs easier to follow.
