### ISSUE TITLE
Incorectly rendered sentence

### ISSUE THREAD

**Issue by VPeruS** [aspnet/EntityFramework.Docs#840]
Last sentence's two word appears on next line, this create huge gap between `application's` word and `Main`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa64390-1232-8dd3-f170-7d5c68e29ad9
* Version Independent ID: 245bbba8-3102-4a66-15eb-650e05eb9e62
* Content: [Design-time DbContext Creation - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation)
* Content Source: [entity-framework/core/miscellaneous/cli/dbcontext-creation.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/dbcontext-creation.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@VPeruS which browser and OS?

**Comment by VPeruS** [comment]
Firefox 61 + linux. 
![default](https://user-images.githubusercontent.com/7927055/42733664-3b43aeb8-883e-11e8-93e0-5dddb9c6e3e4.png)
And from IE
![default](https://user-images.githubusercontent.com/7927055/42733684-8e38bae6-883e-11e8-8144-dae3eba82387.png)

Should be because fixed-length lines.

**Comment by divega** [comment]
There were actually extra spaces there. In markdown two spaces is a line separator.

**Comment by divega** [comment]
The fix will make it to live later. Thanks @VPeruS.
