### ISSUE TITLE
Is this document updated for EF Core 2.1  ? Or is there any other reference for EF VS EF Core 2.1 ?

### ISSUE THREAD

**Issue by kotikavoori** [aspnet/EntityFramework.Docs#858]
i want to know similar differences between EF VS EF Core 2.1[latest available version], any references ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc2d1a4-a434-69f9-3df3-9818c571c978
* Version Independent ID: a272636c-100d-fb7b-d7a9-713adc0b2b8e
* Content: [EF Core & EF6 Feature by Feature Comparison](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features#feedback)
* Content Source: [entity-framework/efcore-and-ef6/features.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/features.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Yes, it is updated.
