### ISSUE TITLE
Only in Development Environment?

### ISSUE THREAD

**Issue by kduenke** [aspnet/EntityFramework.Docs#859]
Is there a recommended way to only seed data when it's a development environment (i.e. ASPNETCORE_ENVIRONMENT = Development)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by AndriySvyryd** [comment]
`HasData` is for seed data that you need to manage using migrations, so for test, development and staging it's best to just clean the database and insert the data normally.

**Comment by nicoleta-scrimint** [comment]
What do you mean by normally? Through sql scripts?
Are migrations recommended for production environment?
