### ISSUE TITLE
Ensure key (relational/non-relational/primary/alternate/etc.) documentation is easy to find

### ISSUE THREAD

**Issue by binhghi5** [aspnet/EntityFramework.Docs#862]
This one https://docs.microsoft.com/en-us/ef/core/modeling/keys
And this one https://docs.microsoft.com/en-us/ef/core/modeling/relational/primary-keys
What is the different between keys (primary) and primary-keys?
The content in 2 links above is different. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a38fe8f-c674-0673-a13f-b87a7a9edf78
* Version Independent ID: fad97301-bb2b-f974-bf1c-c80c9d143b3d
* Content: [Primary Keys - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/primary-keys)
* Content Source: [entity-framework/core/modeling/relational/primary-keys.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/primary-keys.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by roji** [comment]
Thanks @AndriySvyryd, will do this as part of #1669
