### ISSUE TITLE
Fails to mention required default constructor

### ISSUE THREAD

**Issue by albertbori** [aspnet/EntityFramework.Docs#866]
&gt; AddDbContext was called with configuration, but the context type 'MyContext' only declares a parameterless constructor. This means that the configuration passed to AddDbContext will never be used

Requires:

    public MyContext(DbContextOptions&lt;MyContext&gt; options) : base(options) { }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e28b0a8-b7e4-4c07-9e60-0df403bbee28
* Version Independent ID: 12300b31-6f7b-b75c-970d-693365e77013
* Content: [Migrations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/)
* Content Source: [entity-framework/core/managing-schemas/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/index.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by tdykstra** [comment]
@albertbori Is this in reference to a different article?  I don't see anything in this Migrations article about `AddDbContext`.

**Comment by ajcvickers** [comment]
@albertbori Sorry for being slow to respond here. I’m having trouble following your comment. Can you explain the issue/question in more detail?

**Comment by albertbori** [comment]
I'm sorry, but the details for this issue are gone from my memory. If I had to guess, it'd be that one of the steps in the article failed with the error:

> AddDbContext was called with configuration, but the context type 'MyContext' only declares a parameterless constructor. This means that the configuration passed to AddDbContext will never be used

And that it required that I add the following line to my model for it to run correctly:

```public MyContext(DbContextOptions&lt;MyContext&gt; options) : base(options) { }```

If the issue is not reproducible, then it was likely a fragment of a Visual Studio/Package Manager version conflict, or previously missing step.
