### ISSUE TITLE
Support sub query in computed column mapping?

### ISSUE THREAD

**Issue by zxs731** [aspnet/EntityFramework.Docs#873]
Can we map as this when we have sub query?
 .HasComputedColumnSql("select top 1 address.[zipcode] + ', ' + address.[details] from address where [addressId]=address.id");
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d48c064-a896-af4b-9a32-7846e848bb9e
* Version Independent ID: 7d134bc7-7c34-a829-2a56-9ad6ea37015c
* Content: [Computed Columns - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/computed-columns)
* Content Source: [entity-framework/core/modeling/relational/computed-columns.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/computed-columns.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@zxs731 The text passed to HasComputedColumnSql is opaque to EF, so if that works on SQL Server (or whatever database engine you are using) then it should work with EF.
