### ISSUE TITLE
Make cascade delete topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#875]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by tdykstra** [comment]
Closing this issue: on 10/10/18 SkyRay showed 4k page views and 3 ratings (2 of them positive) for the last 30 days. The number of ratings is not enough to draw reliable conclusions; when we do the next sweep for high-traffic/low ratings docs, we can reopen this one if this doc meets those criteria.
