### ISSUE TITLE
Make installing EF Core topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#879]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5747ad3-edd5-1977-883c-2cf77112306c
* Version Independent ID: d66d0616-2aa2-8be4-5ab6-24201ef00b59
* Content: [Installing EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/install/)
* Content Source: [entity-framework/core/get-started/install/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/install/index.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by tdykstra** [comment]
@divega I believe the substantial changes made to the organization of this doc for #965 will also address this issue, meaning we could close this one.  If after a few months its numbers don't improve we could reopen it.
