### ISSUE TITLE
Make EF Core and EF6 comparison topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#880]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0036f8c5-d838-69a5-cc09-dc74df09bc07
* Version Independent ID: 5335749f-e32f-979f-7139-f5f14373e283
* Content: [Compare EF Core & EF6](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/)
* Content Source: [entity-framework/efcore-and-ef6/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/efcore-and-ef6/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by shidcordero12** [comment]
We need this to improve, much better to be functionality base that exists on either of the 2 framework.
