### ISSUE TITLE
Make getting started with SQLite topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#881]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb04585-f54b-70c0-e847-b044b388a4d5
* Version Independent ID: 5e37f568-0621-a082-c75a-d2adf94dce8d
* Content: [Getting Started on .NET Core - New database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
* Content Source: [entity-framework/core/get-started/netcore/new-db-sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/netcore/new-db-sqlite.md)
* Product: **entity-framework**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
9.2 KPV last month. Only 3 ratings so not statistically significant. @tdykstra  or myself will do a pass and see if we can get better reviews.

**Comment by divega** [comment]
This could be related to the fact SQLite is common for Xamarin o UWP (I don't think many are building .NET Core console apps), and those require additional workarounds (which are covered in other topics).

**Comment by tdykstra** [comment]
I went through the tutorial and only found trivial things to fix.  It works flawlessly with .NET Core 2.1, was already updated for that version.  3 reviews isn't enough to draw reliable conclusions, but @divega might be right that people come here wanting Xamarin or UWP info and consider it unhelpful. Could also be some want an ASP.NET version, as this one doesn't tell you how to deal with ASP.NET Core DI.  Also we don't have much guidance on how to deal with SQLite migrations limitations, beyond saying they should delete and re-create the database.

**Comment by divega** [comment]
Thanks @tdykstra. I will close for now. If we get more information we can revisit.
