### ISSUE TITLE
Make data seeding topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#882]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc418ab9-0592-f610-e751-40cb501220da
* Version Independent ID: 822e8923-2647-f573-0c74-66af903776d8
* Content: [Data Seeding - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding)
* Content Source: [entity-framework/core/modeling/data-seeding.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/data-seeding.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **divega**

**Comment by tdykstra** [comment]
Comments from the feedback control about what's missing:

* How to deploy to production?
* How to seed AutoIncrement values; how to get some existing value from the database to perform some calculation onto inserting values.
* How to convert data seeded with EnsureCreated to migrations?"
* How to seed an admin user account, for example how to handle password hashing.
* Missing context for the code examples -- what class is OnModelCreating in? Where does modelBuilder instance come from?

Plus several requests for more examples.

**Comment by weitzhandler** [comment]
Any progress on this? Please see #1191.

**Comment by adam-geisen** [comment]
For custom initialization logic it would be really nice to have an example of:

- Deploying the initialization app with the main app, invoking the initialization routine and disabling or removing the initialization app.

It would also be nice to have an example of changing seed data and how to handle that with custom initialization. Even though changing seed data seems fairly straightforward if your only unique identifier is the auto generated key, how do you change seed data in the database if the keys differ on each environment?

**Comment by bchavez** [comment]
Maybe even have a few EF core seeding examples that use Bogus: https://github.com/bchavez/Bogus

:sunglasses:

**Comment by ajcvickers** [comment]
Closing in favor of #736
