### ISSUE TITLE
Make testing with SQLite topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#884]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4f7b56f-7f91-2f15-1fb6-4f481e97534f
* Version Independent ID: 6d9c65c6-f159-b234-48fd-f25da05f0f32
* Content: [Testing with SQLite - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite)
* Content Source: [entity-framework/core/miscellaneous/testing/sqlite.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/testing/sqlite.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by tdykstra** [comment]
Closing this issue: on 10/10/18 SkyRay showed 2k page views and 1 rating (positive) for the last 30 days. The number of ratings is not enough to draw reliable conclusions; when we do the next sweep for high-traffic/low ratings docs, we can reopen this one if this doc meets those criteria.
