### ISSUE TITLE
Make history table topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#885]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390f9258-6f7c-dbe8-3e79-c83446ba6192
* Version Independent ID: 38896138-0566-d481-2c91-8158f6d8f274
* Content: [Custom Migrations History Table - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/history-table)
* Content Source: [entity-framework/core/managing-schemas/migrations/history-table.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/history-table.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by tdykstra** [comment]
Closing this issue: on 10/10/18 SkyRay showed 1k page views and 0 ratings for the last 30 days. The number of ratings is not enough to draw reliable conclusions; when we do the next sweep for high-traffic/low ratings docs, we can reopen this one if this doc meets those criteria.
