### ISSUE TITLE
Examples: Second Post should have ID = 2

### ISSUE THREAD

**Issue by AlexanderPilhar** [aspnet/EntityFramework.Docs#899]
```
Blog '1' is ...
   Post '1' is ...
   Post '1' is ...
```

should be:

```
Blog '1' is ...
   Post '1' is ...
   Post '2' is ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Cascade Delete - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@divega We should leave this open to look at the sample code.
