### ISSUE TITLE
The disconnected entities documentation does not mention that .Update() can handle deletes.

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/EntityFramework.Docs#901]
There is a separate section on Handling deletes and TrackGraph that seem to imply you have to use the query pattern to perform deletes using the two loops.

I think this section: https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#all-newall-existing-entities
Or this: https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#mix-of-new-and-existing-entities

Should mention that if you removed a blog post, and called Update, it will be deleted.

Also "soft deletes" is mentioned along with query filters but the second half of the equation is overriding default EF functionality to soft-delete on remove and I think it should at lease me mentioned like here https://www.meziantou.net/2017/07/10/entity-framework-core-soft-delete-using-query-filters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9826f28-46b2-e845-f1bf-5cbc2d940208
* Version Independent ID: 9c4a46cf-daa2-0e14-7ff1-c195db237cd0
* Content: [Disconnected Entities - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities#mix-of-new-and-existing-entities)
* Content Source: [entity-framework/core/saving/disconnected-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/disconnected-entities.md)
* Product: **entity-framework**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by ajcvickers** [comment]
@VictorioBerra Sorry for being slow to respond here. Calling `Update` should not have any impact on deleting entities--it should be a no-op in the case you describe. Can you explain in more detail what you mean?

**Comment by VictorioBerra** [comment]
@ajcvickers If you track children of an entity, and you remove one of those children, and you call Update(), it will "save" that you removed a child and will cascade delete, or cascade null depending on your settings. Therefore, Update will try and get the database to match the desired state and perform deletes.

**Comment by ajcvickers** [comment]
@VictorioBerra `Update` should be a no-op in that scenario. If it isn't, then please file a bug at https://github.com/aspnet/EntityFrameworkCore and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.
