### ISSUE TITLE
How do you do .ThenInclude from F#?

### ISSUE THREAD

**Issue by ctaggart** [aspnet/EntityFramework.Docs#903]
After figuring out how to get the proxies to work in F# https://github.com/aspnet/EntityFrameworkCore/issues/12923, I tried to create queries using something like `.Include(fun blog -&gt; blog.Posts).ThenInclude(fun post -&gt; post.Author)`, but post ends up being a collection. It fails in IntelliSense and during compilation. How do I make it work? Is there a workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@ctaggart We can look into this, but two things I can mention off the top of my head:
* Visual Studio IntelliSense doesn't work for this in C#--see https://github.com/dotnet/roslyn/issues/8237 (ReSharper/Ryder IntelliSense works fine for me.)
* You could try using string-based Include. That is, dot-separated navigation properties: `.Include("Posts.Author")`

**Comment by RyanBuzzInteractive** [comment]
Has anyone got this working? I am stuck trying to get child properties loading in F#. The string version doesn't seem to help, the child property is always null.

**Comment by RyanBuzzInteractive** [comment]
I can confirm that the string version of Include is working in F#.

**Comment by dharmaturtle** [comment]
@manchoz's [comment](https://github.com/aspnet/EntityFrameworkCore/issues/6560#issuecomment-369232908) shows how to do it without hardcoding strings:

> F# won't automatically upcast `List<T>` to `IEnumerable<T>`. Explicitly upcasting the `.Include()` lambda to `IEnumberable<T>` seems to resolve the issue:
> 
```fsharp
let q =
    db.Schemas
       .Include(fun sch -> sch.Entities :> IEnumerable<_>)
           .ThenInclude(fun (ents : Entity) -> ents.Fields)
       .ToList()
```
