### ISSUE TITLE
Raw SQL docs suggest bad practice

### ISSUE THREAD

**Issue by jzabroski** [aspnet/EntityFramework.Docs#905]
https://github.com/aspnet/EntityFramework.Docs/edit/master/entity-framework/core/querying/raw-sql.md

Putting in-line constants into a raw SQL query will boat the SQL Server plan cache.
Not sure about other systems and whether this would effect them as well.

**Comment by ajcvickers** [comment]
@jzabroski Which inline constants are you referring to?

**Comment by ajcvickers** [comment]
@jzabroski That code and all the code in the post create parameterized queries. The warning at the bottom is about being careful how the compiler works with regard to creating parameterized queries when using string interpolation. https://github.com/aspnet/EntityFrameworkCore/issues/10996 will address this in 3.0
