### ISSUE TITLE
Register custom ValueConverter for implicit conversion

### ISSUE THREAD

**Issue by Vivelin** [aspnet/EntityFramework.Docs#909]
The docs mention there is no need to specify a converter explicitly when there is a built-in converter. Is it possible to somehow register custom converters to behave the same way? 

For example, I have a custom `UriToStringConverter` class that I would like to use for multiple Uri properties. Currently, I register the converter for every Uri property separately. I don't know if this is something that's possible but missing from the docs (clearly, it works for built-in converters) or if this is a missing feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* GitHub Login: @ajcvickers
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@Vivelin This is being tracked by https://github.com/aspnet/EntityFrameworkCore/issues/10784
