### ISSUE TITLE
Typo Correction

### ISSUE THREAD

**Issue by raghukrishnamoorthy** [aspnet/EntityFramework.Docs#911]
Under the 
"Creating a Model: Code First, the EF Designer, and the EF Workflows" section, the last word should be 'difference' instead of 'different'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d06865-183f-140e-a1f1-099cd36b93fe
* Version Independent ID: 401fd98e-66bf-acbc-50f8-16af48c90adf
* Content: [Get started with Entity Framework 6 - EF6](https://docs.microsoft.com/en-us/ef/ef6/get-started)
* Content Source: [entity-framework/ef6/get-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/get-started.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by raghukrishnamoorthy** [comment]
Not trying to be a pedantic pain in the ass, just making sure the docs are flawless for the next person is all.

**Comment by divega** [comment]
:+1: no worries. This is good feedback. It is also super easy to submit a PR when you find a typo like this. Look for the :pencil: icon in the page.
