### ISSUE TITLE
ToView() equivalent in Data Annotations missing in docs

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [aspnet/EntityFramework.Docs#913]
Doc says to use .ToView() while using Fluent API but it never says how to do it with Data Annotations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **anpete**

**Comment by ajcvickers** [comment]
@carlosmunozrodriguez Data annotations support only a subset of EF Core modeling. For this case I believe you need to use the fluent API. However, I added a note to https://github.com/aspnet/EntityFrameworkCore/issues/10111 to consider adding support for attribute mapping in the future.

**Comment by carlosmunozrodriguez** [comment]
Just to add a note. I have successfully used `[Table("TableName", Schema = "SchemaName")]` to decorate a class that I use with `DbQuery<T>` to map a View

**Comment by MonstraG** [comment]
This was closed in favor of https://github.com/dotnet/efcore/issues/10111 which was closed in favor of https://github.com/dotnet/efcore/issues/10864 which was closed to track these in separate issues (so, this among the others).

As a result, this is still missing.

One way this can be done is to allow `null` in [Table] annotation.

**Comment by ErikEJ** [comment]
Is it not [Keyless] ?

**Comment by MonstraG** [comment]
It still creates a table in the migration, I added [Keyless] and `.ToView(null)` to prevent that.
