### ISSUE TITLE
Document using migrations with transactions

### ISSUE THREAD

**Issue by ageisen2000** [aspnet/EntityFramework.Docs#914]
Does MigrationBuilder.Sql() need to exist inside of a migration operation? Would there be a way to inject sql before and after all of the migration operations when generating scripts?

I want to be able to wrap a transaction around all of my sql migration statements and then commit the transaction if everything worked correctly. Is this possible in EF Core using SQL Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by nicholasyin** [comment]
Yeah, how to use MigrationBuilder directly? Surprised not to find such information.

**Comment by ageisen2000** [comment]
Yes initially we were using dotnet Ef script to generate migration scripts. Sometimes the scripts would fail and be half migrated but still cause the migrations table to be written to.

Since then I changed our projects to use dotnet Ef update database and that seems to have fixed the partial migration issue. 

My initial hope was that when building a migration script I could add a transaction at the beginning and end of the script so that the migration wouldn't apply if it failed. I don't think that would've worked anyways

**Comment by bricelam** [comment]
We’ve had similar feedback before. I’m starting to think we should always generate them in the script. It seems like it would make deployment easier for everyone.

A solution we’ve seen is to generate one sql file per migration then run them one at a time within their own transaction.

**Comment by bricelam** [comment]
Reopening https://github.com/aspnet/EntityFrameworkCore/issues/7681

**Comment by weitzhandler** [comment]
@bricelam
Can you achieve these actions when using [`Database.EnsureCreated`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.ensurecreated?view=efcore-2.1)?

**Comment by bricelam** [comment]
@weitzhandler Can you clarify the question?

**Comment by eskensberg** [comment]
I have a test project where I would like to generate a whole database from scratch for testing. Is it possible to do something like myDbContext.Database.UpdateDatabase(my-test-db-connection-string) ?

Thanks!

**Comment by ajcvickers** [comment]
Tracked by  https://github.com/aspnet/EntityFrameworkCore/issues/7681
