### ISSUE TITLE
Can we register the value converter  use `.HasConversion<EnumToStringConverter>()`

### ISSUE THREAD

**Issue by John0King** [aspnet/EntityFramework.Docs#923]
Do we must pass a instance ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03dfe9f6-e831-ac3f-0b90-acb9b4c0f828
* Version Independent ID: a26156d1-a4b3-7df0-e63e-b8e9f804abbf
* Content: [Value Conversions - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)
* Content Source: [entity-framework/core/modeling/value-conversions.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/value-conversions.md)
* Product: **entity-framework**
* GitHub Login: @ajcvickers
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@John0King You must pass an instance, but usually the same instance will work for all places it is needed.
