### ISSUE TITLE
"ObservableListSource<T>._bindingList" can't be used as a method.

### ISSUE THREAD

**Issue by PavelLJ** [aspnet/EntityFramework.Docs#940]
Hello! I'm complete newbie in C#, writing my first application to Windows which should be PostgreSQL database application using EF6. So, I went through this example but have an error (like in title). I assume the problem is in a way that _bindingList is initialized, but as I'm newbie I can't understad what exactly is wrong. Clarification would be very appreciated. (VS 2017, EF6 + Npgsql, WinForms C#)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93ad154e-e7a6-0ce7-4bb3-8ea56532624b
* Version Independent ID: 19a924ea-6e54-0df8-ace6-702a5bdbb2bc
* Content: [Databinding with WinForms - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/databinding/winforms)
* Content Source: [entity-framework/ef6/fundamentals/databinding/winforms.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/databinding/winforms.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by xXTufXx** [comment]
Hello! I have the same problem, have you figured out how to fix it?

**Comment by navgg** [comment]
I suppose should be _bindingList ?? (_bindingList = this.ToBindingList());

**Comment by xXTufXx** [comment]
I have solve it and the problem is really stupid, someone forgot the equals sign: 
 IList IListSource.GetList()
            {
                return _bindingList = (_bindingList = this.ToBindingList());
            }

**Comment by ajcvickers** [comment]
As @navgg says, the null coalescing operator was missing.
