### ISSUE TITLE
Update documentation to add a reference to Microsoft.EntityFrameworkCore.Design in Blogging.Migrations.Startup project

### ISSUE THREAD

**Issue by joaosantana** [aspnet/EntityFramework.Docs#946]
`Add-Migration InitialCreate` command fails with this error:

&gt; Your startup project 'Blogging.Migrations.Startup' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

Doing so resolves the issue. Please update Documentation to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 439f9dd7-6fff-f3af-15a3-c4f407e2c041
* Version Independent ID: 2779bb58-f0af-c9ee-cf40-50e24371a7fc
* Content: [Getting Started on UWP - New Database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/uwp/getting-started)
* Content Source: [entity-framework/core/get-started/uwp/getting-started.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/uwp/getting-started.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by msmdotnet** [comment]
The documentation was updated.

**Comment by divega** [comment]
We fixed this by correcting the documentation to install the EF Core tools package in the startup project.
