### ISSUE TITLE
How to map a view of "BlogAndPost" eg. LEFT JOIN

### ISSUE THREAD

**Issue by John0King** [aspnet/EntityFramework.Docs#953]
If there is a View of "Blog Left join Post" How do I map it ?
In my case , the Blog is a Table in another Database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace630fc-7310-10b7-39bb-26fcfe3f3950
* Version Independent ID: dbe96b32-0589-0f8c-6558-11a065d84dff
* Content: [Query Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)
* Content Source: [entity-framework/core/modeling/query-types.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/query-types.md)
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **divega**

**Comment by jwisener** [comment]
shame no response to this.

**Comment by ajcvickers** [comment]
@John0King @jwisener Can you provide some more details on what exactly you mean here?

**Comment by John0King** [comment]
It seems this may not make any sence for EF
```C#
class Blog
{
    long id {get;set;}
    string Title{get;set;}
    ICollection<Post> Posts{get;set;}
}
class Post
{
}
```
and a db view 
```sql
Create View BlogAndPost
As
SELECT b.*,p.* FROM dbo.Blog as b 
LEFT JOIN dbo.Post as p ON b.Id = p.BlogId
```
the solution is first to create a new model class that match the view and then do group by locally.

**Comment by ajcvickers** [comment]
@John0King Thanks for the clarification. I think this would be covered by https://github.com/aspnet/EntityFrameworkCore/issues/14525, or something very similar.
