### ISSUE TITLE
I made Reconciler, an alternative GraphDiff-successor

### ISSUE THREAD

**Issue by jtheisen** [aspnet/EntityFramework.Docs#954]
Hi folks,

right now the there's two alternatives to the `GraphDiff` library of EF6: `Detached.EntityFramework`, which is listed here, and a commercial library that's not listed here.

I've made another one that is very close in spirit to the original `GraphDiff` library that comes in both an EF6 and an EF Core version. I think it would be a useful contribution to this list.

[Reconciler](https://github.com/jtheisen/reconciler)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8875eb79-99ff-662b-c189-86eb8cdb5488
* Version Independent ID: fa03a7fa-1922-7aa1-acda-b0d216ef37cb
* Content: [Tools & Extensions - EF Core](https://docs.microsoft.com/en-us/ef/core/extensions/)
* Content Source: [entity-framework/core/extensions/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/extensions/index.md)
* Product: **entity-framework**
* GitHub Login: @ErikEJ
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@jtheisen Please send a pull request for an update to the extensions page.
