### ISSUE TITLE
Add more examples/samples

### ISSUE THREAD

**Issue by lm28** [aspnet/EntityFramework.Docs#957]
Virtually across the entire https://docs.microsoft.com site....there are very few examples showing how to use a feature and its syntax. (EG https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell has no examples.)
Surely this should be a 'Standard Operating Procedure'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [Package Manager Console (Visual Studio) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by Rick-Anderson** [comment]
@lm28  thanks for you comment. This is a reference style page and therefore doesn't have many samples. If you search on "Package Manager Console" you can find many docs with samples in this repo and in the ASP.NET repo. Is there a particular sample you're looking for?

**Comment by BillZiss** [comment]
@Rick-Anderson, if this "reference style" page had samples, or links to samples, then it would actually be useful to real people.
@lm28, see ya out on StackOverflow.  ;)

**Comment by mucciols** [comment]
Hi, with parameter -Connection prompt tell me

Scaffold-DbContext : A positional parameter cannot be found that accepts argument 'Microsoft.EntityFrameworkCore.SqlServer'.
At line:1 char:1
+ Scaffold-DbContext "Server=178.239.177.243;Database=my-wallet;uid=my- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Scaffold-DbContext], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Scaffold-DbContext

**Comment by mucciols** [comment]
Scaffold-DbContext "Server=xxx.xxx.xxx.xxx;Database=xyz;uid=xyz;password=xyz" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -f -Connection DbMyWallet

**Comment by ajcvickers** [comment]
Verified that this page contains examples. For other pages we will add examples are part of updating those pages.
