### ISSUE TITLE
"csharp" misspelled as "chsarp"

### ISSUE THREAD

**Issue by lavinio** [aspnet/EntityFramework.Docs#958]
In the paragraph starting "- To delete the relationship", two examples, instead of being in the same code format of the others and labeled "C#", start with "chsarp" or "csharp". Probably also that paragraph should be a bulleted item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1156c548-5ab9-eb9f-f5cd-61a2a6312911
* Version Independent ID: 6b2d009a-d8db-b065-f46e-d307e25e278a
* Content: [Relationships, navigation properties and foreign keys - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/relationships)
* Content Source: [entity-framework/ef6/fundamentals/relationships.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/relationships.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Thank you @lavinio. Good catch! The formatting of the page was also wrong. I fixed several issues.  

In case you are interested, submitting a fix for something like this is almost as easy as reporting it. To get started, click on the <kbd>✏️ Edit</kbd> button on the document.
