### ISSUE TITLE
Assumes the reader knows the subject

### ISSUE THREAD

**Issue by alecjames** [aspnet/EntityFramework.Docs#959]
Documentation like Add-Migration = Adds a new migration does not help new users.  "Migration" is not defined and there is no link to additional information.  The term "scaffold" is not defined.     

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [Package Manager Console (Visual Studio) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by tdykstra** [comment]
@alecjames Thanks for pointing that out.  I'm adding links and changing the wording in the article to make it clearer.  For migrations, see https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.0#introduction-to-migrations 
Scaffold refers to code generation -- scaffolding a model means generate code for the DbContext and entity classes.
