### ISSUE TITLE
What about Ports?

### ISSUE THREAD

**Issue by ecoffman** [aspnet/EntityFramework.Docs#960]
How does one specify a different port? Is that a matter of specifying the server and then ',&lt;port&gt;'? Like so:

"Server=(localdb)\\mssqllocaldb,1633;Database=EFGetStarted.ConsoleApp.NewDb;Trusted_Connection=True;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db02d-7310-1141-6aeb-539c02326a36
* Version Independent ID: 90062036-aa01-3f73-dac9-b4a092245721
* Content: [Connection Strings - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
* Content Source: [entity-framework/core/miscellaneous/connection-strings.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-strings.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@ecoffman this topic is not trying to cover every possible option of specific database providers, just the patterns that you can use to provide the connection string when working with EF Core. 

But to answer your question, LocalDB uses named pipes, and the (localdb)\name syntax is a shortcut. If you want to use a port, I assume you want to use the TCP transport, in which case you can use tcp:servername, port. This is documented in the SQL Server topic at https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?redirectedfrom=MSDN&view=netframework-4.7.2#remarks (look for the Data Source section).
