### ISSUE TITLE
Allow dependency injection in Seed class

### ISSUE THREAD

**Issue by wooderz** [aspnet/EntityFramework.Docs#967]
I am receiving a "No parameterless constructor" message. Would be good to be able to dependency inject when seeding.

**Comment by AndriySvyryd** [comment]
@wooderz Can you show how the class would look like if dependency injection was supported?

**Comment by wooderz** [comment]
Well currently I have something in the line of:

`public class IntegrationSeed : IEntityTypeConfiguration<Integration>
    {
        public void Configure(EntityTypeBuilder<Integration> builder)
        {
            builder.HasData(
                new
                {
                    Id = 1L,
                    ResourceId = Guid.NewGuid(),
                    DateCreated = DateTime.UtcNow,
                    DateLastUpdated = DateTime.UtcNow,
                    Name = "Integration",
                    Active = true
                });
        }
    }
`

It's run along the same instance as dotnet ef database update --startup-project A -project B so the startup project would normally have Service set up via something like ConfigureServices()

So something along the lines of:

`public class IntegrationSeed : IEntityTypeConfiguration<Integration>
    {
        private readonly IDependency _dependency;
        public IntegrationSeed(IDependency dependency)
        {
            _dependency = dependency;
        }

        public void Configure(EntityTypeBuilder<Integration> builder)
        {
            builder.HasData(
                new
                {
                    Id = 1L,
                    ResourceId = Guid.NewGuid(),
                    DateCreated = DateTime.UtcNow,
                    DateLastUpdated = DateTime.UtcNow,
                    Name = "Integration",
                    Active = true
                });
        }
    }
`

Now I'm sure there are good reasons against this, but thought I'd put it forward anyway! :)

**Comment by AndriySvyryd** [comment]
@wooderz You can replace the `IModelCustomizer` with your own implementation that can have other dependencies. If using SqlServer it would look something like this:
```C#
public class MyModelCustomizer : RelationalModelCustomizer
    {
        private readonly IDependency _dependency;

        public RelationalModelCustomizer(ModelCustomizerDependencies dependencies, IDependency myDependency)
            : base(dependencies)
        {
            _dependency = dependency;
        }

        public override void Customize(ModelBuilder modelBuilder, DbContext dbContext)
        {
            base.Customize(modelBuilder, dbContext);

            _dependency.Customize(modelBuilder);
        }
    }
```

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            var serviceProvider = new ServiceCollection()
                .AddEntityFrameworkSqlServer()
                .AddSingleton<IModelCustomizer, MyModelCustomizer>()
                .BuildServiceProvider();
            optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["MyDB"].ConnectionString)
                .UseInternalServiceProvider(serviceProvider);
        }
```

You would also need to override `IModelCacheKeyFactory` to take the customization into account for the cache key, see https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model
