### ISSUE TITLE
use Scaffold-DbContext tu update existing context with new table without force

### ISSUE THREAD

**Issue by blogcraft** [aspnet/EntityFramework.Docs#968]
In my projects we have a legacy Database which is huge, and it is not reasonable to scaffold the entire database.
While the .Net Core project keeps growing, we need sometimes to add a couple of tables of the legacy database without having to change the model or even the context we already have (and have fine tuned). So having to Force the Scaffold-DbContext is a great problem. There should be an option to only update by adding just the table without altering or replacing previous changes in the context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [Package Manager Console (Visual Studio) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
@blogcraft This feature is being tracked here: https://github.com/aspnet/EntityFrameworkCore/issues/831
