### ISSUE TITLE
Please provide sample for saving disconnected entities with relationship changes

### ISSUE THREAD

**Issue by vincedan** [aspnet/EntityFramework.Docs#970]
I met issues when I wanna save disconnected entities which has relationship changes(navigation property changes), I don't know whether it is bug or not ... could you team provide a sample for demonstrating the correct way for saving disconnected entities with relationship changes.

Thanks a lot.

**Comment by vincedan** [comment]
@ajcvickers

**Comment by ajcvickers** [comment]
@vincedan There is a sample [referenced from the documentation page](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities).
