### ISSUE TITLE
 statement cannot be used inside a user transaction when using MigrationBuilder.Sql

### ISSUE THREAD

**Issue by Liero** [aspnet/EntityFramework.Docs#973]
I've tried:

```
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.Sql("CREATE FULLTEXT CATALOG ft AS DEFAULT");
}
```
but I'm getting
> CREATE FULLTEXT CATALOG statement cannot be used inside a user transaction.

when running `dotnet ef database update` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13eb107-79c2-7824-12c1-e637d2a92add
* Version Independent ID: aafc9673-c635-3cf2-6235-8577ff15d19c
* Content: [Custom Migrations Operations - EF Core](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/operations)
* Content Source: [entity-framework/core/managing-schemas/migrations/operations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/managing-schemas/migrations/operations.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by bricelam** [comment]
Change it to this:
``` csharp
migrationBuilder.Sql(
    "CREATE FULLTEXT CATALOG ft AS DEFAULT",
    suppressTransaction: true);
```
