### ISSUE TITLE
Example code for Many to Many relationships?

### ISSUE THREAD

**Issue by rhires** [aspnet/EntityFramework.Docs#98]
I saw the example for setting up the data model using Code First, but is there example code of how to use it in a controller or repository? I've tried a couple of examples found elsewhere on the internet, but none are EF7, and while I'm likely not doing it right, I'd like to know that there is a working EF7 example that I can reproduce and then go from there.

**Comment by natemcmaster** [comment]
Like this http://docs.efproject.net/en/latest/modeling/relationships.html#many-to-many ?

**Comment by rhires** [comment]
Yes, except that this is the setting up of the data model, right? I was able to follow the example and that is set up. The next part is to use the data model in a controller/repository, where I set my (in the canonical example) Students <==> Courses in the controller/repository and they show up in the join table and their respective tables as well. 

In writing this reply I searched through the EntityFramework repo issues list, and found https://github.com/aspnet/EntityFramework/issues/4093. Might be what I need. I'm not sure if .Docs would be a place to have example code like this, or if it would be found somewhere else, perhaps in a blog or other documentation.

**Comment by rowanmiller** [comment]
@rhires given that many-to-many is modelled as two one-to-many relationships, it's really just the same as working with any other relationships.

```c#
var course = new Course { ... };
context.Courses.Add(course);

var student = new Student { ... };
context.Students.Add(student);

var studentCourse = new StudentCourse { Student = student, Course = course };
context.StudentCourses.Add(studentCourse);

context.SaveChanges();
```

Is there a particular scenario that you are finding difficult to code up?

**Comment by EdRbt** [comment]
Hi,
I'm trying to achieve pretty much the same goal, and I'm facing difficulties.
I have two models, with an entity representing the link table for many to many relationship.

Here are my entities:

```
    public class Profile
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public List<ProfilePermission> ProfilePermissions { get; set; }

        public List<Permission> Permissions { get; set; }

        public static void Configure(EntityTypeBuilder<Profile> profile)
        {
            profile.HasKey(e => e.Id);

            profile.HasIndex(p => p.Name).IsUnique();
            profile.Property(p => p.Name).HasMaxLength(200).IsRequired();
            profile.Ignore(p => p.Permissions);
        }
    }

    public class Permission
    {
        public long Id { get; set; }

        public string Code { get; set; }

        public List<ProfilePermission> ProfilePermissions { get; set; }

        public static void Configure(EntityTypeBuilder<Permission> permission)
        {
            permission.HasKey(e => e.Id);

            permission.HasIndex(p => p.Code).IsUnique();
            permission.Property(p => p.Code).HasMaxLength(200).IsRequired();
        }
    }

    public class ProfilePermission
    {
        public long ProfileId { get; set; }
        public Profile Profile { get; set; }

        public long PermissionId { get; set; }
        public Permission Permission { get; set; }

        public static void Configure(EntityTypeBuilder<ProfilePermission> profilePermission)
        {
            profilePermission.HasKey(pp => new {pp.ProfileId, pp.PermissionId});
            profilePermission.HasOne(pp => pp.Profile)
                .WithMany(p => p.ProfilePermissions)
                .HasForeignKey(pp => pp.ProfileId);
            profilePermission.HasOne(pp => pp.Permission)
                .WithMany(p => p.ProfilePermissions)
                .HasForeignKey(pp => pp.PermissionId);
        }
    }
```

When I create a Profile, I want to associate one or many Permissions (already existing in the database, there is no need to recreate them).
But when I call TrackGraph on my Profile entity, it sets to Added the Permissions too, and it results with the following error: 

`Cannot insert explicit value for identity column in table 'Permission' when IDENTITY_INSERT is set to OFF.`

Here is the generated SQL query:

```
exec sp_executesql N'SET NOCOUNT OFF;
INSERT INTO [Permission] ([Id], [Code], [CreationDate], [Description], [LastUpdateDate], [ProfileType], [SuppressionDate])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
SELECT @@ROWCOUNT;
INSERT INTO [Profile] ([CreationDate], [Enabled], [LastUpdateDate], [Name], [SuppressionDate])
OUTPUT INSERTED.[Id]
VALUES (@p7, @p8, @p9, @p10, @p11);
',N'@p0 bigint,@p1 nvarchar(4000),@p2 datetime2(7),@p3 nvarchar(4000),@p4 datetime2(7),@p5 int,@p6 datetime2(7),@p7 datetime2(7),@p8 bit,@p9 datetime2(7),@p10 nvarchar(4000),@p11 datetime2(7)',@p0=111,@p1=N'20b6e6aa-55c7-467c-a3c1-a787f7a0c666',@p2='2015-12-23 10:52:45.1449099',@p3=N'20b6e6aa-55c7-467c-a3c1-a787f7a0c666',@p4='2015-12-23 10:52:45.1449099',@p5=3,@p6=NULL,@p7='2015-12-23 10:52:45.1449099',@p8=1,@p9='2015-12-23 10:52:45.1449099',@p10=N'5d2c9e73-4324-4476-aff2-a0abd410c30d',@p11=NULL
go
```

**Comment by rhires** [comment]
@rowanmiller - Thank you! That little bit at the end is what did the trick. 

```c# 
var studentCourse = new StudentCourse { Student = student, Course = course };
context.StudentCourses.Add(studentCourse);
```
In some of the examples I've found online, these lines are not included, rather, the examples seem to just say that the join table will automagically populate. I have other questions regarding things like `.include` but I'll do more homework on that before I get too far. I'll leave this open for the other poster, since this is a related issue. Cheers!

**Comment by EdRbt** [comment]
Ok so I found how to resolve my issue, using TrackGraph and excluding "existing" entities.
But I'm facing other issues while trying to update my entities.
Is there an example of complete implementation of Many to Many relationships with detached entities ?

**Comment by rowanmiller** [comment]
@EdRbt no complete examples that I am aware of. You would need to use TrackGraph and somehow tell EF whether the entity is a new join, or an existing one. This is sometimes achieved by having a flag that is set on the client to identify new joins... or you could just give the join entity a separate primary key field and then you can identify new/existing entities by looking for whether that PK field is set.
