### ISSUE TITLE
provide some sample

### ISSUE THREAD

**Issue by MohammadMQ** [aspnet/EntityFramework.Docs#994]
please provide som samples of above methods for both connected and disconnected environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a85575e-e16a-92ee-d689-eea4ed70356c
* Version Independent ID: 516505b4-3082-37c7-e6c9-2e2343a1458d
* Content: [DbContext.Update Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.update?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by subhasiscgr** [comment]
I am assuming this only works if you know how to use objects of type EntityEntity. Doesn't look like a method for everyday use. The name of this method is indeed very deceiving, especially because I am coming from a regular SQL background.

**Comment by ajcvickers** [comment]
@MohammadMQ Documentation and samples are in the [disconnected entities documentation](https://docs.microsoft.com/ef/core/saving/disconnected-entities)

**Comment by MohammadMQ** [comment]
@ajcvickers Thanks for the reply
