### ISSUE TITLE
Expand Fluent API section with nameof instead of fixed strings

### ISSUE THREAD

**Issue by bartlannoeye** [aspnet/EntityFramework.Docs#999]
While the current sample is correct, is it useful to add a second code block?

&gt; Taking it one step further, we can protect our computed query from breaking in the future due to property renames by using nameof.

+ new code block.

If this is desired, I don't mind submitting a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d48c064-a896-af4b-9a32-7846e848bb9e
* Version Independent ID: 7d134bc7-7c34-a829-2a56-9ad6ea37015c
* Content: [Computed Columns - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/computed-columns)
* Content Source: [entity-framework/core/modeling/relational/computed-columns.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/computed-columns.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by collinstevens** [comment]
@divega may I suggest closing this issue in light of #1594?

**Comment by divega** [comment]
@collinstevens Agreed. Closing this issue for the following reason:

The input to HasComputedColumnSql is a SQL expression, hence LastName and FirstName are column names, and not property names.

Although the names may match if the model is mapped by convention (and hence your proposed change would work), the names may not match if you use HasColumnName or ColumnAttribute to customize the column-to-property mappings.

Changing the code snippet to use nameof() may contribute to the confusion between properties and columns.
